### ISSUE TITLE
Make diagnostics display configurable

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#1]
In other words:
- allow turning off the panel
- make sure regions are visible and have hovers, perhaps status message?
- make phantoms configurable

**Comment by tomv564** [comment]
Added `auto_show_diagnostics_panel` setting in https://github.com/tomv564/LSP/commit/797b373629664c1623773404c4d07b23c11444da

Added `show_ diagnostics_phantoms` setting in https://github.com/tomv564/LSP/commit/81e17b57a4b5aeef39fa6c4e00f9db7a6e3f7828

**Comment by rwols** [comment]
> perhaps status message?

Yes, I really like this feature from SublimeLinter, consider implementing that too. Also squiggly lines using `view.add_regions` for the errors/warnings would be good.
