### ISSUE TITLE
Don't show "Code Actions" button in the phantom when there are 0 code actions

### ISSUE THREAD

**Issue by rwols** [tomv564/LSP#10]
I'm not sure if this is possible to implement, but sometimes (often times?) there are 0 "Fix suggestions" for my errors in `clangd`. In that case, the "Code Actions" button in the error phantom should not be visible because it can be confusing if nothing pops up when clicking on that button.

**Comment by tomv564** [comment]
Great suggestion, at the very least we need to show something when no code actions are returned. Maybe a status bar message or even a dummy 'no actions available' item in a context menu. Do you have a preference?

As for the real fix:

Knowing when code actions are available for those phantoms is likely to be expensive as we'd have to query the language server for each diagnostic as they are refreshed.
VS Code and IntelliJ appear to wait until mouse or cursor are near a diagnostic before they query for code fixes and show the UI. This reduces the amount of querying dramatically, at the cost of making the user wait.

Perhaps we can fix it with language (e.g. "Request Code Actions") for now, and try a code actions querying setup later?

**Comment by rwols** [comment]
> Perhaps we can fix it with language (e.g. "Request Code Actions") for now, and try a code actions querying setup later?

Yeah, this is fine with me. Maybe even show a message like "no actions" or something.

**Comment by tomv564** [comment]
I opted for a small popup, it is a bit more visible than the `status_message` used when no definitions or symbols can be found:

<img width="317" alt="screen shot 2017-08-17 at 20 58 51" src="https://user-images.githubusercontent.com/4395832/29428961-4ad22c06-838f-11e7-8004-2b748a3f854e.png">

This hover doesn't always line up to the hover / menu item where the action was clicked on, I left a TODO on fixing this later.

I'll create an issue for pre-querying code actions now, but please comment if you think the popup solution can be improved. Perhaps goto definition and find reference should also show a similar popup?

**Comment by rwols** [comment]
I think this works fine, nice job 👍
