### ISSUE TITLE
bug in displaying completion list

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#101]
It is python language server, and I am trying to trigger auto completion by typing `class`, next I deleted the word and then trigger the completion again. Note that the completion list is different at the second time.

![sep-14-2017 21-52-13](https://user-images.githubusercontent.com/1690993/30462989-333057b2-9997-11e7-923b-c4b9fbf2d12f.gif)

LSP settings
```json
    "show_view_status": false,
    "auto_show_diagnostics_panel": false,
    "diagnostics_highlight_style": "box"
```

**Comment by tomv564** [comment]
Thanks for opening a new issue for this with this clear repro. You have configured LSP to `complete_all_chars` and not `only_show_lsp_completions`, correct?

**Comment by tomv564** [comment]
By the way, @randy3k could you leave some feedback on your diagnostics issue #67 and the proposed PR #96 ?

**Comment by randy3k** [comment]
`complete_all_chars` and `only_show_lsp_completions` as their default values.

**Comment by randy3k** [comment]
I will find some time tomorrow to response those two threads.

**Comment by tomv564** [comment]
I found one solution from SublimeJEDI: Sublime refuses to update the completion list with LSP completions until we hide the list first. This animation shows the behaviour after this fix, with a single `c` entered:

![completion refresh](https://user-images.githubusercontent.com/4395832/30524291-31da4628-9bf1-11e7-8b7e-b5ca246ebdba.gif)

**Comment by tomv564** [comment]
I wonder if LSP should differentiate between normal completion and *member completion*
Without `only_show_lsp_completions`, normal word completions are inserted where you would expect only members to be shown:

<img width="465" alt="screen shot 2017-09-17 at 21 48 12" src="https://user-images.githubusercontent.com/4395832/30524338-28ca3948-9bf2-11e7-99ac-f9f7b4291b90.png">

**Comment by rwols** [comment]
That seems like a really hard problem and language-specific 😞

**Comment by tomv564** [comment]
Agreed.
Feels like completions from language server should get much faster (they can be near-instant). 
Then we only have to figure out how to turn off that initial snippet entry (it feels like `INHIBIT_EXPLICIT_COMPLETIONS` should be doing this already).

**Comment by randy3k** [comment]
but it seems that it now does not show sublime word completions?

**Comment by randy3k** [comment]
I consider it is fixed.

**Comment by smanolloff** [comment]
I am also facing the same issue: regardless of the `only_show_lsp_completions` value, I no longer see the normal word completions from sublime (the ones that are actually present in the initially displayed completion list, which is then hidden and replaced by LSP's completions).

Is there any workaround for this? Am I missing something? I am very used to word regular sublime word completions and I rely on them being first on the list every time I start typing something, but now they are not present at all :(
