### ISSUE TITLE
question: dependencies on external plugins

### ISSUE THREAD

**Issue by florinpatrascu** [tomv564/LSP#107]
Hi there - I am trying to add Elixir support but I am total n00b at developing plugins for ST3, hence my question. The Elixir support will depend on some external ST3 plugins i.e. [elixir-tmbundle](https://github.com/elixir-editors/elixir-tmbundle), so that I can specify them like this (excerpt from the `LSP.sublime-settings`:

```js
      "elixir":
      {
        "command": ["elixir"],
        "scopes": ["source.ex", "source.exs"],
        "syntaxes": ["Packages/elixir-tmbundle/Syntaxes/Elixir.tmLanguage", "Packages/elixir-tmbundle/Syntaxes/EEx.tmLanguage", "Packages/elixir-tmbundle/Syntaxes/HTML (EEx).tmLanguage"],
        "languageId": "elixir"
      },
```

And I thought I could add it to the `dependencies.json`. However, when ST is booting, it complains about the `elixir-tmbundle`, as it cannot be found. How can I specify an external ST3 plugin, as a required dependency? Thank you!

**Comment by rwols** [comment]
[It's impossible at the moment](https://forum.sublimetext.com/t/question-how-install-package-control-package-as-dependency/28083).

**Comment by florinpatrascu** [comment]
Aww, too bad. Thank you!
