### ISSUE TITLE
Command Restart Servers is not working on latest release.

### ISSUE THREAD

**Issue by gmichokostas** [tomv564/LSP#108]
When I give the Restart Servers command this error appears in the console:

```
LSP: no clients found for window 2
LSP: golsp not available for view /Users/nrg/go/src/github.com/sourcegraph/go-langserver/main.go in window 2
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/nrg/Library/Application Support/Sublime Text 3/Packages/LSP/main.py", line 2107, in run
    unload_window_clients(window.id())
  File "/Users/nrg/Library/Application Support/Sublime Text 3/Packages/LSP/main.py", line 647, in unload_window_clients
    window_clients = clients_by_window[window_id]
KeyError: 2
```

**Comment by tomv564** [comment]
I added some safety checking in commit https://github.com/tomv564/LSP/commit/46ff4d6fab643fd654b8b82afec9fa78ec7870a8

But this error should only have occurred if there were no clients registered on that window (which the first log message also suggests?)

Could you test if the restart command works for you now?

**Comment by gmichokostas** [comment]
Unfortunately not, is not working. But I am not getting the Python error anymore.
I am getting:
```
LSP: no clients found for window 2
LSP: golsp not available for view /Users/nrg/go/src/github.com/sourcegraph/go-langserver/main.go in window 2
```
Also the Doc pop up is not appearing any more when I hover on the code.

**Comment by tomv564** [comment]
I can confirm one issue: `didOpen` is not sent for the currently active view after `Restart Servers`, this may cause the server to not respond to hovers (in the case of Pyls, it is).

But in your case, does the server start up successfully the first time you open a go file? Can you share more of your logs (from golsp startup up to the restart?)

**Comment by gmichokostas** [comment]
It looks like for some the reason the plugin is not working well with the [GoSublime](https://github.com/DisposaBoy/GoSublime) package. I've disabled it and everything works well again.
