### ISSUE TITLE
"Server error"

### ISSUE THREAD

**Issue by Azeirah** [tomv564/LSP#114]
I'm trying out this package on Windows 10 with Sublime version 3144 (most recent dev release on Windows).

I've installed LSP via Package Control, and installed pyls via pip.

Whenever I execute any of the commands in the command palette, e.g. "Document Symbols", Sublime's status bar shows `Server error`<sup>1</sup>. Nothing appears in the diagnostics box (100% empty, there's no whitespace or anything), nor does anything interesting show up in Sublime's own console<sup>3</sup>. Apart from this, I haven't changed anything to the default configuration, and the server does seem to start properly<sup>2</sup>.

1: ![pyls-server-error](https://user-images.githubusercontent.com/4040870/30567532-21f429b4-9cd1-11e7-8f96-9c9a354f8e4a.png) (sorry for the poor contrast, this theme's contrast is bad.)

2: ![pyls-initialized](https://user-images.githubusercontent.com/4040870/30567564-3e850c92-9cd1-11e7-99eb-c39e98d16428.png)

3: Sublime's console output:

```
DPI scale: 1
startup, version: 3144 windows x64 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/.../AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/.../AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/.../AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.120855
startup time: 0.164855
first paint time: 0.167855
[...]
reloading plugin LSP.main
[...]
plugins loaded
LSP: Config added: pyls (enabled)
LSP: Config added: clangd (enabled)
LSP: Config added: dotty (enabled)
LSP: Config added: reason (enabled)
LSP: Config added: rls (enabled)
LSP: Config added: golsp (enabled)
LSP: Config added: ocaml (enabled)
LSP: Config added: jsts (enabled)
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2017-09-19 00:11:00, next run at 2017-09-19 01:11:00 or after
```

**Comment by tomv564** [comment]
Thanks for the complete report! 
You will get a lot more logging by adding `"log_debug": True` to your LSP Settings.
Could you share your findings (perhaps more logs if the fix isn't obvious)?

**Comment by Azeirah** [comment]
Turning on `"log_stderror": true` gave me this

`LSP: (stderr):  b'2017-09-19 14:40:29,567 UTC - WARNING - pyls.config - Path c:\\Users\\...\\Desktop\\test.py not in s:\\somerandomfolder\\somerandomnestedfolder`

By adding the `test.py` to the project folder, it started working.

So I think the overall problem is that when a .py (or whatever?) file is outside its sublime project folder, LSP won't work.

**Comment by tomv564** [comment]
Correct!
I'm glad you sorted this out. Would changing the LSP status bar text to "file outside workspace" provide a valuable hint, or would you expect to read about this in the documentation?

**Comment by Azeirah** [comment]
I'd expect the diagnostics to say something at least, or make the "server error" message refer to the diagnostics. That would make a lot more sense to me.

Or perhaps a message in the diagnostics panel saying

"If this is empty, and you're still experiencing errors, turn on the "..._debug" option in the package options" or something among those lines.

**Comment by tomv564** [comment]
Closing in favour of #115, thanks for the feedback!
