### ISSUE TITLE
Log the errors from the client

### ISSUE THREAD

**Issue by golddranks** [tomv564/LSP#116]
While fixing a bug in the Rust Language Server, I found this behaviour:

```
LSP: (stderr):  b'DEBUG:rls::server: dispatch error, Error { code: InvalidRequest, message: "Invalid request", data: None }'
LSP: (stderr):  b'TRACE:rls::server::io: response: "Content-Length: 79\\r\\n\\r\\n{\\"jsonrpc\\":\\"2.0\\",\\"error\\":{\\"code\\":-32600,\\"message\\":\\"Invalid request\\"},\\"id\\":null}"'
LSP: (stderr):  b'DEBUG:rls::server: Server shutting down'
...
LSP: LSP stderr process ended.
```

The LSP simply says that the process has ended, while the RLS debug-prints that it is sending a response that signals an error.

It would be truly useful if LSP would report the error it got. It would help debugging user reports a great deal. (Assuming that LSP actually gets the error! It might be that the server fails to send it? I haven't checked yet. :P)

**Comment by tomv564** [comment]
If LSP receives the error, it *should* show up as a "got json" entry in the logs, and also in the status bar: 
https://github.com/tomv564/LSP/blob/master/main.py#L496-L499

It's possible that LSP fails to read the last message when stdout gets closed, that would be a valuable issue to fix!
