### ISSUE TITLE
User settings are all-or-nothing

### ISSUE THREAD

**Issue by golddranks** [tomv564/LSP#117]
I used to have user settings like this: https://gist.github.com/urschrei/5f526b1a00378bfc049b23323b0002fb

But as one can see, the default settings already contain

```
      "rls":
      {
        "command": ["rustup", "run", "nightly", "rls"],
        "scopes": ["source.rust"],
        "syntaxes": ["Packages/Rust/Rust.sublime-syntax"],
        "languageId": "rust"
      },
```

So I tried to remove these fields from my user settings `rls` object because they seemed redundant. This made `rls` not start.

I suspect that it simply *replaces* the default `rls` settings object with the user `rls` setting object, instead of *merging* it?

**Comment by tomv564** [comment]
Correct, in fact the entire contents of "clients" is replaced by your user settings. We do have configuration merging from User to Project-specific settings.

I'll link / comment this issue with an upcoming proposal on default/user settings could be managed!

**Comment by tomv564** [comment]
This should be solved now that #119 is merged, but I would love some feedback.

The `clients` block in the User LSP.sublime-settings now inherits defaults from `default_clients`, so you are free to only specify overrides for  eg. `command` there.

**Comment by deathaxe** [comment]
Seems to work smoothly. I modified pyls` command line in the user settings to create a logfile and added some env vars. No issues detected so far.

**Comment by tomv564** [comment]
Thanks for the feedback!
