### ISSUE TITLE
Default params to empty dictionary

### ISSUE THREAD

**Issue by sgentle** [tomv564/LSP#118]
In 08fc0589820fd88c134602984fbaae4ea4a76ae5 you stopped sending `params` if it's `None`. While that's spec compliant, it would appear that assuming `params` is always set [is a common issue](https://github.com/search?utf8=%E2%9C%93&q=json-rpc+params+optional&type=Issues) and it may be worth considering making it default to an empty dictionary instead in the interests of robustness.

Similar discussion here in the Microsoft reference implementation: Microsoft/vscode-languageserver-node#171

**Comment by tomv564** [comment]
Fixed in https://github.com/tomv564/LSP/commit/14397dd277e0f52f1e75bcba894f9006e560fd08, thanks for documenting the issue so clearly!
