### ISSUE TITLE
When setting `"only_show_lsp_completions": true`, completions sometimes "flash"

### ISSUE THREAD

**Issue by golddranks** [tomv564/LSP#127]
The RLS doesn't at the moment provide completions for macros such as `println!("foo")`. However, `println` is included in "Snippets". If I set `"only_show_lsp_completions": true`, which should, if I understand correctly, prevent snippets and Sublime's own "dumb" completions, I still see "flashes" of `println` in a pop-up menu. It appears and then disappears really fast.

Is there any reason why this should be the case?

Btw. there is `CompletionHandler` and `CompletionSnippetHandler`. How does Sublime know to call their methods, such as `on_query_completions`? I don't see any registration code in `main.py`. Or is it just "magical"? Do the methods access the language server synchronously, making Sublime to wait for the result? Could it be that it draws the menu while waiting, and makes it disappear after it gets the `sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS` result? Btw. `CompletionSnippetHandler` doesn't return these flags. Are both classes methods called for the same event?

**Comment by rwols** [comment]
Sublime starts querying plugins/snippets for completions upon the first alphabetic character types. The snippet completions return results immediately. So they show up. Now sublime doesn't really support async/promise/future completions, so every plugin that does that has to invent it some way. What usually happens is that once the promised "smart" completions are ready to be presented after a short while, we send a command to ST to hide the completion widget, and then force it to do auto-complete again, but this time with the smart completions ready to be presented. This is why you see a short flash of "dumb" completions.

**Comment by golddranks** [comment]
Okay. I was thinking if there was any way to prevent the flash. Not that it's super awful bug or anything, it's just a bit visually distracting.

Well, I'm going to set the snippets on anyway, as they seem to be useful.
