### ISSUE TITLE
Disabling or Reloading LSP package causes heavy CPU usage of plugin_host 

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#132]
While working on the PR to expand the environment variables, I have to reload the LSP/main.py several times. After doing so, ST starts to lack heavily. Task Manager shows the plugin_host.ext with 30% of CPU usage without dropping some times. 

I checked it with current master and 0.2.1 and 0.2.2 with ST3 3144 x64 portable vanilla install, too. Just Package Control, LSP and its dependencies. As soon as the package is disabled or reloaded, something seems to trigger an endless loop.

Steps to Reproduce

1. Start Sublime Text
2. Open a python file with pyls enabled
3. Run _Package Control: Disable Package_ or save the open main.py
4. Have a look at the Task Manager

Was not yet able to get an idea of what might cause it.

**Comment by rwols** [comment]
I'm noticing this too, I thought it had to do with the debug prints somehow. Not sure if related.

**Comment by tomv564** [comment]
@deathaxe You mention you checked with 0.2.1 and 0.2.2 but didn't clarify if the issue occurs with those versions too? There is only 1 major change since 0.2.2, so it would be helpful to know if that is the culprit!

**Comment by deathaxe** [comment]
Sorry, it happens with both 0.2.1. and 0.2.2, too. The reason must therefore go back a bit further. I had debug disabled in all situations. Just the "out of the box" setup.

**Comment by deathaxe** [comment]
The bug was introduced in 8beb41e4f02a40c5d7275ffae4d024eca7678c25
