### ISSUE TITLE
send `textDocument/didChange` before `textDocument/completion`

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#134]
Otherwise, the server is not able to pick up the most recent changes to generate completion list.

**Comment by tomv564** [comment]
LSP should be sending these, did you check your logs?
Implemented here, see `purge_did_change`: https://github.com/tomv564/LSP/blob/9a546564806453f830ab6394f47e33d56e174181/main.py#L2137-L2151

**Comment by randy3k** [comment]
It seems it is not always the case. Maybe due to buffer not in `pending_buffer_changes`?

**Comment by randy3k** [comment]
After some investigation, it is caused by the dissynchronization between the `view.on_modified_async` and `CompletionHandler`. If `view.on_modified_async` is triggered after `CompletionHandler`, then `pending_buffer_changes` would not be updated and `purge_did_change` is not functional.

A quick fix is changing
https://github.com/tomv564/LSP/blob/3014171cac21f894b71ebeb6c2cc93e2e853f8a9/main.py#L2546-L2546
to `on_modified` so that `queue_did_change` is always called before the completion ViewEventListener. However, it may introduce a little but neglectable overhead.

**Comment by tomv564** [comment]
Glad you could reproduce this reliably! I am curious what can influence the timing of the async handler, but at least now we have a guarantee (and `queue_did_change` is cheap)
