### ISSUE TITLE
Pre-request code actions for visible diagnostics?

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#14]
As a follow-up issue to #10, it would be great to query the language server if code actions are available before showing it in the diagnostic popups/phantoms.

Need to try out how we can restrict the amount of requests being sent when a document full of diagnostics is being opened, edited or scrolled through.

**Comment by predragnikolic** [comment]
> Need to try out how we can restrict the amount of requests being sent when a document full of diagnostics is being opened, edited or scrolled through.

If I understood the problem correctly, you need a way to delay the amount of request being send. 
The first thing that came to my mind when reading this was debounce and throttle.
This site here illustrates how debounce and throttle work. http://demo.nimius.net/debounce_throttle/

I also found this debounce script for python https://gist.github.com/walkermatt/2871026.
Here is an example of how it works:
![2018-08-21-102140_1366x768_scrot](https://user-images.githubusercontent.com/22029477/44389806-1ab4ca00-a52c-11e8-9d33-08bea434cde9.png)

**Comment by tomv564** [comment]
I propose we look into updating the hover popup to do this lookup (together with the bulb functionality) - the user will then only be affected when hovering instead of when diagnostics arrive.

**Comment by tomv564** [comment]
Closed by #741
