### ISSUE TITLE
Occasional short-standing freezes

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#146]
I've started testing this package yesterday with javascript language and noticed that sometimes editor freezes temporarily while waiting for some data. I'm working on nodejs project and there are some logs in the console like `javascript-typescript-stdio: readFile [...]`.

It would be ideal if all operations would be non-blocking. Is there potential for improvement here (I haven't looked at the code myself yet)?

**Comment by tomv564** [comment]
I've seen the console itself freeze if it a large volume of data is printed to it from the language server - it can help to turn `log_stderr` or `log_server` off in the settings. 

Could you confirm if disabling the logging helps? There is also an unreleased fix for LSP in master where the stdout/stdin readers spins in a tight loop when a language server unexpectedly exits.

**Comment by ihodev** [comment]
> I've seen the console itself freeze if it a large volume of data is printed to it from the language server
I can confirm that too :wink:

**Comment by rchl** [comment]
That's not console related. There is just a dozen of short lines printed from LSP when I check it.
`log_stderr` is off. `log_server` is on but it doesn't produce many messages.

Are you saying that all code is async and CAN NOT block the main thread?

**Comment by tomv564** [comment]
The stdin and stdout streams are read by their own threads, and LSP registers to the async version of sublime's event listener where possible, there are some exceptions though.

Could it be that processing a server response becomes such a long-running task that any locks the task holds (GIL maybe?) result in a freeze for the main thread. 

If you could narrow down what kind of actions cause the freezes we can probably find some improvements!

**Comment by tomv564** [comment]
Since some recent changes to LSP and the javascript-typescript server I've noticed full Sublime Text freezes on Windows while editing. 
We've recently started using more sync events (https://github.com/tomv564/LSP/commit/d3a8da3864ffae7222e2f56e3a7154aec7e366f0) and I wonder if we need to now check for blocking logic in the path of these handlers.

**Comment by dre-hh** [comment]
I can reproduce a freeze every time i try to edit code having the javascript Object Spread Operator

```javascript
function todoApp(state = initialState, action) {
  switch (action.type) {
    case SET_VISIBILITY_FILTER:
      return { ...state, visibilityFilter: action.filter }
    default:
      return state
  }
}
```

**Comment by tomv564** [comment]
@dre-hh that is a great test case .. Sublime text will probably fire 3 didchange+complete request sequences when you type `...`. Thanks for the hint!

**Comment by rwols** [comment]
It'd be nice if we could filter firing completion requests for a `punctuation.accessor` scope just before the cursor, but unfortunately that is not reliable.

**Comment by tomv564** [comment]
I think this was fixed a while ago by moving server writes to a dedicated thread.
