### ISSUE TITLE
Mac: Randomly fails to find language servers on start up

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#147]
As documentation states, on Mac there can be issues with binaries not being in the PATH. The suggested fix is to use `SublimeFixMacPath` package. Nether that or similar packages (`CustomPATH`) or built-in-environment-variables-inheriting in ST3 is helping 100% with that as LSP package sometimes initialises before those packages. In that case PATH will not be supplemented yet and finding language server binary will fail.

I'm not sure what would be the best solution to this problem to be honest... Apart from some hacks that come to mind, maybe we should consider asking ST developers for some API or something to help with that.

(BTW. Setting full path to language servers does not always help either. For example if I set full path to `javascript-typescript-stdio` for example, it will still not work in my case, as it won't be able to find my nodejs (it's installed in home directory somewhere using `nvm`)).

**Comment by rwols** [comment]
Issue here: https://github.com/SublimeTextIssues/Core/issues/1877

**Comment by tomv564** [comment]
As we didn't have an issue about this yet, we'll keep this one open for a short while in case anyone is willing to improve the situation.

Fixes from eg. FixMacPath could be made more reliable perhaps?
* Can loading order be influenced?
* Can your shell startup & return variables faster?

PR #50 could also be revisited, if enabled behind a setting.

**Comment by rchl** [comment]
Thanks for the reference.
As I've said, those packages that workaround the problem are not 100% reliable.
We could devise some clever workaround solution for this problem:
Have a window of, let's say, 15s after `plugin_loaded` event, during which, if any language server fails to start, we will re-try starting it every 3 seconds (up to three times). That will not have any negative influence on the cases where language server is started properly on the first try.

**Comment by tomv564** [comment]
Thanks for the suggestion!

I am leaning towards improving PR #50 by making the 2-second delay a setting (default 0).
`start_active_view` causes the immediate server startup in `plugin_loaded`, so the delay may only need to apply there.

**Comment by rchl** [comment]
Honestly, I don't think a setting for something like that makes sense. You would tell your users to flip a setting if package mysteriously fails? It should just work by default.

**Comment by tomv564** [comment]
Agree with that the failure should not be mysterious, but as the target audience is programmers I expect them to be comfortable with changing a setting.

We could perhaps compromise by setting up a likely-to-work default delay for Mac users, but I cannot accept hacks like restarting servers with timeouts when the issue is fundamentally a disagreement between the user and Sublime Text.

Do other packages have an elegant way of handling this?

**Comment by frou** [comment]
> We could perhaps compromise by setting up a likely-to-work default delay for Mac users

Aw man, don't do that. That's effectively "sleep call, with a magic number" which is a hall-of-fame code smell.

A setting which is documented and explains that the ugliness is coming from a deficiency in Sublime is surely good enough for now.

**Comment by FichteFoll** [comment]
It should be possible to check `os.environ['PATH']` periodically until `/usr/local/bin` can be found, which seems to be the most important directory added by a login shell on macOS. Couple it with a timeout in case someone does specifically *not* add that path for whatever reason and the environment has already been loaded.

**Comment by ehuss** [comment]
Have you tried [shellenv](https://github.com/codexns/shellenv)?  I use that in RustEnhanced, and I haven't noticed any particular issues.  Add it as a dependency, and then call `shellenv.get_env()` and update `os.environ` with the result before attempting to launch any servers.

**Comment by tomv564** [comment]
@ehuss this looks like a great solution (especially when it is endorsed by ST developers), let's implement! I would love a PR if someone is particularly eager.

**Comment by ehuss** [comment]
FYI, build 3158 includes a fix for SublimeTextIssues/Core#1877.

**Comment by tomv564** [comment]
Best possible outcome!
Can someone confirm this build fixes their workflow? 

Thinking of the users not running dev builds, I would still consider the `shellenv` workaround.

**Comment by jonathan-s** [comment]
Chiming in here to say that I stumbled upon this issue myself. Installing this plugin fixed it for me: https://github.com/int3h/SublimeFixMacPath
