### ISSUE TITLE
Language servers are not shutdown gracefully.

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#148]
The debug.log of python-language-server shows the following exception, each time the server is closed by ST/LSP.

```
2017-10-03 21:28:50,277 UTC - ERROR - pyls.server - Language server exiting due to uncaught exception
Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\pyls\server.py", line 33, in handle
    data = self._read_message()
  File "c:\apps\python36\lib\site-packages\pyls\server.py", line 77, in _read_message
    raise EOFError()
EOFError
```

According to https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#shutdown a language server is closed by the following request/notification sequence.

1. send request "shutdown"
2. wait for response
3. send notification "exit"

LSP just closes down the server process without this sequence. The server therefore doesn't shutdown normally but due to an unhandled exception.

**Comment by tomv564** [comment]
LSP is impatient :) 
I welcome a *simple* fix to this (sending a shutdown request and then sending `exit` and killing the process)

**Comment by deathaxe** [comment]
I can have a look into this. Should not be too difficult.

**Comment by rwols** [comment]
For clangd it's sufficient to send a shutdown request, I reckon for other language servers it's the same.
