### ISSUE TITLE
Popup links to the documentation can not be opened in the browser (Rust)

### ISSUE THREAD

**Issue by IBUzPE9** [tomv564/LSP#150]
Sublime Text v3.0 build 3143

![Link example](http://saveimg.ru/pictures/05-10-17/ac653e5ea85693c382f0e66f7dc89a8c.jpg)

**Comment by tomv564** [comment]
Thanks for reporting, this should be an easy effort for a contributor to add to the Hovers. (There is already an example of routing the `on_navigate` call to `webbrowser`.)
