### ISSUE TITLE
completion menu shows too late after "tab" is hit

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#152]
When <kbd>tab</kbd> is hit and there are no available completions of a given prefix, Sublime Text will trigger `insert_best_completion` and insert at a tab or spaces. 

With LSP, LSP needs to wait for the server's response to compute the completion list. While waiting for the response, `insert_best_completion` has already inserted the tab or spaces. 

And it is what we will see
![oct-05-2017 13-13-29](https://user-images.githubusercontent.com/1690993/31240542-0c1435e8-a9cf-11e7-9b3e-5ea4d621de25.gif)

**Comment by tomv564** [comment]
To clarify what is happening:
* type 'yi', get matching completions
* press escape? to kill completions popup
* press tab to get a normal tab
* sublime triggers a completion popup with old content, as a new word boundary was started?

I might be misinterpreting this example, but LSP probably needs to do more to clear its completion list when crossing word boundaries .. backspacing through code also tends to allow old completions to be presented for positions no longer present in the code.

**Comment by deathaxe** [comment]
No,

- type `yi`
- type TAB as quick as possible
- a `\t` is inserted after `yi` by ST as if no completions were triggered
- than the completion panel shows up
- committing the completion now adds `yield`
- result: `yi\tyield`

**Comment by randy3k** [comment]
It shouldn't depend on the speed of the server. I don't have to hit <kbd>tab</kbd> very quickly to reproduce this. The esc above is to cancel the auto completion popup menu.

This is what I understand happening:

What <kbd>tab</kbd> is hit, Sublime Text triggers `insert_best_completion` and `on_query_completions` methods are called. If there are no completions available for a given prefix, `insert_best_completion` will insert a tab or spaces after the prefix.

However, when LSP comes into the game, `insert_best_completion` also requests language server completion list. In the first round of the request, the `on_query_completions` of CompletionHandler return an empty list and expect a response to be returned later. However, while waiting for the response to arrive,  the tab/ spaces have been inserted by a previous completion query.

**Comment by deathaxe** [comment]
Adding the following lines to cancel completion, if no results are available causes no tab to be added, but the began word to be completed with some of the best matching word completions ST found in the document. Completions seem to be random and unexpected on a first glance, but at least the completion panel is not opened after adding a tab.

```
            if not self.completions:
                self.view.run_command("hide_auto_complete")
                return
```

But it is still not too easy to trigger as pyls responds very quickly.

**Comment by randy3k** [comment]
Or let me state the steps to reproduce.

1. type `yi`
2. hit `esc` to cancel the auto completion
3. wait for a second
4. hit tab
5. observe that a tab / spaces (depends on setting `translate_tabs_to_spaces`) are added
6. the completion menu pops up

**Comment by deathaxe** [comment]
I can reproduce it. With "hard" I rather meant never to have hit in in real life work. But I am with you in any way. It is an issue. I already tried to find out what happens. The crazy thing is the following:

1. type yield
2. type space
3. type backspace (cursor is now exactly behind yield)
4. hit tab

As the cursor is exactly behind the word, normal completion is not triggered at all.

In this situation only `insert_best_completion` is called by hitting `tab`. This command also triggers `on_query_completions` which causes LSP to fire a request and run "auto_complete" as it was a normal completion. This causes the panel to be displayed.
Here is the command log of what's happening. The `LSP: ` were added by me to see what LSP does.

```
LSP: hide_auto_complete
LSP: auto_complete
command: commit_completion
command: left_delete
command: insert_best_completion {"default": "\t", "exact": false}
LSP: hide_auto_complete
LSP: auto_complete
```

**Comment by randy3k** [comment]
I see what you were saying now. I agree that in practice, no one will hit an `esc` to cancel the auto completion menu. It was just a demonstration of the bug. Your example is another way to trigger the bug. 

I reckon a possible solution is to prevent LSP calling `auto_compleiton` if the previous `insert_best_completion` inserted spaces/tab.

**Comment by randy3k** [comment]
Alternatively, we would undo the tab insertion and display the auto completion menu.

**Comment by deathaxe** [comment]
I was on my way with skipping `auto_completion` in case the server response contains only one completion, which matches the `prefix` and a tab/space was added.

**Comment by tomv564** [comment]
> Alternatively, we would undo the tab insertion and display the auto completion menu.

This is the approach I took, along with other fixes you already covered in the closed PR.
