### ISSUE TITLE
Word completions are no longer shown

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#158]
For some reason,  PR #136 breaks Sublime Text default word completion.

at e04aa1a0f2767a82d6166924296a3ecb3b9b1ffc

It shows both LSP completions and ST completions.
<img width="353" alt="screen shot 2017-10-07 at 1 14 56 am" src="https://user-images.githubusercontent.com/1690993/31304981-fdeaabe4-aafc-11e7-9082-83fa65d3d49a.png">

but at 67b7715326a675a61c058b3ab990eb03b81c3d7d

It shows only LSP completions
<img width="376" alt="screen shot 2017-10-07 at 1 17 10 am" src="https://user-images.githubusercontent.com/1690993/31304999-42d7fe3c-aafd-11e7-8899-db9801069013.png">

cc: @deathaxe

**Comment by tomv564** [comment]
Please report issues to PRs in the PR itself before it is merged. Thanks!

**Comment by randy3k** [comment]
Ya, it was merged 3 days ago.

**Comment by tomv564** [comment]
Great find @deathaxe.
It is early for LSP (tiny user base) to worry about making things look pixel-perfect and we get stupid bugs from it. I am going to stop merging these kind of suggestions for the foreseeable future.

**Comment by randy3k** [comment]
I guess I could never be able to find the cause. It is so subtle. Great job @deathaxe
