### ISSUE TITLE
Hovers show &nbsp;&nbsp; in preformatted code blocks

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#159]
An example of why we should be avoid being clever with standardised formats, remove as much of https://github.com/tomv564/LSP/blob/740b57d2e018f873f9f48af561078684666be123/main.py#L2024-L2030 as possible (if not all of it)

**Comment by deathaxe** [comment]
I'd prefer not to need such hacks at all, too.

**Comment by braver** [comment]
Hm, yeah, that's not ideal but I don't think it's *that* weird to do a little processing on content like that. 

Shouldn't this be applied just to the documentation, not to the code snippets? That's pretty easy to do and also solves this problem. (I wouldn't expect you to need to preserver indentation like that in preformatted blocks, although minihtml is a bit non-standard in other situations too and I wouldn't be surprised if it took some effort)

**Comment by deathaxe** [comment]
mdpopups replaces space with `\u00A0` / `&nbsp;` in code blocks anyway to preserve its indention. So a distinction is not required and just would cause more complex parsing and modification to be required on text whose format is unknown and will therefore most likely fail in the one or the other situation. The protocol-specs define Markdown to be used, but in real life it is just often not.

Have a look on python only. It defines different kinds of docstrings: RST, Google, Numpy, ... . 
Doxygen used by many C/C++ projects has nothing to do with markdown as well.

In the end each language defines its own formats at the moment. Therefore the less manipulation the better it is.

**Comment by braver** [comment]
Right. Probably doesn’t help that markdown isn’t a hard spec either. Indeed best to keep the processing to a minimum then.
