### ISSUE TITLE
How to integrate Anugalr LS with your package?

### ISSUE THREAD

**Issue by iampepe** [tomv564/LSP#164]
In 'the link bellow' there is a guide for installing Angular LS for sublime, but it states that I need a custom sublime plugin for completions in HTML files. 

-> [the link bellow](https://github.com/angular/angular/blob/master/aio/content/guide/language-service.md) <-

Question is how to get Angular suggestion in HTML files?

**Comment by tomv564** [comment]
That documentation likely refers to Microsoft's Typescript package (called "Typescript" in Package Control). The instructions (install the angular service next to your typescript dependency) sound correct, give it a try!

The LSP package does work with the _tslint_ language service in javascript/typescript-langserver, but my guess is no one has tested if the angular service works.

**Comment by iampepe** [comment]
Well thank you for your time :) 
Tried to set it up, it didn't work out. Not your fault, so I will close this.
