### ISSUE TITLE
LSP starts language-server several times after project change

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#174]
As the title says, pyls is started several times when opening a new project.

Steps to reproduce:
1. Open a project in ST.
2. Install ProjectManager package
3. Open a python file to start one pyls instance.
4. Call "Project Manager: Open Project" from command pallet and select another python project
5. Have a look to the console

**Comment by tomv564** [comment]
Not being a Project Manager user, does the "Open Project" command open a new window or does it replace the project of the current window?

**Comment by deathaxe** [comment]
It replaces the open project in the existing window, which seems to be the reason. ST's Quick Switch Project function works properly. I did not yet find a point to start searching for the trigger of this issue.

**Comment by nh2** [comment]
In these lines

https://github.com/tomv564/LSP/blob/78647441c861eb59d1d25bd6284a2814903a7783/plugin/core/main.py#L199-L207

when is a new client inserted into `clients`?

For me LSP starts a new language server process every time I unfocus and focus the window (on the current `master` commit that's linked).

**Comment by nh2** [comment]
Ah, I see, `add_window_client()`. And mine is not getting called because it's in `handle_initialize_result()` and there's an initialisation problem with the server I'm trying to get working.

**Comment by tomv564** [comment]
Good find, but the failure to initialise should have been visible from the status bar. If you can share where the initialisation failed we can at least fix that!
