### ISSUE TITLE
Suggestions popup doesn't resize depending on content

### ISSUE THREAD

**Issue by 3v1n0** [tomv564/LSP#182]
I'm not sure if this problem is related to LSP only, but I noticed it now better since I've longer completions (thanks for your efforts!).

Anyway, as you can see, when looking for longer functions, the size of the popup is still small and doesn't adapt to the width of the content:
![screencast](https://user-images.githubusercontent.com/345675/32032434-d0165388-b9cc-11e7-9629-ef8a758a4654.gif)

**Comment by tomv564** [comment]
The completion box does grow to accommodate in some cases (see `vertex_tmp`), but especially the `g_dbus_connection_new` example shows it getting stuck in the initial size.

I'm not aware of any width parameter to the completion api, may have to narrow down the repro a bit more and take it to the sublime forums.

**Comment by tomv564** [comment]
Sublime text issue, documented here: https://github.com/SublimeTextIssues/Core/issues/633
