### ISSUE TITLE
Shouldn't ignore hover on storage / constant / keyword

### ISSUE THREAD

**Issue by dten** [tomv564/LSP#183]
storage, constant and keyword are currently marked as `NO_HOVER_SCOPES` but they contain useful things often that need hovering over. the [scope naming rules](https://www.sublimetext.com/docs/3/scope_naming.html) say these should be used for proper things but often aren't (the Haskell syntax uses the 'wrong' scopes all over the place)

This just means when using [hie](https://github.com/haskell/haskell-ide-engine) and this plugin then I can't hover over an `Type` usage or imports

Take the hover below over `StateT` for example, this doesn't work in the current release. But with my fork it shows lots of useful info (thanks for that by the way :p).

![image](https://user-images.githubusercontent.com/1019038/32060646-4d41f480-ba67-11e7-8939-9706c5fb1901.png)

**Comment by dten** [comment]
and an example of something badly marked as a constant but worth hovering over (tells you which package it's imported from)

![image](https://user-images.githubusercontent.com/1019038/32061401-6619f4b0-ba69-11e7-96ff-af5c7041b854.png)

**Comment by tomv564** [comment]
Thanks for documenting the issue, I am guessing some people abuse the scopes to get the color schemes to look good :)
Is this `haskell-lsp`? Is it working well for you with this package?

**Comment by dten** [comment]
this is https://github.com/haskell/haskell-ide-engine
it's working OK, I can't figure who's fault it is but quite often the diagnostics appear, then flicker and then disappear and are hard to get back.

**Comment by tomv564** [comment]
Ah, it's the same guy from `haskell-lsp` working on it.
Feel free to open another issue if the logs implicate LSP :)
