### ISSUE TITLE
Add configuration to use status bar to show diagnostic message

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#19]
Follow up on https://github.com/tomv564/LSP/issues/1, this is familiar behavior for SublimeLinter users.

**Comment by tomv564** [comment]
Could use status_message or view.set_status, not sure if status_message is shown too briefly.

**Comment by rwols** [comment]
Probably `view.set_status` would be better. Just check where the cursor is and if it's on a line with a diagnostic use `set_status`, otherwise `erase_status`.

**Comment by tomv564** [comment]
Implemented by #39
