### ISSUE TITLE
Display error message when there's a formatting error

### ISSUE THREAD

**Issue by chenglou** [tomv564/LSP#190]
Maybe it's just our lang-server that's not returning the value correctly? This is the log:

```
LSP: request 8: textDocument/formatting 
LSP: got json:  {"jsonrpc":"2.0","id":8,"result":[]} ...
```

That's it

**Comment by tomv564** [comment]
Looks like your language server is not returning edits.
It's cheap assurance to display a confirmation to the user any time edits are applied, we should do this for all formatting, `rename`, and `workspace/applyEdit` handlers

**Comment by bsansouci** [comment]
On the topic of formatting, it seems like LSP isn’t able to recover from a formatting failure. I have to kill sublime and reopen to get LSP running again, making it almost unusable :/

**Comment by tomv564** [comment]
@bsansouci do you have a reliable way of reproducing this formatting failure? Which language server? I would really like to see your logs. 
We can start a new issue for it as well.

**Comment by tomv564** [comment]
The following should appear in the status bar in master now:

> Applied 0 change(s) to path/to/yourfile

@chenglou - did you have any luck getting formatting working?

**Comment by chenglou** [comment]
It seems to hang on formatting still:

```
LSP:  --> textDocument/formatting
```

**Comment by tomv564** [comment]
@chenglou, not sure if this issue was resolved? Was your language server never receiving the request, or were you able to confirm a useful response was given by debugging your language server? Please re-open this issue if you need further assistance.
