### ISSUE TITLE
Show doc parameters/others

### ISSUE THREAD

**Issue by natanfelles** [tomv564/LSP#193]
Seeing:

![captura de tela de 2017-11-11 23-06-14](https://user-images.githubusercontent.com/3011423/32694993-1bd3c162-c737-11e7-932d-997e1cfc26e6.png)

Thinking:

![captura de tela de 2017-11-11 23-06-14](https://user-images.githubusercontent.com/3011423/32695030-151499ea-c738-11e7-87e0-ba11e07e7b65.png)

---

I do not know if is necessary, but if possible remove the `<?php` tag.

Thank you.

**Comment by rwols** [comment]
Documentation of parameters should display when a lang server provides it. You can enable debug logging in the LSP preferences and see in the ST console if any documentation is sent along with the signature/parameters (the relevant request is called “textDocument/signatureHelp”)

**Comment by rwols** [comment]
Ah, I think you’re talking about hover, so disregard my previous comment.

**Comment by natanfelles** [comment]
Hi, @rwols !

Yes. About the hover popup.

If is possible, to show the parameters/other provide info descriptions.

**Comment by natanfelles** [comment]
SublimeCodeIntel currently do something like:

![captura de tela de 2017-11-11 23-06-14](https://user-images.githubusercontent.com/3011423/32695279-333b4224-c73e-11e7-9fb0-c3930025d761.png)

**Comment by rwols** [comment]
LSP just shows what the language server returns. You're probably using [this language server, right?](https://github.com/felixfbecker/php-language-server) If so, you could dive in in that project and make the changes, then make a pull request incorporating your changes.

**Comment by natanfelles** [comment]
Well, I just installed like is described in the [docs](http://lsp.readthedocs.io/en/latest/#php).

I believe that is right because is working in PHP and JavaScript. My issue is about to show the functions parameters. Currently is showing just the functions descriptions.

I do not know if the LSP Server sends other infos or not...

The images is how are showing in Sublime and PhpStorm, of course, just a comparison to a possible feature if possible. 

I'm starting with Python then, if not solved I will be happy to can open a PR. Your package is awesome.

---

About your first comment. I looked at the console and show that:

```
LSP: global clients: jsts=True, phpls=True
LSP:  --> textDocument/hover
LSP:      {'contents': [{'language': 'php', 'value': '<?php\nfunction in_array ($needle, array $haystack, $strict = false) {}'}, 'Checks if a value exists in an array'], 'range': {'end': {'character': 10, 'line': 1944}, 'start': {'character': 2, 'line': 1944}}}
```

**Comment by natanfelles** [comment]
As far as I can understand this is a more LSP Server related issue.

**Comment by rwols** [comment]
Yes, it’s an issue of the PHP server. I suggest you post the same two screenshots there as an issue, maybe even fork the project and implement the desired changes.

**Comment by natanfelles** [comment]
Ok. Thank you. PHP is more easy for me. :)
