### ISSUE TITLE
Unable to open Unable to open /Users/USER/Library/Application Support/Sublime Text 3/Packages/LSP/LSP.sublime-settings

### ISSUE THREAD

**Issue by golddranks** [tomv564/LSP#194]
I recently installed Sublime Text 3, LSP and Rust Language Server on a new computer.

Here are my settings:
<img width="1137" alt="2017-11-14 8 06 59" src="https://user-images.githubusercontent.com/2675542/32754273-8870e204-c913-11e7-81af-2481ec18b6f1.png">

I seem to be unable to change the settings (I can edit the file but the settings don't have an effect); when I open the console, I see the following message:

```
Unable to open /Users/USER/Library/Application Support/Sublime Text 3/Packages/LSP/LSP.sublime-settings
```

Indeed, that's not where the settings file is! I don't even know if the default settings file is unarchived by default in Sublime 3 (Some preliminary googling suggested that Sublime knows how to read the settings from archived packages?). The user settings file is in:

```
/Users/USER/Library/Application Support/Sublime Text 3/Packages/User/LSP.sublime-settings
```

I don't know if this is a bug/problem in Sublime 3 or in LSP, but I'd be grateful for some pointers.

**Comment by tomv564** [comment]
About the settings not having an effect, those `log_*` settings should live at the root _besides_ the `"clients"` block.
There currently is no way to set these global values on a per-language basis.

Not sure about the `Unable to open` message, but if Sublime Text can show you that dialog then I think it's picking up the right files eventually.

**Comment by golddranks** [comment]
Oops, sorry about the settings confusion.

Also about the `Unable to open` message, it seems like Sublime Text's message. It then falls back from loading the default settings from the zipfile. It finds the user settings after all. It might be just an annoying debug/info message – my settings didn't have effect because I've got them wrong, and that message made me think that's the reason. I'm going to close this.
