### ISSUE TITLE
Autocomplete menu is really long for long types

### ISSUE THREAD

**Issue by chenglou** [tomv564/LSP#199]
<img width="1280" alt="screenshot 2017-11-16 03 08 17" src="https://user-images.githubusercontent.com/1909539/32888266-8fd5e120-ca7b-11e7-87f1-be4a5b332068.png">

Some of them also has line breaks (like the last one), which means you don't see the signature on a single line. That's probably ok but it'd be nice to have some indicator.

**Comment by tomv564** [comment]
Sublime Text has no clipping / marquee support to help deal with this.
LSP exposes a `completion_hint_type` setting so you can display something other than the long "details" field in the second column.
You could alternatively change the language server to send shorter `details` contents.

VS Code "solves" this by opening a separate popup with details for the currently selected completion item. If this can be achieved in Sublime Text, I would suggest we always display "details" in a popup. (AFAIK there is no way to get "currently selected completions item" in Sublime Text)

**Comment by tomv564** [comment]
I hope `completion_hint_type` provided a way around these long signatures, the full signature should be visible once the signature help hover has opened.
