### ISSUE TITLE
Clangd support: pass in compiler flags for header files

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#2]
Clangd supports a non-standard `meta` field on `didOpen`.

LSP would have to extract the extra flags using per-project configuration:
https://github.com/Valloric/ycmd#ycm_extra_confpy-specification

**Comment by tomv564** [comment]
Considering compdb as alternative: https://github.com/Sarcasm/irony-mode/issues/323

**Comment by 3v1n0** [comment]
I think it's a good workaround for now, however the way of using compdb has changed (and not really much documented :)). You've to do something like:

```bash
compdb -c compdb.complementers=headerdb -p . update # or pointing the dir for the compile_commands.json
compdb -c compdb.complementers=headerdb -p . list > compile_commands_full.json
mv compile_commands_full.json compile_commands.json
```
The first command will generate an `headerdb.json` file, the second will merge the two in one (you might also act on multiple directories at once, by providing multiple `-p <path>`'s)...

**Comment by tomv564** [comment]
Having tested cquery with a compilation database in #208 I'm convinced that the clangd extension on `didOpen` is not worth it. I hope we _can_ improve the generation / maintenance of compilation DBs with header files with a clangd/cquery-specific LSP package.
