### ISSUE TITLE
Hover type hint isn't highlighting and contains &nbsp;

### ISSUE THREAD

**Issue by chenglou** [tomv564/LSP#200]
<img width="749" alt="screenshot 2017-11-16 03 11 31" src="https://user-images.githubusercontent.com/1909539/32888353-dddc1cfe-ca7b-11e7-9f8e-7394b75c06f9.png">

**Comment by chenglou** [comment]
Seems that the `nbsp;` issue has been fixed in master. Has there been such change? If not, maybe I got into some weird settings again

**Comment by tomv564** [comment]
If the language server sends a MarkedString (object containing both "language" and "value") then LSP puts it in a Markdown fenced code block (so mdpopup's syntax highlighting can be applied to the text). 
Code blocks don't convert `&nbsp;` but they don't collapse whitespace either. In other words, the language server doesn't need to send &nbsp; in MarkedStrings.
Demo using Github:
``` 
&nbsp;&nbsp;
 <- one space
  <- two spaces
```

**Comment by tomv564** [comment]
Sorry, I didn't actually answer your question. 
It's possible you see this now because the removal of `preserve_whitespace` (https://github.com/tomv564/LSP/commit/761c2c570446d73ecd2c87f5512fc5b7c9757e4f) got released with 0.4.0 5 days ago?

**Comment by tomv564** [comment]
Closing this as LSP should not be replacing with non-breaking spaces in popups anymore.

**Comment by chenglou** [comment]
Indeed fixed. Thanks!
