### ISSUE TITLE
Spaces don't trigger autocompletion

### ISSUE THREAD

**Issue by andfoy** [tomv564/LSP#203]
Under recommended settings, the LSP client does not emit a ``textDocument/completion`` request when an space is entered. This behaviour may limit some autocompletions on some languages, specially if they are required after a keyword. For instance, on Python an user may want to get package suggestions after writing ``import``.

Right now, the only option relies on using Sublime default/defined autocompletion key (e.g., <kbd>Alt0</kbd> + <kbd>/</kbd>) shortcut after writing another character; if this shortcut is invoked just before after writing the keyboard ``import`` it will remove the whitespace and move the cursor back to the end of the keyboard, giving possible autocompletion options that involve the word "import". For illustrative purposes, here's a GIF of the current behaviour:

![peek 16-11-2017 15-07](https://user-images.githubusercontent.com/1878982/32895325-f2e38c4a-cadf-11e7-9d80-9b06a5bf1a85.gif)

**Comment by tomv564** [comment]
Great bug report!
This looks to be the undo command being incorrectly fired by LSP, which @randy3k _just_ tightened down in the open PR #197

**Comment by tomv564** [comment]
The above fix helped, but I still see the following in master with OS-X dev build 3154:
`from a` -> `['abc', 'activate_this', 'aifc', 'antigravity', 'argparse', 'array', 'ast', 'asynchat', 'asyncio', 'asyncore', 'atexit', 'audioop']` (expected)
`import a` -> no completions

Can you confirm if you see this difference, and what build/platform are you using?

**Comment by randy3k** [comment]
@tomv564 I confirm your findings -- `import a` shows nothing for me. But it is like that even before #197 was merged.

**Comment by randy3k** [comment]
`import a` shows nothing because of Sublime Text python [completion rule](https://github.com/sublimehq/Packages/blob/master/Python/Completion%20Rules.tmPreferences) which explicitly disable autocomplete after `import`. One need to trigger the completion menu manually.

**Comment by tomv564** [comment]
Thanks for solving that mystery! I will ask about that LSP bypassing that rule on the forums

**Comment by tomv564** [comment]
The Anaconda package recommends overriding the Python `Completion Rules.tmPreferences` with your own ( https://github.com/DamnWidget/anaconda#auto-complete-for-import-behaves-badly)

This together with the completion triggers and the snippet completions that cannot be disabled is starting to be a bit of a fight against Sublime's defaults (which are reasonable for their built-in completion functionality).

**Comment by tomv564** [comment]
Closing this after documenting/linking to the workaround. As it appears pull requests to adjust built-in completion rules are being merged, a willing volunteer may have some luck proposing a fix at https://github.com/sublimehq/Packages
