### ISSUE TITLE
lsp_symbol_definition not working without include directive in a file

### ISSUE THREAD

**Issue by kubaroth** [tomv564/LSP#205]
Hi there,
I've noticed the jump to definition stops working if the include directive gets removed/commented out. 
As I'm very new to LSP I'm not sure if the problem lays on clangd side or the plugin. 
Any tips how to verify that? I would be very interested how to query clangd directly?

This is the output I get when cursor is positioned at the `aaa;` line.
```
LSP: request 50: textDocument/definition 
LSP: got json:  {"jsonrpc":"2.0","id":50,"result":[]} .
```

and here is the snippet:
```
#include <iostream>
// #include <vector>
using namespace std;
int main() {
    std::vector<int> aaa {1, 2, 3};
    cout << "___" << endl;
    aaa;
    return 0;
}
```
Could anyone verify this please?

**Comment by tomv564** [comment]
Hi, thanks for including the logs - if clangd replies with an empty array then there is little this package can do.

A general LSP debugging tool would be helpful - some languages provide a lot of boilerplate should you choose to build one. (see https://github.com/Microsoft/language-server-protocol/wiki/Language-Server-Protocol-SDKs)

@rwols, I see some tooling exists for finding missing `#include` statements (https://clang.llvm.org/extra/include-fixer.html), any idea if clangd by default will search symbols beyond includes?

**Comment by rwols** [comment]
Hi, I’m not entirely sure if it does more than parse the file. I’m pretty certain it doesn’t do anything text-based, and clangd also doesn’t keep a list of “common” includes. From a compiler’s point of view then, the type “std::vector<int>” is unknown at that point.

There is some work being done on indexing files, but from what I understand that’s not functional yet. I could be wrong on this though.

**Comment by kubaroth** [comment]
Thanks for the info. Feel free to close it. I will reopen if I find anything new. This is currently no.1 on my todo list.
