### ISSUE TITLE
Add Links to Definition / References actions to Hover

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#207]
As suggested by @natanfelles in #78

**Comment by tomv564** [comment]
Added in https://github.com/tomv564/LSP/commit/527089d4ccd723acc9b8a5251bb2fe4d54c44f54

<img width="550" alt="screen shot 2018-01-17 at 23 01 10" src="https://user-images.githubusercontent.com/4395832/35069693-49415578-fbdb-11e7-94ce-0f3c012e46a4.png">

**Comment by AmjadHD** [comment]
that doesn't work for python

**Comment by tomv564** [comment]
@AmjadHD can you clarify what doesn't work?
If you don't see the entries in the hover popup (not the signature help), are you on latest master?
If you do see it, can you enable logging and paste what happens when you hover and click definition?
