### ISSUE TITLE
Handling responses: an empty array as result will make the response be "lost in flight"

### ISSUE THREAD

**Issue by golddranks** [tomv564/LSP#210]
I've been tracing a bug with RLS completions, and I think I found it.

When typing, for example, "use std:", it tries to complete after the ":" character. However, the RLS doesn't understand that, since it manages to complete only after the full "::" operator: "use std::".

This would be fine by itself, but RLS sends back a successful response with an empty result list, a list of 0 items. This, I think, is a valid response by the LSP protocol.

However, the response checking code in `rpc.py` fails to consider that as a valid response, because on the line 168, it tests `result` like this: `if result:`. In Python, an empty list coerces to false, which makes it to consider the value as an error. But since the `error` value isn't set either, the response goes unhandled.

This causes the `CompletionState` to get stuck as `CANCELLING` upon the next completion request, which prevents further messaging.

There's multiple bugs to be fixed:

1) Allow results that are empty lists (`if result is not False:` instead of `if result:`, possibly with a comment that explains the need for it to be that way.)

2) Without the response message, `CompletionState` seems to get stuck as `CANCELLING`, and prevents further requests. I have no clear picture how to fix this without breaking anything; I haven't studied the code in `completion.py` well enough. However, even if 1) is fixed, this is a separate bug, because it would be bad if it got stuck in case a response gets lost "in flight" for some reason.

3) While reading the code, I noticed that there is a setting `log_payloads`. This isn't mentioned in the documentation. Should it?

**Comment by golddranks** [comment]
Btw. arguably not finding completion results with `use std:` can be also considered as a bug, but it's a bug/missing feature in RLS. I'll report that there.

**Comment by tomv564** [comment]
Great research, sounds like hard-to-spot issue!

1. Feel free to send a PR, or I can check in what I have locally. I suggest the following additions: 
* Check `if result is not None` instead
* Add a final `else` case that logs about an incomplete result payload (this would have made this bug much easier to spot.

2. I'd like to avoid the complexity of handling missing responses. Getting out of CANCELLING state might require some kind of timeout hack 🤢 - reopening the document should reset completion state without restarting the language server.

3. We can add `log_payloads` to the documentation - I've used it for in-depth debugging but it would be a good requirement to add

**Comment by golddranks** [comment]
So the current state-machine-like code is to ensure that there is no multiple completion requests at a time to prevent juggling with concurrency? If I understand it right, `CANCELLING` defers any further requests until the response has been got – after that it launches the pending request.

Since each request has an ID, it shouldn't be too hard to track the state of each request separately, and "expire" them when new requests are made. One could store the ID of the currently "fresh" request (the newest request sent), and ignore all the responses from stale requests. I think this would eradicate the need for the explicit state handling.

However, this would allow for multiple concurrent requests. After a quick search here https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md , I couldn't find anything that forbids that, but I wonder if all the servers play well with that. Was the current state-machine-like code there for that reason?

**Comment by tomv564** [comment]
I quickly applied the fixes mentioned earlier so we can move onto discussing the state-machine vs. expectations about responses.

You are correct, allowing only one completion request at a time was done to make completion state a bit easier to reason about. There is enough complexity managing Sublime's api, adding multiple concurrent requests into the picture would make the solution even less maintainable.
And yes, I think it is the "safe"/conservative thing to do towards potentially expensive requests to the server.

> it would be bad if it got stuck in case a response gets lost "in flight" for some reason.

as per http://www.jsonrpc.org/specification:

> When a rpc call is made, the Server MUST reply with a Response, except for in the case of Notifications.

Would it be ok if we revisited this when we have a real case where this affects end users ?

**Comment by golddranks** [comment]
Yes, that sounds entirely reasonable. Good call about that MUST — in light of that, 2) isn't a bug.

**Comment by golddranks** [comment]
Also, thanks for the quick fix for 1)!
