### ISSUE TITLE
space wrongly triggers autocompletion

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#211]
following https://github.com/tomv564/LSP/pull/197#discussion_r151605795

<img width="418" alt="screen shot 2017-11-17 at 12 23 30 am" src="https://user-images.githubusercontent.com/1690993/32930648-f23bb3be-cb2d-11e7-96bf-437671397099.png">

It could be reproduced by typing `y` and `<space>` very quickly or when the language server responds slowly.

We might need to check if the context which triggered the completion is still a prefix of the current cursor.

**Comment by tomv564** [comment]
Thanks for reminding me, it is easy to reproduce but I must have ignored it so far if it occurred in regular coding. Is there a particularly bothersome example where you see this in everyday coding?

As for a solution, prefix checking needs to allow completion if I've typed `yie` when a completion is returned for `y` but not when I've typed `y `. 

We could also check if the last character is whitespace and set the completion state to CANCELLING in `on_modified`?
