### ISSUE TITLE
Evaluate language-specific extensibility 

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#212]
@golddranks and @coder543:

I've done some quick exploration on what it would take to support Rusts's extensions _outside_ of LSP in https://github.com/tomv564/LSP-rust.

Only a single hook was exposed (in branch https://github.com/tomv564/LSP/tree/feature-enhance-clients) for adding extra listeners to Rust's notifications.

Adding functionality for `rustDocument/implementations` was a matter of copying and pasting the References logic and changing a few parameters. This is an example of real value that we can deliver outside the common LSP package.

Are you interested in taking this code and improving the Rust language server experience on top of LSP? 

There are plenty of other features to deliver:
The setup flow in RLS's VS Code client works really hard to help the user keep their server up-to-date and configured correctly for example.

**Comment by coder543** [comment]
Unfortunately, my time has been overwhelmed with other projects and business trips for over a month now, so I don't know when I'll have time. It's something I would like to do eventually.

**Comment by coder543** [comment]
I'm glad to see that work is being done to allow external LSP-extensions, since I'm sure other communities have nonstandard things they want to support, and this foundational work will be necessary to support such things.

**Comment by Jayflux** [comment]
@tomv564  any idea why the auto complete menu doesn't work properly for Rust?
![rls_autocomplete](https://user-images.githubusercontent.com/936006/34182328-a9de1c8e-e50d-11e7-9ae0-cbbed898c652.gif)

**Comment by coder543** [comment]
Under Sublime's general settings, you might need to override its notion of an autocomplete trigger character:

	"auto_complete_triggers":
	[
		{
			"characters": ".:",
			"selector": "source.rust"
		}
	]

But, even then, it doesn't work great. The official VS Code plugin has gotten really good lately. I still enjoy some of the features in my fork of this LSP plugin, but you're probably going to have a better Rust experience on VS Code, in my opinion.

**Comment by golddranks** [comment]
There isn't any inherent reason why it shouldn't work in LSP. If there is an autocompletion that works on VS Code and not on Sublime/LSP, it's a bug, and those are, in my experience, not that hard to fix, since all the plugins do is exchange messages with the server, and the server does the hard work. If you have any example code to link to, I can try and arrange some time to look at it this Friday.

**Comment by Jayflux** [comment]
Thanks @coder543 that fixed it for me, i will see if Rust Enhanced can handle this.
@coder543 what better experience does VSCode offer over sublime at the moment? Ive only toyed with it a bit

**Comment by Jayflux** [comment]
@tomv564 we currently have to override LSP's settings with these:
https://gist.github.com/urschrei/b0427f513dc78a9e32329e4bc8a65846

Could some of these go into the main settings file?

**Comment by tomv564** [comment]
I just added the RustEnhanced syntax in https://github.com/tomv564/LSP/commit/af7166c7bc8f94e3f75115e41a70ff7920dfd700.

Another difference is the `enabled: true` setting.
Because LSP ships with so many configs, all of them are disabled until the user opts-in. I suggest that Rust Enhanced when installed could also globally enable LSP's Rust support.

**Comment by Jayflux** [comment]
@tomv564  when will you be releasing your https://github.com/tomv564/LSP/commit/af7166c7bc8f94e3f75115e41a70ff7920dfd700 fix ?

**Comment by Jayflux** [comment]
also @tomv564 LSP doesn't seem to work when the Rust package is disabled (but Rust Enhanced is enabled) is this by design?

**Comment by Jayflux** [comment]
Sorry another query, is it currently possible to send settings to RLS, similar to how VScode does? https://github.com/rust-lang-nursery/rls#configuration

**Comment by tomv564** [comment]
Hi @Jayflux, I'll try to get a release out soon - it is high time.

I merged the hook mentioned in the first message, allowing you to handle RLS's extra messages as is done in https://github.com/tomv564/LSP-rust.

LSP should be sending settings to RLS at startup (and when changed), they can be provided in two places:

In the global *Preferences: LSP Settings*  (below an example of pyls with settings)

```json
{
  "clients": {
    "rls": {
      "enabled": true,
      "settings": {
        "build_lib": true
      }
    }
  }
}
```

In your Sublime Project settings (where they will override the global settings:

```json
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings": {
		"LSP": {
			"rls": {
				"settings": {
					"build_lib": true
				}
			}
		}
	}
}

```

**Comment by tomv564** [comment]
Hi @Jayflux, the support for RustEnhanced syntax was released a while ago, hope this simplifies your setup!

Also your previous question:

> LSP doesn't seem to work when the Rust package is disabled (but Rust Enhanced is enabled) is this by design?

This is absolutely not by design, would be great if you can share some start up logs with a recent version of LSP!

**Comment by tomv564** [comment]
An update to the initial API which thankfully was never adopted is waiting at #298.

The motivation is:
* I want to delete the "default" configurations eventually (instead, install LSP add-on to get config + extras)
* Expose hooks before and after a client is started for installation and custom messages.

Please leave comments!
