### ISSUE TITLE
dependencies.json set up incorrectly

### ISSUE THREAD

**Issue by jrappen** [tomv564/LSP#213]
Please refer to the top of <http://facelessuser.github.io/sublime-markdown-popups/api/> on how to set `dependencies.json` for packages using `mdpopups`.

```diff
--- ./dependencies.json
+++ ./dependencies.json
@@ -5,7 +5,9 @@
             "python-markdown",
             "mdpopups",
             "python-jinja2",
-            "markupsafe"
+            "markupsafe",
+            "pymdownx",
+            "pyyaml"
         ]
     }
 }
```

and you might want to review the Python code where `mdpopups` is used against the API docs from above as well while at it.

**Comment by tomv564** [comment]
Fixes in https://github.com/tomv564/LSP/commit/c92ca8ab98cba093bc4b1735b3f1887c4680b8d6, thanks for the heads-up!
