### ISSUE TITLE
Override settings causes package to look in the wrong place - (yaml required?)

### ISSUE THREAD

**Issue by jasonwilliams** [tomv564/LSP#215]
Windows 10
Sublime Text 3154

**Problem**
When installing this package via package control, i don't get the options, and i get an error in the console about not finding settings.

**Steps to replicate**
* check this package out via Package Control.
* Navigate to preferences -> Package Settings -> LSP 
* Change some settings in here (with the console open)
* You should get an error about it not finding settings in the Sublime Text 3/Packages folder.

I don't think settings live here if its installed via package control..

However checking it out from github it works fine

**Comment by Jayflux** [comment]
![lsp_no_settings](https://user-images.githubusercontent.com/936006/33245208-48020cdc-d2fc-11e7-91c3-2f365830c64d.png)

Just restarted Sublime and have had the same problem. my LSP options have gone, and the console is moaning (image above)

**Comment by rwols** [comment]
This might be https://github.com/tomv564/LSP/issues/213

**Comment by tomv564** [comment]
I just released 0.4.1 to get the fix for #213 out to everyone.
Running "Satisfy Dependencies" should help getting yaml installed if sublime won't do it for you.

The settings issue sounds like something else, will investigate.

**Comment by tomv564** [comment]
Unable to find any issue with the `edit_settings` command

The documentation suggests that the default sublime-settings file is opened from the package archive despite the use of a physical file path as argument.
