### ISSUE TITLE
It's not working for JavaScript

### ISSUE THREAD

**Issue by bsvipas** [tomv564/LSP#216]
Hi, I don't know why, but it's not working for me with ST3. I'm using it for JavaScript.

I did these steps:
- Installed LSP plugin for ST3.
- `npm install -g javascript-typescript-langserver`
- Opened User settings and added:
```json
"auto_complete_triggers": [
        {
            "characters": ".",
            "selector": "source.js"
        },
        {
            "characters": ".",
            "selector": "source.ts"
        }
]
```
- Enabled all logging.
- Restarted ST3.
- Tested, nothing happened, no autocomplete support and other things with `.js` files. Also opened console and nothing was here related with LSP. Seems it doesn't started or what? I don't understand why it doesn't working and how to make it work.
- Tried with dev build and with stable build, same...

**Comment by rwols** [comment]
Did you run "LSP: Enable Language Server Globally"?

**Comment by bsvipas** [comment]
@rwols Hi, what did you mean?

**Comment by rwols** [comment]
In the Command Palette, if you type "LSP:", a list of commands should appear. One of them should be "LSP: Enable Language Server Globally". Select the javascript language server in the popup menu that appears.

**Comment by bsvipas** [comment]
@rwols I didn't saw such option in command palette, only LSP settings. I will try to reinstall everything.

**Comment by bsvipas** [comment]
@rwols Seems everything is good, but it's very buggy, it worked for me only 1 time for new project, I did yarn add express and it never started normally after that.

**Comment by rwols** [comment]
If you happen to find the time, we'd appreciate if you could share the debug output in the console (enable it with `"log_debug": true` in your LSP settings).
