### ISSUE TITLE
Needs more documentation

### ISSUE THREAD

**Issue by rwols** [tomv564/LSP#22]
To lift this plugin off the ground it should have way more documentation in the readme:

1. "What does it do and why would you care?" section (Yes, I see that it lists the features but it's somewhat dry).
2. Explain the big picture: client-server thing, this plugin is only the client, can talk to any server respecting the LSP.
3. Give some practical examples to get started with popular languages.

**Comment by tomv564** [comment]
Agreed, a short paragraph ~ 2 sentences should tell the what and the why.

The feature list is perhaps best replaced with a few animated GIFs of compelling action sequences?

Do you think it's okay to mention the most functional/popular setups and link to a (hopefully drastically improved) section in the documentation? I would like to avoid users having to scroll past technical details before hitting the Installation section.

**Comment by tomv564** [comment]
The images on the package control-hosted Readme are also broken

**Comment by tomv564** [comment]
Most of the issues have been addressed now. I'd like to see new issues for specific suggestions in the future as a "Needs more documentation" issue could probably live perpetually :)
