### ISSUE TITLE
pyls refusing to provide diagnostics for files outside first project directory

### ISSUE THREAD

**Issue by stevenkaras** [tomv564/LSP#221]
Not sure if this is a limitation of the LSP plugin or the pyls server, but figured it was worth documenting.

Using python-language-server version 0.11.1, and LSP version 0.4.1.

Steps to reproduce:

* Open a new Sublime window
* Add a second folder to the project
* Enable debug logging for the LSP plugin
* Enable the LSP for the project
* Open a python file under the second folder
* Check the console for `LSP: Skipping diagnostics for file /.../second/hello.py  it is not in the workspace`

**Comment by tomv564** [comment]
Hi Steven, it's good you found the issue from the logs.

There was some discussion much earlier about supporting multiple folders in https://github.com/tomv564/LSP/issues/33.

As you found in your PR, there are some unknowns in supporting multiple workspaces in LSP - perhaps we can make a subset of LSP work well under clear conditions.

**Comment by stevenkaras** [comment]
Ok. Didn't see that issue when I was browsing through to see what was causing this.

I think there's some confusion in both the code and the discussion as to what is a LSP workspace vs a Sublime workspace. I'll see about at least adding some comments to the code to clarify that.

**Comment by tomv564** [comment]
It's good this comes up for discussion, I don't expect people to dig through all the old issues :)

We might see some inspiration from VS Code:
https://code.visualstudio.com/docs/editor/multi-root-workspaces

One issue with this package is how configuration is applied:
 
We only define one set of language server settings in a sublime-project, which has to take care of potentially multiple different root folders.

**Comment by stevenkaras** [comment]
The reason I opened a ticket is because completion, symbol search, hover, etc worked, but diagnostics didn't. Which definitely surprised me that some language server features would be supported but others not. Probably a good idea to explain the caveat on diagnostics (and other affected features) in the readme.

It does make sense that if you're going to start a separate language server per-project folder, then you'd want to push a different configuration for each one. But at first, I'd just reuse the project config for each folder. Adding an extra level of configuration to be applied (global, user, project - currently) feels like it should be the second half of this.

**Comment by tomv564** [comment]
I removed the filtering of diagnostics as the need for it was not documented anyways.
Also added a note to the Readme as you suggested.

Thanks for your suggestions! I hope we can have a proper look at multiple-folder support in the future.
