### ISSUE TITLE
applyEdit fails to move code. Applies deletion, does not apply insertion

### ISSUE THREAD

**Issue by rictic** [tomv564/LSP#224]
I've got some source like so:
```html
<dom-module id="some-thing">
  <style></style>
  <template>
  </template>
</dom-module>
```

My language server can send an applyEdit request to move the `<style>` element into the `<template>` element. This is done as two deletions and one insertion. In Atom and VSCode this works as intended, in Sublime LSP the deletions happen but the insertion does not.

Expected output:
```html
<dom-module id="some-thing">
  <template>
    <style></style>
  </template>
</dom-module>
```

Actual output:
```html
<dom-module id="some-thing">
  <template>
  </template>
</dom-module>
```

applyEdit message:
```js
    {
      'edit': {
        'changes': {
          'file:///Users/rictic/open/project/element.html': [
            {
              'range': {
                'start': {'line': 0, 'character': 28},
                'end': {'line': 1, 'character': 2}
              },
              'newText': ''
            },
            {
              'range': {
                'start': {'line': 1, 'character': 2},
                'end': {'line': 1, 'character': 17}
              },
              'newText': ''
            },
            {
              'range': {
                'start': {'line': 2, 'character': 12},
                'end': {'line': 2, 'character': 12}
              },
              'newText': '\n    <style></style>'
            }
          ]
        }
      }
    }
```

Traceback:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "plugin.core.edit in /Users/rictic/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package", line 53, in run
IndexError: list index out of range
```

**Comment by tomv564** [comment]
Thanks for reporting! This must be polymer-editor-service?

It looks sublime may be removing the region itself when the contents of a region is deleted.
Will get back to you with a fix soon!

**Comment by rictic** [comment]
Yep! If you'd be interested I could send over a PR to add it as a default_client in LSP.sublime-settings

**Comment by tomv564** [comment]
I think the above commit to master should handle regions being dropped after erasing their content.
A PR for a default_client entry would be great!

**Comment by rictic** [comment]
Can confirm this is fixed at master. Sent over https://github.com/tomv564/LSP/pull/229 to add polymer-ide as a default client
