### ISSUE TITLE
Highlight current active parametar in tooltip when calling a function

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#231]
Add bold and underline to an active parameter. 

Current behavior:
![output](https://user-images.githubusercontent.com/22029477/34406646-8a39a908-ebba-11e7-92e9-1f12a1d02e63.gif)

Expected behavior:
![tern](https://user-images.githubusercontent.com/22029477/34406676-abc9326e-ebba-11e7-8f2d-cef061c0b277.gif)

Also notice that the tooltip doesn't disappear when typing in the "scope"
 of the bracets `()`, unless a new scope is created like a function, here is an example: 

![tern2](https://user-images.githubusercontent.com/22029477/34406925-f3eabee0-ebbb-11e7-861b-aa434768cdb8.gif)

**Comment by tomv564** [comment]
Hi @luka-lazov, thanks for the detailed reports, I agree both are important usability issues with the current signature help.

> Add bold and underline to an active parameter.

This was in @rwols's original implementation but we decided to merge without this feature.
The current implementation takes the `label` field from the server's SignatureHelp response and passes it through the syntax highlighter.
The initial implementation did a search & replace on the highlighted output to add bold/underline by parameter name. Needless to say this falls apart with similarly named parameters etc.
Breaking apart the parameters block and highlighting by parameter index would avoid this, but would also burden LSP with having to know how signatures can look in all the languages it supports.

> Also notice that the tooltip doesn't disappear when typing in the "scope"
of the bracets

The work for this is in a branch waiting to be merged: https://github.com/tomv564/LSP/tree/keep-signature-help-open. I didn't merge it yet as this is an example where we have to fight Sublime Text (see the linked issue / the `on_hide`), but it seems inevitable to me.

I think it's time we have another look at solving both issues aiming for the "it works 80% of the time" sweet spot.

**Comment by rwols** [comment]
I intend to revisit that work on highlighting the active param; we should have it as an option beside the "classic" mdpopups-style.

**Comment by tomv564** [comment]
Note that tern's popup handling is extremely simple - perhaps the autocomplete setting prevents sublime from closing popups on certain keystrokes?

https://github.com/ternjs/tern_for_sublime/blob/91a27a39b1b0a33a9043aa685e1ee48c64a58274/utils/renderer.py#L194-L202

**Comment by tomv564** [comment]
Initial impression was deceiving: The tern plugin does little with Sublime, but does some pretty language-specific parsing to determine if the cursor is in a signature: https://github.com/ternjs/tern_for_sublime/blob/91a27a39b1b0a33a9043aa685e1ee48c64a58274/tern.py#L465-L482

Using scopes to detect if we're in a call signature did not turn out well - the Typescript syntax I am using does not even have the `meta.function-call` scope :/

Looking at the tern logic, I propose we take some of its ideas:

- Store the start of the first & current argument when requested by '(' or ','.
- Cache signature help results with those positions
- On selection change, re-render the popup (what if the user doesn't want it?)
- On selection change, hide the popup if the cursor has left the argument list (does sublime expose a "find matching param" in its API?)

Highlighting the current argument (which @rwols already started on ) might be best done _after_ these changes.

**Comment by tomv564** [comment]
This was addressed by #235, which turned added a `highlight_active_signature_parameter` setting defaulted to true.
