### ISSUE TITLE
How to set flake8 configurationSources in pyls?

### ISSUE THREAD

**Issue by gerardroche** [tomv564/LSP#239]
The `python-language-server` says:

> The default configuration source is pycodestyle. Change the `pyls.configurationSources` setting to `['flake8']` in order to respect `flake8` configuration instead.

How do you set `pyls.configurationSources` from Sublime Text?

I've tried various different settings e.g:

```

    "clients": {
        "pyls": {
            "command": [
                "~/.local/bin/pyls",
            ],
            "scopes": ["source.python"],
            "syntaxes": ["Packages/Python/Python.sublime-syntax"],
            "languageId": "python",
            "settings": {
            },
            "initializationOptions": {
                "configurationSources": ["flake8"]
            },
        },
    }
```

**Comment by gerardroche** [comment]
I think I must be expecting behaviour that the python language just doesn't provide.

You can debug `pyls` with something like:

```
    "clients": {
        "pyls": {
            "command": [
                "~/.local/bin/pyls"
                "--log-file",
                "/tmp/pyls.log",
                "-vvv"
            ],
            "scopes": ["source.python"],
            "syntaxes": ["Packages/Python/Python.sublime-syntax"],
            "languageId": "python",
            "settings": {
                "pyls": {
                    "configurationSources": ["flake8"],
                }
            },
        },
}
```

As you can probably see, I discovered that if you pass:

```
                "pyls": {
                    "configurationSources": ["flake8"],
                }
```

`pyls` seems to recognise it. It even looks like like it's loading the correct configuration. A `.flake8` file in the root of the project:

```
[flake8]
max-line-length = 120

ignore = D100,D101,D102,D103,D104,D105,D107
```

But in the diagnostics panel I get:

```
 ◌ lib/file.py:
       14:1   	pycodestyle 	warning   	E302 expected 2 blank lines, found 1
       25:1   	pycodestyle 	warning   	E303 too many blank lines (4)
        1:1   	pydocstyle  	warning   	D100: Missing docstring in public module
       11:1   	pydocstyle  	warning   	D103: Missing docstring in public function
       14:1   	pydocstyle  	warning   	D103: Missing docstring in public function
       18:1   	pydocstyle  	warning   	D103: Missing docstring in public function
      108:1   	pydocstyle  	warning   	D103: Missing docstring in public function
      114:1   	pydocstyle  	warning   	D103: Missing docstring in public function
```

`D100` and `D103` should be ignored. 

But besides that, I'm expecting `flake8` to be used, not `pycodestyle` or `pydocstyle`.

**Comment by gerardroche** [comment]
For anybody who hits this issue, this is how you configure it:

```
            "settings": {
                "pyls": {
                    "configurationSources": ["flake8", "pycodestyle"],
                }
```

The above says use `flake8` configurations, else use pycodestyle configations.

If you interested in the code of those configurations:

* flake8: https://github.com/palantir/python-language-server/blob/85907d6f7af5aaf1d6fd13c543327319b0c02282/pyls/config/flake8_conf.py
* pycodestyle: https://github.com/palantir/python-language-server/blob/85907d6f7af5aaf1d6fd13c543327319b0c02282/pyls/config/pycodestyle_conf.py

You don't have to define both, you can just define one if you like:

```
            "settings": {
                "pyls": {
                    "configurationSources": ["flake8"],
                }
```

if you want to debug the python-language-server you set verbose flags:

```
        "pyls": {
            "command": [
                "~/.local/bin/pyls",
                "-vvv"
            ],
            "scopes": ["source.python"],
            "syntaxes": ["Packages/Python/Python.sublime-syntax"],
            "languageId": "python",
            "settings": {
                "pyls": {
                    "configurationSources": ["flake8", "pycodestyle"],
                }
            },
        },
```

That'll give you extra debug messages from `pyls` (mine is located in `~/.local/bin/pyls`, yours may not be).

There is a [bug in pyl](https://github.com/palantir/python-language-server/issues/210) where some user configurations are not recognised, but that's not much to do with sublime/LSP so I'm going to close this issue.

**Comment by tomv564** [comment]
Thanks for the research and documentation!

 I'm not envious of `pyls`'s need to support so many different linters and respective configurations :)

**Comment by Mario4420** [comment]
where exactly is the config file?
