### ISSUE TITLE
Failed to initialize php language server on win10

### ISSUE THREAD

**Issue by django-wong** [tomv564/LSP#240]
Win10 x64
Sublime 3156
LSP commit c9d0fd4bdb5e947d2619b183802a91e30c121751
PHP 7.1.5 (cli)
felixfbecker/language-server： v5.3.4

The console does not provide enough information, even though I have set the all log_* to true in the settings.
Here are my settings and logs, hope it can help you diagnose the problem.

LSP.sublime-settings
```json
{
	"auto_show_diagnostics_panel": false,
	"clients":
	{
		"phpls":
		{
			"command":
			[
				"php",
				"-d",
				"memory_limit=4096M",
				"C:\\Users\\me\\.vscode\\extensions\\felixfbecker.php-intellisense-2.2.5\\vendor\\felixfbecker\\language-server\\bin\\php-language-server.php"
			],
			"enabled": true,
			"languageId": "php",
			"scopes":
			[
				"source.php",
				"embedding.php"
			],
			"syntaxes":
			[
				"Packages/PHP/PHP.sublime-syntax"
			]
		}
	},
	"complete_all_chars": true,
	"completion_hint_type": "detail",
	"diagnostics_gutter_marker": "dot",
	"diagnostics_highlight_style": "underline",
	"log_debug": true,
	"log_stderr": true,
	"log_payloads": true,
	"log_server": true,
	"only_show_lsp_completions": false,
	"resolve_completion_for_snippets": true,
	"show_diagnostics_in_view_status": false,
	"show_diagnostics_phantoms": true,
	"show_status_messages": true,
	"show_view_status": true
}
```

Console output
```
...
LSP: global clients: phpls=True
LSP: starting active= C:\Users\me\Workspace\NuPoint\NuPoint - PHP\app\Http\Controllers\APIv1\OrderController.php other= 0
LSP: starting in C:\Users\me\Workspace\NuPoint\NuPoint - PHP
LSP: starting ['php', '-d', 'memory_limit=4096M', 'C:\\Users\\me\\.vscode\\extensions\\felixfbecker.php-intellisense-2.2.5\\vendor\\felixfbecker\\language-server\\bin\\php-language-server.php']
LSP:  --> initialize
lang_service_enabled: True
LSP: LSP stderr process ended.
LSP: LSP stdout process ended.
...
```

When I open a .php file and try to hover on code
```
LSP: Already starting on this window: phpls
LSP: phpls not available for view C:\Users\me\Workspace\Demo\Demo - LSP\index.php in window 2
LSP: Already starting on this window: phpls
```

composer.json
```
{
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "felixfbecker/language-server": "v5.3.4"
    },
    "scripts": {
        "parse-stubs": "LanguageServer\\ComposerScripts::parseStubs",
        "post-update-cmd": "@parse-stubs",
        "post-install-cmd": "@parse-stubs"
    }
}

```

**Comment by tomv564** [comment]
Clearly we need better logging (or perhaps sockets / named pipes support) for PHP for Windows as we've seen mostly unsolved issues with it. It worked for you before, right?

I'll try to duplicate your setup in the next couple of days.

**Comment by django-wong** [comment]
> It worked for you before, right?

No. Actually This is the first time I try on Windows

**Comment by tomv564** [comment]
It looks the same as https://github.com/tomv564/LSP/issues/151, so you're definitely not the only person to have issues on Windows.

**Comment by tomv564** [comment]
I started some work on tcp support in PR #248.

It's strange that there is no output at all from the PHP language server when stdin/stdout get killed.
I don't recognise the `lang_service_enabled: True` line.
What if you just start it manually from the command line?
I see you had a `-d` argument in the command, is that needed?
Any options in the php.ini to toggle surface some errors?

**Comment by django-wong** [comment]
Hi, I left my PC at home. I will check the command output and `php.ini` when I get home later today.

`-d` and `memory_limit=4096M ` are not mandatory

**Comment by django-wong** [comment]
The command line just output nothing (it seems waiting for input).
I have `error_reporting = E_ALL` in the `php.ini`

**Comment by django-wong** [comment]
` lang_service_enabled` probably output by typescript plugin

**Comment by tomv564** [comment]
Ok! I'll continue setting it up in Windows so I can test the TCP setup.
I just checked how the VS Code extension runs PHP language server - it only supports TCP because of issues with blocking stdio (which plagues Windows mostly):
https://github.com/felixfbecker/vscode-php-intellisense/blob/master/src/extension.ts#L65

**Comment by tomv564** [comment]
TCP support is now merged into master, I tested the php language server with these settings:
```
"phpls":
		{
			"command": [
				"php",
				"~/vendor/felixfbecker/language-server/bin/php-language-server.php",
				"--tcp-server=0.0.0.0:5555"
			],
			"enabled": true,
			"tcp_port": 5555
		}
```
Can you let me know if it works for you?

**Comment by tomv564** [comment]
Closing this as we got the language server on Windows via TCP in #151. There are some helpful troubleshooting tips there, too!
