### ISSUE TITLE
Passing argument to language server?

### ISSUE THREAD

**Issue by otto-md** [tomv564/LSP#241]
Hi and thanks for a nice package.

Its seems like the go-langserver got a new argument `-gocodecompletion` when https://github.com/sourcegraph/go-langserver/pull/219 was merged.

Changing the LSP package setting to: `"command": ["go-langserver -gocodecompletion"],` didn't work. Is there another way of doing this?

Would more changes be needed to get `textDocument/completion` support?

**Comment by rwols** [comment]
Can you try `"command": ["go-langserver",  "-gocodecompletion"],` ?

**Comment by otto-md** [comment]
That seems to work. I event get some code completion now. Thanks!
