### ISSUE TITLE
initializationOptions not being passed to the server

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#245]
I have set my settings like:
```json
{
	"clients": {
		"pyls": {
			"enabled": true,
			"initializationOptions": {
				"--verbose": 3
			}
		}
	}
}
```
But when the server starts, it does not got the option on its command line:

![image](https://user-images.githubusercontent.com/5332158/35052542-f7616384-fb8e-11e7-992e-85b75314625f.png)

**Comment by tomv564** [comment]
This is as expected, initializationOptions are included in the first request to the language server _once it has been started_ (see: https://microsoft.github.io/language-server-protocol/specification#initialize)
I think few language servers use it.

The correct way to specify pyls's verbosity is to edit the `command` setting of your pyls client config:

```
"pyls":
    {
      "command": ["pyls", "-vv"],
    }
````

So far I see `-v` corresponds to INFO and `-vv` corresponds to DEBUG 
See: https://github.com/palantir/python-language-server/blob/af4dcb325d70629435456ce253275edbb84877e1/pyls/__main__.py#L59-L64
```

Hope this helps!

**Comment by evandrocoan** [comment]
Thanks!
