### ISSUE TITLE
toplevel completions are ignored

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#25]
The CompletionHandler drops all completions from the language server, if the cursor is not located directly after a completion character.

```python
class CompletionHandler(sublime_plugin.EventListener):
   
    ...

    def on_query_completions(self, view, prefix, locations):
        ...
                 if prev_char not in autocomplete_triggers:
                    return None
```

This prevents toplevel completions from being displayed. Jedi as an example, provides a list of all available modules after the `import` keyword. Those completions are filtered at the moment.

Instead of filtering I'd rather suggest to use the completion character published by the language server to dynamically create an auto-completion trigger for the view. Accessors like `->` could be added as `>` and the `on_query_completions` could check for the preceding `-` to decide whether to provide completions or not.

**Comment by philippotto** [comment]
I agree! To rephrase it a bit: Every time ST shows autocompletions, a request should be made to the server. ST does this by default only for "alpha" characters. This is why the `autocomplete_triggers` should be used to invoke additional autocompletion queries.

**Comment by deathaxe** [comment]
In #4 was discussed how to easily setup these additional triggers. With the knowledge about language-servers providing these information, I could imagine to automatically add this setting to each supported view. This way no trigger needs to be configured by user.

**Comment by tomv564** [comment]
This investigation supports your conclusion:
https://github.com/Microsoft/language-server-protocol/issues/268

and I am for turning on completions for alphanumeric characters.

But I would like to verify that the performance is acceptable, some recent implementations against the javascript/typescript implementations ran into problems: https://github.com/sourcegraph/javascript-typescript-langserver/issues/331

**Comment by tomv564** [comment]
@philippotto, it might be good to have the Flow language server additionally send `['.']` for triggerCharacters. Do you want to create an issue?

**Comment by philippotto** [comment]
@tomv564 Sure, I created it [here](https://github.com/flowtype/flow-language-server/issues/52).

Regarding potential performance problems, this answer from your referenced issue is interesting:

> Drastically reducing how often we called completion has solved problems on Atom. Now we just trigger it on . and when manually requested.

As long as autocompletions are not blazingly fast anyway, I would leave it at that logic (on . and manually requesting). Hitting CTRL + Space for requesting autocompletions is probably idiomatic? We could still have a setting for triggering it after each keystroke (throttled), which is off by default maybe?

**Comment by deathaxe** [comment]
The current implementation always cancels auto-completions not triggered by the triggerCharacter. No matter whether it is triggered automatically or manually by Ctrl+Space. A package doesn't know whether completion was triggered manually or automatically.

I saw implementations, which returned no completions with word and explicit completions disabled in on_query_completion() but only fired the request to the language server. If the respond is received, they manually called show_completion to open it. This may cause some delay but doesn't cause ST to block while waiting for an answer.

**Comment by philippotto** [comment]
> A package doesn't know whether completion was triggered manually or automatically.

Couldn't we add a keybinding for ctrl + space which calls show_completion?

**Comment by tomv564** [comment]
@philippotto ctrl+space is already hooked up, but LSP disables most calls as it expects the character before the cursor to be a triggerCharacter.

@deathaxe can you think of a way to detect manually invoked completions? I think that's a fairly safe step forward for now.

As for your second suggestion, I like seeing sublime's word completions as they are often relevant and/or confirm that I'm typing the symbol correctly. Perhaps we can still return word completions and replaced with LSP completions when they arrive?

**Comment by philippotto** [comment]
> @philippotto ctrl+space is already hooked up, ...

With "hooked up" you mean that it's a default keybinding of ST? We we could either override it or choose another keybinding? I think this is the easiest way to distinguish between manually and automatically invoked completions. But maybe there's another way..


> I like seeing sublime's word completions as they are often relevant and/or confirm that I'm typing the symbol correctly. Perhaps we can still return word completions and replaced with LSP completions when they arrive?

Totally agree. I like ST's fast completions and wouldn't want it to be aggravated by an extension. Adding the LSP completions when they arrive sounds good, but I'd suggest to add them to the bottom of the already provided list. Otherwise, the user might have already navigated in the list of completions and then the entire list gets replaced, which would be annoying.

**Comment by deathaxe** [comment]
> Perhaps we can still return word completions and replaced with LSP completions when they arrive?

1. Sublime Text merges all completions from plugins/sublime-completions/words in this order of priority. A plugin has the ability to tell ST to skip explicit and or word-completions (see: https://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.EventListener)

2. Doing so will in most cases result flickering as simply returning None in on_query_completions() will show completions from sublime-completions/words and some milliseconds later it will reopen with the results from language-server. Try Anacoda, then you'll know what I mean. It is just a terrible feeling.

So the only two solutions from my point of view are:
- block and wait for results from language-server
- cancel completion and call show_completions if response arrived.

To handle automatic/manual completions, we may modify the "auto_complete" view setting to disable automatic completions, but I didn't check that right now.

**Comment by tomv564** [comment]
Both word and manual completions are now enabled, hoping to iron out the remaining issues in the near future!

**Comment by rwols** [comment]
I stil need to write my own triggers per language, right?

**Comment by tomv564** [comment]
Yes, for non-alphabetic characters. 
LSP should honour manual completions (`ctr+space`) by default, if you want to try if a given trigger character gives good results with your language server.
