### ISSUE TITLE
Investigate the transitions library

### ISSUE THREAD

**Issue by rwols** [tomv564/LSP#257]
Currently, the completion handler uses a home-brewed state machine. From experience I know that once you recognize a state-machine you should probably start using a proper state-machine library. Like [transitions](https://github.com/pytransitions/transitions). Ideally this would be a Package Control dependency but there is currently nobody maintaining this. The "is visible" state machine of the signature help handler could also benefit from this. Any thoughts?

**Comment by tomv564** [comment]
Completions for sure would be a good use for a properly written state machine.

My impression of transitions is it's very string-based configuration (so mypy won't help us much), and configuring the machine may hide the equally relevant handling of language server and sublime APIs.

What is your opinion on using the state pattern as shown on http://python-3-patterns-idioms-test.readthedocs.io/en/latest/StateMachine.html ?

**Comment by tomv564** [comment]
Anything to add to this @rwols ? I'd welcome a PR or example on how the completions logic would improve with transitions.

**Comment by rwols** [comment]
I haven't found the time to try this yet; it's okay to close this 👍
