### ISSUE TITLE
Missing diagnostic highlighting when SublimeLinter is not installed

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#26]
LSP currently leans on SublimeLinter's scopes (`sublimelinter.mark.error`) as they are guaranteed to be present in any color scheme.

There is now a configuration setting named `diagnostic_error_region_scope` since https://github.com/tomv564/LSP/commit/f1be851d6c0e587145a64da1d4de22d6000eed70 for users to provide an alternative, but this is not an acceptable solution.

There is an initiative to popularise `markup.*` scopes at https://github.com/sublimehq/Packages/issues/1036, perhaps LSP should default to those?

**Comment by tomv564** [comment]
#23 might be an example of the broken user experience when the user only sees the default phantoms.

**Comment by deathaxe** [comment]
I thought about it yesterday, too, with PR #29 as a result. Maybe we could add `markup.deleted` as default scope, which should be part of most color schemes.

But this might be a general issue with color schemes. There is no really complete RFC about which scopes to support and which not. The minimal set of required scopes in https://www.sublimetext.com/docs/3/scope_naming.html does not target `markup.` at all. So you'll find (older) color schemes missing certain scopes for sure.

From my point of view clean scopes like meta.error, meta.warning, meta.info should be used and pronounced as such. With a hint in the README about the used scopes (see GitGutter) everyone is open to file an issue in his favorite's color scheme repository or modify/add the scopes.

**Comment by tomv564** [comment]
Fixed by https://github.com/tomv564/LSP/commit/5e349a746e4a8513a44548bda1687ea02bdba4e4
