### ISSUE TITLE
Keyboard shortcut for mousover tooltip?

### ISSUE THREAD

**Issue by gilbert** [tomv564/LSP#260]
As an alternative to using the mouse to hover over an identifier for tooltip info, is there a configurable command to see info for the identifier currently under the cursor? [Typescript sublime](https://github.com/Microsoft/TypeScript-Sublime-Plugin#features) has this feature, calling it "Quick Info".

**Comment by tomv564** [comment]
Good idea, this can be quickly implemented. The hard part with Sublime Text is usually finding a free keybinding, so perhaps we can leave that up to the user unless a good default can be found?

**Comment by gilbert** [comment]
Yes, I think leaving it up to the user is best.

**Comment by tomv564** [comment]
Pushed this to master, tested with this line in the keybindings:
```
	{ "keys": ["super+option+h"], "command": "lsp_hover"}
```

Thanks for the suggestion!
