### ISSUE TITLE
Automatically wrap the settings dictionary with the client name

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#262]
Currently we need to manually repeat the client name on the configuration: https://github.com/tomv564/LSP/issues/244#issuecomment-358483406
```javascript
{
    "clients": {
        "pyls": {
            "enabled": true,
            "settings": {
                "pyls": {
                    "plugins": {
                        "pycodestyle": {
                            "enabled": false
                        }
                    }
                }
            }
        }
    }
}
```

However, we can wrap it on a `pyls` dictionary after loading it, then we can write it simpler like:
```javascript
{
    "clients": {
        "pyls": {
            "enabled": true,
            "settings": {
                "plugins": {
                    "pycodestyle": {
                        "enabled": false
                    }
                }
            }
        }
    }
}
```
Now, do we have another setting which goes on the same level as `"plugins"`?

If not, then we can also internally wrap the everything under setting under `pyls-->plugins` and write a simpler settings without the extra `pyls-->plugins`:
```javascript
{
    "clients": {
        "pyls": {
            "enabled": true,
            "settings": {
                "pycodestyle": {
                    "enabled": false
                }
            }
        }
    }
}
```

**Comment by tomv564** [comment]
As I mentioned in the comment, it is _pyls_ that determines the shape of its configuration. Other language servers (see the [Rust Language Server](https://github.com/rust-lang-nursery/rls)) do not have the deeply nested configuration structure. 

Imagine if LSP had parsing logic to make the settings look right for every supported language server - wouldn't it be a huge mess? Plus, then I would have to make changes whenever each language server changes its configuration structure.

Is it also not risky to assume that there will never be another setting adjacent `plugins`?
