### ISSUE TITLE
Hide Context.sublime-menu when working on projects without language servers

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#266]
![image](https://user-images.githubusercontent.com/5332158/35592598-a96edd08-05f4-11e8-844d-9ad02da032dc.png)

**Comment by rwols** [comment]
This is a good idea, but is it implementable?

**Comment by evandrocoan** [comment]
I am implementing it now. I created this class:
```python
class LspContextMenu(sublime_plugin.TextCommand):
    def __init__(self, view):
        super(LspContextMenu, self).__init__(view)

    def is_visible(self):
        return is_supported_view(self.view)
```

Now I am extending it for every context menu command class:
```python
class LspSymbolRenameCommand(LspContextMenu):
```

I am just not sure whether this `return is_supported_view(self.view) is going to do the job right.

**Comment by evandrocoan** [comment]
@rwols, I opened a pull request with it. Seems to be working fine here. You can try it out.

**Comment by tomv564** [comment]
Nice initiative, I wonder if there is any relation between `is_enabled` and `is_visible` being called? Can we remove some duplicate checks if the API guarantees that `is_enabled` is not called if `is_visible` returns false?

**Comment by evandrocoan** [comment]
>  I wonder if there is any relation between is_enabled and is_visible being called? Can we remove some duplicate checks if the API guarantees that is_enabled is not called if is_visible returns false?

I just did it and no errors so far. Anyways, if there were errors, it would be a Sublime Text bug because makes no sense for the Sublime Text API to be calling `is_enabled` and it `is_visible` is already returning false.
