### ISSUE TITLE
The language server is not closed when you use Project -> Quick Switch Project...

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#268]
But if you use `Project -> Open Recent -> Unrelated Project` and a new window opens and you close the old one, the language server is shutdown.

**Comment by tomv564** [comment]
This _should_ be currently handled by a `initialize_on_open` calling `unload_old_clients` when a supported document is opened in the project you've switched to. If you switched to a project where you're not opening supported documents.
If there is a clear event for detecting Quick Switch Project this would allow significant improvements, but I'm trying to avoid listening to _everything_ just to make this scenario work.
