### ISSUE TITLE
Blocking Sublime Text async thread while waiting the language server to answer

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#269]
Related to: 

https://github.com/tomv564/LSP/issues/255 python-language-server hanged Sublime Text by several seconds on file close event

**Comment by tomv564** [comment]
Why not add this to the existing issue?

**Comment by tomv564** [comment]
Also a duplicate of https://github.com/tomv564/LSP/issues/146?
Again, investigate the language server or include logs if you think LSP is doing something wrong
