### ISSUE TITLE
PHP supports

### ISSUE THREAD

**Issue by django-wong** [tomv564/LSP#27]
Hi @tomv564 , one thing I really want to see is LSP can work with PHP.
Maybe I was doing something wrong, but I got this from console panel after I setup the [php-language-server](https://github.com/felixfbecker/php-language-server)
```
LSP: starting in /Users/DjangoWong/Workspace/freight-x 
LSP: starting ['php', '~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php'] 
LSP: client registered for window 2 {'phplsp': <LSP.main.Client object at 0x10f636f90>} 
LSP: LSP: LSP stdout process ended.LSP stderr process ended.  
```
And this is my lsp settings:
```json
"clients": {
	"phplsp": {
		"command": ["php", "~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php"],
		"scopes": ["source.php"],
		"syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
		"languageId": "php"
	},
},
```

btw, Im using ST3142 and php7 on MacOS sierra 10.12.6

Thanks

**Comment by rwols** [comment]
Could you try replacing `~` with your home directory manually?

**Comment by django-wong** [comment]
Thanks, that work for me @rwols

**Comment by django-wong** [comment]
Hi, me again...
I can see the auto-complete now but when I press `Enter` the `$re` been removed and nothing more happens.

![image](https://user-images.githubusercontent.com/4019240/29496219-f1512410-8600-11e7-8fd1-66faa83d84f6.png)

**Comment by tomv564** [comment]
Hi, thanks for coming back to report.

The completions items returned by the PHP language server look correct.
LSP should be inserting the contents of the `label` field as we don't support the `textEdit` field yet.

Sublime Text can be configured to 'commit' a completion on Enter or Tab, did you try both keys and/or check what the `auto_complete_commit_on_tab` setting contains?

**Comment by django-wong** [comment]
Yes, I tried both enter and tab, `auto_complete_commit_on_tab` was true.
I will revert ST to a freshly installed state and try again.

**Comment by django-wong** [comment]
Same problem in freshly installed state.

**Comment by tomv564** [comment]
I just installed the PHP language server, I'll try to reproduce your issue shortly!

**Comment by tomv564** [comment]
Funny bug, LSP needs to escape the leading '$' with a '\$' or Sublime Text.

I pushed a fix for this to master: https://github.com/tomv564/LSP/commit/a0190f0eff49e07b71c92bfb134c13e7bfcfd177

It solved your issue for me, but I found completions were still behaving strange. Perhaps this thread can help: https://forum.sublimetext.com/t/auto-complete-issues-when-snippet-starts-with/7322/7

**Comment by rwols** [comment]
As an aside, maybe expand any `~` to the user's homedir in a setting with [`os.path.expanduser`](https://docs.python.org/3/library/os.path.html#os.path.expanduser).

**Comment by broiniac** [comment]
> Could you try replacing ~ with your home directory manually?
Awesome! That was an issue for me as well!

@tomv564 Thank you so much for these awesome package!

**Comment by tomv564** [comment]
Thanks for trying the package!
I am trying to add some documentation for the PHP language server for fellow users, can you help me complete these details?

* PHP7 is needed, and `composer config minimum-stability RC`
* Is it customary to install the language server in the project or globally using `composer global require felixbecker/language-server`?
* Any other settings needed for this language server to work? (completion triggers?)

**Comment by django-wong** [comment]
I have installed it globally.

The following is the whole process:
1. modify `~/.composer/composer.json` to set
```
"minimum-stability": "dev",
"prefer-stable": true,
```

2. run `composer global  require felixfbecker/language-server`

3. run `composer run-script --working-dir=~/.composer/vendor/felixfbecker/language-server parse-stubs`

4. modify `LSP.sublime-settings - User`
```
{
	"clients": {
		"phplsp": {
			"command": ["php", "/Users/DjangoWong/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php"],
			"scopes": ["source.php"],
			"syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
			"languageId": "php"
		}
	}
}
```

5. add triggers to `Preferences.sublime-settings - User`
```
"auto_complete_triggers":
[
	{
		"characters": "$>abcdefghijklmopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:\\",
		"selector": "source.php"
	}
],
```

**Comment by tomv564** [comment]
Thanks for sharing!

We'll make some changes to allow ~ when setting the command, and enable
completions on alphabetical keystrokes by default in the future.

**Comment by tomv564** [comment]
Completions with `$` were fixed, and configuration has been documented (see https://lsp.readthedocs.io).
Please open new issues to report errors/suggestions or get help using the PHP language server with LSP.
