### ISSUE TITLE
Hanging Sublime Text while waiting the language server to respond

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#270]
Related to:

1. https://github.com/tomv564/LSP/issues/255 python-language-server hanged Sublime Text by several seconds on file close event

This is not a simple problem. Sometimes the language server goes nuts and takes like 10 to 25 seconds to just respond `No definitions found`.

**Comment by tomv564** [comment]
What is the difference with #269 and #255?

**Comment by evandrocoan** [comment]
1. #269 is for the background task which does not hang the Sublime Text interface, but all async pending tasks.
1. #255 is for didClose event
1. #270 is for on_hover event

**Comment by evandrocoan** [comment]
Perhaps you would like to merge them all at one?

**Comment by tomv564** [comment]
Duplicate of https://github.com/tomv564/LSP/issues/146. Also your situation will be improved more if you fix the language server issue.
