### ISSUE TITLE
Add CSS language server example

### ISSUE THREAD

**Issue by bgarrant** [tomv564/LSP#275]
Any chance you can show an example for how to connect the Microsoft VS Code CSS/Sass language server?

**Comment by bgarrant** [comment]
How can I connect to https://github.com/Microsoft/vscode/tree/master/extensions/css?

**Comment by tomv564** [comment]
Microsoft's VS Code services are often only configured to be loaded directly by the VS Code extension, with communication over Node interprocess communication.

They do have the ability to convert to a standalone server over stdio with some effort, I tried this out with their eslint service here: https://github.com/Microsoft/vscode-eslint/compare/master...tomv564:add-stdio-support

The exact same thing is also being done for a popular PHP extension in this issue: https://github.com/tomv564/LSP/issues/259 if you'd like some more inspiration!

**Comment by evandrocoan** [comment]
That CSS server can be only supported by VSCode or it was not yet ported to be run outside VSCode. You can open a issue on their issue tracker  asking about that.

While I was searching on the https://github.com/Microsoft/vscode/issues, I found this issue:

1. https://github.com/Microsoft/vscode/issues/39088 [css] API/configuration to extend the CSS language server

Then I think they already had extracted the language server from VSCode and its code is hosted on https://github.com/Microsoft/vscode-css-languageservice

Or perhaps I am wrong and they are not the same language server.

**Comment by tomv564** [comment]
Ah, the Eclipse guys figured this one out, found out relevant code here:
https://github.com/mickaelistria/eclipse-bluesky/blob/e05d55ad2e4a68a5f3949ef96a4e35845b4f5024/org.eclipse.bluesky/src/org/eclipse/bluesky/css/CSSLanguageServer.java#L40

in other words:
```bash
# perhaps install globally?
npm install vscode-css-languageserver
```

Then in your config:
```
 "vscode-css":
    {
      "command": ["node", "PATH_TO_NODE_MODULES/vscode-css-languageserver/out/cssServerMain.js", "--stdio"],
      "scopes": ["source.css"],
      "syntaxes": ["Packages/CSS/CSS.sublime-syntax"],
      "languageId": "css"
    },

```

**Comment by bgarrant** [comment]
I will try this. Thanks so much

**Comment by ctf0** [comment]
@tomv564 is it possible to use the same server for scss ? if yes can u plz tell me how to configure it ?

**Comment by tomv564** [comment]
Documented in 3f91f3878e6178260e67731b1c87f70901dbfd6b, please open issues if LSP doesn't cooperate with this server!
