### ISSUE TITLE
Feature request: Toggle diagnostic panel

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#283]
Hi Tom, I have a suggestion.

Right now I have a keyboard shortcut to open the diagnostic panel `ctrl+shift+m`.
As you can see. When I open the panel with that keybinding, and press the keybinding again the panel is still visible. 

![notoggle](https://user-images.githubusercontent.com/22029477/36727088-45b28d4a-1bbc-11e8-9f72-3a6d7f611f09.gif)

Wouldn't it be better if the panel could be toggled like this? :)

![output3](https://user-images.githubusercontent.com/22029477/36727446-8e5a78d6-1bbd-11e8-8968-a914264a20da.gif)

If the answer is yes? I have already done that and I could create a pull request if you want :)

**Comment by tomv564** [comment]
Hi, agree this sounds useful! Thanks for the examples as well.
Looking forward to a pull request!
