### ISSUE TITLE
Vue support using vue-language-server

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#284]
I successfully started the server, and got some suggestions, but at some point I stop getting them. 

First I installed:
`npm install -g vue-language-server` more info about the server can be found [here](https://www.npmjs.com/package/vue-language-server).

And my configuration:
```json
"vue-ls":{
	"command": [
		"node",
		"/ABSOLUTE/PATH/TO/SERVER/.npm-global/bin/vls"
	],
	"enabled": true,
	"languageId": "vue",
	"scopes": [
		"text.html.vue"
	],
	"syntaxes": [
		"Packages/Vue Syntax Highlight/vue.tmLanguage"
	]
}
```

### This is what works:
* it starts :D
* get warnings from vue, 
* get attributes and directives(v-if, v-show...) suggestions

![output3](https://user-images.githubusercontent.com/22029477/36752615-d6d01576-1c03-11e8-9614-1c89a530c30b.gif)

### Here is what doesn't work:
* get property suggestions from the `data` method defined in the `exporte default object`, in places like `v-if=""` or `v-show=""` or in the curly brackets `{{ }}`  

### This is how it should work:
Note:  `ctrl+space` is my keybinding for getting autocompletion.
* I have a `person` object, and a `messages` array defined in the `data` method.
* I expect if I am in a `v-if=""` directive, and type `per` and press `ctrl+space` I should get `person` autocompleted.
* If I then continue typing `.na` and press `ctrl+space` I should get `v-if="person.name"`

### Here is a working example in vs code:
![output3](https://user-images.githubusercontent.com/22029477/36755842-b3cf795e-1c0d-11e8-8473-e1bac6c54156.gif)

### Here is how it behaves in sublime:
* no autocomplete for `person` or `person.name`, and a strange sublime bug caught on type with curly bracket surrounding the `li` element. Probably has nothing to do with lsp.

![output3](https://user-images.githubusercontent.com/22029477/36756481-61df615c-1c0f-11e8-85a2-e2ea4793815f.gif)
 
In example bellow as you can see when I type `"message in mes"` and press `ctrl+space` I get nothing. 
It looks like it works at the end (see `message`, and `messages` suggestions inside the `li` tag) but that is probably sublimes own autocompletion. 

![output3](https://user-images.githubusercontent.com/22029477/36756756-379b2312-1c10-11e8-8d46-5b005e2569ce.gif)

* If you lost yourself in this long issue the problem is `getting property autocompletion`, and at some point if I trigger autocompletion, and don't get anything, I won't be able to get other completions like I used to get(v-if, v-for, v-show ...).

Sorry for the long issue, I just want to be specific. :)

**Comment by tomv564** [comment]
Thanks for the detailed description, could you enable debug logging and confirm / share in the logs what kind of textDocument/completion requests are being sent? 

Instructions are here: https://lsp.readthedocs.io/en/latest/#troubleshooting

**Comment by predragnikolic** [comment]
`object of type 'NoneType' has no len()` . This error happened when i tried to type between the {{ }} something and press `ctrl+space` for autocompletion. 
```
LSP: initialize on open 2 /home/predrag/Documents/sandbox/laravel/app/resources/assets/js/components/ExampleComponent.vue
LSP: starting in /home/predrag/Documents/sandbox/laravel/app
LSP: starting ['node', '/home/predrag/.npm-global/bin/vls']
LSP:  --> initialize
LSP: Unhandled notification: window/logMessage
LSP:  --> initialized
LSP: vue-ls client registered for window 2
LSP:  --> textDocument/didOpen
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/documentHighlight
LSP:  --> textDocument/documentHighlight
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/documentHighlight
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/documentHighlight
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/documentHighlight
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/documentHighlight
LSP:  --> textDocument/didChange
LSP:  --> textDocument/documentHighlight
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/documentHighlight
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/completion
Error handling server payload
Traceback (most recent call last):
  File "/home/predrag/.config/sublime-text-3/Packages/LSP/plugin/core/rpc.py", line 323, in receive_payload
    self.response_handler(payload)
  File "/home/predrag/.config/sublime-text-3/Packages/LSP/plugin/core/rpc.py", line 342, in response_handler
    self._response_handlers[handler_id](result)
  File "/home/predrag/.config/sublime-text-3/Packages/LSP/plugin/completion.py", line 257, in handle_response
    if len(items) > 1 and items[0].get("sortText") is not None:
TypeError: object of type 'NoneType' has no len()

LSP:  --> textDocument/didChange
LSP:  --> textDocument/documentHighlight
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/documentHighlight
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/documentHighlight
LSP: <--  textDocument/publishDiagnostics
```

**Comment by tomv564** [comment]
Thanks for the logs, we can see where the completion provider breaks.
Re-opening the document generally gets the completions working again, but let's look at the real issue.
The traceback points to completions.py:257, at which point the completions provider expects to have received either an object containing an `items` field with an array, or an array from the server:

```python
items = response["items"] if isinstance(response, dict) else response
```

This case doesn't handle `null` which has been added a few months ago as a valid response to a bunch of calls in https://github.com/Microsoft/language-server-protocol/issues/261

Personally I'm not too enthused about all these extra null checks needed to be done for almost no end-user value, but a spec is a spec :) 

Would welcome a PR handle all `None` responses in the above spec change as meaning "empty'.

**Comment by predragnikolic** [comment]
This seems to fix the error. Is this good? 

![2018-02-28-231114_681x382_scrot](https://user-images.githubusercontent.com/22029477/36816109-1f81678c-1cdd-11e8-8666-bfb694e1dde4.png)

**Comment by tomv564** [comment]
Looks like it prepares for the next trigger without failing 👍 
We should take a complete look at all the "new" possible null responses in the future.

**Comment by tomv564** [comment]
I pushed a variant of your fix to master (handling `null` as `[]`) and created another issue to cover all possible null responses. 

Looking at this issue, the following remains:

* Completion within strings is hard-disabled (this is intentional, see NO_COMPLETION_SCOPES in completion.py). We should fix this for eg. template literals. 

Can you share the scopes assigned to the strings following `v-for` or `v-if` attributes by using the "Show scope name" command from the Tools -> Developer menu?

* Error handling completion - this should be fixed now, can you confirm?

* Documenting this setup - should we add your example config to the docs?

**Comment by tomv564** [comment]
Documented in https://github.com/tomv564/LSP/commit/724edbaba84852396e1c76b5fc7b6f5d102c35d2
