### ISSUE TITLE
document_highlight_style highlights everything

### ISSUE THREAD

**Issue by chenglou** [tomv564/LSP#286]
Repro:

- Have lsp set up
- clone https://github.com/BuckleScript/bucklescript
- open `super_typecore.ml`
- See this behavior:

<img width="752" alt="screenshot 2018-02-28 17 00 19" src="https://user-images.githubusercontent.com/1909539/36821657-e0ba81e8-1ca8-11e8-8cf6-b5d22af9c30e.png">

Maybe accepting `document_highlight_style` of value `false` is fine to patch this too.

**Comment by tomv564** [comment]
Agreed, a flag to disable the highlighter seems to be missing. @rwols, do you want to look at this?

**Comment by rwols** [comment]
I have a fix almost ready. In the meantime, you can just use a bogus string for the `document_highlight_style` setting and it won't display anything (but it will still do the requests).
