### ISSUE TITLE
A setting to ignore language diagnostics from a certain language server

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#290]
I have a language server which is only sending non-sense as errors, i.e., the code is completely correct, but the language server somehow thinks otherwise: https://github.com/cquery-project/cquery/issues/493

I would not like to disable the language server because its other services like go to definition and documentation hover are working correctly.

**Comment by jfcherng** [comment]
+1 for this because I may somehow prefer using other linters to do diagnosis.

**Comment by tomv564** [comment]
Is this not achievable with an existing combination of settings keeping the panel closed and changing the `diagnostics_highlight_style` setting?

It's in everyone's best interest to keep the language servers working to their intended design and not bloat LSP with settings for all possible edge cases.
