### ISSUE TITLE
Set the language server CPU affinity to n cores when starting

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#291]
My system resources are limited and I cannot have a multi-threading language server eat 100% of all my CPU cores when they fell like.

I would restrict all my language servers processes to use the same CPU core, drastically reducing the impact all other applications when the language server goes nuclear on CPU usage.

**Comment by jfcherng** [comment]
Sounds like doing the first time indexing?

**Comment by evandrocoan** [comment]
Usually it is this which causes it, but just saving a file can also trigger it.

**Comment by tomv564** [comment]
Guessing this is also about `cquery` which advertises how much up-front processing it does? If that model doesn't work for you, perhaps take it up with them or see if `clangd` performs better?

`psutil` has support (https://github.com/giampaolo/psutil/issues/238) but not on OS-X, sounds like something you might add in your fork?
