### ISSUE TITLE
Enabling server in Project doesn't work without Global

### ISSUE THREAD

**Issue by ehuss** [tomv564/LSP#293]
### Bug:

When you first install LSP and open a relevant file, it instructs you to "Setup Language Server".  If you choose to enable the server in **Project**, the server doesn't actually start.

* Tested on Mac and Windows, with Python and RLS servers.
* LSP 0.4.2 installed from Package Control

### Reproduction
1. Delete `clients` settings from LSP.sublime-settings (or start with a fresh install).
2. Open a file that has a valid language server.
3. Notice it tells you to "Setup Language Server", run that command.
4. Choose "This Package Only".  Also try the `LSP: Enable Language Server in Project` command.
5. It will update your `.sublime-project`, but the server never actually starts.

Also notice with debug logs, it continues to say:

    LSP: config not available for view path/to/foo.py

### Workaround
If you enable the server globally, it works.  It also works if you then disable the server globally, but leave it enabled per-project.  

I suspect the issue is that a server will not work if there is no definition for it in `LSP.sublime-settings`.

### Expectations
Running "Enable Language Server in Project" for the first time should work.

**Comment by tomv564** [comment]
Thanks for the super-detailed bug report! 
I can take the investigation from here, or feel free to comment here if you want to fix it immediately :)

**Comment by tomv564** [comment]
This seems to be working in latest master
