### ISSUE TITLE
Add support for CompletionItem.textEdit (& additionalTextEdits)

### ISSUE THREAD

**Issue by nanoant** [tomv564/LSP#294]
* Windows 10 / macOS 10.13.3
* Latest LSP from Package Control
* EditorServiceHost (PowerShell) language server accoring to recipe at: https://github.com/PowerShell/PowerShellEditorServices/pull/629#issuecomment-373787797

LSP currently supports completion with `CompletionItem.insertText` only, while it may be good enough for some servers e.g. [python-language-server](https://github.com/palantir/python-language-server), for some cases like EditorServiceHost this is simply not enough as `insertText` requires some extra logic on editor side.

Concrete example for EditorServiceHost
1. `$tru`<kbd>Ctrl</kbd><kbd>Space</kbd> gets completed to `$$true` (double `$$`) instead of `$true`

    Payload:
    ~~~
    [
    {'filterText': '$true', 'insertText': '$true', 'sortText': '0001true', 'label': 'true', 'additionalTextEdits': None, 'detail': None, 'data': None, 'kind': 6, 'command': None,
     'textEdit': {'newText': '$true', 'range': {'end': {'line': 5, 'character': 2}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None}, {'filterText': '$tokens', 'insertText': '$tokens', 'sortText': '0002tokens', 'label': 'tokens', 'additionalTextEdits': None, 'detail': '[Token[]]', 'data': None, 'kind': 6, 'command': None, 'textEdit': {'newText': '$tokens', 'range': {'end': {'line': 5, 'character': 2}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None}, {'filterText': '$this', 'insertText': '$this', 'sortText': '0003this', 'label': 'this', 'additionalTextEdits': None, 'detail': None, 'data': None, 'kind': 6, 'command': None, 'textEdit': {'newText': '$this', 'range': {'end': {'line': 5, 'character': 2}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None}
    ]
    ~~~

2. `$env:U`<kbd>Ctrl</kbd><kbd>Space</kbd> gets completed to `$env:$env:USERPROFILE` instead of `$env:USERPROFILE`:

    Payload:
    ~~~
    [
    {'filterText': '$env:UATDATA', 'insertText': '$env:UATDATA', 'sortText': '0001UATDATA', 'label': 'UATDATA', 'additionalTextEdits': None, 'detail': None, 'data': None, 'kind': 6, 'command': None, 'textEdit': {'newText': '$env:UATDATA', 'range': {'end': {'line': 5, 'character': 6}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None}, {'filterText': '$env:USERDNSDOMAIN', 'insertText': '$env:USERDNSDOMAIN', 'sortText': '0002USERDNSDOMAIN', 'label': 'USERDNSDOMAIN', 'additionalTextEdits': None, 'detail': None, 'data': None, 'kind': 6, 'command': None, 'textEdit': {'newText': '$env:USERDNSDOMAIN', 'range': {'end': {'line': 5, 'character': 6}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None}, {'filterText': '$env:USERDOMAIN', 'insertText': '$env:USERDOMAIN', 'sortText': '0003USERDOMAIN', 'label': 'USERDOMAIN', 'additionalTextEdits': None, 'detail': None, 'data': None, 'kind': 6, 'command': None,
     'textEdit': {'newText': '$env:USERDOMAIN', 'range': {'end': {'line': 5, 'character': 6}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None},
    {'filterText': '$env:USERDOMAIN_ROAMINGPROFILE', 'insertText': '$env:USERDOMAIN_ROAMINGPROFILE', 'sortText': '0004USERDOMAIN_ROAMINGPROFILE', 'label': 'USERDOMAIN_ROAMINGPROFILE', 'additionalTextEdits': None, 'detail': None, 'data': None, 'kind': 6, 'command': None, 'textEdit': {'newText': '$env:USERDOMAIN_ROAMINGPROFILE', 'range': {'end': {'line': 5, 'character': 6}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None}, {'filterText': '$env:USERNAME', 'insertText': '$env:USERNAME', 'sortText': '0005USERNAME', 'label': 'USERNAME', 'additionalTextEdits': None, 'detail': None, 'data': None, 'kind': 6, 'command': None, 
     'textEdit': {'newText': '$env:USERNAME', 'range': {'end': {'line': 5, 'character': 6}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None},
    {'filterText': '$env:USERPROFILE', 'insertText': '$env:USERPROFILE', 'sortText': '0006USERPROFILE', 'label': 'USERPROFILE', 'additionalTextEdits': None, 'detail': None, 'data': None, 'kind': 6, 'command': None, 
     'textEdit': {'newText': '$env:USERPROFILE', 'range': {'end': {'line': 5, 'character': 6}, 'start': {'line': 5, 'character': 0}}}, 'commitCharacters': None, 'range': None, 'documentation': None}
   ]
   ~~~

Quoting https://microsoft.github.io/language-server-protocol/specification:

> The `insertText` is subject to interpretation by the client side. Some tools might not take the string literally. For example VS Code when code complete is requested in this example `con<cursor position>`  and a completion item with an `insertText` of `console` is provided it will only insert `sole`. Therefore it is recommended to use `textEdit` instead since it avoids additional client side interpretation.

Therefore for to avoid additional logic and misinterpretations `textEdit` (when provided by server) should be supported and used instead `insertText` by LSP and also (optionally `additionalTextEdits`).

**Comment by tomv564** [comment]
Hi, thanks for this investigation (and the PR which I'll look at shortly, too)!

Just to understand these cases, it looks like SublimeText (at least in the powershell syntax) considers `$` and `:` as symbol boundaries when applying completion results?

If so, yes, that would be hard to fix otherwise :)

Although `:` looks like a namespacing token to me - it would be helpful if the language server returned symbols relative to the current namespace only.

**Comment by nanoant** [comment]
> Just to understand these cases, it looks like SublimeText (at least in the powershell syntax) considers $ and : as symbol boundaries when applying completion results?

That is correct, `$` and `:` are symbol boundaries in PowerShell grammar.

To be more precise, without any assumptions about current language grammar on Sublime side (and if I understand correctly), the completion replacement boundaries are the boundaries of the completion prefix by Sublime in `on_query_completions(self, view, prefix, locations)`, so `locations[0]-len(prefix)` -> `locations[0]`.

And this is what my PR tries to do - trim `textEdit` completion boundaries to the boundaries of Sublime completion prefix.

> Although : looks like a namespacing token to me - it would be helpful if the language server returned symbols relative to the current namespace only.

That's why I suppose using `textEdit` gives unequivocal information and it is recommended to use in Language Servers spec, while `insertText` is subject of interpretation.
