### ISSUE TITLE
Usage with user-installed python on linux?

### ISSUE THREAD

**Issue by brandondube** [tomv564/LSP#296]
Hello,

Suppose I install the miniconda distribution of python on fedora27.  When I `pip install python-language-server` its executable goes in `~/miniconda3/bin/pyls`

I changed my user settings file to LSP to point to this,
```
{
	"clients":
	{
		"pyls":
		{
			"enabled": true,
                        "command": "/home/bdube/miniconda3/bin/pyls"
		}
	}
}
```
but this throws a permission error.  How do I alleviate this issue?

**Comment by tomv564** [comment]
Could you share the permission error (from sublime's console)?
Can you start `pyls` manually from the command line, and is that after your shell has 'activated' the miniconda distribution in some way?

**Comment by brandondube** [comment]
Hi Tom,

I recently wiped my USB key with linux on it to make an installer, but I need an extra cable to install the second SSD in my laptop for a proper linux install which will arrive in the mail late next week at the earliest.  I can get back to you with more detail when it arrives.

However, I know I was able to run the `pyls` command on the command line, either zsh or bash.  The ~/miniconda3/bin folded is prepended to my path when the shell initializes.  I installed it as a global package, so it is available in all venvs.

I think the permission error is because conda is in my home directory -- does subl run itself or plugins as a user other than the current user or root?  The error was an OSError/FileSystemError I believe.

**Comment by tomv564** [comment]
I don't suspect a user permissions problem, but it is possible that the process creation by LSP doesn't inherit some environment properties that your interactive shell does have.

If you are still hoping to get this working, please share some logs :)

**Comment by divmgl** [comment]
I'm having a permissions error as well. The problem with permissions errors is that it seems LSP does not actually print out the error itself to the Sublime log, so it makes it difficult to understand where the error actually is.

**Comment by predragnikolic** [comment]
Can you paste the sublime log, even though you said that it doesn't log to it. Just to check that maybe something other is wrong. 

Enable the `log_debug` and `log_server` flags in the setting. Close sublime, and open it. Copy the log and paste it here.

Also, it would be helpful if you provided your entire LSP settings file content?

And least, are you on Linux or Mac?
