### ISSUE TITLE
Signature help explicit command and manual (key) trigger

### ISSUE THREAD

**Issue by nanoant** [tomv564/LSP#297]
Right now `plugin/signature_help.py` is triggered only when typing certain characters eg `(`, `,` in Python. The problem is that one I move my cursor, help is gone, and only way to retrigger it is to manually retype trigger character.

Would be nice if there was some certain way to manually trigger signature help popup and `lsp_signature_help` was exposed as a command that can be bound to a key, e.g. <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Space</kbd>.

**Comment by tomv564** [comment]
Would require extracting implementation (which currently lives 100% in the SignatureHelpListener) so another command can trigger it.
Another option is to remove the HIDE_ON_MOUSE_MOVE_AWAY flag from the popup.
Agree this is worth fixing!

**Comment by tomv564** [comment]
@rwols good point, I had `HIDE_ON_MOUSE_MOVE_AWAY` commented out in that branch (perhaps just to make testing easier?)

I'm thinking the following:
* Popup should support manual trigger
* Preferably, popup should always stay open while typing within arguments
* `HIDE_ON_MOUSE_MOVE_AWAY`, I see this as "forget this signature, I need to check something else". Is there some use case where it's helpful to keep the popup open anyways?

As for a shortcut, it looks like VS Code uses 
<kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>Space</kbd> on Windows (https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf).

**Comment by tomv564** [comment]
Did a quick implementation as extracting shared logic/state from a command and listener would entail a fair bit of work. Using the suggested <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Space</kbd> on all platforms for now. 

Only available in master, let me know if it works for you!

**Comment by nanoant** [comment]
@tomv564 Awesome! I'll test it tomorrow and let you know.

**Comment by nanoant** [comment]
@tomv564 Just tested it and it works like a charm. Thank you very much.
