### ISSUE TITLE
Elixir integration sample

### ISSUE THREAD

**Issue by laibulle** [tomv564/LSP#304]
hello, 

I am trying to get LSP for Elixir with the following configuration

```
      	"elixir":
      	{
        	"command": ["mix", "elixir_ls.language_server"],
      		"scopes": ["source.ex", "source.exs"],
      		"syntaxes": ["Packages/elixir-tmbundle/Syntaxes/Elixir.tmLanguage", "Packages/elixir-tmbundle/Syntaxes/EEx.tmLanguage", "Packages/elixir-tmbundle/Syntaxes/HTML (EEx).tmLanguage"],
      		"languageId": "elixir"
		}
```

But I get LSP has no built-in configuration for a Elixir language server.

Best regard

**Comment by tomv564** [comment]
That looks like it should have worked, if you or someone else can confirm it does then I'll gladly add it to the documentation!
