### ISSUE TITLE
Configuration for Elixir

### ISSUE THREAD

**Issue by laibulle** [tomv564/LSP#305]
hello, 

I am trying to get LSP for Elixir with the following configuration

```
      	"elixir":
      	{
        	"command": ["mix", "elixir_ls.language_server"],
      		"scopes": ["source.ex", "source.exs"],
      		"syntaxes": ["Packages/elixir-tmbundle/Syntaxes/Elixir.tmLanguage", "Packages/elixir-tmbundle/Syntaxes/EEx.tmLanguage", "Packages/elixir-tmbundle/Syntaxes/HTML (EEx).tmLanguage"],
      		"languageId": "elixir"
		}
```

But I get "LSP has no built-in configuration for a Elixir language server" message. It look like the config file was not used.

Best regard

**Comment by tomv564** [comment]
Agree with your conclusion, looks like your config block was not in the place LSP expected to find it. See the related issue (347) for a working example
