### ISSUE TITLE
activate lsp for julia

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#306]
### Question:

How to get the julia language server ?

**Comment by tomv564** [comment]
The server itself must be installed, not sure how this is achieved in Julia but the GitHub repo is at https://github.com/JuliaEditorSupport/LanguageServer.jl

Then you will have to edit your LSP settings in Sublime Text. 
There are default settings, added along with some explanations in https://github.com/tomv564/LSP/pull/198

You will have to change the 'command' setting to match where the server is installed on your machine.
