### ISSUE TITLE
Goto next error

### ISSUE THREAD

**Issue by thunderkid** [tomv564/LSP#308]
### Question:
Is there a quick way to jump to the next error? There doesn't seem to be one in the context menu and I find it much slower to click on each line in the diagnostics window than to use hotkeys to jump between errors. (I'm using with scala but I assume this would apply the same for all languages.)

**Comment by tomv564** [comment]
The diagnostics panel offers `F4` and `shift-F4` keys to toggle next/previous result. It may only work when that panel is focused.
