### ISSUE TITLE
What exactly does this do?

### ISSUE THREAD

**Issue by EmilMoe** [tomv564/LSP#312]
I have tried work around with this plugin for a while now and have come to the conclusion I want to ensure myself, that I understand correct what it is about.

I love Sublime Text and it has beautiful skins (I use Spacegray). However I lack the feature so much of code completion (I think it's also called IntelliSense) that I mainly use PHPStorm. I have been looking many times for some way to implement this feature to Sublime Text so I can finally go to that editor.

Then I stumpled on this thing called LSP and read about it and it looks like it does exactly that, or? I have installed this plugin to my SublimeText and it does some indexing at some points and a popup in the bottom shows me I do errors once in a while, but that's it. Shouldn't I be able to get some sort of box up telling me available methods in a class and their parameters? Or am I misunderstanding something. All I get, when I however, is `No description available`.

I am using PHP and have also installed the suggested PHP server from here `npm install -g intelephense-server`

My LSP config looks like this, in case I did something incorrectly:

```
// Settings in here override those in "LSP/LSP.sublime-settings",

{
    "auto_complete_triggers": [
        {
            "characters": ".",
            "selector": "source.js"
        },
        {
            "characters": "$>:\\",
            "selector": "source.php"
        }
    ],
    "clients": {
        "vue-ls":{
          "command": [
            "node",
            "/usr/local/lib/node_modules/vue-language-server/bin/vls"
          ],
          "enabled": true,
          "languageId": "vue",
          "scopes": [
            "text.html.vue"
          ],
          "syntaxes": [
            "Packages/Vue Syntax Highlight/vue.tmLanguage"
          ]
        },
        "intelephense-ls":
          {
            "command": ["node", "/usr/local/lib/node_modules/intelephense-server/lib/server.js", "--stdio"],
            "scopes": ["source.php", "embedding.php"],
            "syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
            "languageId": "php",
            "initializationOptions": {
              "storagePath": "/tmp/intelephense"
            }
          }
    }
}
```

**Comment by rwols** [comment]
I cannot tell you exactly why there is no pop-up box showing completions, because I don't write PHP myself. However I'm pretty certain that your `auto_complete_triggers` are in the wrong place. You should have a file at `Packages/User/PHP.sublime-settings`, and it should contain this:
```
{
  "auto_complete_triggers": [
    {
      "selector": "source.php - comment",
      "characters": "$>:\\"
    },
    {
      "selector": "embedding.php - comment",
      "characters": "$>:\\"
    }
  ]
}
```
If things still don't work, run the command `Preferences: LSP settings` from the command palette, and add this:
```
	"log_debug": true,
	"log_stderr": true,
	"log_server": true,
```
Then, open the Sublime Text Console and let us know if you see anything that goes wrong.

**Comment by EmilMoe** [comment]
Thanks @rwols 

I have moved the PHP settings to the right config (and left Vue out for now).

However I can see some errors occurring in the console. I have tried to re-install Node and Python (3), but the errors persist.

So I guess it's related to `/usr/local/lib/node_modules/intelephense-server/lib/server.js`

```
LSP: global clients: intelephense-ls=True, vue-ls=True
LSP: starting active= /Users/USER/Documents/Websites/PROJECT/FILE.php other= 0
LSP: initialize on open 3 /Users/USER/Documents/Websites/PROJECT/FILE.php
LSP: starting in /Users/USER/Documents/Websites/PROJECT
LSP: starting ['node', '/usr/local/lib/node_modules/intelephense-server/lib/server.js', '--stdio']
Failed to start server
Traceback (most recent call last):
  File "plugin.core.main in /Users/USER/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package", line 330, in start_server
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'node'

LSP: Could not start ['node', '/usr/local/lib/node_modules/intelephense-server/lib/server.js', '--stdio'] , disabling
environment variables loaded using: /bin/bash -l
```

**Comment by EmilMoe** [comment]
I updated the config a seem to have fixed that error by replacing `command` in the config from `"node"` to `"/usr/local/bin/node"`

However there's still no popup (I believe - feel free to post a screenshot so I am sure I know what to look for.)

```
LSP: Unhandled notification: window/logMessage
LSP: Unhandled notification: window/logMessage
LSP:  --> initialized
LSP: intelephense-ls client registered for window 3
LSP:  --> textDocument/didOpen
LSP: initialize on open 3 /Users/USER/Documents/Websites/PROJECT/FILE.php
LSP:  --> textDocument/didChange
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
```

**Comment by rwols** [comment]
From these logs I see that the LSP plugin requests completions two times. The intelephense server should respond with a bunch of completion items that look something like this:

```
{"id":2,"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[{"detail":"long","filterText":"result","insertText":"result","insertTextFormat":2,"kind":6,"label":"result","sortText":"40eccccdresult"},{"filterText":"reinterpret_cast","insertText":"reinterpret_cast<${1:type}>(${2:expression})","insertTextFormat":2,"kind":15,"label":"reinterpret_cast<type>(expression)","sortText":"41000000reinterpret_cast"},{"filterText":"return","insertText":"return ${1:expression}","insertTextFormat":2,"kind":15,"label":"return expression","sortText":"41000000return"},{"filterText":"radvisory","insertText":"radvisory","insertTextFormat":2,"kind":7,"label":"radvisory","sortText":"41666666radvisory"},{"detail":"int","filterText":"raise","insertText":"raise(${1:int})","insertTextFormat":2,"kind":3,"label":"raise(int)","sortText":"41666666raise"},{"detail":"long","filterText":"random","insertText":"random()","insertTextFormat":2,"kind":3,"label":"random()","sortText":"41666666random"},{"filterText":"random_access_iterator_tag","insertText":"random_access_iterator_tag","insertTextFormat":2,"kind":7,"label":"random_access_iterator_tag","sortText":"41666666random_access_iterator_tag"},{"detail":"void","filterText":"random_shuffle","insertText":"random_shuffle(${1:_RandomAccessIterator __first}, ${2:_RandomAccessIterator __last})","insertTextFormat":2,"kind":3,"label":"random_shuffle(_RandomAccessIterator __first, _RandomAccessIterator __last)","sortText":"41666666random_shuffle"}
```

I also see two unhandled window messages. Maybe that contains vital information, but I don't immediately know how to inspect those.

**Comment by EmilMoe** [comment]
I switched the other option, which you mention in the docs, maybe that works, but I'm not sure if it should be capable of displaying more than this?

![image](https://user-images.githubusercontent.com/555083/39269918-9084a4d0-48d4-11e8-9fa0-a22fe59cc74b.png)

**Comment by tomv564** [comment]
Hi! The screenshot you just posted shows a _hover_, not a completion. Those are capable of showing eg. documentation about Authenticatable, but that's up to intelephense to provide.

Do you ever see the completions PHP files, even if intelephense is not running?
We can figure out if intelephense is sending back completion entries.
In addition to Raoul's suggestions, can you change this in your LSP settings:
```
"log_payloads": true
``` 
and then paste the logs like you did before?

**Comment by EmilMoe** [comment]
@tomv564 it returns things like this (I have again removed my name and project details):

```
LSP:      {'items': [{'insertText': 'findSlug($0)', 'label': 'findSlug', 'sortText': 'findSlug', 'command': {'command': 'editor.action.triggerParameterHints', 'title': 'Trigger Parameter Hints'}, 'insertTextFormat': 2, 'detail': 'findSlug($slug): Packages\\PROJECT', 'documentation': 'Find by given slug.', 'kind': 2}, {'insertText': 'boot()', 'label': 'boot', 'sortText': 'boot', 'detail': 'boot(): void', 'documentation': 'The "booting" method of the model.', 'kind': 2}], 'isIncomplete': False}
LSP: <--  textDocument/publishDiagnostics
LSP:      {'uri': 'file:///Users/NAME/Documents/Websites/PROJECT/FILE.php', 'diagnostics': [{'message': 'Unexpected CloseBrace.', 'source': 'intelephense', 'severity': 1, 'range': {'end': {'line': 76, 'character': 5}, 'start': {'line': 76, 'character': 4}}}]}
```

**Comment by tomv564** [comment]
That looks like correct information, and you should see a dropdown at the cursor like this example:

<img width="523" alt="screen shot 2018-04-29 at 12 06 44" src="https://user-images.githubusercontent.com/4395832/39405474-e2a808b4-4ba5-11e8-83eb-d24e4f2f6f61.png">

If you installed from package control, there is unreleased 1 bug fix for completions with intelephense - I believe you would see errors in the log if that was affecting you.

Completions can also be triggered with `ctrl+space`, in case your trigger setup is not working.

**Comment by rwols** [comment]
@EmilMoe, as @tomv564 mentions you could be the victim of [this bug](https://github.com/tomv564/LSP/issues/307), have you tried running LSP from the master branch?

**Comment by tomv564** [comment]
Nice, thanks for digging this up. I'll do a release soon in case this was the cause.

**Comment by tomv564** [comment]
Release 0.6.0 (
https://github.com/tomv564/LSP/releases/tag/0.6.0) included the completions fix, so your Sublime Text should have had the fix since June 1st.
