### ISSUE TITLE
Format Document causes a jump in the window viewport

### ISSUE THREAD

**Issue by JeanMertz** [tomv564/LSP#319]
Whenever I call `LSP: Format Document`, the cursor is moved to the last line of the file, _and_ the viewport is moved up (but not _all_ the way to the top, the top most visible line becomes the second line in the document).

I was considering using this command combined with the [sublime-hooks](https://github.com/twolfson/sublime-hooks) plugin to add auto-formatting functionality for my Golang files, but with the current behaviour, that's pretty much undoable due to the distraction of having your cursor + viewport move every time you save.

**Comment by JeanMertz** [comment]
Closing this, as I believe this is actually related to https://github.com/sourcegraph/go-langserver/pull/83.

**Comment by tomv564** [comment]
The described behaviour (erase and rewrite entire document) is/was similar to python language server, but I've only ever manually invoked the format call. Thanks for reporting, please re-open if there is something LSP _should_ do to handle this better.
