### ISSUE TITLE
LSP: phpls in state 0  for view...

### ISSUE THREAD

**Issue by kapitanluffy** [tomv564/LSP#321]
I can't seem to make it work..

When I try hovering to a method, it just says
`LSP: phpls in state 0  for view ... in window 2`

I have the language server running.

Other details are..
- langserver is `felixfbecker/php-language-server`. 
- OS is windows 7
- ST is dev 3171

```
LSP: initialize on open 2 ...
LSP: Already starting on this window: phpls
LSP: phpls in state 0  for view ... in window 2
LSP: phpls in state 0  for view ... in window 2
LSP: phpls in state 0  for view ... in window 2
LSP: phpls in state 0  for view ... in window 2
```

Settings
```json
{
	"clients":
	{
		"phpls":
		{
			"command":
			[
				"phplsp.bat",
                                 "--memory-limit=1024M",
			],
			"enabled": true,
			"languageId": "php",
			"scopes":
			[
				"source.php",
				"embedding.php"
			],
			"syntaxes":
			[
				"Packages/PHP/PHP.sublime-syntax"
			]
		}
	},
	"log_debug": true,
	"log_payloads": true,
	"log_stderr": true,
	"show_diagnostics_phantoms": true,
}
```

Autocomplete triggers
```json
	"auto_complete_triggers":
	[
		{
			"characters": "<",
			"selector": "text.html"
		},
		{
			"characters": "$>:\\",
			"selector": "source.php"
		}
	],
```

**Comment by tomv564** [comment]
On Windows this language server only supports TCP mode (which LSP supports!)

We discovered and fixed that problem in this issue:
https://github.com/tomv564/LSP/issues/151

If you can get it working (like we did in that issue), then we should make sure this requirement is clearly stated in the docs (feel free to open a PR for this!).

**Comment by tomv564** [comment]
I noticed that the `initialize` payload is not in your logs despite your config having it turned on?

I highly recommend you read the entire #151 issue and try to get logging from the PHP language server - LSP appears to be doing its work and is just waiting for the server to respond to `initialise`.
