### ISSUE TITLE
`workspace/applyEdits` confuses edits

### ISSUE THREAD

**Issue by nikeee** [tomv564/LSP#325]
### Bug:
I am having a LSP which returns several text edits to a single file. Assume the following edits:
```javaScript
[
    { newText: "a", range: {...} },
    { newText: "b", range: {...} },
    { newText: "c", range: {...} },
    { newText: "foo", range: {...} }
]
```
Now, if the `foo` edit is actually located before the `a` edit (as defined in their ranges), the edit of `foo` gets inserted at the location of the edit `a`.

If this is a bug, it might be located here:
https://github.com/tomv564/LSP/blob/2ce9c0f5dcdb0d7d02735712befe339172cbdce5/plugin/core/edit.py#L43-L63

- OS and language server: Windows 10, Currently using a custom language server for the DOT language
- How you installed LSP: Package Control

### Minimal reproduction steps:
File contents before edits:
```DOT
strict graph {
	a -- b;
	c -> d;
	e -- f;
}
```
Edits:
```JSON
{
    "label": "Change of all edges to \"->\"' and change graph to \"digraph\"",
    "edit": {
        "changes": {
            "foo.dot": [
                {
                    "range": {
                        "start": {
                            "line": 1,
                            "character": 3
                        },
                        "end": {
                            "line": 1,
                            "character": 5
                        }
                    },
                    "newText": "->"
                },
                {
                    "range": {
                        "start": {
                            "line": 3,
                            "character": 3
                        },
                        "end": {
                            "line": 3,
                            "character": 5
                        }
                    },
                    "newText": "->"
                },
                {
                    "range": {
                        "start": {
                            "line": 0,
                            "character": 7
                        },
                        "end": {
                            "line": 0,
                            "character": 12
                        }
                    },
                    "newText": "digraph"
                }
            ]
        }
    }
}
```
File contens after `workspace/applyEdits`:
```
strict -> {
	a -> b;
	c -> d;
	e digraph f;
}
```

Expected:
```
strict digraph {
	a -> b;
	c -> d;
	e -> f;
}
```

### Suggestion:
My current fix is to set the order of edits according to their position in the document. However, I think it's a bug in the language client.

**Comment by tomv564** [comment]
It's likely that the current implementation (which works with a few servers) has gotten lucky with the order of incoming edits so far :)
Agree this sounds like an LSP bug, will look at adding sorting of edits before applying!

**Comment by tomv564** [comment]
Sorting `changes` by offset should solve it. Looking at the code, it's likely that the regions are _created_ in the server-provided order, but probably not _returned_ in that order in this line:
```python
updated_regions = self.view.get_regions('lsp_edit') 
```

**Comment by nikeee** [comment]
I submitted a PR for this one.

**Comment by nikeee** [comment]
I think we can close this one.
