### ISSUE TITLE
LSP not performing textDocument/rename from PYLS

### ISSUE THREAD

**Issue by slice** [tomv564/LSP#330]
**OS:** macOS 10.12.6 (16G1314)
**Language Server:** python-language-server (pyls) 0.18.0+5.gd8eb65f
**Installation:** Latest revision (72fa593b39cb3bdf6a3aa6840a076375a682d268)

## Reproduction steps

Have the following code:

```py
def return_one() -> int:
    return 2


print(return_one())
```

* Place the caret on `return_one`.
* Right click.
* Select "Rename Symbol".
* Rename the symbol to something else.

Expected behavior: The symbol is renamed properly.
Actual behavior: Nothing happens. No status message appears, either.

## LSP configuration

https://gist.github.com/slice/a3b873321cb179ca2f6a47b8e436d61d

## Messages

```
LSP:  --> initialized
LSP: pyls client registered for window 3
LSP:  --> textDocument/didOpen
LSP: <--  textDocument/publishDiagnostics
LSP:      {'diagnostics': [], 'uri': 'file:///Users/slice/testing/test.py'}
LSP:  --> textDocument/rename
LSP:      {'documentChanges': [{'edits': [{'newText': 'def ohwow() -> int:\n    return 2\n\n\nprint(ohwow())\n', 'range': {'end': {'character': 0, 'line': 5}, 'start': {'character': 0, 'line': 0}}}], 'textDocument': {'version': 0, 'uri': 'file:///Users/slice/testing/test.py'}}]}
```

### pyls payload

```json
{
  "documentChanges": [
    {
      "edits": [
        {
          "newText": "def renamed() -> int:\n    return 2\n\n\nprint(renamed())\n",
          "range": {
            "end": {
              "character": 0,
              "line": 5
            },
            "start": {
              "character": 0,
              "line": 0
            }
          }
        }
      ],
      "textDocument": {
        "version": 0,
        "uri": "file:///Users/slice/testing/test.py"
      }
    }
  ]
}
```

**Comment by tomv564** [comment]
LSP doesn't support the versioned `documentChanges` yet (see https://microsoft.github.io/language-server-protocol/specification#workspaceedit)
This should be added to all edit-related response handling.
