### ISSUE TITLE
Support for html language server

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#331]
### installation
`npm install --global vscode-html-languageserver-bin` more info about the server can be found [here](https://github.com/vscode-langservers/vscode-html-languageserver-bin).

### configuration
```json
"html-ls":{
	"command":
	[
		"html-languageserver",
		"--stdio"
	],
	"enabled": true,
	"languageId": "html",
	"scopes":
	[
		"text.html.basic"
	],
	"syntaxes":
	[
		"Packages/HTML/HTML.sublime-syntax"
	]
}
```
Here are some problems that I noticed:
* No autocompletion for attribute values due to `NO_COMPLETION_SCOPES = 'comment, string'`. Example:
`<form method="|">` expect to see `POST, GET` as suggestions.

* I have a php language server set up. 
When I open a php file, I expect the php server to start, but it doesn't. 
Instead the html language server starts but I got no php autocompletion. 
Ideally both server should be started or the php should have precedence.

Here is my php configuration:
```json
"php-ls": {
	"command": ["node", "/home/predrag/.npm-global/lib/node_modules/intelephense-server/lib/server.js", "--stdio"],
	"enabled": true,
	"initializationOptions": {"storagePath": "/tmp/intelephense"},
	"languageId": "php",
	"scopes":
	[
		"embedding.php",
		"source.php"
	],
	"syntaxes": ["Packages/PHP/PHP.sublime-syntax"]
}
```
Here is the log when I open I php file:
```
plugins loaded
LSP: starting active= /home/predrag/Sites/gta/index.php other= 0
LSP: initialize on open 2 /home/predrag/Sites/gta/index.php
LSP: starting in /home/predrag/Sites/gta
LSP: starting ['html-languageserver', '--stdio']
LSP:  --> initialize
LSP: initialize on open 2 /home/predrag/Sites/gta/index.php
LSP: Already starting on this window: html-ls
reloading settings Packages/User/Package Syncing.sublime-settings
LSP:  --> initialized
LSP: html-ls client registered for window 2
LSP:  --> textDocument/didOpen
Package Syncing: Start Complete Sync
Package Syncing: End Complete Sync
LSP: <--  textDocument/publishDiagnostics
Package Syncing: Already running
Package Control: Skipping automatic upgrade, last run at 2018-06-03 10:55:56, next run at 2018-06-03 11:55:56 or after

```
#### Maybe some helpful info...
The scope for the html file is `text.html.basic`,
The scopes for the php are :
```
embedding.php 
text.html.basic 
meta.embedded.block.php 
source.php 
meta.class.php meta.block.php 
meta.function.php 
meta.block.php:
```

**Comment by tomv564** [comment]
There's no support for multiple servers per document at this time. I think LSP should support it eventually.

**Comment by Kronuz** [comment]
Now that #339 has been merged, you could set up your PHP scopes as:

```json
{
        "languageId": "php",
	"scopes":
	[
		"text.html.basic embedding.php",
		"source.php"
	]
}
```

And that would give priority to PHP over HTML.

**Comment by predragnikolic** [comment]
PHP configuration:
```json
"languageId": "php",
"scopes":
[
	"embedding.php text.html.basic",
	"source.php"
],
```
HTML configuration:
```json
"languageId": "html",
"scopes":
[
	"text.html.basic"
],
```
Yes this will give priority to PHP server, but only it this case.
I open a project. 
Threre I have two files. For example `index.html` and `index.php`.

If I first open the PHP file, this will initialize the PHP server,  
and then if I open the HTML file, it will initialize the HTML server. This works as expected.

But if I first open the HTML file, this will initialize the HTML server,
and then if I open the PHP file, this will initialize the HTML server also. This doesn't work as I expect. because I expect the PHP server to start :D

**Comment by Kronuz** [comment]
That is certainly weird, it should still work... I wonder if there is some cache I don’t know about... any idea @tomv564 ?

**Comment by Kronuz** [comment]
I know what it is now, I think, there really is another level of cache, once html is in the `window_client_configs` (after the html file is opened first), when opening the php it stops there and it no longer looks for php in the `client_configs.all`...

**Comment by tomv564** [comment]
Rather than using scope (which as you concluded is dependent on cursor position) I just switched to using syntax for document sync in master.

If you add the PHP syntax to html language server, then you should see both servers started, document sync notifications fired to both. Remaining interaction should still use scope (by cursor/mouse position).

**Comment by predragnikolic** [comment]
It still doesn't start the `HTML` and `PHP` server at the same time for the same file. 
Maybe I am missing something.
```jsonc
// Here is my config
"html-ls":
{
	"command": ["node", "/home/predrag/.npm-global/bin/html-languageserver", "--stdio"],
	"enabled": true,
	"languageId": "html",
	"scopes": ["text.html.basic"],
	"syntaxes":
	[
		"Packages/HTML/HTML.sublime-syntax",
		"Packages/PHP/PHP.sublime-syntax" // <-- Added the PHP Syntax 
	]
},
"php-ls": {
	"command": ["node", "/home/predrag/.npm-global/lib/node_modules/intelephense-server/lib/server.js", "--stdio"],
	"enabled": true,
	"initializationOptions": {"storagePath": "/tmp/intelephense"},
	"languageId": "php",
	"scopes": ["embedding.php", "source.php"],
	"syntaxes": ["Packages/PHP/PHP.sublime-syntax"]
},
```

There are two possible outcomes for me. (The outcome depends on where the caret(cursor) is in the file, when the file opens.)
<details>
<summary>first case: Cursor is in HTML scope</summary> 

![2018-08-02-202802_683x384_scrot](https://user-images.githubusercontent.com/22029477/43612196-d73cab46-96ab-11e8-9722-e215d7cbecf4.png)

The HTML server starts (look in the bottom left corner, <b>one </b>`html-ls` server), but the PHP server doesn't start. 
I get completions for HTML attributes. No auto completion for PHP.
  <details>
    <summary><b>log for the first case</b></summary>
<pre><code>plugins loaded
LSP: starting active= /home/predrag/Documents/sandbox/php_and_html.php other= 0
LSP: initialize on open 2 /home/predrag/Documents/sandbox/php_and_html.php
LSP: starting in /home/predrag/Documents/sandbox
LSP: starting ['node', '/home/predrag/.npm-global/bin/html-languageserver', '--stdio']
LSP:  --> initialize
LSP: html-ls client registered for window 2
reloading settings Packages/User/Package Syncing.sublime-settings
LSP: initialize on open 2 /home/predrag/Documents/sandbox/php_and_html.php
LSP: Already starting on this window: html-ls
LSP:  --> initialized
LSP:  --> textDocument/didOpen
Package Syncing: Start Complete Sync
LSP:Package Syncing: End Complete Sync
 <--  textDocument/publishDiagnostics
Package Syncing: Already running
Package Control: Skipping automatic upgrade, last run at 2018-08-02 23:29:57, next run at 2018-08-03 00:29:57 or after
</code></pre>
  </details>
</details>

<hr>

<details>
<summary>second case: Cursor is in PHP scope</summary>

![2018-08-02-202432_683x384_scrot](https://user-images.githubusercontent.com/22029477/43612896-fabfb836-96ad-11e8-85ba-db72afb686b7.png)

The PHP server starts (look in the bottom left corner,  <b>two</b> <code>php-ls</code> servers separated by a comma) but no HTML server.

I get completions for PHP, hover, etc. But no auto completion for HTML.
  <details>
    <summary><b>log for the second case</b></summary>
<pre><code>plugins loaded
LSP: starting active= /home/predrag/Documents/sandbox/php_and_html.php other= 0
LSP: initialize on open 2 /home/predrag/Documents/sandbox/php_and_html.php
LSP: starting in /home/predrag/Documents/sandbox
LSP: starting ['node', '/home/predrag/.npm-global/lib/node_modules/intelephense-server/lib/server.js', '--stdio']
LSP:  --> initialize
LSP: php-ls client registered for window 2
LSP: initialize on open 2 /home/predrag/Documents/sandbox/php_and_html.php
LSP: Already starting on this window: php-ls
reloading settings Packages/User/Package Syncing.sublime-settings
LSP: <--  window/logMessage
server: Initialising
LSP: <--  window/logMessage
server: Initialised in 496 ms
LSP:  --> initialized
LSP:  --> textDocument/didOpen
LSP:  --> textDocument/didOpen
Package Syncing: Start Complete Sync
Package Syncing: Already running
Package Syncing: End Complete Sync
Package Control: Skipping automatic upgrade, last run at 2018-08-02 23:29:57, next run at 2018-08-03 00:29:57 or after
</code></pre>
  </details>
</details>

<br>

So Tom, If I missed a step, please say, I am on the latest master :D 
If I wasn't clear enough and you need more detail, just say

**Comment by predragnikolic** [comment]
I lied! :D but not on purpose. I am 4 commits behind the latest master, so don't take in account what I earlier said. :man_facepalming: 

I did a git fetch yesterday, but apparently before you pushed the 4 commits. I thought the change came with #386 (multiple session per document).

I will try it today. Sorry for this.

**Comment by tomv564** [comment]
Both the problems mentioned in this issue (the completion issue was a relative of #301) are now fixed.

I decoupled server startup and didOpen sync to resolve the issue I found yesterday.

The multi-server per document support is unfortunately a pandora's box for new issues with  features like signature help / completion, as they like to initialise for just one server per view.

Please help test and report new issues!
