### ISSUE TITLE
Client completion capabilities are misleading

### ISSUE THREAD

**Issue by tboby** [tomv564/LSP#333]
### Suggestion:

The client capabilities for completion are sent as follows:
```
                    "completionItem": {
                        "snippetSupport": True,
                        "documentationFormat": ["plaintext"]
                    },
```

Which indicates that LSP supports plaintext documentation. As far as I can tell LSP currently only pulls from the `details` field, not the `documentation` field.

I suggest that the completion text is pulled from both `details` and `documentation` (or fallback from one to the other). If that isn't possible, it would be nice if `documentationFormat` was set to `[]`, which would let me detect this serverside, and return `details`. :)

**Comment by tomv564** [comment]
Good suggestion.
I don't expect to be using the documentation field in LSP unless we get a way to display a companion popup the way VS Code does. 

Feel free to send a PR, or I'll fix it on a future sweep through the issues!

**Comment by tomv564** [comment]
I hope leaving out the property works, too. The assumption is that "details" is shorter and easier to provide than "documentation".
