### ISSUE TITLE
Missing publishDiagnostics.relatedInformation capability

### ISSUE THREAD

**Issue by edgardmessias** [tomv564/LSP#334]
### Bug:

Missing `textDocument.publishDiagnostics.relatedInformation` capability

```
	/**
	 * Capabilities specific to `textDocument/publishDiagnostics`.
	 */
	publishDiagnostics?: {
		/**
		 * Whether the clients accepts diagnostics with related information.
		 */
		relatedInformation?: boolean;
	};
```

Add in `plugin/core/main.py`
```
                "publishDiagnostics": {
                    "relatedInformation": True
                },
```

**Comment by tomv564** [comment]
Thanks for pointing out this new API!
Are you using it with LSP? I'd like to avoid turning the capability on until it is in use (so language servers can save the effort of calculating the field contents)

**Comment by edgardmessias** [comment]
I use only internal LSP, the VSCode example use it: https://github.com/Microsoft/vscode-extension-samples/blob/4581ade9c7ef054751c672cc2e6fdf43bcd328a8/lsp-sample/server/src/server.ts#L33

**Comment by tomv564** [comment]
Ok, good to know for the future.
I'm not sure what the "bug" or current improvement to LSP is?
The protocol allows omitting the field and that sounds like a reasonable thing to do until we have a use for it the data. I'll close this issue for now!
