### ISSUE TITLE
Connect LSP-client to already running server via TCP

### ISSUE THREAD

**Issue by numberpi** [tomv564/LSP#335]
### Suggestion:
Allow to specify "tcp_port" in the configs and drop the "command" property, so that the client simply connects to a LSP-server already running locally.

Starting point:
https://github.com/tomv564/LSP/blob/b2527a3c5fc26eeb0d4c9c8bd431821cffbb6201/plugin/core/main.py#L214

**Comment by tomv564** [comment]
This should be working in master (not yet released), where this path should be entered if  "command" is omitted / empty in the client config.

https://github.com/tomv564/LSP/blob/0a2806da34c8c0a512e8ddfb937bd5a74b009fce/plugin/core/sessions.py#L38
