### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by nikeee** [tomv564/LSP#337]
### Question:

I've used the docs as a reference. The docs provide this code as a configuration for `flow-language-server`:
```JSON
"flow": {
	"command": ["flow-language-server", "--stdio"],
	"scopes": ["source.js"],
	"syntaxes": ["Packages/Babel/JavaScript (Babel).sublime-syntax", "Packages/JavaScript/JavaScript.sublime-syntax"],
	"languageId": "javascript"
}
```

### Bug:
I expected to start the server normally. However, the Python function `subprocess.Popen` failes to start the process. Staring the server on the command line works.

Stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/main.py", line 347, in start_server
    startupinfo=si)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

* Windows 10, [flow-language-server](https://github.com/flowtype/flow-language-server)
* Installed via Package Control

### Suggestion:

I recently encountered a similar problem in the Language Client implementation ov VSCode, see: https://github.com/Microsoft/vscode-languageserver-node/issues/358

Due to the language server being a globally installed NPM package, the "binary" is actually a shell script.

#### Reproduction:
I fiddled around with the Python API and couldreproduce the problem:
```python3
import subprocess
import os
env = os.environ.copy()
si = None
if os.name == "nt":
    si = subprocess.STARTUPINFO()  # type: ignore
    si.dwFlags |= subprocess.SW_HIDE | subprocess.STARTF_USESHOWWINDOW  # type: ignore

subprocess.Popen(
    [ "flow-language-server", "--stdio" ],
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    cwd="C:\\",
    env=env,startupinfo=si)
```
This results in the same error as above. If we add `shell=True` to the arguments of `Popen`, it works as [this SO answer](https://stackoverflow.com/a/28903670) also indicates.

Suggestions for resolving the problem:
- Add `shell=True` to the call of `Popen` or
- Add a proptery in the client config be able to set the `shell` parameter of `Popen`

If the latter is used, the docs should be changed as well.

**Comment by tomv564** [comment]
This is a Windows-specific issue as the npm command wrappers are not real executables.

Thankfully, it generally is enough to append `.cmd`: so `Popen(["flow-language-server.cmd", "--stdio"], ...`. Can you try this?

I would like to avoid setting shell=True globally :) Documenting it is certainly possible!

**Comment by nikeee** [comment]
> Thankfully, it generally is enough to append `.cmd`

Didn't know that. This worked, thanks!

> I would like to avoid setting shell=True globally

That's what I think, too. 

Looking at the docs of the [vue language server (vls)](https://github.com/tomv564/LSP/blob/master/docs/index.md#vue-javascript), it seems that the command could be simplified by using the `.cmd` extension on windows and without `.cmd` on unix.

Is there any use case were we want to have `shell=True`? If so, we could think of adding an optional field to the client configuration. Something like this (defaulting to false):
```JSON
"flow": {
	"command": ["flow-language-server", "--stdio"],
	"shellCommand": true,
	"scopes": ["source.js"],
	"syntaxes": ["Packages/Babel/JavaScript (Babel).sublime-syntax", "Packages/JavaScript/JavaScript.sublime-syntax"],
	"languageId": "javascript"
}
```
But if there is no use case that couldn't be fixed by adding the `.cmd` extension, this is not necessary.

**Comment by alexmacavei** [comment]
Man you guys saved my day! Had same issue with lsp-tsserver. Thanks, this should be in the docs!

**Comment by tomv564** [comment]
Agreed this should be in the config for all node-based language servers (they all have this problem in Windows).
The better solution is for an add-on package to LSP to install, detect and configure the server (example for lsp-tsserver: https://github.com/tomv564/LSP-tss/blob/master/plugin.py#L12-L13)

**Comment by john-cj** [comment]
Guys, I have the same problem with https://github.com/microsoft/TypeScript-Sublime-Plugin. Could you explain what I need to do?

@tomv564 

> Agreed **this** should be in the docs for all node-based language servers (they all have this problem in Windows).

Could you elaborate what exactly I need to do to fix this issue for https://github.com/microsoft/TypeScript-Sublime-Plugin?

**Comment by rchl** [comment]
The `microsoft/TypeScript-Sublime-Plugin` repo is for the `Typescript` ST package and has nothing to do with this repo.

The alternative for you would be to switch to `LSP` + `LSP-typescript` packages.

If you are on ST3 rather than ST4 then you can also install the https://packagecontrol.io/packages/TypeScript%20Syntax package to get syntax support for Typescript. ST4 has that built in.

**Comment by john-cj** [comment]
Thanks, it seems I figured these things out. It seems that now it works.
