### ISSUE TITLE
Scopes priorities while selecting configuration

### ISSUE THREAD

**Issue by Kronuz** [tomv564/LSP#338]
## Bug:

When there are multiple language servers configured, all of which are for similar scopes (Ex. `source.json`, `source.json.sublime.settings`) the configuration with the most specific scope should be preferred; however right now one or the other could "win", some times leading to erroneous configuration.

Example comes from configuring **vscode-json-languageserver** to work with both `json` and `jsonc` languageIds.

### Suggestion:

Give priority to the configuration with the most specific scope that matches.

**Comment by tomv564** [comment]
Did you configure the language server to have two client configurations, one for each languageId?
I've wondered if the configuration for syntaxes/scopes shouldn't be a lookup per supported languageId instead. Would that solve your problem?
