### ISSUE TITLE
Setting LSP for java

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#344]
I can't make lsp work for java so:

Do I need to build the eclipse jdtls so it can work in sublime text ?
Do i need to install eclipse so that i can work with jdtls in sublime ?
what is the PATH_TO_CONFIG_DIR ?
Do I need to change the command in lsp jdtls settings ?

Any help please !

**Comment by tomv564** [comment]
No one has volunteered to document the eclipse jdtls setup, but I investigated it for a user on the sublime forums here: https://forum.sublimetext.com/t/lsp-universal-language-server-plugin/30554/24?u=tomv564

You'd make at least a few users happy if you could help us confirm and put those steps in the LSP docs!

**Comment by AmjadHD** [comment]
I would but i don't know what is the PATH_TO_CONFIG_DIR  ?
and whether i need to build the server with Maven ?

Besides, aren't there other java servers that don't require all this hassle ?
i think vscode [has one](https://github.com/redhat-developer/vscode-java)

**Comment by AmjadHD** [comment]
This is AWESOME Thanks man, now i can code java without the need for the cpu consuming eclipse and Intellij, Really thanks man you just saved my day.

**Comment by tomv564** [comment]
Glad to hear it's working. 
VS Code often has an extension for each language server, that takes care of operating-system specific details of verifying Java is installed, downloading the server, locating it once installed, etc.

This LSP page also supports language handlers that can be installed, if no one else has done it then a `LSP-jdtls` package would be a great way to automate it.
I did a related effort for the new Scala dotty-based language server, see  my `LSP-dotty` repo for details.

**Comment by ryanpcmcquen** [comment]
@tomv564, did we ever get Java documented?
