### ISSUE TITLE
Code Actions Broken for jdtls

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#346]
code actions in jdtls don't work, it produces this error
```
LSP:  --> workspace/executeCommand
LSP:      {'message': "Internal error, please look at the server's logs.", 'code': -32603}
```

I wonder where to find the server's log ?

**Comment by tomv564** [comment]
Not sure, but it's possible the server logs to stderr (which LSP can show in the Sublime console, if you enable the setting, probably `log_stderr` or something)
Alternatively, check the jdtls repo if it's documented there?
