### ISSUE TITLE
Implement goto next/previous error commands

### ISSUE THREAD

**Issue by Kronuz** [tomv564/LSP#350]
### Feature:

For errors/warnings found while linting, we need to implement goto next/previous error command. Commonly these are set up as:

**Goto next error**: <kbd>CTRL</kbd> + <kbd>CMD</kbd> + <kbd>E</kbd>

and

**Goto prev error**: <kbd>CTRL</kbd> + <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>E</kbd>

**Comment by predragnikolic** [comment]
#308 :)

**Comment by tomv564** [comment]
The existing hotkeys in the diagnostics panel (mentioned in that issue) don’t work for you? 
I’d like people to learn Sublime hotkeys instead of introducing more mental overhead.

**Comment by Kronuz** [comment]
Well, these keys are the standard in SublimeLinter, so I suppose a lot of people are just trying to use them for that purpose, that’s why. I don’t use the diagnostics panel so much either, what are those hot keys there?

**Comment by Kronuz** [comment]
Yes they work even when the panel is closed! ...however, where did <kbd>F4</kbd> came from? I'd prefer the other two (standardized by SublimeLinter)

**Comment by predragnikolic** [comment]
These are from the `Default.sublime-keymap`. You can change it if you want.
```json
{ "keys": ["f4"], "command": "next_result" },
{ "keys": ["shift+f4"], "command": "prev_result" },
```

**Comment by Kronuz** [comment]
I hadn't realized <kbd>F4</kbd> and <kbd>SHIFT</kbd>+<kbd>F4</kbd> was a Sublime Text feature, it's ok as is then... although cycling could be useful.

**Comment by tomv564** [comment]
Additionally supporting SublimeLinter shortcuts sounds like a smart idea, I didn't see what you meant by "commonly" :) 
But ideally without writing more code to handle this functionality!

**Comment by reagle** [comment]
I was looking for these too, and didn't know about `F4`. I also expected to see something in the command palette.
