### ISSUE TITLE
Implement opening external resources

### ISSUE THREAD

**Issue by Kronuz** [tomv564/LSP#351]
### Feature:

Some language servers return uris to external resources; for example TypeScript's (javascript-typescript-langserver) returns `git://github.com/Microsoft/TypeScript?v2.8.3#lib/lib.es5.d.ts` when going to definition of `Readonly<>` in the snippet bellow:

```typescript
function getName(obj: Readonly<{name: string}>) {
  return obj.name;
}
```

This results in an empty buffer opened `/Microsoft/TypeScript`.

#### Expected Behavior:

It should download the external resource somewhere (a temporary file or a cached file) and open the file from there. There are several URL scheme handlers that could/should be implemented. `http`, `https`, `git`, etc.

**Comment by predragnikolic** [comment]
I think this could be used with the [vscode-json-languageserver-bin](https://www.npmjs.com/package/vscode-json-languageserver-bin).

In order for the json server to get suggestions for the given file (package.json, tsconfig.json) it need to download a schema from this [site](http://schemastore.org/json/). This thread atom/ide-json#2 explains how the server should be implemented.

**Comment by tomv564** [comment]
I think this is a consequence of sourcegraph’s “language servers in the cloud” model. Don’t those typings exist on disk (in node_modules) somewhere?

**Comment by Kronuz** [comment]
They do, inside `node_modules/typescript/lib`, I think... the thing is they’re tagging the version too, and users probably could have other versions installed, or it might be using the version “bundled” in the server... so line numbers may not match.

**Comment by tomv564** [comment]
I would support this if the protocol dictates this need, or if Sublime provided the functionality. 

My own typescript server links to the project's `node_modules/typescript/lib/lib.es5.d.ts` when going to definition on `Readonly`, I think this is correct behaviour?

`vscode-json-languageserver-bin` does the downloading for you.
