### ISSUE TITLE
Whether this plug-in can support cquery???

### ISSUE THREAD

**Issue by suzukajiang** [tomv564/LSP#366]

**Comment by rwols** [comment]
Yes, this plugin most definitely supports cquery.

**Comment by suzukajiang** [comment]
I've tried to configure cquery, but it doesn't work。

this is my config:

	"clients": {
		"clangd":{
			"enabled":false
		},
	    "cquery":
	    {
	      "command": ["cquery", "--language-server"],
	      "scopes": ["source.c", "source.c++", "source.objc", "source.objc++"],
	      "syntaxes": ["Packages/C++/C.sublime-syntax", "Packages/C++/C++.sublime-syntax", "Packages/Objective-C/Objective-C.sublime-syntax", "Packages/Objective-C/Objective-C++.sublime-syntax"],
	      "languageId": "objc++"
	    },
	},

**Comment by tomv564** [comment]
Did you see the guidelines in the text field when creating a new issue?

A search for past issues would have confirmed that the cquery is supported, and show you working configurations to compare with. (https://github.com/tomv564/LSP/issues?utf8=✓&q=is%3Aissue+cquery)

If it still doesn't work, please share a log - as described in the troubleshooting section.

**Comment by maddanio** [comment]
Put these in the readme maybe? Issues as documentation seems non-ideal...
