### ISSUE TITLE
Any way to hint the static methods and constants in PHP?

### ISSUE THREAD

**Issue by dingo-d** [tomv564/LSP#370]
I'm wondering is it possible to include hinting of the constants or static methods in PHP?

For instance I aliased a certain class, and I'm using a `public static` method from that class

![screen shot 2018-07-06 at 11 54 45](https://user-images.githubusercontent.com/8638515/42372886-bf4cfd2c-8113-11e8-8777-5d14e3143a1e.png)

Hovering on the class, gives me a nice popup about it (yay!)

However hovering on the method itself doesn't provide any info about it, event though there is a nice docblock + typehinting on that method

![screen shot 2018-07-06 at 11 54 51](https://user-images.githubusercontent.com/8638515/42372972-ec1d85e2-8113-11e8-9677-2c585948861f.png)

![screen shot 2018-07-06 at 11 58 28](https://user-images.githubusercontent.com/8638515/42372981-ef7c58b2-8113-11e8-9fc0-3c44d71d7d44.png)

Hovering on the passed argument works (since it's inside the method where this other method is being called)

![screen shot 2018-07-06 at 11 54 58](https://user-images.githubusercontent.com/8638515/42373008-00f446a4-8114-11e8-9d53-eb0b05ce1f12.png)

The same thing happens when I try to check any constant in a class, either defined in the class (`self::CONSTANT`) or one that is inherited (`static::CONSTANT`).

Any workarounds for this?

**Comment by tomv564** [comment]
Which language server? 

I think the issue is likely not with this package - the "no description available" text is typically shown when the server gives an empty response.

I recommend opening an issue with your language server.

**Comment by jfcherng** [comment]
Iirc, LSP only asks the server to index a file when the file is being opened?

**Comment by dingo-d** [comment]
> Which language server?

Is there a way I can check this?

**Comment by tomv564** [comment]
Which instructions did you follow to get it working?  At the very least you must have installed a server (via NPM if js-based or composer if felixfbecker's PHP-based server)? 

As @jfcherng mentioned, the server re-indexing is a likely cause for missing hover/completion info. I'm not sure there is rock-solid support from any of the PHP language servers yet.

**Comment by dingo-d** [comment]
I remebered to check the LSP settings and in them I have 

```json
{
  "clients": {
    "phpls": {
      "command": ["php", "/Users/infinum-denis/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php"],
      "scopes": ["source.php"],
      "syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
      "languageId": "php"
    }
  },
  "auto_show_diagnostics_panel": false
}
```

So I guess I should ask this in the [PHP Language Server](https://github.com/felixfbecker/php-language-server) repo? Thanks for the help :)
