### ISSUE TITLE
Missing debug logging

### ISSUE THREAD

**Issue by ehuss** [tomv564/LSP#371]
Debug logging of stderr of servers doesn't seem to be working in latest repo version (7f7b7336fdafb565a2a05fe9646a3c01bd859289).

Recent changes in #360 seem to have changed how servers are started.  The function [`start_client`](https://github.com/tomv564/LSP/blob/7f7b7336fdafb565a2a05fe9646a3c01bd859289/plugin/core/main.py#L181-L223) doesn't seem to be called anymore (is it dead code?).  It looks like servers are now started in `create_session`, however `create_session` doesn't seem to do all the same things that `start_client` does.  In particular, it doesn't seem to start up debug logging on stderr.  I'm not sure what other differences there are.

**Comment by ehuss** [comment]
Perhaps related to these recent changes, the `restart servers` command does not seem to be working.  After running it, nothing works, and I see the following in the console:

```
LSP: initialize on open 6 /Users/eric/Proj/rust/scratch/src/main.rs
LSP: Already starting on this window: rls
LSP: no session found
```

**Comment by tomv564** [comment]
Sorry about all the regressions!
The new code path through `create_session` should attach stderr logging, I will take a look soon at that.
Some of the dead code is already cleaned up in follow-up work to be merged over the next days.

**Comment by tomv564** [comment]
#385 (merged today) fixes the stderr loggin
