### ISSUE TITLE
 How to get `sublime` and `sublime_plugin` modules autocompletion with `pyls`?

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#374]
Hello, I already read  #133, but I am not sure which `PYTHONPATH` should i put in the `SOME_PROJECT.sublime-project` file, to get autocompletion for `sublime` and `sublime_plugin` modules.

Here is how my `SOME_PROJECT.sublime-project` looks like:
```json
{
  "folders":
  [
    {
      "path": "."
    }
  ],
  "settings": {
    "LSP": {
      "pyls": {
        "env": {
          "PYTHONPATH": "/opt/sublime_text"
        }
      }
    }
  }
}
```
I use `Linux`, and all I know is that the `sublime` and `sublime_plugin` are located in this folder `/opt/sublime_text`.
```bash
λ  /opt/sublime_text  ls 
changelog.txt   Icon      plugin_host    sublime_plugin.py  sublime_text
crash_reporter  Packages  python3.3.zip  sublime.py
```

And all other related folders for sublime are located whitin this folder `~/.config/sublime-text-3`.
```bash
λ  ~/.config/sublime-text-3  ls 
 Cache   Index  'Installed Packages'   Lib   Local   Packages   sync_packages   sync_packages.zip
```

**Comment by randy3k** [comment]
I don't think you could run the python shipped by Sublime Text directly. Plus there is no way (or difficult) to install the language server to Sublime Text's python.

**Comment by predragnikolic** [comment]
Thanks for replying Randy, but I got it working now.

![output](https://user-images.githubusercontent.com/22029477/42540203-cf1c4266-849d-11e8-9b67-449d5280cac5.gif)


I just moved the `sublime.py` and `sublime_plugin.py` from `/opt/sublime_text` to the root of the project. And I got the completions :D

**Comment by randy3k** [comment]
I guess you could also move them to your python package directory.

**Comment by predragnikolic** [comment]
And you are right,
I moved the 2 files to `/home/predrag/.local/lib/python3.6/site-packages` and everything works.
Thanks :)

**Comment by tomv564** [comment]
Strange that it didn't work with your `env` settings, they looked like they should work!

**Comment by predragnikolic** [comment]
I don't know what is wrong and I have nothing more to say that could help solve this.
