### ISSUE TITLE
Popup messages are not displayed correctly if they contain angle brackets

### ISSUE THREAD

**Issue by IBUzPE9** [tomv564/LSP#378]
![popup](https://user-images.githubusercontent.com/16499542/42989829-953d7128-8c09-11e8-860b-49a95bb0fb55.jpg)

Sublime Text 3.1.1 (Build 3176), Rust Language Server

**Comment by tomv564** [comment]
Good find, we can never trust server-returned content that doesn't identify as html or markdown. I suspect html encoding should do the trick.

**Comment by predragnikolic** [comment]
While this may fixed the issue, it introduced another. But it is an easy fix.
Here is the problem. 

See the error popup, it should't look like this. 
There is also an error in the console: `Parse Error: #x27; code: Unknown entity`.
![2018-09-09-134855_746x575_scrot](https://user-images.githubusercontent.com/22029477/45264103-65dd4100-b437-11e8-9e47-745e5db020f8.png)

To fix this, in [plugin/hover.py](https://github.com/tomv564/LSP/blob/e56e20444fb6153a4ff2751f8ef71471d0af60fc/plugin/hover.py#L93-L95) file the `escape` function takes an additional optional argument.
 If the optional flag quote is true (the default), the quotation mark characters, both double quote (") and single quote (') characters are escaped. 

Which in this case is not preferred and setting it to `False` fixes the error popup and it looks like this:
 
![2018-09-09-135828_587x497_scrot](https://user-images.githubusercontent.com/22029477/45264163-7a6e0900-b438-11e8-88bf-670883f33b98.png)

**Comment by tomv564** [comment]
Pushed a fix for this just now, thanks for the research and instructions!
