### ISSUE TITLE
Bug, no code higlighting in hover popup.

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#383]
I use [lsp-tsserver](https://github.com/tomv564/lsp-tsserver) server (it is great) :)

I noticed a bug  that occurs only in `.js` and `.ts` files. 
When I hover over a symbol, the code in the hover popup is not highlighted and it is dark. 
Making it hard to read.

![screenshot from 2018-07-25 00-02-04](https://user-images.githubusercontent.com/22029477/43169041-b1feb18e-8f9f-11e8-93dc-8d76f9d6e97e.png)

The way I 'fix' it is: 
I open, for example, a `index.php` file, and I hover over a symbol over there. 

![screenshot from 2018-07-25 00-03-43](https://user-images.githubusercontent.com/22029477/43169132-2336ef06-8fa0-11e8-86cd-4c532ff1b197.png)

And then I get back to the `.js` or `.ts` file. and the highlighting in the hover popup starts working again.

![screenshot from 2018-07-25 00-04-18](https://user-images.githubusercontent.com/22029477/43169112-061905bc-8fa0-11e8-8eff-183cd46965c2.png)

**Comment by predragnikolic** [comment]
I forgot to run `Package Control: Satisfy Dependencies` when I installed the plugin.

**Comment by rwols** [comment]
> Does anyone else have this problem?

No 🤔 though I recall that if I "ran" an InputHandler on start up (without the command palette, via an EventListener.on_load event for example), I saw the same dark text. Maybe it's an ST bug?

**Comment by predragnikolic** [comment]
Thanks for replying Raoul :)

Changing the UI theme from `Default.sublime-theme` to another solves the problem for me. 
I will close this, because I think it is not related to LSP.
