### ISSUE TITLE
double "textDocument/documentHighlight" request

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#392]
Every time I click on a word "textDocument/documentHighlight" is sent twice:
```
LSP:  --> textDocument/documentHighlight
LSP:      [{'kind': 2, 'range': {'start': {'line': 1, 'character': 4}, 'end': {'line': 1, 'character': 13}}}]
LSP:  --> textDocument/documentHighlight
LSP:      [{'kind': 2, 'range': {'start': {'line': 1, 'character': 4}, 'end': {'line': 1, 'character': 13}}}]
```
is this a bug or it's deliberate ?

**Comment by AmjadHD** [comment]
another thing is that often time, the request is not sent at all, I need to close and reopen the file in order for highlighting to work.

**Comment by tomv564** [comment]
I fixed the behaviour, for some reason the view event listener received two identical selection changed events.

As for the 2nd problem, what language server are you using and can you share a log with a repro (possible the highlight handler crashes?)

**Comment by AmjadHD** [comment]
I don't think it has something to do with the language server, the problem is with all LS:
There's nothing useful in the log, it doesn't work the first time( doesn't send `textDocument/documentHighlight`), I close and reopen the file and the request is sent when i click on a word, I can't understand why it does this ?

**Comment by AmjadHD** [comment]
I noticed that if you click on words too many times (nagging) while the client is starting the LS, highlighting won't work (requests won't be sent) for that file until you close and reopen the file but works fine for other files, can you try and confirm ?

**Comment by rwols** [comment]
Is this before or after https://github.com/tomv564/LSP/commit/5cc11e8a721a6608d40d642462e241ca98188f34?

**Comment by AmjadHD** [comment]
that's before, I'm not using the master's version.

**Comment by rwols** [comment]
I tried here what you describe but I cannot reproduce it. I am using the clangd language server. So, I start up ST and then click on an identifier a few times while LSP is starting up and after that clangd starts up. I get document document highlights.

**Comment by AmjadHD** [comment]
I suppose that was fixed with  5cc11e8, i will try the master's version and see if it persists.

**Comment by AmjadHD** [comment]
I cloned the repo to my packages dir and satisfied dependencies but the plugin is not working:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\LSP\boot.py", line 19, in <module>
    from .plugin.rename import *
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\rename.py", line 1, in <module>
    from .core.clients import LspTextCommand
ImportError: cannot import name LspTextCommand
```
and indeed .core.clients doesn't have a `LspTextCommand`, is it working for you ?

**Comment by rwols** [comment]
Working fine for me. Are you sure you cloned it into your Packages directory?

**Comment by AmjadHD** [comment]
apparently @tomv564 made breaking change in .plugin.rename without realizing it, try pulling the latest changes, It probably will give the same error, anyway I reverted the change (`from .core.clients import LspTextCommand` => `from .core.registry import client_for_view, LspTextCommand`) and now it's working, but not the highlighting, unfortunately the bug persists for me, Anyway it's not that annoying, i can live with it :smiley: .

**Comment by rwols** [comment]
I think this can be closed.

**Comment by tomv564** [comment]
Thanks for the reminder!
