### ISSUE TITLE
TypeScript server diagnostics clash with Vue server

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#393]
### Bug:
* Linux, [lsp-tsserver](https://github.com/tomv564/lsp-tsserver), [vue-language-server](https://www.npmjs.com/package/vue-language-server)
* Installed LSP from git
* Minimal reproduction steps
1. Make the TypeScript server start when a vue file is open by putting the vue syntax in the ts-server-config.
```jsonc
"vue-ls": {
  "command": ["node", "/home/predrag/.npm-global/bin/vls"],
  "enabled": true,
  "languageId": "vue",
  "scopes": ["text.html.vue"],
  "syntaxes": [
 	"Packages/Vue Syntax Highlight/Vue Component.sublime-syntax"
  ]
},
"ts-ls": {
  "command": ["node", "/home/predrag/.npm-global/bin/lsp-tsserver", "--stdio"],
  "enabled": true,
  "languageId": "typescript",
  "scopes": ["source.js", "source.ts"],
  "syntaxes": [
	"Packages/JavaScript/JavaScript.sublime-syntax",
	"Packages/TypeScript Syntax/TypeScript.tmLanguage",
	"Packages/Vue Syntax Highlight/Vue Component.sublime-syntax" // <-- added this here
  ]
},
```

2. Create a `some.vue` file.
3. Paste this in `some.vue`. (This is a valid vue file, should not display any error).
```html
<template>
  <div>
    <ul>
      <li 
        v-for="name in names"
        :key="`id-${name}`">
        {{ key }}
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  data () {
    return {
      names: ['Gaga', 'Dijana', 'Dana']
    }
  }
}
</script>

```

What I expect to see. I expect to see no errors.
What I do see, a lot of TypeScript errors. 

![2018-08-09-021216_683x768_scrot](https://user-images.githubusercontent.com/22029477/43870817-c3ea7a00-9b79-11e8-8233-8b998d1f1b55.png)

### log 

```plugins loaded
LSP: global configs ['eslint=False', 'py-ls=True', 'vue-ls=True', 'golsp=False', 'html-ls=True', 'rls=False', 'polymer-ide=False', 'php-ls=True', 'reason=False', 'pyls=False', 'rlang=False', 'phpls=False', 'clangd=False', 'css-ls=True', 'ts-ls=True', 'jdtls=False', 'ocaml=False']
LSP: window 2 starting 1 initial views
LSP: window 2 requests vue-ls for /home/predrag/.config/sublime-text-3/Packages/LSP/index.vue
LSP: starting in /home/predrag/.config/sublime-text-3/Packages/LSP
LSP: starting ['node', '/home/predrag/.npm-global/bin/vls']
LSP:  --> initialize
LSP: window 2 added session vue-ls
LSP: window 2 requests ts-ls for /home/predrag/.config/sublime-text-3/Packages/LSP/index.vue
LSP: starting in /home/predrag/.config/sublime-text-3/Packages/LSP
LSP: starting ['node', '/home/predrag/.npm-global/bin/lsp-tsserver', '--stdio']
LSP:  --> initialize
LSP: window 2 added session ts-ls
reloading settings Packages/User/Package Syncing.sublime-settings
Package Syncing: Start Complete Sync
LSP:  --> textDocument/didOpen
LSP:  --> initialized
LSP: <--  window/logMessage
server: Vetur initialized
LSP:  --> textDocument/didOpen
LSP:  --> initialized
Package Syncing: Already running
LSP: <--  textDocument/publishDiagnostics
LSP: <--  textDocument/publishDiagnostics
```

The typescript server doesn't see this as a vaild `.js` or `.ts` file.

**Comment by predragnikolic** [comment]
I found I weird way to make it work the way it should work, it has it downsides.  
But just to demonstrate.
 
I noticed that if i put the typescript client configuration outside of the `clients` configuration and
when the vue language starts, I get `JavaScript` autocompletion, hover, just like before, but the  diagnostics reports only errors that occur in the script tag. See picture bellow. 
**Main point, it reports what it should report.**

![2018-08-09-023500_683x697_scrot](https://user-images.githubusercontent.com/22029477/43871426-e09e185c-9b7c-11e8-96ef-51100103d433.png)
The diagnostics `source` is None, not a big problem.

Here is how the `config` should look like if you want to try it yourself.  
```jsonc
{
	"auto_show_diagnostics_panel": false,
	"clients":
	{
		//... other servers
		"vue-ls": {
			"command": ["node", "/home/predrag/.npm-global/bin/vls"],
			"enabled": true,
			"languageId": "vue",
			"scopes": ["text.html.vue"],
			"syntaxes": [
				"Packages/Vue Syntax Highlight/Vue Component.sublime-syntax"
			]
		},
	},
	// outside of the client configuration
	"highlight_active_signature_parameter": false,
	"log_debug": true,
	"ts-ls": {
		"command": ["node", "/home/predrag/.npm-global/bin/lsp-tsserver", "--stdio"],
		"enabled": true,
		"languageId": "typescript",
		"scopes": ["source.js", "source.ts"],
		"syntaxes": [
			"Packages/JavaScript/JavaScript.sublime-syntax",
			"Packages/TypeScript Syntax/TypeScript.tmLanguage",
			// This is also unneccssary "Packages/Vue Syntax Highlight/Vue Component.sublime-syntax"
		]
	}
}
```

The downside by putting the TypeScript client configuration outside of the `clients` config... is that  the `lsp-tsserver` won't start for `.js`, `.ts` files.

**Comment by tomv564** [comment]
My guess is that a plain javascript/typescript language server won't parse these "vue" files unless it understands that embedding is used (and that it should look for the `<script>` block.

The Vetur language server wraps the vue language server, perhaps it can be of help?
See also how that project switches between providers when handling embedded content: 
https://github.com/vuejs/vetur/blob/master/server/src/modes/embeddedSupport.ts

**Comment by predragnikolic** [comment]
Sorry for the late reply on this, Tom.  
I tried to tinker around this, but I didn't solve this. But here is maybe something useful what I concluded.

I didn't like the thing where I needed to put the syntax of some language (Vue) in some other language server configuration (Typescript) to start the server `typescript` server in a `vue` file. 

I wanted the server to start based on the scope, not the syntax :pray:.
But I can't just rely on the scope where the cursor is. Luckily  there is a `find_by_selector` on the `view` object, looks something like this `view.find_by_selector("source.js")`. The only thing was to supply it the scopes, which I can grab from the `LanguageConfig` instance.

I ended up discarding all the changes, because it didn't work like I expected. But maybe you can reconsider moving to scope instead of syntax. 

I think this approach would be better than relying on somebody needing to put the syntax into the configuration. What do you think?

**Comment by tomv564** [comment]
What is wrong with having to add syntaxes to your language server config?

It would be a significant (and perhaps less performant) change to setup event listeners that listen to _every_ view all the time in case a relevant scope shows up. Syntax is a more constant filter for LSP to not have to check "is this file now supported" ?

**Comment by tomv564** [comment]
I think we're veering from the actual problem now?

You don't need a separate typescript server, but you likely need to do some research to find out why the vue language server doesn't provide hover or completion features in vue components.
