### ISSUE TITLE
golsp stopped working with 0.7

### ISSUE THREAD

**Issue by otto-md** [tomv564/LSP#394]
Hello,

after I upgraded to 0.7 golsp is no longer starting for me. I have not changed my config (see below). If I look in the Activity Monitor I can also verify that `go-langserver` is not started. Which it used to do.

Also I see no LSP messages in the gutter when I launch Sublime. I used to see a LSP starting message there, I think.

And LSP features like go to reference no longer works.

* OS and language server
macOS
* How you installed LSP (Package Control or from git?)
Package Control
* Minimal reproduction steps
Start Sublime with config below. Expect `golsp` to start.
* Log (trimmed)

I got this after having enabled `log_debug`:
```
LSP: global configs ['polymer-ide=False', 'pyls=False', 'ocaml=False', 'rlang=False', 'reason=False', 'rls=False', 'eslint=False', 'phpls=False', 'clangd=False', 'golsp=False', 'jdtls=False']
LSP: window 3 starting 1 initial views
```

My config:
```json
// Settings in here override those in "LSP/LSP.sublime-settings",
{
  "log_debug": true,
	"clients": {
		"golsp": {
      "command": ["go-langserver", "-gocodecompletion"],
      "scopes": ["source.go"],
      "syntaxes": ["Packages/Go/Go.sublime-syntax"],
      "languageId": "go",
      "initializationOptions": {
        "goimportsLocalPrefix": "mindoktor.io"
      }
    },
  },
}
```

**Comment by predragnikolic** [comment]
I can see in the logs that `LSP: global configs [..., 'golsp=False', ...]`. I think your server is not enabled.

Can you open the command palette and run `LSP: Enable Language Server Globaly`, and from the list of servers that will appear chose  `golsp`?

**Comment by predragnikolic** [comment]
Nothing ;)

> Any idea why I had to do that now? Its not anything Ive had to do before.

I can only guess. Maybe when you upgraded, your config for `golsp` didn't have the `"enabled": true,` option set up. So maybe, LSP just assumed that it wasn't enabled. 

That is just my theory, I may be completely wrong :D

**Comment by OberstKrueger** [comment]
I had the same issue with RLS. Maybe somewhere in the upgrade, the enabled option was removed or something, but it was working a few weeks ago, and then when I started to use it again today after everything updated, RLS had to be manually enabled again.
