### ISSUE TITLE
[JavaScript] get LSP: config not available for view error

### ISSUE THREAD

**Issue by rzec-r7** [tomv564/LSP#396]
**OS**: Max OS X
**Language Server**: lsp-tsserver

So I wanted to give this plugin a try as an alternative to VS Code as this is really the only thing missing from SublimeText that VS Code has however it does not seem to be working properly.

I have installed the package through Package Manager and installed `lsp-tssserver` globally with `npm install -g lsp-tsserver`. My configuration looks like this:

```
{
  "js": {
    "command": ["lsp-tsserver"],
    "enabled": true,
    "languageId": "javascript",
    "scopes": ["source.js"],
    "syntaxes": ["Packages/Babel/JavaScript (Babel).sublime-syntax", "Packages/JavaScript/JavaScript.sublime-syntax"]
  },
  "jsts": {
    "command": ["lsp-tsserver"],
    "enabled": true,
    "languageId": "typescript",
    "scopes": ["source.ts", "source.tsx"],
    "syntaxes": ["Packages/TypeScript-TmLanguage/TypeScript.tmLanguage", "Packages/TypeScript-TmLanguage/TypeScriptReact.tmLanguage"],
  },
  "log_debug": true,
  "log_server": true,
  "log_stderr": true
}
```

The LSP related logs from the console are:

```
...
reloading plugin LSP.boot
...
plugins loaded
LSP: global configs ['clangd=False', 'polymer-ide=False', 'reason=False', 'rlang=False', 'golsp=False', 'ocaml=False', 'pyls=False', 'jdtls=False', 'eslint=False', 'phpls=False', 'rls=False']
LSP: window 2 starting 1 initial views
```

Any time I click into a .js file, I get something like this:

```
LSP: config not available for view /path/to/focused/file/in/editor.js
```

I have double checked that the scopes include `source.js` when I view them for the file in question and made sure the syntax that shows up when I do `sublime.active_window().active_view().settings().get("syntax")` for that file is in the syntaxes config array so I am not sure what else I can try to get this working.

Any help would be appreciated.

**Comment by rtxm** [comment]
Same here for python since last update of LSP.
OS: Linux
Language server: pyls

**Comment by predragnikolic** [comment]
Hello, 
Your configuration for servers should be nested in `"clients"`.
So it should look like this.
```json
{
  "clients": {
     "js": {
      "command": ["lsp-tsserver"],
      "enabled": true,
      "languageId": "javascript",
      "scopes": ["source.js"],
      "syntaxes": ["Packages/Babel/JavaScript (Babel).sublime-syntax", "Packages/JavaScript/JavaScript.sublime-syntax"]
    },
    "jsts": {
      "command": ["lsp-tsserver"],
      "enabled": true,
      "languageId": "typescript",
      "scopes": ["source.ts", "source.tsx"],
      "syntaxes": ["Packages/TypeScript-TmLanguage/TypeScript.tmLanguage", "Packages/TypeScript-TmLanguage/TypeScriptReact.tmLanguage"],
    }
  },
  "log_debug": true,
  "log_server": true,
  "log_stderr": true
}
```

**Comment by rzec-r7** [comment]
🤦‍♂️ that was the issue, thanks for pointing out the errors of my way (a.k.a. dumb question).

**Comment by predragnikolic** [comment]
Things like this happen :-D
