### ISSUE TITLE
Error for textDocument/hover in javascript file

### ISSUE THREAD

**Issue by rzec-r7** [tomv564/LSP#397]
OS: Max OS X
LSP Source: Package Manager

My config:

```json
{
  "clients": {
     "js": {
      "command": ["lsp-tsserver"],
      "enabled": true,
      "languageId": "javascript",
      "scopes": ["source.js"],
      "syntaxes": ["Packages/Babel/JavaScript (Babel).sublime-syntax", "Packages/JavaScript/JavaScript.sublime-syntax"]
    }
  },
  "log_debug": true,
  "log_server": true,
  "log_stderr": true,
  "log_payloads": true
}
```

I have an npm package that does something like this:
```js
//...
import * as utils from 'src/utils';
//...
```

and then exports that like this:

```js
export {
  //...
  utils,
  //...
}; 
```

Then I import that like this:

```js
import {utils} from 'npm-package-name';
```

now if I do `utils.` I get a list of the expected auto complete results however when I select a function for example, I get this error:

```
LSP:  --> textDocument/signatureHelp
LSP:      {'code': -32603, 'message': 'Request textDocument/signatureHelp failed with message: Debug Failure. False expression.'}
```

if I hover over the function name, I get pretty much the same thing:

```
LSP:  --> textDocument/hover
LSP:      {'code': -32603, 'message': 'Request textDocument/hover failed with message: Debug Failure. False expression.'}
```

The same exact code give the function signature help in VS Code so I am not sure what is going on here.

**Comment by tomv564** [comment]
This issue belongs in the https://github.com/tomv564/LSP-tsserver repo.
As I just upgraded to a newer typescript library and haven't seen all issues yet, you may want to consider reverting to a previously published version of lsp-tsserver

**Comment by tomv564** [comment]
By the way, thanks for the report, will look into it!
