### ISSUE TITLE
Make autocomplete trigger setup easy

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#4]
Options are:
* detect missing triggers and add them programmatically
* ship trigger defaults as part of the package

**Comment by deathaxe** [comment]
Not sure if it is possible to catch all 3rd party syntaxes programmatically.

In this case I think a set of defaults in a syntax specific settings file for each of the most well known packages or a Preferences.sublime-settings with the list of rules might be the best idea.

Alternatively we could file an issue in https://github.com/sublimehq/Packages/issues to ask for selectors to be added to the default syntax packages. From my perspective this was even better as even simple word completion triggered by `->` or `::` or `.` in C/C++ by default is even better than nothing and you don't need to mess around with settings which belong to external packages.

**Comment by rwols** [comment]
The problem with `->` and `::` has always been (IMO) that you'll have to use `>:` as the trigger characters and that will also trigger on less-than signs and ternary operators. I'd like to see support for trigger *strings* instead of trigger characters. Anyway, you can just add a file like `C++.sublime-settings` and add those triggers if you want, see e.g. [here](https://github.com/rwols/Clara/blob/master/plugin/C%2B%2B.sublime-settings).

> In this case I think a set of defaults in a syntax specific settings file for each of the most well known packages or a Preferences.sublime-settings with the list of rules might be the best idea.

I agree.

**Comment by tomv564** [comment]
I did not know Packages could contribute syntax-specific settings! If these can be overridden by the user's `C++.sublime-settings`, then I would be in favour of collecting sensible defaults in a `/Languages` subfolder.

I like the trigger strings suggestion, we should revisit it in a future issue (or feel free to create one now)

**Comment by rwols** [comment]
> I like the trigger strings suggestion

Yes, but I think this is more of a core sublime issue. Other plugins have worked around this limitation of Sublime in various ways by checking the surrounding text upon a completion trigger.

> If these can be overridden by the user

Yep: http://docs.sublimetext.info/en/sublime-text-3/customization/settings.html#order-of-precedence-of-sublime-settings-files

**Comment by tomv564** [comment]
As this issue cannot solve missing completion triggers generically, I'll close it but leave this summary:
* Language/server specific LSP add-ons are a great place to apply sensible non-LSP Sublime defaults
* Multi-character trigger awareness would likely improve responsiveness around spread operators (`...`) in javascript and or scope resolution operators (`::` or _Paamayim Nekudotayim_, lol) in many languages. For this I'll create a new issue.
