### ISSUE TITLE
LSP got confused by multiple LanguageHandler's

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#401]
I am running on macOS and the version of LSP from this [PR](https://github.com/tomv564/LSP/pull/400).

There are two LanguageHandler's called [rlang](https://gist.github.com/randy3k/dbc42df4fdff110e3e4b5a94240cadea) and [cquery-r](https://gist.github.com/randy3k/89cc5991e05458bb67b76720da9b91b0) on my system.

When I open any C files, for some reasons, both LanguageHandler's got triggered

<img width="363" alt="screen shot 2018-08-25 at 5 35 12 pm" src="https://user-images.githubusercontent.com/1690993/44622753-3eaa3f80-a88d-11e8-870d-94d197db811d.png">

On the other hand, if I open an R file, nothing happens.

Each of the servers itself works fine if I remove the other one from the system. So it seems to me that it is due to the initializations of the handlers.

**Comment by randy3k** [comment]
I tracked down the error and it is likely caused by the default values in the constructor of [`ClientConfig `](https://github.com/tomv564/LSP/blob/c317572d683d2957c50e0712d6228a5088672e7a/plugin/core/types.py#L55). All ClientConfig instances are sharing the same `languages` variables if they do not provide one.

To see the bug:

```python
class A:
    def __init__(self, x=[]):
        self.x = x

a = A()
b = A()

a.x.append(1)
b.x  # == a.x
```


A simple workaround to my case is to specify pass `languages=[]` to `ClientConfig`.

**Comment by tomv564** [comment]
Great find, copying the default languages value in the constructor might fix ClientConfig?
I'll try to get a fix in as soon as possible!

**Comment by tomv564** [comment]
I could repro and fix in https://github.com/tomv564/LSP/commit/a902ce56e421cced36768963f98dfe5528ee2509

Hope it solves the multiple servers for you!
