### ISSUE TITLE
Ability to use a remote server in TCP mode

### ISSUE THREAD

**Issue by jduquennoy** [tomv564/LSP#403]
Hi,

I am trying to use the LSP plugin in sublimeText with a remote protocol server.
As far as I have understood, the only thing that can be specified is a TCP port, and indeed, in the code, I can see that the host is hard coded to localhost.

Is there a technical difficulty with remote TCP hosts ?
If no, do you think it would be possible to add a host parameter to the configuration, so that we can specify a server that is not installed locally ?

### Setup informations:
* OS and language server:
Sublime text running on Mac OS X, the language server is OpenHAB, hosted on Linux
* How you installed LSP (Package Control or from git?)
Installed by cloning the git repo

**Comment by tomv564** [comment]
Hi, good idea, I've added `tcp_host` just now. Hope it works for your language server!
