### ISSUE TITLE
Show popup for 'info' level diagnostics

### ISSUE THREAD

**Issue by tophattom** [tomv564/LSP#405]
### Question:

Is there a way to show popup dialog for diagnostics of `info` level? Currently I can only see the popup for `warning` messages. `info` diagnostics are only shown in the status bar at the bottom of the screen.

*Please include in your report:*

* OS and language server: OS X 10.11.6
* How you installed LSP (Package Control)

### Suggestion:

Maybe add a setting to control which diagnostics open a popup.

**Comment by tomv564** [comment]
Good suggestions, and a good opportunity to remove some duplication around error and warning displays.

**Comment by tomv564** [comment]
Added `auto_show_diagnostics_panel_level` setting to control when the panel is opened. 
Please show me if the popups on hover are unmanageable!
