### ISSUE TITLE
LSP dont pick up document changes with keybindings like ['j', 'j']

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#406]
### Bug:

Hello,
I use the Vintage plugin and I have this keybinding for exiting insert mode:
```json
{ 
    "keys": ["j", "j"], "command": "exit_insert_mode",
    "context":
    [
        { "key": "setting.command_mode", "operand": false },
        { "key": "setting.is_widget", "operand": false }
    ]
},
```

![output](https://user-images.githubusercontent.com/22029477/45183737-3bb43500-b225-11e8-9cef-dd23c51b3bf0.gif)

Here is the problem, when I type `['j','j']` lsp reports that there is an error `cannot find name 'j'`, but should't report nothing.

Here is the log and what I think is happening:
```jsonc
LSP:  --> textDocument/didOpen
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange // first time pressed j, document is changed, because j is added to the document
LSP:  --> textDocument/completion  // got autocomplete suggestion, pressed j again, j is removed from document, because ['j','j'] is a keybinding. I think that this should  trigger textDocument/didChange, but it doesn't.
LSP: <--  textDocument/publishDiagnostics // I get the diagnostic `cannot find name 'j'`,
```

**Comment by tomv564** [comment]
I had no idea Vintage-registered keypresses actually hit the document.
I think the diagnostics are hard to avoid as we do a sync didChange for completions on that first 'j'.
Only using completions manually or on trigger chars would probably help.

But does the diagnostic disappear once the Vintage has executed and the 'j' is removed from the buffer?

**Comment by predragnikolic** [comment]
`['j','j']`, it is not included in the default Vintage key bindings. I added it and it is just an alias for pressing `esc` to exit from insert mode to normal mode.

> But does the diagnostic disappear once the Vintage has executed and the 'j' is removed from the buffer?

No, the diagnostic won't disappear until I make a change to the document again. 
Like for example, I type something new. 
Or like I showed in the gif above, If you noticed at the end, I pressed `x` and `u`. 
`x` deleted a character beneath the cursor, and `u` to undo that. This causes LSP to refresh diagnostics.

I could just use `esc` and don't have this issue, but I like pressing `j j` and it is a just a little annoying seeing diagnostics when the document is fine. 
It is like LSP didn't pick up when `j` was removed. 
This issue is not that important, I just wanted to know if there is a easy way to fix this. If not, than I will use `esc` :)

**Comment by predragnikolic** [comment]
> Only using completions manually or on trigger chars would probably help.

I set `"complete_all_chars"` to `false`. It does the trick. but then I lost some autocompletion suggestions. So I set it back to `true`.

I partially solved my problem by setting `"auto_complete_delay"` in the default settings, from `50` to `200`. It still happens sometimes, but it is definitely more rare when I increased the delay.
