### ISSUE TITLE
Goto definition/reference/diagnostic can open duplicate views

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#407]
As reported by @drew-wallace in #289 

>  I'm still experiencing some weirdness after this fix in 0.7.1. I use goto definition to take me to a location within the same file, but a new tab opens up instead. Turns out it's because the drive letter is lower case so Sublime thinks it's a different file even though it's the same

Which was VS Code's funky uri handling leaking into vue language server:

https://github.com/Microsoft/vscode-uri/blob/b1d3221579f97f28a839b6f996d76fc45e9964d8/src/index.ts#L1025

That said, it looks like it used to work in Sublime and broke in a certain build:

https://github.com/SublimeTextIssues/Core/issues/2320

This issue tracks how LSP is affected and a possible workaround.

**Comment by rwols** [comment]
This should be fixed as of build 3180 (we're at build 3190 at the time of this comment).
