### ISSUE TITLE
Request intelephense server support

### ISSUE THREAD

**Issue by carlevison** [tomv564/LSP#409]
I noticed the last issue was closed in January but considering intelephense is superior to the current PHP intellisense we have has anybody tried to implement this.

https://github.com/bmewburn/intelephense-server

It would be fantastic to have this in Sublime.

**Comment by rwols** [comment]
People seemed to have got it working in this issue: https://github.com/tomv564/LSP/issues/259

**Comment by carlevison** [comment]
Thanks @rwols i've just visited this issue but unfortunately I can't get it to work, it doesn't seem to be indexing.

**Comment by jfcherng** [comment]
I am using it and could confirm it's working. Here's my settings for it.

```javascript
        "intelephense-ls":
        {
            // npm i -g intelephense-server
            "enabled": true,
            "command": [
                "node",
                "C:/Users/jfcherng/AppData/Roaming/npm/node_modules/intelephense-server/lib/server.js",
                "--stdio",
            ],
            "scopes": ["source.php", "embedding.php"],
            "syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
            "languageId": "php",
            "initializationOptions": {
                "storagePath": "C:/Users/jfcherng/AppData/Local/Temp/intelephense-ls",
            },
        },
```


---


[intelephense-server](https://github.com/bmewburn/intelephense-server) runs obviously faster than [php-language-server](https://github.com/felixfbecker/php-language-server) but some latest PHP features would be linted as errors.

- https://github.com/bmewburn/intelephense/issues/122
- https://github.com/bmewburn/intelephense/issues/143

**Comment by carlevison** [comment]
Now we're getting somewhere! I'm missing a lot of completions, am I missing something?

VSCode

<img width="1711" alt="screen shot 2018-09-08 at 16 55 48" src="https://user-images.githubusercontent.com/6619631/45256014-5fdc5700-b388-11e8-862d-e1ae10ae8905.png">

Sublime

<img width="1711" alt="screen shot 2018-09-08 at 16 56 07" src="https://user-images.githubusercontent.com/6619631/45256018-65d23800-b388-11e8-9118-eff1a6a8526d.png">

Thanks for your help :)

**Comment by jfcherng** [comment]
@carlevison Probably because files (maybe `App\Http\Controllers\Controller` in your example) are not indexed. If you open the parent class files, they would be index... And more completions would show.

https://github.com/tomv564/LSP/issues/259#issuecomment-378065182

**Comment by carlevison** [comment]
@jfcherng Unfortunately not, I still don't get completions.

<img width="1711" alt="screen shot 2018-09-08 at 17 36 18" src="https://user-images.githubusercontent.com/6619631/45256410-ffe8af00-b38d-11e8-91c5-9c89c3556abf.png">

**Comment by jfcherng** [comment]
@carlevison I have no clue then. I have the same issue as well, to a certain degree .

**Comment by carlevison** [comment]
@jfcherng Thank you anyway.

Hopefully someone will work on this so it works how it does in VSCode which is entirely possible.

**Comment by tomv564** [comment]
One hint can be to investigate the VS Code extension for the intelephense server. Any extra logic beyond the standard messages would have to be implemented as an additional package to LSP.

We should document the configuration for sure!

**Comment by tomv564** [comment]
Added intelephense to the documentation. 
If someone adds a "bin" field to their package.json then it can be part of the LSP default configs.
There is an issue here documenting why the server alone doesn't update/parse from disk.
https://github.com/bmewburn/intelephense-server/issues/1
