### ISSUE TITLE
Allow outline and background regions for highlighting

### ISSUE THREAD

**Issue by FichteFoll** [tomv564/LSP#411]
### Suggestion:

Please allow displaying related highlight as outlines or solid boxes (with background color). My color scheme defines an alpha color for `markup.changed`, for example, which I like for normal purposes, but underlines are only barely visible with it. Or maybe it's not even alpha but just the color in general.

Either way, this is very hard to notice:

![2018-09-14_00-50-08](https://user-images.githubusercontent.com/931051/45520123-3708f700-b7b8-11e8-8992-9fd2c395b236.png)

**Comment by tomv564** [comment]
Good suggestion, I added "fill" and "box".

**Comment by tomv564** [comment]
I’ll try to do a release this weekend!
