### ISSUE TITLE
Not using `"shell_environment"` setting's python executable; so `pyls` doesn't exist

### ISSUE THREAD

**Issue by OJFord** [tomv564/LSP#414]
### Bug:

* macOS & python-language-server
* package control
* enable pyls for project or globally
* [how do I get log? 'show diagnostics' is empty]

macOS/ST/LSP/pyls all at latest stable release.

The status bar says 'starting pyls' while I hover over a python file, and never seems to start - autocompletion not working as a basic test.

I've tried restarting LSP & ST. I can start pyls OK by `python -m pyls`.

**Comment by OJFord** [comment]
```json
{
    "log_debug": true,
    "clients": {
        "pyls": {
            "enabled": true
        }
    }
}
```

If I run `LSP: Show diagnostics` it just opens an empty console, am I looking in the wrong place?

**Comment by predragnikolic** [comment]
Wrong place it is :D  you need to press ``ctrl+` `` to open the sublime console.

Not with `log_debug` enabled. Close and reopen sublime, and open a python file. 
Press `` ctrl+` ``, the console should popup with messages like these:
``` 
...
plugins loaded
LSP: received config rls from LspRlsPlugin
LSP: global configs ['rls=True', 'vue-ls=True', 'py-ls=True', 'ts-ls=True', 'jdtls=False', 'polymer-ide=False', 'clangd=False', 'reason=False', 'intelephense-ls=False', 'html-ls=True', 'ocaml=False', 'phpls=False', 'php-ls=True', 'eslint=False', 'pyls=False', 'json-ls=True', 'css-ls=True', 'golsp=False']
LSP: window 2 starting 1 initial views
LSP: window 2 requests py-ls for /home/predrag/.config/sublime-text-3/Packages/LSP/plugin/core/protocol.py
LSP: starting in /home/predrag/.config/sublime-text-3/Packages/LSP
LSP: starting ['/home/predrag/.local/bin/pyls']
LSP:  --> initialize
LSP: window 2 added session py-ls
reloading settings Packages/User/Package Syncing.sublime-settings
Package Syncing: Start Complete Sync
LSP:  --> textDocument/didOpen
LSP:  --> initialized
Package Syncing: End Complete Sync
Package Syncing: Already running
LSP: <--  textDocument/publishDiagnostics
``` 
Copy those and paste them here :)

**Comment by OJFord** [comment]
Ah, thanks.
```
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'pyls'
```
That'll do it! That's the wrong python. I have `"shell_environment": "/usr/local/bin/fish"` set, which should mean it runs with me shell's environment which has (by default):
```
...>which python
.../.pyenv/shims/python
...>python --version
Python 3.7.0
```

so from where does LSP get its `python`, and how can I change it?

**Comment by predragnikolic** [comment]
In the terminal type `which pyls`  you should get a path like this `/home/predrag/.local/bin/pyls`. Copy it.

now in you `pyls` settings 
```jsonc
{
    "log_debug": true,
    "clients": {
        "pyls": {
            "command": [
	       "/home/predrag/.local/bin/pyls" // paste it here.
            ],
            "enabled": true
        }
    }
}
```

Let me now if this works for you.

**Comment by OJFord** [comment]
I'd rather not over configure though, and ` File "./python3.3/...` is bound to cause other problems later - why isn't it using the python version from my env?

**Comment by predragnikolic** [comment]
The error was `FileNotFoundError: [Errno 2] No such file or directory: 'pyls'`, so I assume it can't start the server cause it can't find `pyls`. Just try what I said in the earlier message.
What could go wrong?

**Comment by OJFord** [comment]
Yes and the reason it can't find a file or directory `'pyls'` is that it's not using an environment in which that exists. If it were using the `python` executable from my shell environment (and as I said I do have `"shell_environment": "path/to/shell"` set) `python` would be not v3.3 but v3.7.0, and `pyls` would be available.

> What could go wrong?

The next thing that tries to use `./python3.3`, wherever that is.

**Comment by OJFord** [comment]
With `python -m pyls` there's no error, the starting message disappears, but nothing happens - still nothing in diagnostics; no autocomplete, no complaint about undefined variables etc.
```
LSP: window 2 requests pyls for <.../...>.py
LSP: starting in /path/to/project
LSP: starting ['python', '-m', 'pyls']
LSP:  --> initialize
LSP: window 2 added session pyls
LSP: LSP stdout process ended.
```

**Comment by predragnikolic** [comment]
Here is how my configuration for python looks.
````json 
"py-ls": {
	"command": [
		"/home/predrag/.local/bin/pyls"
	],
	"enabled": true,
	"languageId": "python",
	"scopes": [
		"source.python"
	],
	"syntaxes": [
		"Packages/Python/Python.sublime-syntax"
	]
},
```

**Comment by tomv564** [comment]
The language server appears to exit abruptly - can you set `log_server` to true in the LSP settings and try again?

LSP doesn't create a shell to launch the server process, this is perhaps why your environment python is not used.
If you start sublime using `subl` from the terminal, does it work with "pyls" then?

Some side notes for future improvements:

* "LSP stdout process ended." is a crappy way to say the language server shut itself down.

* LSP should really notice the failure to start and do something useful in this case, as few users check the console. At the same time, an LSP add-on package could help handle virtual environments.

* The new issue template needs updating, as this is an extremely common problem covered in the  troubleshooting guide (https://lsp.readthedocs.io/en/latest/#troubleshooting)

**Comment by AmjadHD** [comment]
I don't if this is the right place to mention this but every time pyls is started  it shows this error and the plugin_host is shut down:
```
LSP: starting ['pyls']
LSP:  --> initialize
LSP: window 2 added session pyls
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

**Comment by brotherdust** [comment]
I get the same issue. Here's the details:
Console:
```
LSP: global configs ['phpls=False', 'rls=False', 'clangd=False', 'golsp=False', 'jdtls=False', 'reason=False', 'eslint=False', 'polymer-ide=False', 'ocaml=False', 'pyls=True']
LSP: window 2 starting 1 initial views
LSP: window 2 requests pyls for D:\Code\RBB\Sonar Tools\sonar-rest-api\get-radius-reply-attributes.py
LSP: starting in D:\Code\RBB\Sonar Tools\sonar-rest-api
LSP: starting ['pyls']
LSP:  --> initialize
LSP: window 2 added session pyls
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```
LSP.sublime-settings (User):
```
{
    "log_debug": true,
    "log_server": true,
    "clients": {
        "pyls": {
            "enabled": true
        }
    }
}
```

**Comment by tomv564** [comment]
The next release of LSP will clearly show that the server failed to start and why in some cases.

Some further thoughts:

When "/usr/bin/local/fish" is started, does it automatically activate "/.pyenv/shims/python"?

The `./python3.3` you saw in the exception traceback is Sublime Text's internal python - it is not the python used to run "pyls" in that case. (You can run `import shutil; shutil.which('python')` to find out which python it's trying to use)

You should also be able to just use `"pyls"` instead of `"python -m pyls"`as the command on OS-X.

@AmjadHD and @brotherdust, I opened issue #426 for your problem.
