### ISSUE TITLE
add Kotlin Language Server

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#415]
### Feature Request:

add support for [kotlin language server](https://github.com/fwcd/KotlinLanguageServer)
requires [building](https://github.com/fwcd/KotlinLanguageServer/blob/master/BUILDING.md) first.

here's the settings:
```json
"kotlinls":
{
    "command":
    [
        "PATH_TO_KotlinLanguageServer/build/install/kotlin-language-server/bin/kotlin-language-server.bat"
    ],
    "enabled": true,
    "languageId": "kotlin",
    "scopes":
    [
        "source.Kotlin"
    ],
    "syntaxes":
    [
        "Packages/kotlin/Kotlin.tmLanguage"
    ]
}
```
additionly you need to install the [Kotlin sublime package](https://github.com/vkostyukov/kotlin-sublime-package) for syntax highlighting.

**Comment by tomv564** [comment]
Thanks for documenting this one, too!
