### ISSUE TITLE
Incorrect behavior when having both lsp-tsserver and vls (vue language server)

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#417]
## Configuration

```
{
	"clients":
	{
		"typescript": {
			"enabled": true,
			"command": ["lsp-tsserver"],
			"languageId": "javascript",
			"scopes": [
				"source.js",
				"source.ts",
				"source.tsx",
			],
			"syntaxes": [
				"Packages/JavaScript/JavaScript.sublime-syntax",
				"Packages/TypeScript-TmLanguage/TypeScript.tmLanguage",
				"Packages/TypeScript-TmLanguage/TypeScriptReact.tmLanguage",
			]
		},
		"vue-ls":
		{
			"enabled": true,
			"command": ["vls"],
			"scopes": [
				"text.html.vue",
			],
			"languageId": "vls",
			"syntaxes": [
				"Packages/Vue Syntax Highlight/Vue Component.sublime-syntax"
			],
		},
	},
}
```

## Example files

example.vue
```vue
<template>
    <div>HI</div>
</template>

<script>
import Vue from 'vue';

Vue.mixin({});
</script>
```

example.js
```js
import Vue from 'vue';

Vue.mixin({});
```

### Expected:
Open both files so that both servers are initialised and then hover Vue object in both of those files. In both cases you should get object definition.

### What happens:
Hovering the object in vue file fails because typescript language server is used.

## Conclusion
The reason for the bug is that `source.js` syntax is more specific inside of the script tag of vue file so typescript server is chosen (script tag in vue file has these scopes:
```text.html.vue source.js.embedded.html source.js meta.export.js meta.object-literal.js meta.sequence.js punctuation.section.brackets.end.js```)

I've enabled [your debugging code](https://github.com/tomv564/LSP/blob/c0d5eab043de728c9b5b8895ca2158428973cd70/plugin/core/configurations.py#L40) to check scope weights and this is what I got when hovering object in Vue file:
```
LSP: scope match score text.html.vue vue-ls 24
LSP: scope match score source.js typescript 128
LSP: chose  typescript
```

**Comment by rchl** [comment]
One way to fix it would be to add `"text.html.vue source.js"` scope for vls client.
Then we get these scores:
```
LSP: scope match score source.js typescript 128
LSP: scope match score text.html.vue vue-ls 24
LSP: scope match score text.html.vue source.js vue-ls 152
LSP: chose  vue-ls
```

**Comment by rchl** [comment]
I do wonder though why `syntaxes` configuration doesn't prevent typescript client from running in vue files... Is it a bug?

**Comment by tomv564** [comment]
It sounds like a bug, you are correct that the typescript config should not pick up example.vue. 

Once the _two_ servers are active for the `.vue` file, we're at the mercy of the scope weights.

We need to take a closer look at the config-for-syntax lookup!

**Comment by tomv564** [comment]
Great troubleshooting @rchl!

I hope the knock-on effects of this fix are minimal.
@predragnikolic this might improve the issue you were chasing as well!
