### ISSUE TITLE
OSX PATH issues

### ISSUE THREAD

**Issue by matt-allan** [tomv564/LSP#419]
Hello,

I was having a lot of difficulty getting LSP to to successfully start the PHP language server on one of my machines.  I reviewed the troubleshooting guide before posting this.

I have two machines with identical shell environments and sublime text configurations.  On one machine the language server starts without issue, but on the other one it fails immediately.  When this happens the console displays:

```
LSP: starting ['php', '/Users/matt/code/php-language-server/bin/php-language-server.php']
LSP:  --> initialize
LSP: window 2 added session phpls
LSP: LSP stream logger stopped.
LSP: LSP stdout process ended.
```

Eventually I was able to determine this was caused by the incorrect `php` binary being found.  I was able to fix the issue by changing `php` in the `command` configuration to the absolute path.

The strange thing is, I always start Sublime using the `subl` binary.  If I dump my path in the Sublime console (using `from os import environ; environ['PATH']`) I can see the PHP binary is in my path, and the path is identical between both machines.  I also tried installing the SublimeFixMacPath package and that did not resolve the issue.  Any idea why it would be failing to find the correct binary?

After reading through the plugin code I would have expected to see something in the logs if the process failed to start.  I ran the subprocess in the console manually and was able to recover an error message on stdout and a non zero exit code.  Apparently it's using an old version of PHP, I'm guessing the one in `/usr/bin/php` that comes with macOS.  It seems like we might be able to log the exit code and read stdout if the process quits unexpectedly?

```
>>> import subprocess
>>> from subprocess import PIPE
>>> process = subprocess.Popen(["php", "/Users/matt/code/php-language-server/bin/php-language-server.php"], stdout=PIPE, stderr=PIPE)
>>> stdout, stderr = process.communicate()
>>> stderr
b''
>>> stdout
b'\nParse error: parse error, expecting `"identifier (T_STRING)"\' in /Users/matt/code/php-language-server/bin/php-language-server.php on line 3\n'
>>> process.returncode
255
```

LSP settings:

```json
{
	"clients":
	{
		"phpls":
		{
			"command":
			[
				"php",
				"/Users/matt/code/php-language-server/bin/php-language-server.php"
			],
			"enabled": true,
			"languageId": "php",
			"scopes":
			[
				"source.php",
				"embedding.php"
			],
			"syntaxes":
			[
				"Packages/PHP/PHP.sublime-syntax"
			]
		}
	},
	"log_debug": true,
	"log_payloads": true,
	"log_server": true,
	"log_stderr": true,
	"only_show_lsp_completions": true
}
```

Language Server: https://github.com/felixfbecker/php-language-server

OS: macOS Sierra 10.12.3

How I installed LSP: Package Control

**Comment by tomv564** [comment]
Glad to hear you got it working, thanks for following the troubleshooting steps and reporting these issues!

The PATH issue sounds very similar to #414 - although sublime loads the correct PATH from the shell, this is not used when starting a language server process. I'd like to figure this out soon!

There should be a "Language server phpls has crashed, do you want to restart it?" dialog. Dumping stdio to the logs might be interesting in some cases, but in many others the explanation is in stderr (which `log_server` shows).

**Comment by tomv564** [comment]
I've added an error popup for failed startup - I'll look into the unexpected process termination popup next.

Can you run `import shutil; shutil.which('php')` to confirm which php is being started?

**Comment by tomv564** [comment]
I just realised why I didn't experience the same issue - High Sierra ships with PHP 7 as default PHP.

Regardless we want LSP to respect the PATH parameter, but it seems like Sublime itself also doesn't apply it when invoking subprocess..

**Comment by yuloh** [comment]
Hi @tomv564,

Thanks for the quick response! Looks like it is using the default PHP from OSX.

```
>>> import shutil; shutil.which('php')
'/usr/bin/php'
```

**Comment by rwols** [comment]
Can you list your installed packages for both the working machine and the failing machine?

**Comment by tomv564** [comment]
Closing due to lack of response.

**Comment by aquilacf** [comment]
I assume the following error is related this issue:

`Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/aquila.freitas/Library/Application Support/Sublime Text 3/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 20, in run_in_thread
    subprocess.check_call(popen_args, shell=sublime.platform() == 'windows')
  File "./python3.3/subprocess.py", line 542, in check_call
  File "./python3.3/subprocess.py", line 523, in call
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'npm'`


https://github.com/int3h/SublimeFixMacPath doesn't seem to be maintained anymore.

**Comment by rwols** [comment]
That's because this has all been fixed in ST3 for a long time. Read https://github.com/sublimelsp/LSP-vue/issues/20 for more troubleshooting tips.
