### ISSUE TITLE
Make it clearer that language servers must be enabled

### ISSUE THREAD

**Issue by leifmetcalf** [tomv564/LSP#421]
I spent much time trying to get this plugin work with haskell-ide-engine, as it kept returning "Config not available." Eventually I found that I had to run "LSP: Enable Language Server Globally." If this is not a bug it should be documented somewhere in the install instructions.

**Comment by kamranjon** [comment]
How do you run this? I tried typing it into the sublime console and I get 'invalid syntax'

**Comment by kamranjon** [comment]
For those still struggling with this - it's either Tools -> Command Palette OR shift+ctrl+P to open the command menu - and then you start typing LSP and it will give you a list of all the commands. Enable Language Server Globally fixed my issues as well.

**Comment by tomv564** [comment]
Thanks for the feedback, it should be more visible but I think we can still do more to reduce on boarding pain!
