### ISSUE TITLE
LSP and Microsoft Python Language Server

### ISSUE THREAD

**Issue by espositofulvio** [tomv564/LSP#429]
This is only to inform you that I managed to replace Palantir's Python Language Server with the Microsoft new implementation (which seems reasonably faster).

I left a note on their repository at https://github.com/Microsoft/python-language-server/issues/212

I figured this could help someone else.
Cheers

**Comment by tomv564** [comment]
Nice, if it’s easy to install/launch then we could add it to the default configs

**Comment by espositofulvio** [comment]
Unfortunately they don't provide yet a packaged build, so you basically have to build the server yourself (which is written in C# targeting .NET Core 2.1 and works on Linux and MacOS as well). It's not hard for a developer, but I would wait until they have a nice package available. In the meantime I've written a little guide that was accepted in their repo with the instructions, you can find it [here](https://github.com/Microsoft/python-language-server/blob/master/Using_in_sublime_text.md)

**Comment by tomv564** [comment]
Linked your guide in the documentation, thanks for your effort!
