### ISSUE TITLE
Missing debug information

### ISSUE THREAD

**Issue by ad-si** [tomv564/LSP#432]
### Question:

I want to build my own language server, but it's not working and I'm lacking any debug information which help me move forward. So apparently I'm too stupid, but nonetheless it would be cool if LSP could help me 😅.

The debug log so far says:

```txt
LSP: window 2 requests testlint for /Users/adrian/Projects/feram/website/testlint/source/TestLint/Server.hs
LSP: starting in /Users/adrian/Projects/feram/website/testlint
LSP: starting ['testlint-server']
LSP:  --> initialize
LSP: window 2 added session testlint
```
and the log of exchanged messages is:

```
>>>>>>>>>>>>>>>>>>>>>>>>>
{"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {"capabilities": {"workspace": {"didChangeConfiguration": {}, "applyEdit": true}, "textDocument": {"codeAction": {}, "synchronization": {"didSave": true}, "documentHighlight": {}, "hover": {"contentFormat": ["markdown", "plaintext"]}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["markdown", "plaintext"]}}, "rename": {}, "documentSymbol": {"symbolKind": {"valueSet": [1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14]}}, "rangeFormatting": {}, "references": {}, "formatting": {}, "definition": {}, "completion": {"completionItemKind": {"valueSet": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]}, "completionItem": {"snippetSupport": true}}}}, "rootPath": "/Users/adrian/Projects/feram/website/testlint", "rootUri": "file:///Users/adrian/Projects/feram/website/testlint", "processId": 58091}}

>>>>>>>>>>>>>>>>>>>>>>>>>

<<<<<<<<<<<<<<<<<<<<<<<<<
Content-Length: 377

{"result":{"capabilities":{"foldingRangeProvider":true,"textDocumentSync":1,"documentHighlightProvider":true,"renameProvider":true,"colorProvider":{},"definitionProvider":true,"hoverProvider":true,"codeActionProvider":true,"completionProvider":{"triggerCharacters":["/"],"resolveProvider":false},"documentSymbolProvider":true,"referencesProvider":true}},"jsonrpc":"2.0","id":1}

<<<<<<<<<<<<<<<<<<<<<<<<<
```
And that's it, no more messages afterwards.
So does this mean my result is malformed or what else could it be?

**Comment by ad-si** [comment]
I fixed the error (didn't flush the whole message to stdout), but maybe LSP could have showed me that it received something, but it wasn't a valid message?

**Comment by tomv564** [comment]
Fun initiative! Agree it would be nice to have the client help with such an annoying detail.

With the goal of keeping logs and implementation code simple, I haven't built in extensive debugging support into the LSP package - at least not at the transport level.

So far, I've reasoned that coders could clone the repo and add their own logging where needed. Does that work for you?

**Comment by ad-si** [comment]
> So far, I've reasoned that coders could clone the repo and add their own logging where needed. Does that work for you?

Uhm, my Python capabilites aren't really stellar 😅. All I would have needed is just a "log / dump everything mode". I think this shouldn't be hard to implement and also wouldn't really clutter the code, would it?

**Comment by ad-si** [comment]
> How is your server project going?

Good. Once you've figured out the basic protocol, it's more straight forward.

> I forgot to mention the LSP settings `log_stderr` and `log_payloads`, those should give you more details, and see server output if you are logging to stderr.

Yeah, I already saw and activated them.

> If logging is lacking in some area, you can try adding `debug` statements. For example, before this line to detect your previous issue:

Now that it's working, I can easily log everything on the server side, so that's not a problem anymore, but thanks for the tip. It was just hard at the beginning when the server log looked OK, but the client didn't log anything 😅.

**Comment by tomv564** [comment]
Best of luck, I'll close this issue now then!
