### ISSUE TITLE
Spammed by "temporarily disable server" dialog

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#433]
In new version (with f5a4dcfbe117ddf1a07e1c971e8b14ca7e311c00), I've opened Sublime, it failed to get environment variables from shell (as it was taking more time) and LSP triggered dialog to temporarily disable server as it couldn't find one. I've clicked cancel (I could have disabled it but I didn't) and then the dialog opened again. It kept opening every time on canceling, effectively ddos'ing sublime window.

I guess the easy solution was to just disable server temporarily but I guess I was afraid that the setting will be stored and then I will have to revert that later.

In any case, the dialog probably should only pop up max once per session (or at least until configuration is changed), per server.

**Comment by tomv564** [comment]
Thanks for writing some feedback on this new mechanism. The spamming is annoying and the dialog should be clearer on the effect of your options.

You have to close and re-open the window (or use the "LSP: Enable language server" command) to re-enable the server. 

The behaviour on Cancel is expected. (A supported view is activated when the dialog is closed, which is what usually triggers server startup). I'd like to avoid introducing yet another state for "ignored servers" that the user also should be able to get out of.

Do you have suggestions on how to make the dialog clearer, or another suggestion of handling this situation?

**Comment by rchl** [comment]
1. I think message could be improved to say that server will be disabled *for session* only.

2. Re-enabling doesn't seem to work correctly right now. For example I have vue-language-server defined in my user settings and after I disable it temporarily from the dialog, trying to enable it using "Enable language server globally", it doesn't even appear in the list. I suppose it's only showing servers defined in default config file.

3. Even if "2" would be working, I think it would be confusing as I wouldn't know for sure if I should use "Enable globally" or "Enable per project". Basically there is no command that would have parity with "disable temporarily" functionality. Would expect something like "Enable temporarily disabled server" or similar.

4. I would be fine with not having option to enable temporarily disabled server (and having to restart sublime) but then the dialog should rather say "Server failed to start" which would be enough of an indication that it's not functioning and won't be available for the session.

**Comment by tomv564** [comment]
The above commit removes the retry/spam option and clarifies that the server is disabled in the current window. 
Agree that explicitly enabling/disabling from this state adds confusion, just re-start sublime or reopen the window.
