### ISSUE TITLE
Exclude some folders in project for LSP

### ISSUE THREAD

**Issue by gubsky90** [tomv564/LSP#435]
Can i exclude some folders in project for LSP?
I have some protected folders in mys project, so i got:

LSP:      {'message': "UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/www-data/services/db/data/mysql): failed to open dir: Permission denied in...

Problem in php-language-server (https://github.com/felixfbecker/php-language-server)

**Comment by tomv564** [comment]
The PHP language server itself is wandering into that directory? I don’t think Sublime Text or this package are asking it to go in there. Can you report at the server’s repo so they can help you?

**Comment by gubsky90** [comment]
Yes, php-language-server explore all php files in rootPath (now sublime project_path). 

Please see my pull request : https://github.com/tomv564/LSP/pull/436

**Comment by tomv564** [comment]
In general this package doesn't try to take on features for just one language server. Fixing the issue in PHP language server would help people using other editors as well.

I found the server's failure to handle permissions here:
https://github.com/felixfbecker/php-language-server/issues/462
