### ISSUE TITLE
[Feature Request] jump back to symbol

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#438]
### Suggestion:

Would you add a "jumb back" command so that one can easily go back to the symbol on which a "goto definition" action has been triggered.

**Comment by predragnikolic** [comment]
Yes it is supported, but it doesn't always jump back to the exact previous point.

**Comment by tomv564** [comment]
Perhaps setting the cursor to the clicked symbol before navigating to definition will ensure that location is visible when returning?

**Comment by AmjadHD** [comment]
Oh, I apologize, didn't know about that, <kbd>ctrl</kbd>+<kbd>-</kbd> doesn't work though, I had to rebind the command.

**Comment by tomv564** [comment]
Closing, feel free to open a new issue or PR for improvements!
