### ISSUE TITLE
Don't query language server for completions in strings / comments?

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#44]

**Comment by rwols** [comment]
I think that is a safe bet, yes.

**Comment by tomv564** [comment]
LSP will no longer handle completion requests in strings and comments (see bf26384b09e5737a01bec225f5331fe077697129). Should fix slowdowns when eg. entering relative paths in strings.

If sublime completions in strings are totally undesired, the trigger characters must also be restricted, e.g.:
`
"auto_complete_triggers": [ {"selector": "source.python - comment - string", "characters": "."} ],
`
