### ISSUE TITLE
[Question] Diagnostics panel to show types

### ISSUE THREAD

**Issue by adamgajzlerowicz** [tomv564/LSP#442]
Is it possible to show types using diagnostics panel, for where the cursor currently is? 

I use vim mode and currently I need to use mouse to see info about function signature of variable type. It would be awesome to just travel with keyboard and just have that bottom panel to popup whenever I put my cursor on a function, variable or type, rather then the lint error visible currently.

![image](https://user-images.githubusercontent.com/675615/47613396-e65f0c00-da8e-11e8-99b7-877755e744bd.png)

Thanks

**Comment by tomv564** [comment]
Yep, this is is possible but not enabled by default because it's hard to find non-conflicting keybindings.
From the quick panel, choose Edit Keybindings. Then add this entry to the array:
```
	{ "keys": ["super+option+h"], "command": "lsp_hover"}
```
For OS-X, this would bind <kbd>cmd</kbd>+<kbd>option</kbd>+<kbd>h</kbd> to trigger the popup.

**Comment by adamgajzlerowicz** [comment]
Thank you for your answer. The shortcut does work, but I actually meant to have definition automatically showing in `diagnostics panel` at the bottom of the screen. 

As you move the cursor around between symbols, the panel would update automatically.  It feels like the data is already there, but showing in the bubble. It would be awesome to see it at the bottom without the need to trigger it.

**Comment by tomv564** [comment]
Triggering hover updates automatically is probably the easy part.

Creating a new panel to show hover content sounds useful (although it may fight with the diagnostics panel which has its own reasons for showing). The biggest issue is that the hover UI is HTML based, while the diagnostics panel is a regular text buffer (only supports syntax highlighting). Making text-based panel render something useful for all types of hover responses might be a challenge!

**Comment by rchl** [comment]
Panel is IMO not a good idea because it interferes with escape handling. As in, pressing escaping will close the panel first, before handling any other action like canceling autocomplete popup or removing selection. Diagnostics have same issue, that's why I find them very annoying.

If permanent panel like that is desired, it would probably be better to split the view into two rows. But that is tricky to handle.

**Comment by tomv564** [comment]
Yeah, that's an even better point for VIM or keyboard-oriented users. 

You could try setting up a `ViewEventListener` that sets up a timeout on `on_selection_modified` to run the `lsp_hover` command. You'll be using the sublime popups instead of a panel, but maybe it works for you?

**Comment by adamgajzlerowicz** [comment]
That sounds good - I will that a go. Thanks!
