### ISSUE TITLE
Don't move cursor at the end when populating the diagnostics panel

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#446]
When the diagnostics are populated the cursor in the panel is moved to the end. See [here](https://github.com/tomv564/LSP/blob/2869978d8b46d717da27eb0ac7a7e234840b218d/plugin/core/panels.py#L53-L56).

Is there a reason for this? 

Because I can't use the `f4` keybinding to goto the next result when it is opened.
Instead I need first to press the `shift + f4`, which is the backward direction.

Here is a simple solution.
```diff
     def run(self, edit, characters):
         self.view.replace(edit, sublime.Region(0, self.view.size()), characters)
 
-        # Move cursor to the end
+        # Clear the selection
         selection = self.view.sel()
         selection.clear()
-        selection.add(sublime.Region(self.view.size(), self.view.size()))
```

**Comment by tomv564** [comment]
Unsure, the change was never explained by @rmccue in https://github.com/tomv564/LSP/pull/91
Feel free to open a PR to remove it, maybe we'll find out why soon!
