### ISSUE TITLE
A universal diagnostics panel for LSP and SublimeLinter

### ISSUE THREAD

**Issue by philippotto** [tomv564/LSP#45]
Shortly before I found the LSP package, I developed another ST package which provides a diagnostics panel for SublimeLinter (see [SublimeLinter-Dashboard](https://github.com/philippotto/SublimeLinter-Dashboard); the PR for being managed by package control is still pending).

Obviously, the diagnostics panel of my package is very similar to the one provided by the LSP package. I'm not too sure about the exact differences. The LSP's highlighting/formatting looks better, however, it provides no keyboard shortcuts within the panel as far as I can see.

I think it would be nice to have one universal diagnostics view which is capable of showing errors and warnings originating from compilers/linters/language servers.
One approach for that would be to have a separate diagnostics panel package, which is responsible for rendering. Packages like SublimeLinter and ST-LSP could push errors/warnings (including click handlers and additional information) for each view to this package.

What do you think about this approach? Or do you think in the long run, linters should be implemented using the language server protocol?

I would be happy to work together for such an unified diagnostics panel.

**Comment by deathaxe** [comment]
The language-server-protocol intends to provide a standardized way to handle language depended stuff, such as completions/tooltips/schemes/linting/etc. The idea is to make proprietary solutions for each editor obsolete. All language packages existing for ST do nearly the same thing. They run some existing language tools and parse their output  to provide some useful information - but each with its own protocol or even communication technology. Now multiply it with the number of editors out their. A short look on some ST packages reveals most of them seem no longer maintained. The effort to create a solution for each editor is just too high.

If you ask me, the approach of a common language-server-protocol is the only useful way to handle all language depended stuff in an editor. Therefore LSP should be the place to provide such a standard diagnostics panel/tools. Functionality for each language should be provided by language-servers then. The only drawback of this solution is the requirement to sync the editor's content with the language server, who then calls all required tools. 

Not sure how long it will take to get an language server for each language, but this should be the goal and if available for most languages should make tools like SublimeLinter or Anaconda, ... which use none standard interface obsolete. 

Not sure about the whole designed feature set of the LSP, but it may also be used to trigger a compiler or debugger, whose information may need to be rendered somewhere.

**Comment by philippotto** [comment]
I agree that LSP is the most sensible approach in the long run. As a result, this means that the SublimeLinter will become obsolete. I'm not sure how much of its framework capabilities will be missed / needs to be reimplemented (probably not much).

Wrapping existing linters for LSP seems to be very doable (if they are too slow to be executed for each edit, they can only be run in response to a save-event).
However, it certainly requires that ST-LSP allows running multiple servers for the same file. Is that possible at the moment?

**Comment by rwols** [comment]
I took a look at your plugin and it seems very useful, but why not just make a PR for SublimeLinter and/or LSP?

**Comment by philippotto** [comment]
> I took a look at your plugin and it seems very useful, but why not just make a PR for SublimeLinter and/or LSP?

@rwols It's a separate package largely because I wanted to program it quickly and I didn't feel like going through the process of convincing the SL maintainers of that feature. The SL repository has 25 open PRs and the latest commit was in April. That would probably take a while.
Additionally, a separate package doesn't really have big disadvantages (apart from the fact that I had to monkeypatch SL at runtime to get updates, but that's only an issue for long-term maintenance and could be fixed by a small PR for SL).

**Comment by tomv564** [comment]
@philippotto great idea, I had a similar patch to use the LSP panel (broken now)
https://github.com/tomv564/SublimeLinter3/commit/5e053891ddef3b5f37dfbad16d87254117b68ef9

I think LSP and SublimeLinter's usage of a diagnostics panel line up pretty well, and the more building blocks (like **mdpopups**) we have, the more quality packages we'll get.

From an implementation point of view, the match is less ideal:
* A lot of code is shared with the References panel
* LSP's panel works like ST3's build results (navigate with F4/shift-F4), so users don't have to learn another UI.

Could we extract a shared "grouped file locations panel" that can be made to work like LSP's existing panels?

Linting (with code fixes!) over LSP is ideal, but it will take time for everyone to have language server support.
Multiple servers per file should be possible, but I'm happy avoiding that complexity for now :)

**Comment by deathaxe** [comment]
> LSP's panel works like ST3's build results (navigate with F4/shift-F4)

Must be added to the README / documentation.

> Multiple servers per file should be possible, but I'm happy avoiding that complexity for now :)

Linters are language specific stuff and should be part of the language servers. I like the approach of python-language-server, which has a plugin API itself to support several linters. With `pyls-mypy` there is only one package at the moment but maybe more will follow. I don't think it is meant for an editor to manage several servers, is it?

**Comment by philippotto** [comment]
> Linting (with code fixes!) over LSP is ideal, but it will take time for everyone to have language server support.
Multiple servers per file should be possible, but I'm happy avoiding that complexity for now :)

Yes, it will take some time. However, on a second thought, I think that we should try to push (i.e., facilitate) linters via LSP instead of investing energy into extracting a "grouped file locations" package. Building blocks are certainly very nice to have, but I can't think of many use cases (except for diagnostics which are doable via LSP).

For example, we could think about creating some boilerplate code, which could be easily used to have a very basic LSP-supporting linter. That boilerplate (or wrapper) would be able to speak the basic LSP protocol and the author of a lsp-linter would only need to fill in how the linter is invoked and how its results are parsed? This boilerplate wouldn't be part of this repository, but could help to drive linters away from SublimeLinter to LSP.
I think, this makes more sense in the long run.

**Comment by tomv564** [comment]
Closing this now as the discussion has veered away from a shared panel implementation (which was a nice offer, thanks!)
