### ISSUE TITLE
Add support for client config?

### ISSUE THREAD

**Issue by pearofducks** [tomv564/LSP#467]
It seems other language-server clients have support for a client config - e.g. [coc for neovim](https://github.com/neoclide/coc-vetur/blob/master/src/index.ts)

This would probably prove useful for several clients (other examples of client-options are available on other coc implementations - [here's Java](https://github.com/neoclide/coc-java/blob/master/src/index.ts#L40)).

However it will especially be useful for Vue, since the `vue-language-server` crashes repeatedly because of some problematic code on their behalf that assumes `config` exists and [has certain attributes](https://github.com/vuejs/vetur/blob/master/server/src/modes/vue/index.ts#L15).

I've reached out to the Vetur folk [here](https://github.com/vuejs/vetur/issues/977) asking for `config` to be populated with some sane defaults, or these problematic `config` queries to be safely accessed instead of assuming they exist.

**Comment by rwols** [comment]
Yup, client-config is definitely lacking. I'll have to investigate what the possibilities are though.

**Comment by rwols** [comment]
After reading into it a bit more it seems you're talking about the settings that come with the vue extension for VSCode? Like .sublime-settings?

**Comment by pearofducks** [comment]
I'm not intending to talk about any specific implementation. Looking at some of the _coc_ implementations I linked to it seemed like maybe there was a (standard?) way language-servers could accept a config.

If there's not a standard way this is done (e.g. 'send me an object on language-server boot with this shape'), this is ofc. pretty difficult to solve.

**Comment by predragnikolic** [comment]
Hello Dave, 

> e (e.g. 'send me an object on language-server boot with this shape')

Maybe you are looking for `initializationOptions`.
As an example the intelephense language server uses `initializationOptions` to provide the `storagePath` before the server is initialized.
```json
"intelephense-ls":
{
    "command": ["node", "/home/predrag/.npm-global/lib/node_modules/intelephense-server/lib/server.js", "--stdio"],
    "languageId": "php",
    "scopes": ["source.php"],
    "syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
    
    "initializationOptions":
    {
        "storagePath": "/tmp/intelephense"
    },
},

```

**Comment by pearofducks** [comment]
@predragnikolic - That's one of the use-cases (server config vs. client-config) I was thinking of, yes! Not sure how I missed that looking at the docs, but thanks! :D

**Comment by rwols** [comment]
Yes, initializationOptions seems to be the way to go for a language server. Closing this because we can't really do anything about the vscode-specific options from sublime.

**Comment by tomv564** [comment]
The other configuration mechanism (`workspace/didChangeConfiguration`) is also in use with vetur, you can add the entries in a dict named `settings` in your vetur language server config.  

You can see the options vetur accepts here:
https://github.com/vuejs/vetur/blob/24495504e25e6381c9ed750d92fede75e087dc09/server/src/services/vls.ts#L117-L131
