### ISSUE TITLE
clangd does not like special characters in paths

### ISSUE THREAD

**Issue by fanselm** [tomv564/LSP#468]
Thanks for a great plugin. I followed the instructions for setting up the clangd server and client and when opening a C++ file in Sublime it gave the following error message:
`server: Failed to find compilation database for /home/filipr/git/quantumsource-xtr/c%2B%2B/src/physics/blochwavecontainer.cpp`

I digged into the problem and found that the issue was the URL-encoded path, i.e. it works if I move the source code to a directory called `cpp` instead of `c++`. This is however not a viable solution for me (it's not my own code) so instead I removed the `pathname2url(path)` in `plugin/core/url.py`. This works for now in my case, but I guess it was there for a reason.

I don't know whether this is a bug in the LSP client or in the clangd server: either the path is sent in the wrong format or clangd can't deal with the correct format.

I use Sublime3 3.1.1, Python 3.5.2 and clangd-6.0 on Ubuntu 16.04

**Comment by rwols** [comment]
I tried duplicating your issue but it seems to handle paths like /Users/raoulwols/dev/c++/main.cpp fine here. What is the output of `clangd --version`?

**Comment by fanselm** [comment]
```
LLVM (http://llvm.org/):
  LLVM version 6.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
```

**Comment by rwols** [comment]
I have version 8 running here. So it seems there's an [URI class](https://github.com/llvm-mirror/clang-tools-extra/blob/master/clangd/URI.h) now that decodes the Uris. You could try fetching LLVM 7 via these apt repositories: https://apt.llvm.org, or you could even try installing the development versions from there.

**Comment by fanselm** [comment]
Hi again, sorry for the long wait. I now managed to get LLVM+clangd 7.0.0 installed and it does not have the problem, so I guess this closes this issue.
