### ISSUE TITLE
Language server settings are not reloaded after changing User/LSP.sublime-settings

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#477]
I had edited the `LSP.sublime-settings` setting `{'plugins': {'pydocstyle': {'enabled': False}` and run the command `LSP: Restart Servers`, but the log show that it send `{'plugins': {'pydocstyle': {'enabled': True}` to the language server.
```
12:01:38:652.962923 2.05e+02 - LSP.plugin.core.windows.end_session:415 - unloading session pyls
12:01:38:652.962923 6.65e+00 - LSP.plugin.core.rpc.send_request:94 -  --> shutdown
12:01:38:653.961897 7.55e-04 - LSP.plugin.core.rpc.response_handler:160 -      None
12:01:38:653.961897 2.00e-04 - LSP.plugin.core.rpc.send_notification:99 -  --> exit
12:01:38:701.467991 4.87e-02 - LSP.plugin.core.windows._handle_session_ended:509 - session pyls ended
12:01:38:701.467991 3.06e-04 - LSP.plugin.core.windows._handle_all_sessions_ended:493 - clients for window 3 unloaded
12:01:38:701.968908 2.25e-04 - LSP.plugin.core.windows._handle_all_sessions_ended:495 - window 3 sessions unloaded - restarting
12:01:38:706.995964 5.30e-03 - LSP.plugin.core.windows.start_active_views:333 - window 3 starting 1 initial views
12:01:38:712.976933 5.53e-03 - LSP.plugin.core.windows._initialize_on_open:351 - window 3 requests pyls for D:\User\Dropbox\SoftwareVersioning\Forks\python-language-server\pyls\python_ls.py
12:01:38:713.469982 8.19e-04 - LSP.plugin.core.windows._start_client:368 - starting in D:\User\Dropbox\SoftwareVersioning\Forks\python-language-server
12:01:38:713.969946 1.93e-04 - LSP.plugin.core.windows._start_client:371 - project_path: D:\User\Dropbox\SoftwareVersioning\Forks\python-language-server
12:01:38:713.969946 1.67e-04 - LSP.plugin.core.windows._start_client:372 - config: ClientConfig tcp_port: None, init_options: {}, enabled: True, env: {'PYTHONPATH': ['${sublime_libs}', '${sublime_path}', '${packages}', '${project_path}']}, languages: [LanguageConfig scopes: ['source.python'], syntaxes: ['Packages/Python/Python.sublime-syntax'], id: 'python';], settings: {'pyls': {'plugins': {'pydocstyle': {'enabled': True}, 'rope': {'ropeFolder': None}, 'pycodestyle': {'enabled': False}}}}, binary_args: ['F:\\Python\\Scripts\\pyls.exe', '-vvv', '--log-file', 'F:/SublimeText/debug2.txt'], name: pyls, tcp_host: None;
12:01:38:716.000080 2.16e+02 - LSP.plugin.core.process.start_server:45 - starting ['F:\\Python\\Scripts\\pyls.exe', '-vvv', '--log-file', 'F:/SublimeText/debug2.txt']
12:01:38:718.971014 6.52e-02 - LSP.plugin.core.rpc.send_request:94 -  --> initialize
12:01:38:719.470978 5.53e-03 - LSP.plugin.core.windows._start_client:388 - window 3 added session pyls
```

**Comment by tomv564** [comment]
Any evidence of changed settings being detected and propagating to each window? Do the enable/disable server commands do something special?

**Comment by kerma** [comment]
It may be related to the fact that the settings file is looked up from the wrong place. I'm seeing this in the console:

`Unable to open /Users/margus/Library/Application Support/Sublime Text 3/Packages/LSP/LSP.sublime-settings`

There is no such folder. LSP installed via Package Control, the package itself lives in `/Users/margus/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package`. 

After this user settings are dropped: I lose my added client. Path for user settings is `/Users/margus/Library/Application Support/Sublime Text 3/Packages/User/LSP.sublime-settings`.

**Comment by tomv564** [comment]
I think the "Unable to open" error is expected and _should_ be safe to ignore - apparently Sublime Text reads that path first and should fall back to the sublime-package:

https://forum.sublimetext.com/t/unable-to-open-default-preferences/38674/4

But user settings not being taken into account sounds like a serious (but different) issue, what does your user settings file look like?

**Comment by kerma** [comment]
I think I had the same `"enabled": true` issue. I didn't have this in my settings file. Or it was some other plugin (gometalinter) causing issues. 

Currently my settings looks like:

```
{
	"clients":
	{
		"golsp":
		{
			"command":
			[
				"/Users/margus/src/go/bin/bingo"
			],
			"enabled": true,
			"env":
			{
				"GOPATH": "/Users/margus/src/go"
			},
			"languageId": "go",
			"scopes":
			[
				"source.go"
			],
			"syntaxes":
			[
				"Packages/Go/Go.sublime-syntax"
			]
		}
	},
	"log_debug": true,
	"log_payloads": true,
	"log_stderr": true,
	"only_show_lsp_completions": true
}
```

**Comment by tomv564** [comment]
This should be fixed now!

**Comment by AmjadHD** [comment]
@tomv564 why restart servers, wouldn't it be better to send a `workspace/didChangeConfiguration` when settings change ?

**Comment by tomv564** [comment]
@AmjadHD because I didn't find a way to monitor when project settings change - so the behaviour would be half-complete.

**Comment by rwols** [comment]
I'm pretty sure we can subscribe to view setting change events, but then we would have to keep all settings in all views. See sublime.Settings.add_on_change method.
