### ISSUE TITLE
Laravel Eloquent @property don't show up in suggestion

### ISSUE THREAD

**Issue by Prezi2907** [tomv564/LSP#479]
I use Intelephense long time, right now I have some big problem.

When I write the model in laravel and set @property:

```
/**
 * New model for test
 * 
 * @property mixed $test
 * @var mixed $test2
 * @method viod testMethod
 * 
 */
class NewModel extends Model
```
and when I'm doing:
```
$newModel = NewModel::first();
$newModel->[here no sugesstion for any of DockBlock position]
```

A few days ago it was working correctly, now I have problems.
Php: 5.3.68 and 7.1.24 (7.1.24 was set to check Intellisense)
VS Code: 1.30
Os: Ubuntu LTS 16.04
All other extensions all off right now.

Help wanted :)

**Comment by predragnikolic** [comment]
Are you sure you are in the right repository? :-)
I noticed you mention VS Code, but this is the repository of LSP for Sublime Text

**Comment by Prezi2907** [comment]
Never mind... :P
