### ISSUE TITLE
LSP should't clear the diagnostics  

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#483]
I think I found a little deviation from the LSP specification for diagnostics.
Currently LSP clears diagnostics for a given view, when the view closes, correct me if I am wrong. 
```
//  calls to remove diagnostics when the view closes
 plugin/core/windows.py:
	     457:14   self._diagnostics.remove(view, session.config.name)
	     493:22   self._diagnostics.remove(view, config_name)
```
I have read the [LSP spec for diagnostics](https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics) and it turns out that it is not the client responsibility to clear the diagnostics. :)

**Comment by tomv564** [comment]
Nice, good to see the spec clarify who owns diagnostics.
Should we add a setting for it, or just remove the diagnostics removal?
We could provide a "Clear Diagnostics" command so the user can clean up leftover diagnostics in a window.

**Comment by predragnikolic** [comment]
Removal of the diagnostics removal and a Clear Diagnostics command sounds ok to me.
