### ISSUE TITLE
Visual indication if code actions exist

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#485]
VS code uses a bulb to indicate if code actions exist.

![2018-12-15-200218_683x384_scrot](https://user-images.githubusercontent.com/22029477/50046500-b0103700-00a4-11e9-8930-d01a52939c01.png)
 
Currently LSP doesn't show any visual indication that code action exist.
But here is what I come up with:

![output](https://user-images.githubusercontent.com/22029477/50046524-139a6480-00a5-11e9-905e-3fe891107db0.gif)

What do you think about that?

**Comment by tomv564** [comment]
Are you proposing that we look up code actions when the cursor has rested - similar to document highlights? I like that way of introducing action lookups!

Can we have something a more visible gutter icon? Or maybe an unobtrusive popup could behave like the lightbulb?

**Comment by predragnikolic** [comment]
> Are you proposing that we look up code actions when the cursor has rested - similar to document highlights? 

Yes, I am proposing that. :)

> More visible gutter icon?

Something like this? (example, just to showcase)
![screenshot from 2018-12-24 12-13-04](https://user-images.githubusercontent.com/22029477/50398172-cf2e5900-0775-11e9-96f6-be7fc5f74fc9.png)

I wouldn't go with a popup, placing the bulb in the gutter seems like the most unobtrusive way to tell that there are diagnostics. 

As soon as I polish some things, I will do a PR.
