### ISSUE TITLE
Error mdpopups: Failed to convert/retrieve scheme to CSS!

### ISSUE THREAD

**Issue by OdinTech3** [tomv564/LSP#487]
I keep on getting this error message:
```
mdpopups: Failed to convert/retrieve scheme to CSS!
```
logged to the console whenever I hover over a symbol on my code base. It occurs irrespective of the language server I am using. I have seen it logged while using the `pyls` and `rlang` language server

I am using: 
* MacOS 10.13.6
* Sublime Text Build 3184 (Dev Channel)
* LSP v0.7.3 installed using Package Control

Has this behaviour been observed by others?

**Comment by rwols** [comment]
What version of mdpopups do you have? You can check what version you have by running the following in your sublime console:
```
import mdpopups; mdpopups.version()
```
(my version seems to be 3.3.3)
If your version is very out-of-date, you can try running the command
```
Package Control: Satisfy Dependencies
```
from the command palette. I am not sure if this will fix your problem though.

**Comment by OdinTech3** [comment]
This is the version I have
```
>>> import mdpopups; mdpopups.version()
(3, 3, 4)
```

**Comment by tomv564** [comment]
Nice hints so far. Other than running a slightly newer OS-X version my Sublime and MdPopups are the same.

The error you receive is from mdpopups failing to configure the color scheme it applies in popups, see implementation here:
https://github.com/facelessuser/sublime-markdown-popups/blob/abaeba680328e1c79def249f187ca40dca949533/st3/mdpopups/__init__.py#L178

I tried changing `mdpopups.use_sublime_highlighter` in the Sublime User preferences to `false` and back to `true`, but I do not experience the same issue.

But I see from the code that if you also change `mdpopups.debug` to `true`, the error traceback will be logged in the console - that should be very helpful.

Restarting Sublime may be needed when you change these mdpopups settings.

**Comment by OdinTech3** [comment]
Okay so I turned on `mdpopups.debug` to the highest number 3
```
{
...
    // Controls which information are dumped out to the console.
    // This is more useful for plugin developers. It works by specifying an error level.
    // "0" don't print any message
    // "1" print errors
    // "2" print errors, warnings
    // "3" print errors, warnings, debug infos
    "mdpopups.debug": 3,
...
}
```

So when I tried to hover over a symbol I obtain this

```
mdpopups: Failed to convert/retrieve scheme to CSS!
mdpopups: Traceback (most recent call last):
  File "/Users/nickmuoh/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 183, in _get_scheme
    default_css = _get_default_css()
  File "/Users/nickmuoh/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 194, in _get_default_css
    return clean_css(sublime.load_resource(DEFAULT_CSS))
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found

mdpopups: =====CSS=====
mdpopups: 

    .lsp_popup {
        margin: 0.5rem 0.5rem 0 0.5rem;
    }
    .lsp_popup .highlight {
        border-width: 0;
        border-radius: 0;
    }
    .lsp_popup p {
        margin-bottom: 0.5rem;
        padding: 0 0.5rem;
        font-family: system;
    }
    .lsp_popup li {
        font-family: system;
    }
    .lsp_popup .errors {
        border-width: 0;
        background-color: color(var(--redish) alpha(0.25));
        color: var(--whitish);
        margin-bottom: 0.5rem;
        padding: 0.5rem;
    }
    .lsp_popup .warnings {
        border-width: 0;
        background-color: color(var(--yellowish) alpha(0.25));
        color: var(--whitish);
        margin-bottom: 0.5rem;
        padding: 0.5rem;
    }
    .lsp_popup .info {
        border-width: 0;
        background-color: color(var(--bluish) alpha(0.25));
        color: var(--whitish);
        margin-bottom: 0.5rem;
        padding: 0.5rem;
    }
    .lsp_popup .hints {
        border-width: 0;
        background-color: color(var(--bluish) alpha(0.25));
        color: var(--whitish);
        margin-bottom: 0.5rem;
        padding: 0.5rem;
    }


mdpopups: =====HTML OUTPUT=====
mdpopups: 
<p>No description available.</p><p><a href='definition'>Definition</a> | <a href='references'>References</a> | <a href='rename'>Rename</a></p>
```

**Comment by OdinTech3** [comment]
Okay I found that changing the `DEFAULT_CSS` path from 'Packages/mdpopups/css/default.css' to 'Packages/mdpopups/default.css' and the subsequently making a copy of the default.css file to the root of the mdpopups directory fixed the problem.

Do you guys think that `sublime.load_resource` method that was used to get the css file can not load nested directories?

**Comment by tomv564** [comment]
Great troubleshooting, definitely sounds like an issue with the mdpopups package itself. Can you follow up at https://github.com/facelessuser/sublime-markdown-popups/issues ?
