### ISSUE TITLE
Change the hint region display?

### ISSUE THREAD

**Issue by predragnikolic** [tomv564/LSP#496]
Currently hints looks like this: green squiggly line covering the whole word 
![2019-01-14-205347_653x354_scrot](https://user-images.githubusercontent.com/22029477/51137334-de696980-183e-11e9-8715-eac5a0e059ad.png)

But what do you think of this? 
![2019-01-14-205101_653x354_scrot](https://user-images.githubusercontent.com/22029477/51137494-fb9e3800-183e-11e9-985a-c746a25b4b2a.png)

4 white dots covering just the first letter, it look similar to vs code.
![2019-01-14-205436_653x354_scrot](https://user-images.githubusercontent.com/22029477/51137602-356f3e80-183f-11e9-8654-64fe4fb43f44.png)

**Comment by tomv564** [comment]
What about changing your settings to use the thin dots for all diagnostics?

I see the improvement, just not sure if it's worth adding more code for.

**Comment by predragnikolic** [comment]
> What about changing your settings to use the thin dots for all diagnostics?

No, I like the errors and warnings to be red and yellow squiggly lines. 

The point of this was just to make it consistent with other tools. https://code.visualstudio.com/updates/v1_22#_hints-in-the-editor 

> I see the improvement, just not sure if it's worth adding more code for.

This is just a UI suggestion, nothing that important. :)
I think that hints with dot representation looks cleaner and consistent with other tools, that's it.

Because this is not that important, I will close this for now. 
But if someone else would like it, leave a comment.
