### ISSUE TITLE
CCLS support / "complete_using_text_edit"

### ISSUE THREAD

**Issue by TheAifam5** [tomv564/LSP#498]
https://github.com/MaskRay/ccls/issues/226

## Currently
```c
client->a
```

I get autocompletion like this: `a : int tcp_client_s`
After selecting that autocompletion the code looks like this:
```c
client->a : int
```

#### OS and language server:
ArchLinux with ccls for C/C++/ObjC (git version installed a5f600a7)
https://github.com/MaskRay/ccls

#### How you installed LSP:
Package Control

#### Client configuration:
```
"ccls":
{
  "command":
  [
    "ccls"
  ],
  "initializationOptions":
  {
    "cacheDirectory": "/tmp/ccls"
  },
  "languages":
  [
    {
      "languageId": "c",
      "scopes":
      [
        "source.c"
      ],
      "syntaxes":
      [
        "Packages/C++/C.sublime-syntax"
      ]
    },
    {
      "languageId": "cpp",
      "scopes":
      [
        "source.c++"
      ],
      "syntaxes":
      [
        "Packages/C++/C++.sublime-syntax"
      ]
    },
    {
      "languageId": "objective-c",
      "scopes":
      [
        "source.objc"
      ],
      "syntaxes":
      [
        "Packages/Objective-C/Objective-C.sublime-syntax"
      ]
    },
    {
      "languageId": "objective-cpp",
      "scopes":
      [
        "source.objc++"
      ],
      "syntaxes":
      [
        "Packages/Objective-C/Objective-C++.sublime-syntax"
      ]
    }
  ]
}
```

**Comment by rwols** [comment]
So I tried the ccls server mentioned, and I get the same kind of completions. The ccls server sends `textEdit` in addition to a `label` for its completion items.

There is an easy fix for your problem. There's a "hidden" setting called `complete_using_text_edit` that will enable the functionality to prefer `textEdit` over `label`. Just put
```
	"complete_using_text_edit": true,
```
somewhere in your LSP preferences.


Some background reading: https://github.com/tomv564/LSP/issues/368 https://github.com/tomv564/LSP/issues/294

**Comment by TheAifam5** [comment]
Definition, References, Rename functions does not work with CCLS.

**Comment by rwols** [comment]
> Definition, References, Rename functions does not work with CCLS.

It does for me. Are you working with cmake? If so, you need to put a generated `compile_commands.json` file with `cmake path/to/src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` in the root of your source dir (something like `ln -s compile_commands.json path/to/build/dir/compile_commands.json`)

**Comment by TheAifam5** [comment]
No. I’m working with meson and I softlinked the compile_commands.json to the root project too.

**Comment by TheAifam5** [comment]
Oh, I needed to add the file to meson, build it (to generate new compile_commands.json) and then restart Sublime to get that working again.

**Comment by tomv564** [comment]
Ah right, so it sends label but no insertText. We should probably change `complete_using_text_edit` to be the default behaviour, ideally after adding some test coverage

**Comment by rwols** [comment]
Yeah. In fact, I think `insertText` is deprecated.

**Comment by CoolOppo** [comment]
> Ah right, so it sends label but no insertText. We should probably change `complete_using_text_edit` to be the default behaviour, ideally after adding some test coverage

Has this happened yet? I just spent like a half hour trying to get ccls to work just to figure out that `complete_using_text_edit` breaks the LSP plugin now.

**Comment by rwols** [comment]
In what way does it break this plugin?

**Comment by rwols** [comment]
@CoolOppo PR #524 makes the plugin prefer textEdit over insertText by default.

**Comment by CoolOppo** [comment]
Awesome, didn't see that. I deeply appreciate the hard work on this project, it literally is making my job (and life) so much better.
