### ISSUE TITLE
Does MS Python Language Server not support format document?

### ISSUE THREAD

**Issue by hujianxin** [tomv564/LSP#502]
HI, thanks for this excellent extension.

I met a issue when configuring Microsoft pyls for sublime, the `format document` item is grey and I can not click it.

Is it a issue of LSP or mspyls?

Thanks.

**Comment by tomv564** [comment]
I searched their repo for you, looks like formatting is not yet implemented:
https://github.com/Microsoft/python-language-server/issues?utf8=✓&q=is%3Aissue+formatting+

The greyed out UI is a sign that LSP has functionality not supported by a server.

A "server info" command would perhaps be helpful for these cases!

**Comment by hujianxin** [comment]
@tomv564 thanks very much

**Comment by predragnikolic** [comment]
Probably the Microsoft python language server don't support the "documentFormattingProvider" capability. 

If the server supports that capability, the LSP plugin enables that menu option.
If not, that it is disabled.

**Comment by predragnikolic** [comment]
I am late :-D

**Comment by hujianxin** [comment]
@predragnikolic thanks for your patient explanation
