### ISSUE TITLE
[Question] Where local settings are saved?

### ISSUE THREAD

**Issue by kud** [tomv564/LSP#503]
Hey,

I'd like to know where are saved the fact you enable or disable a client for local project?

**Comment by tomv564** [comment]
It should be visible under the settings key if you choose `Edit Project` from the Project menu:
<img width="405" alt="screenshot 2019-01-30 at 21 38 08" src="https://user-images.githubusercontent.com/4395832/52011160-88035880-24d7-11e9-9020-c217d8a4ad5b.png">

**Comment by kud** [comment]
Ooooooooooooooooh okay. It's because I never use "Project". So I've got nothing. Thanks @tomv564
