### ISSUE TITLE
New style of Autocomplete ? 

### ISSUE THREAD

**Issue by gj1118** [tomv564/LSP#506]
Hi I am on MacOS Mojave and on latest sublime dev build (3189). I have LSP installed using it with JS projects. 

Since the very latest sublime build, I have started getting this kind of autocomplete :

![image](https://user-images.githubusercontent.com/473101/52168568-b2ccf700-26f9-11e9-8188-994866c8cfde.png)

 
but previously I used to get this kind of autocomplete

![image](https://user-images.githubusercontent.com/473101/52168571-bceef580-26f9-11e9-9280-b5fb5d3ccd6e.png)

 
**How do I disable the first in order to get the second ?** 

Note : When I press the backspace button , the original popup (from the second screenshot) appears

![image](https://user-images.githubusercontent.com/473101/52168579-c6785d80-26f9-11e9-81f7-c1b17621a610.png)

Following is how I have configured LSP 

```
{
	"auto_show_diagnostics_panel": false,
	"clients":
	{
		"eslint":
		{
			"enabled": false
		},
		"javascript-typescript-langserver":
		{
			"enabled": true
		},
		"lsp-tsserver":
		{
			"enabled": true
		},
		"pyls":
		{
			"enabled": true
		},
		"typescript-language-server":
		{
			"enabled": true
		}
	},
	"flow":
	{
		"command":
		[
			"flow-language-server",
			"--stdio"
		],
		"languageId": "javascript",
		"scopes":
		[
			"source.js"
		],
		"syntaxes":
		[
			"Packages/Babel/JavaScript (Babel).sublime-syntax",
			"Packages/JavaScript/JavaScript.sublime-syntax"
		]
	}
}

```
I installed LSP from Package Control.

**Comment by tomv564** [comment]
Looks like LSP is fighting with another package over the view's popups when showing signature help (autocomplete is a dropdown list of options). 

I've seen those non-LSP popups before too, do you have a TernJS or Typescript package installed/enabled?

**Comment by gj1118** [comment]
Thank you for looking into this over the weekend . Much appreciated Sir. Here is the list of packages that I have 

![image](https://user-images.githubusercontent.com/473101/52179893-d2255c00-27ad-11e9-9b3d-204930392559.png)

I do have the typescript package installed.But I had it installed a while ago and LSP was working after that as well. It was only since Friday since it started behaving that way.

**Comment by rwols** [comment]
Try disabling the language server of the typescript package.

**Comment by gj1118** [comment]
I have disabled the Typescript package and it is indeed working. I am using the `javascript-typescript-langserver` language server.  Between the three, can you please let me know which one is the better one going around ? Thanks.
