### ISSUE TITLE
Vue-language-server does not work for me

### ISSUE THREAD

**Issue by ouweiya** [tomv564/LSP#507]
#### My configuration:
**sublime version: build 3176**

```json
{
	"clients": {
		"js": {
			"command": ["lsp-tsserver"],
			"enabled": true,
			"languageId": "javascript",
			"scopes": ["source.js"],
			"syntaxes": ["Packages/JavaScript/JavaScript.sublime-syntax"]
		},
		"lsp-tsserver": {
			"enabled": true
		},
		"vue-ls": {
			"command": ["node", "D:\\Mymodule\\node_modules\\.bin\\vls"],
			"enabled": true,
			"languageId": "vue",
			"scopes": ["text.html.vue"],
			"syntaxes": ["Packages/Vue Syntax Highlight/Vue Component.sublime-syntax"]
		}
	},
	"log_debug": true
}
```

#### Log message:
```json
LSP: global configs ['polymer-ide=False', 'js=True', 'eslint=False', 'golsp=False', 'vue-ls=True', 'clangd=False', 'reason=False', 'haskell-ide-engine=False', 'typescript-language-server=False', 'rls=False', 'lsp-tsserver=True', 'jdtls=False', 'cquery=False', 'javascript-typescript-langserver=False', 'pyls=False', 'ocaml=False', 'phpls=False']
LSP: window 2 starting 1 initial views
LSP: window 2 requests lsp-tsserver for C:\Users\H\Desktop\vue-app2\src\main.js
LSP: starting in D:\Cli
LSP: starting ['lsp-tsserver.cmd']
LSP:  --> initialize
LSP: window 2 added session lsp-tsserver
LSP:  --> initialized
LSP:  --> textDocument/didOpen
LSP: <--  textDocument/publishDiagnostics
Unable to open /D/SublimeText3/Data/Packages/LSP/LSP.sublime-settings
```

#### Lsp-tsserver works fine
![snipaste_2019-02-06_01-38-13](https://user-images.githubusercontent.com/28357731/52292539-e3d65180-29af-11e9-9330-08e9cbb864a4.png)

**Comment by predragnikolic** [comment]
Ok, I don't see anything wrong :)

You are in a js file. 
The vue server will start in .vue files. (To be exact in views that have this syntax `Packages/Vue Syntax Highlight/Vue Component.sublime-syntax` assigned). 
You can verify that by opening a vue file and typing `view.settings().get('syntax')` in the sublimes console.

You can further verify that the vue server works by opening a vue file and putting the caret after a tag and trigger auto-completion.
![2019-02-05-194417_653x354_scrot](https://user-images.githubusercontent.com/22029477/52296733-61ce3480-297f-11e9-933b-56138a73b7dd.png)

**Comment by ouweiya** [comment]
> Ok, I don't see anything wrong :)
> 
> The vue server will start in .vue files. (To be exact in views that have this syntax `Packages/Vue Syntax Highlight/Vue Component.sublime-syntax` assigned).
> You can verify that by opening a vue file and typing `view.settings().get('syntax')` in the sublimes console.
> 
> You can further verify that the vue server works by opening a vue file and putting the caret after a tag and trigger auto-completion.
> ![2019-02-05-194417_653x354_scrot](https://user-images.githubusercontent.com/22029477/52296733-61ce3480-297f-11e9-933b-56138a73b7dd.png)
> 
> Maybe, the command argument for starting vue is wrong `"command": ["node", "D:\\Mymodule\\node_modules\\.bin\\vls"],`
> 
> If you have `vls` globally installed try setting it to `"command": ["vls"],`

#### Thanks for the API you provided, I checked out the current grammar range problem, there is an old plugin that modifies my syntax range, I disabled it and the problem was solved.
```
>>> view.settings().get('syntax')
'Packages/Vue Syntax Highlight/vue.tmLanguage'
```

#### Can you tell me how to set a check error only when saving a file?
![snipaste_2019-02-06_10-49-26](https://user-images.githubusercontent.com/28357731/52317883-e743fa00-29fc-11e9-90f2-ad9bf32eb269.png)

**Comment by ouweiya** [comment]
> Ok, I don't see anything wrong :)
> 
> The vue server will start in .vue files. (To be exact in views that have this syntax `Packages/Vue Syntax Highlight/Vue Component.sublime-syntax` assigned).
> You can verify that by opening a vue file and typing `view.settings().get('syntax')` in the sublimes console.
> 
> You can further verify that the vue server works by opening a vue file and putting the caret after a tag and trigger auto-completion.
> ![2019-02-05-194417_653x354_scrot](https://user-images.githubusercontent.com/22029477/52296733-61ce3480-297f-11e9-933b-56138a73b7dd.png)
> 
> Maybe, the command argument for starting vue is wrong `"command": ["node", "D:\\Mymodule\\node_modules\\.bin\\vls"],`
> 
> If you have `vls` globally installed try setting it to `"command": ["vls"],`

**Comment by predragnikolic** [comment]
Glad it works!

> Can you tell me how to set a check error only when saving a file?

Currently there is no option for that. 
There is an issue for it #381. It is up to people to build it :)  

> Why is your sublime ui the same as chrome?

I like rounded tabs :)
A better question is, why is your sublime ui the same as atom? :D

**Comment by ouweiya** [comment]
> Glad it works!
> 
> > Can you tell me how to set a check error only when saving a file?
> 
> Currently there is no option for that.
> There is an issue for it #381. It is up to people to build it :)
> 
> > Why is your sublime ui the same as chrome?
> 
> I like rounded tabs :)
> A better question is, why is your sublime ui the same as atom? :D

#### I used a theme package, it is the package I found closest to atom.
[https://github.com/andresmichel/one-dark-theme](https://github.com/andresmichel/one-dark-theme)

#### What theme do you use?

**Comment by predragnikolic** [comment]
You can find it here, https://github.com/predragnikolic/Sone
Don't mind the old image in the readme, it is a bit outdated. 

if your Vue issue is gone, feel free to close this issue :)

**Comment by LiteKat** [comment]
> Ok, I don't see anything wrong :)
> 
> The vue server will start in .vue files. (To be exact in views that have this syntax `Packages/Vue Syntax Highlight/Vue Component.sublime-syntax` assigned).
> You can verify that by opening a vue file and typing `view.settings().get('syntax')` in the sublimes console.
> 
> You can further verify that the vue server works by opening a vue file and putting the caret after a tag and trigger auto-completion.
> ![2019-02-05-194417_653x354_scrot](https://user-images.githubusercontent.com/22029477/52296733-61ce3480-297f-11e9-933b-56138a73b7dd.png)
> 
> Maybe, the command argument for starting vue is wrong `"command": ["node", "D:\\Mymodule\\node_modules\\.bin\\vls"],`
> 
> If you have `vls` globally installed try setting it to `"command": ["vls"],`

OMG 2 days and the server didn't work just because i was pointing to the SAME syntax file butn in another directory. That should be optional D:

**Comment by predragnikolic** [comment]
LSP-vls coming... soon 
https://github.com/wbond/package_control_channel/pull/7566
