### ISSUE TITLE
mypy issue

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#509]
I really don't know whether this issue belongs to this issue tracker or not, so you'll have to execuse me
![screenshot_1](https://user-images.githubusercontent.com/33235928/52371900-01122b00-2a57-11e9-879d-8b46e381a9ec.png)
I have a test project, in the folder I have a python file (typed_mod.py) containing a simple function (f()) defined as
```python
def f(a):
    return a
```
a stub file (typed_mod.pyi) that annotates the f function as:
```python
def f(a: int) -> int: ...
```
I was expecting that the function signature will be inspected from the stub file, and an error will be issued when using `f()` with a string parameter, but it doesn't, and completion is provided for `b` as a string, on the other hand when working with a module with type annotations "inline", I get correct results

![screenshot_2](https://user-images.githubusercontent.com/33235928/52373574-4fc1c400-2a5b-11e9-9a07-bf79e012b5c6.png)

I don't know whether this has to do with LSP, pyls or mypy.

**Comment by rwols** [comment]
My guess: the python-language-server should be configured so that it can find the .pyi file. I doubt this has anything to do with this plugin. Though feel free to ask around in the gitter chat.

**Comment by AmjadHD** [comment]
> the python-language-server should be configured so that it can find the .pyi file

I do have a mypy.ini file in my folder.

**Comment by tomv564** [comment]
Also, consider testing with mypy from the command line (what pyls-mypy does is similar) and searching the issues from the mypy repository!

**Comment by AmjadHD** [comment]
> and searching the issues from the mypy repository!

Thanks, I found it [here](https://github.com/python/mypy/issues/5520)

**Comment by tomv564** [comment]
You could compare your project with this LSP project, as we also keep the stubs in a subfolder, as configured in the mypy.ini here: https://github.com/tomv564/LSP/blob/ecd9f0f6e274341493b34389442fe55a0b628316/mypy.ini#L5

**Comment by AmjadHD** [comment]
@tomv564, don't you face this problem ?

**Comment by tomv564** [comment]
Did you run mypy from the command line and observe the same issue? 

I only use stubs for code that mypy can’t reach (the sublime API is not importable by mypy as mypy doesn’t run in the sublime python environment). don’t see the point of maintaining
