### ISSUE TITLE
Quick switch project should restart language server

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#51]
It currently re-uses the existing client for a given language, as the window hasn't changed.

**Comment by tomv564** [comment]
After watching the logs with `sublime.log_commands(True)`, I am not sure how this event can be observed directly.

**Comment by rmccue** [comment]
Related question on the forum: https://forum.sublimetext.com/t/is-there-an-on-project-load-event/29660/2

**Comment by tomv564** [comment]
Thanks for the tips, #95 should solve this.
