### ISSUE TITLE
Let the client manage the socket life cycle

### ISSUE THREAD

**Issue by kenkangxgwe** [tomv564/LSP#513]
I have been looking for issues related to `socket`, `tcp server` and `port`, but I still haven't found a way to make sublime client open a socket port and let the language server to connect to it. 

This is encouraged by current [specification](https://microsoft.github.io/language-server-protocol/specification).

> Server lifetime
> The current protocol specification defines that **the lifetime of a server is managed by the client** (e.g. a tool like VS Code or Emacs). It is up to the client to decide when to start (process-wise) and when to shutdown a server.

It will be really helpful if sublime can auto-detect the available port and setup a socket server for language server to connect, see https://github.com/Microsoft/vscode-languageserver-node/issues/245#issuecomment-336054699.

**Comment by tomv564** [comment]
The current support assumes the language server listens and the client connects.

This implementation was common in many language servers (python language server, php language server) - you should have found issues or PRs confirming this functionality existed.

> To avoid any timing or port issues the pipe and the sockets are owned by the client processes

That explains the ugliness with timeouts and retries in our `start_tcp_transport` function, so I agree with that reasoning. Feel free to investigate the needed changes, if it won't hurt the codebase or break existing tcp server functionality then it would be great to have!

(by the way, current tcp-based server configuration uses hardcoded port numbers, which means if you open two windows that want pyls sessions at port 4000, the second session will fail. Random port selection would be nice, but that's an argument you'd have to provide to each server :/)

**Comment by tomv564** [comment]
Should be working now (see latest documentation or PR #751)!

Tested it with `lsp-tsserver --socket={port}` (you'll need latest master for lsp-tsserver to get the --socket support), would love to hear of other servers that work (or don't work!)
