### ISSUE TITLE
support "workspace/didChangeWatchedFiles"

### ISSUE THREAD

**Issue by ayoub-benali** [tomv564/LSP#516]
At least Metals LSP server would need such a feature, see https://github.com/scalameta/metals/issues/533

Any idea on how such a feature would be implemented given the sublime API ?

**Comment by rwols** [comment]
This is impossible with the current ST3 api.

**Comment by olafurpg** [comment]
FWIW, Metals has its own file watcher for critical functionality but due to API limitations we delegate `workspace/didChangeWatchedFiles` notifications to the editor client for nice-to-have but non-essential features like detecting build changes by background processes.

**Comment by tomv564** [comment]
Might be practical to write a small Sublime package that hooks `workspace/didChangeWatchedFiles` from LSP and uses [watchman](https://github.com/facebook/watchman) to service that API. 

The LanguageHandler API is a bit too specific, this package could do it for _any_ language, so we could expose a new API for hooking in these kind of services.
