### ISSUE TITLE
debug('global configs'...) is called twice on LSP start up

### ISSUE THREAD

**Issue by evandrocoan** [tomv564/LSP#525]
Given the following sequence of function calls:
https://github.com/tomv564/LSP/blob/cbf13fbe143f706dd406f9ea0b15eec0571a1312/plugin/core/main.py#L19-L22

https://github.com/tomv564/LSP/blob/cbf13fbe143f706dd406f9ea0b15eec0571a1312/plugin/core/registry.py#L42-L45

Leads to `debug('global configs'...)` being called twice when the LSP starts up:
https://github.com/tomv564/LSP/blob/cbf13fbe143f706dd406f9ea0b15eec0571a1312/plugin/core/settings.py#L106

After checking the code, `load_handlers()` does not require for the settings to be loaded before it is called. Then, we can replace `client_configs.update_configs()` call on `load_handlers()` by `load_settings()` and remove `load_settings()` from `startup()`. Hence, `debug('global configs'...)` should be only called once at the LSP start up.

**Comment by tomv564** [comment]
I understand it feels suboptimal but for now this is a symptom of the language handlers being a layer on top of the existing LSP functionality. I do not believe your introduction of a boolean check to avoid a tiny bit of extra work is worth the noise in the code.
