### ISSUE TITLE
bug in auto completion when edit behind the completion position

### ISSUE THREAD

**Issue by ayoub-benali** [tomv564/LSP#536]
When autocomplete has to edit before the completion position the trimming introduced in https://github.com/tomv564/LSP/pull/295 leads to a bug, see [line](https://github.com/tomv564/LSP/blob/master/plugin/completion.py#L296) 

You can see an example bellow using Scala with [Metals](https://scalameta.org/metals/):
![broken-autocomplete](https://user-images.githubusercontent.com/1632384/54742160-dde3ab00-4bc0-11e9-9f73-a9078ddecec7.gif)

Here is the `CompletionItem` sent back by the server:
```
{
	'insertTextFormat': 2,
	'data': {
		'symbol': 'example/Foo#myFunction().',
		'target': 'file:/home/ayoub/workspace/testproject/?id=root'
	},
	'detail': 'override def myFunction(): Unit',
	'sortText': '00000',
	'filterText': 'override def myFunction',
	'preselect': True,
	'label': 'override def myFunction(): Unit',
	'kind': 2,
	'additionalTextEdits': [],
	'textEdit': {
		'newText': 'override def myFunction(): Unit = ${0:???}',
		'range': {
			'start': {
				'line': 7,
				'character': 2
			},
			'end': {
				'line': 7,
				'character': 18
			}
		}
	}
}
```

### Expected behavior
Before:
```scala
def myF<ctrl+space>
```
After:
```scala
override def myFunction(): Unit = ???
```

Please note the bug doesn't happen when the prefix is fully specified:
![broken-autocomplete-2](https://user-images.githubusercontent.com/1632384/54742571-189a1300-4bc2-11e9-9c9a-77b77158bee6.gif)

* OS and language server: Ubuntu 18.04
* How you installed LSP (Package Control or from git?): Package Control version 0.8.2

Any ideas on how to fix this kind of issues ? I am willing to make a PR but first would like to get your thoughts

cc @nanoant

**Comment by ayoub-benali** [comment]
One idea could be that we:
1. remove the trimming applied [here](https://github.com/tomv564/LSP/blob/master/plugin/completion.py#L296) 
2. after completion we add extra logic in [CompletionSnippetHandler](https://github.com/tomv564/LSP/blob/master/plugin/completion.py#L67) to remove any leftovers. 

We know:
- the last prefix 
- the range of the replacement present in `textEdit` 
- that Sublime replaces only the last prefix and not the whole range specified in `textEdit`  

Therefore we can assume that the remaining can simply deleted.

Example 
```scala
// first
def myF<ctrl+space>
```
```scala
// after user choice we get broken code
def override def myFunction1(): Unit = ???
```
```scala
// finaly delete the borken prefix with a diff between and range and last prefix
override def myFunction1(): Unit = ???
```
The whole challenge is to somehow know which choice the user make so we can decide which fix we need to apply if need to be

@rwols can you think of a case where this logic would brake things ?

**Comment by nanoant** [comment]
@ayoub-benali Unfortunately, I don't see good solution for this, other than making Sublime Text aware of completion text replacement ranges. The problem is that the completion prefix `myFunction`<kbd>Ctrl</kbd><kbd>Space</kbd> and its completion text `override def myFunction1(): Unit = ???` starts before the prefix.

This is shortcoming of Sublime Text that does not provide explicit way to apply replacement with explicit range. It does only replace current prefix with proposed text, see https://github.com/tomv564/LSP/pull/295#discussion_r175924508.

Therefore I have added feature request to Sublime Text there: https://github.com/SublimeTextIssues/Core/issues/2754

**Comment by ayoub-benali** [comment]
fixed by https://github.com/tomv564/LSP/pull/602
