### ISSUE TITLE
Also tested with the  D Programming Language 

### ISSUE THREAD

**Issue by andre2007** [tomv564/LSP#537]
This plugin was successfully tested with the Language Server for the D Programming Language (https://github.com/d-language-server/dls) .

Could you add this note to the README?

**Comment by tomv564** [comment]
Great to hear there's D support!

If there's any chance the language server installation steps guarantee an executable command on all platforms (eg `dls` on the PATH) then I'd love to move the config from the docs into LSP's built-in configs!
