### ISSUE TITLE
Does wrong commented method for user settings matter? 

### ISSUE THREAD

**Issue by aunpyz** [tomv564/LSP#538]
I did see that method name in a comment is different from [specification](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration)

>#### _Notification:_
>- method: ‘workspace/didChangeConfiguration’,
>- params: DidChangeConfigurationParams defined as follows:

 https://github.com/tomv564/LSP/blob/6d64e31fed6a008473ed3f692c85cb94e45be17e/LSP.sublime-settings#L27-L28

**Comment by rwols** [comment]
Thanks for your interest in LSP.

> Does wrong commented method for user settings matter?

No. But feel free to make a pull request that fixes this typo.
