### ISSUE TITLE
Seeking advice on how to use this plugin to develop an LSP server

### ISSUE THREAD

**Issue by haferburg** [tomv564/LSP#541]
I would need to frequently start the server, test, stop, and recompile it. When I disable the server globally in the settings, the plugin doesn't stop it. So I have to restart ST3.

Conversely, when I enable the server in the settings, the plugin doesn't start the server. Is that a bug? In the console it says `LSP: no config found or enabled for view ...` when I activate a view. Again, I have to restart ST3.

Is there anything I can do to make this process a bit smoother?

**Comment by rwols** [comment]
The plugin should in principle shut down completely when you disable it via Package Control, and then restart once you enable it via Package Control. Have you tried doing that?

The functions `plugin_loaded` and `plugin_unloaded` are invoked by ST once you disable/enable the package: https://github.com/tomv564/LSP/blob/master/boot.py (and also when ST starts up)

**Comment by haferburg** [comment]
Oh, that's a good idea. Unfortunately the server process is still there when I disable LSP. But, when I enable it back, the server is started automatically, so that's a lot better, thanks!

**Comment by haferburg** [comment]
After reading through the code, I believe the server is expected to handle a `shutdown` request gracefully, and since mine doesn't do that yet, the client just lets it live. And that's why it's still running.
Thank you for your help!

**Comment by rwols** [comment]
The server should at least respond to the `shutdown` request, but can stay alive until the `exit` notification.

**Comment by rwols** [comment]
One more thing that might help: the plugin listens for `window/logMessage` notifications, so, one of the first things that you should do is set up a logging system that logs via `window/logMessage` notifications. LSP will then pick that up and print the message to the SublimeText console.

**Comment by haferburg** [comment]
Thank you very much. What I have been using so far is the `log_stderr` setting, which is quite helpful.
