### ISSUE TITLE
LSP doesn't restart the server after it crashed

### ISSUE THREAD

**Issue by haferburg** [tomv564/LSP#544]
During development I kill the server process to recompile. When the client notices this, it asks "Language server ... has crashed, do you want to restart it?". But it never does when I click Yes. It still sends a shutdown request. Maybe it's waiting for a response.

Console output:

    Failure writing to stdout
    Traceback (most recent call last):
      File "AppData\Roaming\Sublime Text 3\Packages\LSP\plugin\core\transports.py", line 201, in write_stdin
        self.process.stdin.flush()
    OSError: [Errno 22] Invalid argument

    LSP: unloading session
    LSP:  --> shutdown {"jsonrpc": "2.0", "method": "shutdown", "id": 4}
    ending client

Possible duplicate of #250 and #236. Maybe this is a regression?

**Comment by rwols** [comment]
fixed by #545
