### ISSUE TITLE
LspApplyDocumentEditCommand is slow

### ISSUE THREAD

**Issue by haferburg** [tomv564/LSP#548]
I'm testing my formatter with a 5k LoC file every now and then. My server computes the required edits quickly. LSP then freezes Sublime for 5 s while it applies the ~800 edits. For 1360 changes it takes 30 s. I traced this to the `LspApplyDocumentEditCommand`, which looks like it's at least in O(n²).

The algorithm uses the Sublime API to repeatedly query regions for each change, so Sublime needs to build that list again and again.

Alternatively, we could apply the changes in reverse order, so that the regions we're about to edit are still valid. We're sorting the changes anyways, all it takes is a `reverse=True`. The `TextEdit[]` specification says "_Text edits ranges must never overlap, that means no part of the original document must be manipulated by more than one edit._"

Preparing a PR from https://github.com/haferburg/LSP/tree/faster-edit-command. After my change, it always takes less than 1 s.

Am I missing something?

The LSP spec also says "_If multiple inserts have the same position, the order in the array defines the order in which the inserted strings appear in the resulting text._" I'm not sure if that already works, but I think it does. Needs more thorough testing.

**Comment by rwols** [comment]
Agreed, we should apply edits from top to bottom and not care about other edits.

**Comment by haferburg** [comment]
My idea was to apply them bottom to top. E. g. if you want to transform "ab" into "a\nb\n", you would use two regions (1,1) and (2,2). If you apply insert the \n at 1 first, the position of b would change from 2 to 3, and you would also need to change the second index from 2 to 3. The old algorithm used the Sublime API to do that. But if you apply every change in reverse order, all the indices for edits that you have not yet applied always remain valid, because removing or inserting text only affects the ranges that appear later in the text.

**Comment by rwols** [comment]
Ah yes, I meant bottom to top. Mixed up the words.

**Comment by tomv564** [comment]
Great work, the insight to work bottom-to-top (with the TextEdit guarantee of no overlap) is really elegant! Look forward to seeing your PR!

**Comment by haferburg** [comment]
@tomv564 Thank you! :)

Unfortunately I wasn't aware of the way PRs interact with branches, so I failed to make a separate branch for #545 in my fork. I'll open the PR for this issue as soon as #545 is closed. I was hoping you would find some time to review it. Thanks!

**Comment by rwols** [comment]
fixed by https://github.com/tomv564/LSP/pull/554.
