### ISSUE TITLE
Use of monospace font in Symbol References quick_panel

### ISSUE THREAD

**Issue by frou** [tomv564/LSP#549]
To start with, this is a nice feature that I appreciate!

Though, I feel the use of monospace font (`sublime.MONOSPACE_FONT` flag) makes things look worse than simply using the default quick_panel style.

![Screenshot 2019-04-02 at 20 33 40](https://user-images.githubusercontent.com/172663/55430989-49e1ee00-5587-11e9-87ce-fbb15234e48d.png)

vs.

![Screenshot 2019-04-02 at 20 31 58](https://user-images.githubusercontent.com/172663/55430994-4d757500-5587-11e9-97f1-7a18428eba9c.png)

Don't you agree?

cc @alin23

**Comment by alin23** [comment]
I think this is a personal preference and it is best solved by implementing a setting like 
```js
"quick_panel_monospace_font": false
```

I'd be glad if you could open a PR for that ^_^

**Comment by tomv564** [comment]
Many built-in quick panels use the regular sans-serif font, so I feel like we introduced an exception here. I guess the argument is that we're showing code in it?

Monospace fonts are optimised for typing/legibility at small point sizes, and the quick panel size for me a few steps larger than editor text. It's a bit jarring compared to reading nicely kerned text.

I'm for changing the default (to match Sublime) and adding an option for monospace if needed.
