### ISSUE TITLE
Expand variables in language server command setting

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#55]
As described in #27, PHP's language server can be installed globally in the user's home, or local to the project.

It is a minor effort for the user to fill in the absolute path, but if we support `~` we can provide default or copy-paste-able configuration for more language servers.
Language servers installed per-project cannot be achieved unless we expand `$project_path` etc.

**Comment by rmccue** [comment]
SublimeLinter's behaviour might be useful to copy here: https://github.com/SublimeLinter/SublimeLinter3/blob/a5f6c28ac7d88bfe28d524f6c2a6c2ed6b563cbc/lint/linter.py#L522
