### ISSUE TITLE
Don't send textDocument/didSave unless server advertises support for it

### ISSUE THREAD

**Issue by tophattom** [tomv564/LSP#550]
I ran into an issue with using Dart analyzer server in LSP mode. Every time I would save a file I would get an error saying `Unknown method textDocument/didSave`. Turns out this should be fixed in the client by not sending `textDocument/didSave` if the server doesn't support that.

More information: https://github.com/dart-lang/sdk/issues/36464 and https://github.com/natebosch/vim-lsc/issues/164

Please include in your report:

* Minimal reproduction steps:
   Setup Dart language server and try saving Dart files:
   ```json
   "dart": {
		"command": ["<DART SDK PATH>/bin/dart", "<DART SDK PATH>/bin/snapshots/analysis_server.dart.snapshot", "--lsp", "--instrumentation-log-file", "/usr/local/var/log/lsp.sublime.txt"],
		"enabled": false,
		"languageId": "dart",
		"scopes": [
			"source.dart"
		],
		"syntaxes": [
		     "Packages/Dart/Dart.tmLanguage"
		]
   },
   ```

cc @DanTup

**Comment by DanTup** [comment]
(I'm a dev on the Dart LSP server)

I don't think the spec is super clear here (though I've opened https://github.com/Microsoft/language-server-protocol/issues/713 asking for it to be made clearer) but the reason I think this is a client issue is based on the table at https://github.com/Microsoft/language-server-protocol/issues/288#issue-253180885. The `didSave` notification wasn't in the original version and therefore is opted in to by the server populating the `save` field of `ServerCapabilities.textDocumentSync`.

We could add an empty handler in the Dart server to ignore this , but I think it would generally improve compatibility with more servers if it wasn't sent by the client in this case.

**Comment by tomv564** [comment]
Yep, doesn't look like the nicest logic based on the table in that linked issue, but I agree we should follow those rules. A PR would be much appreciated!

**Comment by DanTup** [comment]
I'm not a sublime user and not well placed to contribute this, though FWIW the LSP spec was updated to make this clearer (our assumptions that it shouldn't be sent were correct): https://github.com/Microsoft/language-server-protocol/issues/713
