### ISSUE TITLE
Improve Markdown to HTML translation in signature help

### ISSUE THREAD

**Issue by cixtor** [tomv564/LSP#552]
I found myself a bit annoyed with the Markdown to HTML formatting of the function signatures (and corresponding comments/documentation). The plugin uses `mdpopups` for the conversion, and I think it is doing one part incorrectly. I want to know people’s opinion before I send a patch to that project.

### Sample Code

```golang
// Lorem ipsum dolor
//
//   text with 2-leading spaces becomes code
//   text with 2-leading spaces becomes code
//   text with 2-leading spaces becomes code
//
// More text that’s part of the documentation.
func Hello(name string) {
    fmt.Printf("Hello %s", name)
}
```

This gets translated into the following HTML:

```html
<p><div class="highlight"><pre><span style="color: #c695c6; font-style: italic;">func</span><span style="color: #333333;">&nbsp;</span><span style="color: #5fb4b4;">Hello</span><span style="color: #333333;">(</span><span style="color: #f9ae58;">name</span><span style="color: #333333;">&nbsp;</span><span style="color: #6699cc; font-style: italic;">string</span><span style="color: #333333;">)</span><br></pre></div>Lorem ipsum dolor </p><p><div class="highlight"><pre><span style="color: #333333;">text&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp;code</span><br><span style="color: #333333;">text&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp;code</span><br><span style="color: #333333;">text&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp;code</span><br></pre></div>More text that’s part of the documentation. </p>
```

Here is the same HTML code, with human formatting:

```html
<p>
    <div class="highlight">
        <pre>
            <span style="color: #c695c6; font-style: italic;">func</span>
            <span style="color: #333333;">&nbsp;</span>
            <span style="color: #5fb4b4;">Hello</span>
            <span style="color: #333333;">(</span>
            <span style="color: #f9ae58;">name</span>
            <span style="color: #333333;">&nbsp;</span>
            <span style="color: #6699cc; font-style: italic;">string</span>
            <span style="color: #333333;">)</span>
            <br>
        </pre>
    </div>
    Lorem ipsum dolor
</p>
<p>
    <div class="highlight">
        <pre>
            <span style="color: #333333;">text&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp;code</span>
            <br>
            <span style="color: #333333;">text&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp;code</span>
            <br>
            <span style="color: #333333;">text&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp;code</span>
            <br>
        </pre>
    </div>
    More text that’s part of the documentation.
</p>
```

So what I find annoying is the fact that the paragraph containing the `<div class="highlight">` is not closed before the first line of the documentation is rendered. In my imaginary perfect web browser **mdpopups** should create four paragraphs, like this:

```html
<p>
    <div class="highlight">…</div>
</p>
<p>
    Lorem ipsum dolor
</p>
<p>
    <div class="highlight">…</div>
</p>
<p>
    More text that’s part of the documentation.
</p>
```

What do you guys think? Am I the only one? Should I send a pull-request to patch this? Or is this the correct way to do the Markdown translation? Because of this “bug” I can see an extra whitespace in the popup because `<pre>` and `<br />` both have margins, which is redundant.

## Possible Solution

I managed to fix one part of the annoyance by patching `hover_content()` defined in `plugin/hover.py`, instead of returning the output of `mdpopups.md2html()` I save it in a variable, and then use simple String replacement to remove all the unnecessary `<br />`. However, this doesn’t address the fact that the function comments are being wrapped along with the highlighted code, I think they should all be wrapped inside individual HTML paragraphs.

I also tweaked the CSS in `plugin/core/popups.py` to make better use of the margins.

| Current UI | Proposed UI |
|------------|-------------|
| <img width="551" alt="old" src="https://user-images.githubusercontent.com/1933999/55596642-78360980-56fe-11e9-9ff8-7ed1025216f2.png"> | <img width="551" alt="new" src="https://user-images.githubusercontent.com/1933999/55596643-7c622700-56fe-11e9-9aa7-c4d924b3b3da.png"> |

**Comment by tomv564** [comment]
Great investigation. Is there any chance you can share the raw markdown content from the language server?

CSS changes look good, but we should fix the HTML first!

**Comment by cixtor** [comment]
Hello @tomv564 , thank you for taking a look at this.

---

Here is the sample code:

```go
// Lorem ipsum dolor
//
//   text with 2-leading spaces becomes code
//   text with 2-leading spaces becomes code
//   text with 2-leading spaces becomes code
//
// More text that’s part of the documentation.
func Hello(name string) {
    fmt.Printf("Hello %s\n", name)
}
```

Here is the Markdown _(added `@@@` to denotate edges)_:

    @@@```go
    func Hello(name string)
    ```
    Lorem ipsum dolor 
    
    ```
    text with 2-leading spaces becomes code
    text with 2-leading spaces becomes code
    text with 2-leading spaces becomes code
    
    ```
    More text that’s part of the documentation. 
    
    @@@

Here is the HTML code _(added new lines for readability)_:

```html
@@@<p><div class="highlight"><pre><span style="color: #9ee7fc; f
ont-style: italic;">func</span><span style="color: #f8f8f2;">&nb
sp;</span><span style="color: #50fa7b;">Hello</span><span style=
"color: #f8f8f2;">(</span><span style="color: #f8f8f2;">name</sp
an><span style="color: #f8f8f2;">&nbsp;</span><span style="color
: #9ee7fc; font-style: italic;">string</span><span style="color:
 #f8f8f2;">)</span><br></pre></div><br />Lorem ipsum dolor </p><
p><div class="highlight"><pre><span style="color: #f8f8f2;">text
&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp;code</sp
an><br><span style="color: #f8f8f2;">text&nbsp;with&nbsp;2-leadi
ng&nbsp;spaces&nbsp;becomes&nbsp;code</span><br><span style="col
or: #f8f8f2;">text&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;bec
omes&nbsp;code</span><br></pre></div><br />More text that’s part
 of the documentation. </p>@@@
```

Now that I look at the Markdown code more carefully, I realized that the problem may be in the language server itself. I am using the _—what is going to be—_ the [official Go language server: gopls](https://github.com/golang/go/wiki/gopls). I believe it should add new lines between the backticks and the paragraphs. For example, in the sample code above, I believe there should be an additional new line before “Lorem”, and another one before “More text”. I tested my theory by hardcoding a modified version of the Markdown code above into “hover.py”:

```html
<div class="highlight">…</div>
<p>
    Lorem ipsum dolor <br />
    <div class="highlight">…</div>
</p>
<p>More text that’s part of the documentation. </p>
```

Notice how the first code block is not correctly rendered outside of the first paragraph. However, the second code block is now inside the first paragraph, which was not happening before. With this I can say there is both a bug in “gopls” and “mdpopups”. I am not sure which one I should patch first. For now, I simply added this to “hover.py” _(aside from the CSS tweaks)_:

```diff
--- a.py    2019-04-05 09:57:47.000000000 -0700
+++ hover.py    2019-04-05 09:57:51.000000000 -0700
@@ -143,7 +143,10 @@
             else:
                 formatted.append(value)

-        return mdpopups.md2html(self.view, "\n".join(formatted))
+        html = mdpopups.md2html(self.view, "\n".join(formatted))
+        html = html.replace("<p><div", "<div")
+        html = html.replace("<br />", "<p>")
+        return html

     def show_hover(self, point, contents):
         mdpopups.show_popup(
```

With this patch, the generated HTML code becomes:

```html
@@@<div class="highlight"><pre><span style="color: #9ee7fc; font
-style: italic;">func</span><span style="color: #f8f8f2;">&nbsp;
</span><span style="color: #50fa7b;">Hello</span><span style="co
lor: #f8f8f2;">(</span><span style="color: #f8f8f2;">name</span>
<span style="color: #f8f8f2;">&nbsp;</span><span style="color: #
9ee7fc; font-style: italic;">string</span><span style="color: #f
8f8f2;">)</span><br></pre></div><p>Lorem ipsum dolor </p><div cl
ass="highlight"><pre><span style="color: #f8f8f2;">text&nbsp;wit
h&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp;code</span><br><s
pan style="color: #f8f8f2;">text&nbsp;with&nbsp;2-leading&nbsp;s
paces&nbsp;becomes&nbsp;code</span><br><span style="color: #f8f8
f2;">text&nbsp;with&nbsp;2-leading&nbsp;spaces&nbsp;becomes&nbsp
;code</span><br></pre></div><p>More text that’s part of the docu
mentation. </p>@@@
```

Here is the same HTML code, formatted for readability:

```html
<div class="highlight">
    <pre>
        <span style="color: #9ee7fc; font-style: italic;">func<…
        <span style="color: #f8f8f2;">&nbsp;</span>
        <span style="color: #50fa7b;">Hello</span>
        <span style="color: #f8f8f2;">(</span>
        <span style="color: #f8f8f2;">name</span>
        <span style="color: #f8f8f2;">&nbsp;</span>
        <span style="color: #9ee7fc; font-style: italic;">strin…
        <span style="color: #f8f8f2;">)</span>
        <br>
    </pre>
</div>
<p>Lorem ipsum dolor </p>
<div class="highlight">
    <pre>
        <span style="color: #f8f8f2;">text&nbsp;with&nbsp;2-lea…
        <br>
        <span style="color: #f8f8f2;">text&nbsp;with&nbsp;2-lea…
        <br>
        <span style="color: #f8f8f2;">text&nbsp;with&nbsp;2-lea…
        <br>
    </pre>
</div>
<p>More text that’s part of the documentation. </p>
```

I believe the correct way to fix this is to patch “gopls”, then wait for them to merge the improvements. Then patch “mdpopups”, and wait for their corresponding merges. Finally, test this LSP plugin again, and see if it still suffers from the same problems described above, if not, case closed. I was thinking to create a pull-request with the improvements in the CSS, but now I think they are closely tied to these changes in the HTML, so it’s better to fix these first.

Thank you.

**Comment by tomv564** [comment]
If you are going to look at *gopls*, I would recommend checking how the same signature help looks in Visual Studio Code, as many gopls users are probably going to use that editor.

**Comment by tomv564** [comment]
Closing this now by lack of updates. Did you open an issue with mdpopups?
