### ISSUE TITLE
No syntax highlighting in popups

### ISSUE THREAD

**Issue by jdkato** [tomv564/LSP#56]
Hi,

First of all, great work on this package&mdash;I'm already getting quite a bit of use out of it.

I have one question, though: unlike in the README's screenshot, the hover popups often seem to lack some combination of syntax highlighting and formatting. Here are a few examples:

<table>
    <tr>
        <td width="50%">
           <img width="609" alt="screen shot 2017-08-29 at 9 10 06 am" src="https://user-images.githubusercontent.com/8785025/29831394-e3ab735c-8c99-11e7-9cbd-1cc1fa62b409.png">
            </a>
        </td>
        <td width="50%">
           <img alt="no-syntax" src="https://user-images.githubusercontent.com/8785025/29831180-2e1db8ce-8c99-11e7-8b73-49ac32bbd43d.png">
            </a>
        </td>
    </tr>
    <tr>
        <td width="50%"><code>pyls</code> popup without code formatting or
 syntax highlighting.</td>
        <td width="50%"><code>go-langserver</code> popup without syntax highlighting.</td>
    </tr>
</table>

Is this intended?

Thanks!

**Comment by tomv564** [comment]
Hi, glad you like it!

The highlighting requires two things to cooperate:
* The language server should return MarkedString entries with a valid language field (https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#hover-request)
  * I believe the python language server doesn't support this yet
  * go-langserver sends "go" as language with some strings (see https://github.com/sourcegraph/go-langserver/blob/master/langserver/hover.go#L142)
* The `mdpopups` library used for the popups should be configured to syntax highlight for that language
  * This appears to be the problem in your go-langserver example (you do get the darkened background)
  * The language identifier "go" is recognized by mdpopups (see: https://github.com/facelessuser/sublime-markdown-popups/blob/master/st3/mdpopups/st_mapping.py)

`mdpopups` also has two highlighters, the default pygments highlighter might not be working.
Could you try setting ` "mdpopups.use_sublime_highlighter": true ` in your sublime user settings to see if it makes a difference?

**Comment by jdkato** [comment]
Yep, that did it&mdash;I added `"mdpopups.use_sublime_highlighter": true` and now the `go-langserver` popups look great.

Thanks for the details.
