### ISSUE TITLE
not sending changes through to lsp-tsserver?

### ISSUE THREAD

**Issue by princemaple** [tomv564/LSP#560]
Hi all,

Thanks a lot for the great package!

This is very likely not an LSP issue, I [filed an issue on lsp-tsserver](https://github.com/tomv564/lsp-tsserver/issues/8) already but am not 100% sure.

Mirroring the content here:

I'm having a weird problem on my new computer. I'm not really sure if it's on LSP's side or lsp-tsserver. When I open a file the language server seems to get the file fine, but if I make any change to the file the language server seems to not get my changes, even if I save the file.

first open, placing caret on the constructor parameter, correctly highlights the reference
![image](https://user-images.githubusercontent.com/1329716/55923866-e0c73e00-5c4a-11e9-8621-f94c62dbc09a.png)

adding a few spaces in front of the reference, it seems the language server is still working on the first opened version
![image](https://user-images.githubusercontent.com/1329716/55923924-19ffae00-5c4b-11e9-8e39-1d3dc314d233.png)

Any idea what could be the cause/fix? Thanks a lot.

I'm on Sublime 3206, LSP 0.8.2, lsp-tsserver 0.0.4, Windows 10 17763

Edit: Just tested on my old computer, where everything still works. I have the same Windows version, same Sublime, LSP and lsp-tsserver version. My Sublime User folder is even synced with onedrive so Sublime on the two computers have exactly the same configs.

**Comment by princemaple** [comment]
Fixed by upgrade node from 11.13 to 11.14

**Comment by tomv564** [comment]
Thanks for updating with your fix - would have been nice to see logs from the server to figure out what is breaking on the server. But I guess things can break on "current" Node.

**Comment by princemaple** [comment]
Yeah didn't go that far. I added logging to the python package, and immediately realized that LSP is merely sending file path and caret location to the language server, the problem had to be on node / lsp-tsserver side. My first suspicion was the installation of node - I used to use chocolatey on my old computer, now I'm using scoop on the new one. I tried installing node with chocolatey, which of course installed the latest (11.14) which happen to fix the problem. I almost commented on the issue and closed it, but decided to see if it was the version instead. And... here we are, yes it was just a bad version, scoop is all good. If that didn't work, I'd start adding logs in lsp-tsserver.

**Comment by princemaple** [comment]
Hmm, looks like node version wasn't the real cause. I had the same problem on my Surface Pro with node v11.14
Fixed it with uninstalling and re-installing node in an admin console, still using scoop.

**Comment by princemaple** [comment]
Somehow this issue came back. I've uninstalled and re-installed nodejs several times, with or without admin privilege, the problem doesn't seem to go away. If you were to make a best guess, what would you say that the cause is?

**Comment by princemaple** [comment]
Also, what kind of logs would be helpful? Please let me know. Thanks!

**Comment by princemaple** [comment]
typescript-language-server works, but it is not showing highlights (the blue, green underlines). Closing since this is not an LSP issue. A word about why typescript-language-server doesn't show highlights would be appreciated, the project pages says it supports `textDocument/documentHighlight`
