### ISSUE TITLE
LSP launching language server Elixir-LS on non-Elixir files

### ISSUE THREAD

**Issue by tmepple** [tomv564/LSP#564]
For some reason LSP is launching the Elixir-LS language server no matter what non-Elixir file type I open... then promptly crashes.

* OS and language server
MacOS Mojave (10.14.4)
ST3 build 3206
Elixir-LS (https://github.com/JakeBecker/elixir-ls)

* How you installed LSP (Package Control or from git?)
Package Control

* Minimal reproduction steps
1. Open any random non-Elixir file... like `subl -n data.csv`
1. In status bar bottom right, it says `Plain Text (CSV)` which is the proper file type detection.
1. In status bar bottom left it says `elixir-ls initialized`, then an error comes from the language server `No mixfile found in project.` which isn't surprising since I opened a CSV file.
1. Finally a popup says "Elixir LS has crashed. See Output panel." and "Language server elixir-ls has crashed, do you want to restart it?"

* Log
```
using gpu buffer for window
server: Started ElixirLS
server: Elixir version: "1.8.1 (compiled with Erlang/OTP 21)"
server: Erlang version: "21"
server: 
11:42:47.822 [warn]  Did not receive workspace/didChangeConfiguration notification after 5 seconds. Using default settings.
server: Compiling with Mix env test
server: Compile took 61 milliseconds
server: 
11:43:02.921 [error] GenServer ElixirLS.LanguageServer.Server terminating
```

* My config:
```
{
  "clients": {
    "elixir-ls": {
      "command": ["~/Programs/language_servers/elixir-ls/language_server.sh"],
      "enabled": true,
      "languageId": "elixir",
      "scopes": ["source.elixir"]
    }
  },
  "log_debug": true
}
```

**Comment by rwols** [comment]
Perhaps try adding a `”syntaxes”` key to your client config, as it seems to be missing. I am unsure what the behavior is when the syntaxes key is missing.

**Comment by tmepple** [comment]
Thanks @rwols that fixed it.  I thought the `"syntaxes"` key was optional but I guess not.
