### ISSUE TITLE
Code actions of CodeActionLiteral type are not supported (used by eslint-server)

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#566]
While experimenting with [eslint-server](https://github.com/Microsoft/vscode-eslint/tree/master/server), I've noticed that its code actions for fixing lint issues are not handled properly.

I found two issues:
 - handling CodeActions action list as an array of `Command` while protocol also allows array of `CodeAction`.
 - Passing `args` param to `workspace/executeCommand` instead of expected `arguments` param.

**Comment by tomv564** [comment]
CodeAction literals were added in protocol version 3.8.0 and should be gated by `textDocument.codeAction.codeActionLiteralSupport`

I vote we do a minimal implementation for CodeAction, including the workspaceEdit + command sequence.

The other (`args`) is great but that code was not being used for code actions previously! I'll send in a fix for that now.

**Comment by rchl** [comment]
I'm not very familiar with the code base so adding full support for CodeAction related things would be quite an undertaking for me.

You decide if you want to build on top of that or add just those changes without advertising support for CodeAction, or...

Those changes are enough to make code actions work in eslint-server at least (well, also implementation of `workspace/configuration` is needed, which I only have in pretty hacky state right now).

**Comment by rchl** [comment]
Well, `workspace/applyEdit` is already implemented so maybe it wouldn't be that hard.
