### ISSUE TITLE
Unable to make this work with ocaml-language-server

### ISSUE THREAD

**Issue by chenglou** [tomv564/LSP#57]
Hello! So glad to see LSP in ST. The OCaml/Reason language server is pretty complete: https://github.com/freebroccolo/ocaml-language-server

I've tried the following config:

```json
{
  "clients": {
    "reason": {
      "command": ["ocaml-language-server", "--stdio"],
      "scopes": ["source.ml", "source.mli", "source.re", "source.rei"],
      "syntaxes": ["Packages/User/sublime-reason/Reason.tmLanguage"],
      "languageId": "reason"
    }
  }
}
```

This config didn't seem to work. It says `LSP: config not available for view path/to/test.re`, though the scope is definitely correctly specified.

**Comment by tomv564** [comment]
Another language service I hadn't tried out, welcome!

It looks like `source.reason` is missing from your scopes list. If the others are file extensions, they may not be necessary. 

<img width="629" alt="screen shot 2017-08-31 at 07 38 50" src="https://user-images.githubusercontent.com/4395832/29908119-018cb322-8e20-11e7-9566-f7a2cecc3a78.png">

The language server wants to tell users to install merlin / set reasonpath through `window/showMessageRequest`, which this package does not handle yet. I'll add an issue for that - it's great that your language server communicates configuration issues!

Let me know if updating the scopes fixes your issue !

**Comment by tomv564** [comment]
If I may ask about the language serve's implementation, is there a reason why you are sending showMessageRequest instead of showMessage in this case?

**Comment by chenglou** [comment]
I didn't implement ocaml-language-server. Not sure about this one.

That correction to `source` worked. I think this works well enough for us to recommend it as the ST Reason/OCaml integration. Thank you for your work =)
