### ISSUE TITLE
Feature request: Please add an option for disabling popups on hover.

### ISSUE THREAD

**Issue by agilesteel** [tomv564/LSP#574]
I am constantly finding myself hiding my mouse cursor in the corners of my screen since even when I don't touch my mouse for a while some code always slides under the cursor and some random popup steals my focus.

It is already possible to bind a key to display a popup like so: `{ "keys": ["ctrl+space"], "command": "lsp_hover"}` however this does not disable the default behavior which triggers a popup as soon as the mouse cursor finds itself hovering over something it considers relevant.

**Comment by tomv564** [comment]
Sounds annoying!
I tried to repro this on a recent dev build on OS-X but noticed that the mouse cursor disappears as soon as I start typing, and I don't get hover popups until I use the touchpad again.

I'm not sure if it's always been like this, but this behaviour sounds like it should prevent your problem. Is the mouse cursor active while typing in your sublime text? Do other editors (eg. IntelliJ?) have some smart way of avoiding this on your platform?

**Comment by agilesteel** [comment]
Interesting, it might be related to the fact that I'm running it inside of a VM. My host is Windows 10 and my guest is Ubuntu 16.04. I'm not sure about other editors. I haven't used IntelliJ for a long time now. In fact for similar reasons. IDEs keep doing some stuff all the time that I haven't asked them to do, Sublime doesn't which is why I love it. It stays out of my way and I usually set it up in such a way that I don't even see auto complete popups (only triggered by a key binding).

BTW VS code doesn't have the hover problem since its LSP respects the `"editor.hover.enabled": false` setting. Maybe Sublime LSP should also respect the native `"show_definitions": false` Sublime setting? Just a suggestion...

**Comment by tomv564** [comment]
We probably can introduce a new setting instead! Good to see an example of another editor disabling them.

**Comment by tomv564** [comment]
There is a new `disabled_capabilities` setting, adding "hover" to the array in your LSP settings should disable the automatic hover popups.

**Comment by skobes** [comment]
FYI it appears the setting is now "hoverProvider", e.g.

```
{
  "disabled_capabilities": { "hoverProvider": true }
}
```

Just in case anyone else finds this issue while looking for the way to disable popups.
