### ISSUE TITLE
Support window/showMessage(Request)

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#58]
As seen in the ocaml language server (#57), there is great value in language servers telling the user how to fix configuration etc. The language server protocol exposes a notification and a request from the server:

showMessage: show in status bar + allow user to specify getting a message box
showMessageRequest (with actions to respond with?): quick panel?

**Comment by ayoub-benali** [comment]
@tomv564 I am working on a fix to have the actions in a quick panel. 
Needed for this LSP server for example: https://scalameta.org/metals/docs/editors/new-editor.html#import-build

Can I issue an WIP PR ?
