### ISSUE TITLE
Docs need to be specific to windows users

### ISSUE THREAD

**Issue by LiteCatDev** [tomv564/LSP#581]
In the docs i used dart_language_server instructions in linux normally from https://lsp.readthedocs.io/en/latest/ , however in windows they don't work, LSP plugin doesn't know and says that the file doesn't exist . An easy fix is to append the .bat extension at the end , or whatever extension is the language server
```
"command": [
    "PATH_TO_PUB_BIN/dart_language_server.bat"
  ],
```

I think that the docs should at least mention this for windows users

**Comment by tomv564** [comment]
This issue should be easy to fix with the same logic as we use for node's `.cmd` wrappers, see here:
https://github.com/tomv564/LSP/blob/e2ad3be8dda4bca130a3fce08904c6bb42abaa42/plugin/core/process.py#L25

Would really like to avoid extra steps for windows users!
