### ISSUE TITLE
[Request] Support Apache Camel Language Server

### ISSUE THREAD

**Issue by apupier** [tomv564/LSP#590]
it would be nice to support Apache Camel language Server https://github.com/camel-tooling/camel-language-server

i tried to find how to add support for it but cannot find how to do.

It is a language server which is packaged as a SpringBoot application, so the server can be launched using a single java command.
Users that will use it will also usually use Java so they have Java already installed in most cases.

**Comment by tomv564** [comment]
Hi, I think the documentation at https://lsp.readthedocs.io/en/latest/#client-config covers the settings to add in Sublime (see *Preferences - LSP Settings* in the quick panel)

That said, the screenshot on your home page shows a regular XML file being edited. If you want the server to work on all XML files:
```
"camel-language-server": {
"syntaxes": ['Packages/XML/XML.sublime-syntax'],
"scopes": ['text.xml'],
"languageId": 'camel'
"command": ['java', 'arg1', 'arg2', 'arg3'],
"enabled": true
}
```

Unsure if there's a built-in way to only associate *camel* XML files with the language server, but this should get your started at least!

**Comment by apupier** [comment]
thanks to the pointers.
for reference, I tried and provided steps to configure it here https://github.com/camel-tooling/camel-lsp-client-sublime/blob/master/README.md
I have sometimes strange behavior with completion not showing up but cannot detect a pattern of when it is happening yet.
