### ISSUE TITLE
Custom launch scripts

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#598]
currently server is launched through executing the command specified in the configuration, that should do in some cases but in many cases the execution of the server require more than a static command like specifying options based on certain conditions. can't LSP provide launch scripts a la VSCode ?

**Comment by tomv564** [comment]
That's what the `config` property of LanguageHandler is for - if a language server really needs a complicated set of arguments then it can be implemented (and maintained!) outside of this repo.
Many servers don't seem to need it - for example the xml server could just as well default `DwatchParentProcess`.
