### ISSUE TITLE
[Request] Add option for character limit in autocompletion

### ISSUE THREAD

**Issue by LiteCatDev** [tomv564/LSP#599]
This so far is working awesome. But there is something missing.

Again, using Dart Language Server the autocompletion popup shows, but the description is so big that it goes out of the screen [since i'm using a big font size] . It would be great if in the configuration you could set a character limit for the description text and just add "..." if the description is too big. I have implemented something like this but since i don' t know python that well, i don't have the courage to make a pull request 

My implementation is this one 

In the file LSP/plugin/core/completion.py line 37 i think

> if len(replacement) > 0 and replacement[0] == '$':  # sublime needs leading '$' escaped.
>         replacement = '\\$' + replacement[1:]
>     //if len(trigger) + len (hint) > 80:     <- this is checking if it exceeds the character limit
>       //  hint = hint[0:80 - len(trigger)]  <-this changes the hint so it can't be greater that the character limit
>     return "\t  ".join((trigger, hint)) if hint else trigger, replacement

again this is only an idea, it is of no importance , just customization

**Comment by tomv564** [comment]
Can you share a screenshot of what it looks like now? 

As over time we've accumulated many settings for many preferences, I'd like to instead find a solution that works for all users. Perhaps `kind` is a better default for the `completion_hint_type`?

**Comment by tomv564** [comment]
Can re-open if this is a common issue, but so far only 1 report with Dart language server, and a workaround is available with the `completion_hint_type` setting.
