### ISSUE TITLE
Missing dependencies.json

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#6]
As you use _mdpopups_ package, you should add a dependencies.json to your package to let Package Control install it automatically if not yet available.

**Comment by tomv564** [comment]
Thanks for the reminder, https://github.com/tomv564/LSP/commit/0dc8f93f40df238a4029216f4d34311e8a7f5b6f contains the dependencies.json.

I'll leave this issue open until I verify it all works with a clean install of the package.

**Comment by tomv564** [comment]
Just tested, got a notification about 6 missing packages being installed after installing LSP.
