### ISSUE TITLE
[Feature request] ignore certain lint errors

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#60]
Some language servers report also code styling warnings and some of the warnings are over-killed.
Besides launching the language server with extra arguments (and some servers do not take arguments at all), It would be nice to ignore certain lint errors at Sublime Text level.

**Comment by tomv564** [comment]
Configuration for language servers is one of the highest priorities.
If after that the undesired warnings are still too much, we could configure a threshold at which to show / highlight diagnostics.
Which language server are you seeing excessive code styling warnings from?

**Comment by randy3k** [comment]
I was using `python-language-server` but soon later I figured out it checks `setup.cfg`.

But still, it would be nice to have some kinds of filters.

**Comment by tomv564** [comment]
It sounds like your original issue is resolved.
A PR implementing a `show_diagnostics_threshold` would be welcome, but improving the language server's behaviour is always preferred.
