### ISSUE TITLE
Hover popups scroll vertically instead of fitting to content

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#604]
![image](https://user-images.githubusercontent.com/33235928/59054655-702c4e80-8894-11e9-9aab-3f2f886157c1.png)

* OS: Windows 10
* How you installed LSP (Package Control or from git?): git
* Minimal reproduction steps
1. open a css file with vscode-css
2. hover over e.g `sans-serif`

**Comment by tomv564** [comment]
I've seen this too! Would be great if someone could try to address it with our `popup_css` ... assuming Sublime Text has not introduced new layout behaviour in newer versions.

**Comment by AmjadHD** [comment]
sorry, css is not my cop of tea :)

**Comment by AmjadHD** [comment]
possible duplicate of #486

**Comment by tomv564** [comment]
Yeah, it's a duplicate, but nice to see some solutions in linked issues from #486. Closing this now!
