### ISSUE TITLE
show_popup_menu: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by cixtor** [tomv564/LSP#605]
Hello @rwols I noticed that you fixed a [similar bug 5+ months ago](https://github.com/tomv564/LSP/issues/494) but I it seems the “TypeError” is a common thing in other parts of the code. I’m using [gopls](https://github.com/golang/go/wiki/gopls) with [LSP 0.8.4](https://github.com/tomv564/LSP/releases/tag/0.8.4), and noticed the following crash while hovering a function name.

* Using **macOS** with **gopls** _(default configuration)_
* I installed LSP using “Package Control”
* Minimal reproduction steps: I am not able to reproduce the bug with consistency because it requires a language server crash, and I’m not entirely sure what steps exactly are causing this chain of events. All I know is that it happens during `textDocument/hover`, and immediately after the language server responds to the request.

```
Error handling server payload
Traceback (most recent call last):
  File "LSP.sublime-package/plugin/core/rpc.py", line 141, in receive_payload
    self.response_handler(payload)
  File "LSP.sublime-package/plugin/core/rpc.py", line 160, in response_handler
    handler(response["result"])
  File "LSP.sublime-package/plugin/code_actions.py", line 39, in <lambda>
    lambda response: on_response_recieved(response))
  File "LSP.sublime-package/plugin/code_actions.py", line 101, in handle_response
    self.show_popup_menu()
  File "LSP.sublime-package/plugin/code_actions.py", line 104, in show_popup_menu
    if len(self.commands) > 0:
TypeError: object of type 'NoneType' has no len()
```

I hope the backtrace is descriptive enough to fix it.

**Comment by tomv564** [comment]
I think this issue with `code_actions.py` was just fixed today: https://github.com/tomv564/LSP/commit/1836426c85826f20de73e50ab285a948eebbeba4
