### ISSUE TITLE
Some servers provide tooltips for ignored scopes

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#607]
The vscode-json-languageserver provides tooltips for json keys, but the `string` scope is ignored
https://github.com/tomv564/LSP/blob/1836426c85826f20de73e50ab285a948eebbeba4/plugin/hover.py#L21

**Comment by tomv564** [comment]
Sure, we can remove the string scope from there, but we probably also want to remove the default "no hover content available" popup then? Want to open a PR?

**Comment by AmjadHD** [comment]
I was thinking maybe just ignore json keys from `NO_HOVER_SCOPES`
 ```python
NO_HOVER_SCOPES = 'comment, string - string.quoted.double.json'
```
if not maybe introduce an optional setting for servers like `"no_hover_scopes"`.
