### ISSUE TITLE
Signature help formatting issues after new implementation

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#609]
**Too much escaping** (Fixed in pull request #608):

<img width="634" alt="Screenshot 2019-06-03 at 00 49 10" src="https://user-images.githubusercontent.com/4395832/59147739-91f61480-89ff-11e9-98f2-b5ccef4c29e2.png">

<strike>**Chopped up signature in LSP from pyls:**</strike>
(cannot reproduce this after updating from pyls 0.19.0 to 0.26.1)

<img width="1100" alt="Screenshot 2019-06-08 at 12 09 20" src="https://user-images.githubusercontent.com/4395832/59147733-7ee34480-89ff-11e9-8a32-57043b49e5d2.png">

**Strange signature from `isinstance` from pyls:**

(signature label is `Return whether an object is an instance of a class or of a subclass thereof.`, looks like https://github.com/palantir/python-language-server/issues/309 may be relevant)

<img width="937" alt="Screenshot 2019-06-08 at 12 13 25" src="https://user-images.githubusercontent.com/4395832/59147734-8571bc00-89ff-11e9-80d1-9346e8d2c714.png">

**Comment by rwols** [comment]
also consider using `variable.function` instead of `entity.name.function`:

* `variable.function` is for function(-like) calls.
* `entity.name.function` is for function definitions/declarations.

**Comment by tomv564** [comment]
That choice is intentional as I want the signature to look like the definition, not the invocation.

**Comment by rwols** [comment]
Cool, then that's the viewpoint we take.

**Comment by tomv564** [comment]
Verified that the `is instance` is fixable from pyls, all known LSP issues are fixed for the moment.
