### ISSUE TITLE
signature html escape

### ISSUE THREAD

**Issue by princemaple** [tomv564/LSP#610]
![image](https://user-images.githubusercontent.com/1329716/59168540-82024000-8b79-11e9-8eb5-26c642b3f987.png)

Not sure if it's a sublime mini-html limitation, thought I should file this anyway. Please close if it's not LSP's issue.

**Comment by rwols** [comment]
This should be fixed in a next release: https://github.com/tomv564/LSP/pull/608

**Comment by princemaple** [comment]
Thanks!

**Comment by princemaple** [comment]
There seem to be more
![image](https://user-images.githubusercontent.com/1329716/61266898-26ab1980-a7d9-11e9-8e9a-4f3ce61c7a33.png)

**Comment by princemaple** [comment]
This is supposed to be Partial<>

**Comment by rwols** [comment]
Version 0.8.5 was released on package control a few days ago, this should be *really* fixed now :)
