### ISSUE TITLE
Pylint not working

### ISSUE THREAD

**Issue by dhelonious** [tomv564/LSP#614]
I recently discovered LSP and I really like it so far. I want to use it mainly for Python and replace other packages like Anaconda, Jedi and SublimeLinter. I was also glad to see that the python-language-server supports pylint since [5e785fe](https://github.com/palantir/python-language-server/commit/5e785fe688378628c015956e085ff6ddf0021944). However, I have not managed to enable pylint so far.

I was hoping that I could enable pylint the same way as other plugins. My config for the python-language-server looks like this:
```json
  "clients":
  {
    "pyls":
    {
      "enabled": true,
      "command": ["pyls"],
      "scopes": ["source.python"],
      "syntaxes": [
        "Packages/Python/Python.sublime-syntax",
        "Packages/MagicPython/grammars/MagicPython.tmLanguage"
      ],
      "languageId": "python",
      "settings": {
        "pyls": {
          "configurationSources": ["flake8"],
          "plugins": {
            "mccabe": {"enabled": true, "threshold": 15},
            "pyflakes": {"enabled": false},
            "pylint": {"enabled": true}
          }
        }
      }
    }
  }
```

I suspect that this issue occurs, since pylint only works on saved files. The commit message in python-language-server reads:

*This also adds an `is_saved` argument to the pyls_lint hookspec, since
pylint doesn't expose an API for operating on in-memory contents, only
files.*

Has someone else also tried this already? Is there any way to make pylint work with LSP in Sublime Text?

Best regards

Daniel

**Some additional information:**
* I tested this only on Windows 10 so far. However, I do suspect that this is no OS-dependent issue.
* I use the LSP repository instead of the Package Control release.
* The log:
```LSP: global configs ['polymer-ide=False', 'ruby=False', 'pyls=True', 'javascript-typescript-langserver=False', 'clangd=False', 'ra-lsp=False', 'ocaml=False', 'lsp-tsserver=False', 'typescript-language-server=False', 'jdtls=False', 'cquery=False', 'reason=False', 'haskell-ide-engine=False', 'phpls=False', 'gopls=False', 'dart=False', 'golsp=False', 'rls=False', 'bashls=False', 'vscode-css=False', 'eslint=False', 'flow=False', 'metals=False', 'intelephense-ls=False']
LSP: window 2 starting 1 initial views
LSP: window 2 requests pyls for C:\Users\daniel\Projekte\Python\test.py
LSP: starting in C:\Users\daniel\Projekte\Python
LSP: starting ['pyls']
LSP:  --> initialize
LSP: window 2 added session pyls
LSP:      {'capabilities': {'textDocumentSync': 2, 'referencesProvider': True, 'codeLensProvider': {'resolveProvider': False}, 'completionProvider': {'resolveProvider': False, 'triggerCharacters': ['.']}, 'documentSymbolProvider': True, 'hoverProvider': True, 'documentHighlightProvider': True, 'documentRangeFormattingProvider': True, 'documentFormattingProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(', ',']}, 'definitionProvider': True, 'experimental': {}, 'renameProvider': True, 'executeCommandProvider': {'commands': []}, 'codeActionProvider': True}}
LSP:  --> initialized
LSP:  --> textDocument/didOpen
LSP:  --> workspace/didChangeConfiguration
LSP: <--  textDocument/publishDiagnostics
LSP:      {'diagnostics': [], 'uri': 'file:///C:/Users/daniel/Projekte/Python/test.py'}
```

**Comment by tomv564** [comment]
Your logs don't include changing and saving the document, so it's hard to confirm if something is not working from the LSP side. That said, it will be very helpful to change your pyls command to `["pyls", "-vvv"]` and have the `log_server` LSP setting on `true` - then you'll see all the pyls logging as well!

**Comment by dhelonious** [comment]
Thanks for your reply. I turned on all logging. On saving I receive the following:
```
2019-06-16 15:33:46,930 UTC - DEBUG - pyls.plugins.mccabe_lint - Running mccabe lint with threshold: 15:
2019-06-16 15:33:46,930 UTC - DEBUG - pyls.config.config -   finish pyls_lint --> [[], []] [hook]:
:
2019-06-16 15:33:46,930 UTC - DEBUG - pyls_jsonrpc.endpoint - Sending notification: textDocument/publishDiagnostics {'uri': 'file:///C:/Users/daniel/Test/test.py', 'diagnostics': []}:
LSP: <--  textDocument/publishDiagnostics
LSP:      {'diagnostics': [], 'uri': 'file:///C:/Users/daniel/Test/test.py'}
LSP:  --> textDocument/didSave
2019-06-16 15:33:52,864 UTC - DEBUG - pyls_jsonrpc.endpoint - Handling notification from client {'params': {'textDocument': {'uri': 'file:///C:/Users/daniel/Test/test.py'}}, 'method': 'textDocument/didSave', 'jsonrpc': '2.0'}:
2019-06-16 15:33:53,366 UTC - DEBUG - pyls.config.config -   pyls_lint [hook]:
config: <pyls.config.config.Config object at 0x0000016A870565C0>:
workspace: <pyls.workspace.Workspace object at 0x0000016A87056550>:
document: file:///C:/Users/daniel/Test/test.py:
is_saved: True:
:
```

In the additional logging I also found that the `pylint_lint.py` plugin of the python-language-server seems to be loaded:
```
2019-06-16 15:33:30,462 UTC - INFO - pyls.config.config - Loaded pyls plugin pylint from <module 'pyls.plugins.pylint_lint' from 'c:\\users\\daniel\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pyls\\plugins\\pylint_lint.py'>:
...
2019-06-16 15:33:30,612 UTC - DEBUG - matplotlib - loaded modules: [..., 'pyls.plugins.pylint_lint', 'pylint', 'pylint.__pkginfo__', 'pylint.epylint', ...]:
```

However, pylint does not provide any diagnostics. pyflakes on the other hand works perfectly well.

**Comment by tomv564** [comment]
perhaps you can add some logging to pyls to confirm its invoking pylint as
expected.

Also, running pylint directly from the same working directory produces the
expected output?

**Comment by dhelonious** [comment]
pylint is working properly when I run it manually, so does SublimeLinter-pylint.

I will try to do some more debugging and testing with pyls when I have some leisure time again. Thanks for your help so far!

**Comment by dhelonious** [comment]
Update: I tested pylint on my linux machine and it's working properly. So this seems to be a Windows issue. I will check if this happens because of my setup. I think we can close this issue for now.
