### ISSUE TITLE
Private fields are displayed in the completion popup

### ISSUE THREAD

**Issue by RUSshy** [tomv564/LSP#616]
OS: Windows 10 - x64
Sublime Text: v3.2.1
LSP: 0.8.4 (From Package Manager)

I am using it with the D plugin: https://github.com/d-language-server/dls

Private fields are shown in the completion popup, but they shouldn't!

**Comment by RUSshy** [comment]
![sublime_text_wuTvV4VAO1](https://user-images.githubusercontent.com/18348637/59604843-9b713200-910d-11e9-963c-fb7e2d71f3b7.png)

**Comment by RUSshy** [comment]
```
_host
_port
_socket
_state
_thread
```

**Comment by rwols** [comment]
It looks like this will be fixed once DCD v0.12 is released according to the linked issue.
