### ISSUE TITLE
Sort items in completion popup

### ISSUE THREAD

**Issue by RUSshy** [tomv564/LSP#617]
OS: Windows 10 - x64
Sublime Text: v3.2.1
LSP: 0.8.4 (From Package Manager)

I am using it with the D plugin: https://github.com/d-language-server/dls

It would be nice to be able to have sorted items in the popup list

For the moment it is all A-Z, what would be nice is items sorted by Types (Variable, Functions, Keywords) just like in Jetbrains IDEs

**Comment by rwols** [comment]
The LSP CompletionItem's are sorted according to their `sortText` key. When that key is not present, they are sorted according to the `label` (which should always be present). The D language server should provide a smarter `sortText` key to present the user with more relevant completions at the top of the completion widget.

Link to the issue on the dls repo: https://github.com/d-language-server/dls/issues/51

**Comment by rwols** [comment]
I'll close this now as the discussion has been moved to the dls repo.
