### ISSUE TITLE
No completion info if typo in word

### ISSUE THREAD

**Issue by RUSshy** [tomv564/LSP#619]
OS: Windows 10 - x64
Sublime Text: v3.2.1
LSP: 0.8.4 (From Package Manager)

I am using it with the D plugin: https://github.com/d-language-server/dls

If i type the word correctly, info is shown:

![sublime_text_6F7D2rOsbT](https://user-images.githubusercontent.com/18348637/59605496-34ed1380-910f-11e9-9a38-eb27b306407b.png)

But if i make a mistake, but want to rely on auto-correct, then it don't display the info

![sublime_text_nKvQWdFJEY](https://user-images.githubusercontent.com/18348637/59605540-4c2c0100-910f-11e9-8b4e-3f349151ab18.png)

**Comment by tomv564** [comment]
The second example looks like Sublime's built-in word completions. If you only want to see completion items from the server, change the `only_show_lsp_completions` to true in the LSP settings.

**Comment by RUSshy** [comment]
ah thanks!
