### ISSUE TITLE
No completion of a class until I open it

### ISSUE THREAD

**Issue by devnix** [tomv564/LSP#621]
Hi! I'm using your plugin with the intelephense server. I'm noticing some behavours that I feel kinda strange, and I don't know if I have to check LSP or the language server.

When I try to get the autocompletion of a class it will not work at all, until I open the file which contains the class with Sublime Text. Then, the completion will work on every file. I wonder if would be expected to have the project scanned·

This is the look of the plugin when the autocompletion works, it's awesome! 

![image](https://user-images.githubusercontent.com/1777519/59828416-4450a480-933b-11e9-9fb3-5e7e36d424b6.png)

My LSP config:

```json
{
	"clients":
	{
		"intelephense-ls":
		{
			"command":
			[
				"node",
				"/usr/lib/node_modules/intelephense-server/lib/server.js",
				"--stdio"
			],
			"enabled": true,
			"initializationOptions":
			{
				"storagePath": "/tmp/intelephense"
			},
			"languageId": "php",
			"scopes":
			[
				"source.php",
				"embedding.php"
			],
			"syntaxes":
			[
				"Packages/PHP/PHP.sublime-syntax"
			]
		}
	}
}
```

**Comment by rwols** [comment]
Can you inspect the Sublime Text console to see if this LSP plugin is requesting the expected methods?

**Comment by tomv564** [comment]
Intelephense might not be scanning un-opened files from disk - it sounds like the server should be investigated.

**Comment by tomv564** [comment]
Note to avoid confusion: the UI in the screenshot is not completion, but signature help. 

Closing this now, but to follow up:
* Check the Sublime console to confirm textdocument/completion is being sent.
* Report the issue on the language server's repo.
