### ISSUE TITLE
Timing out while starting solargraph on macOs

### ISSUE THREAD

**Issue by giovdk21** [tomv564/LSP#622]
* OS and language server: macOS `10.14.5 (18F132)`, `ruby`, ST3 build: `3207`, Solargraph: `0.33.2`
* How you installed LSP: `Package Control`
* Minimal reproduction steps:

- Make sure no `ruby` process are running and that port `7658` is available
- Open sublime (from finder / dock); sublime should open with a previously saved ruby project for which the ruby LSP is enabled

Expected behaviour:
- LSP for ruby should be initialised and connection established between ST3 and Solargraph

Actual behaviour:
- ST3 becomes unresponsive until the following message pops up:

> Could not start ruby
> Timeout connecting to socket
> Server will be disabled for this window

The console shows:
```LSP: global configs ['ra-lsp=False', 'gopls=False', 'dart=False', 'golsp=False', 'typescript-language-server=False', 'pyls=False', 'vscode-css=False', 'ruby=False', 'jdtls=False', 'ocaml=False', 'clangd=False', 'phpls=False', 'javascript-typescript-langserver=False', 'flow=False', 'bashls=False', 'eslint=False', 'metals=False', 'haskell-ide-engine=False', 'reason=False', 'cquery=False', 'polymer-ide=False', 'intelephense-ls=False', 'rls=False', 'lsp-tsserver=False']
LSP: window 4 has override for ruby {'enabled': True}
LSP: window 4 starting 1 initial views
LSP: window 4 requests ruby for /abcd/code/zzzzz/zzzzz-frontend/app/models/hjkl_updater.rb
LSP: starting in /abcd/code/zzzzz/zzzzz-frontend
LSP: starting ['solargraph', 'socket']
LSP: connecting to localhost:7658
```

And if, before getting the timeout message, I check the port I get:
```
$ netstat | grep 7658
tcp4       0      0  localhost.57599        localhost.7658         SYN_SENT
```

However at this point if I quit Sublime, the ruby process is left hanging. Reopening ST3 at this point usually results in LSP to actually successfully connect to Solargraph, however this doesn't happen all the times.

**Comment by tomv564** [comment]
Don't have time to research this but #513 might be relevant - the server wants to connect to Sublime instead of sublime connecting to the server.

**Comment by giovdk21** [comment]
Thanks; I subscribed to 513.
I'll let you know in case I manage to look into this a bit further; in the meantime I might have found a possible workaround.

It seems to work if I connect using `stdio` with no `tcp_port`:

```js
// Packages/User/LSP.sublime-settings
{
	"clients":
	{
		"ruby":
		{
			"command":
			[
				"solargraph",
				"stdio"
			],
			"tcp_port": false,
		}
	}
}
```

**Comment by tomv564** [comment]
If stdio works then I will consider this issue resolved. If TCP is very desirable over stdio then we can try to prioritise the linked issue about socket lifecycle.

**Comment by HungLe14** [comment]
I'm using neovim and get this issue too. How can i fix it?
