### ISSUE TITLE
Leading colon dropped from auto-completions when accepted

### ISSUE THREAD

**Issue by taylorthurlow** [tomv564/LSP#623]
Consider this short Ruby code example:

~~~ruby
something = {}
something[:key] = "some value"
~~~

In a new line, typing `something[:k` will begin auto-suggest like so:

![Screen Shot 2019-06-21 at 8 46 55 PM](https://user-images.githubusercontent.com/761640/59959123-ebc9f600-9465-11e9-828b-a119cb7f286d.png)

Accepting this auto-complete, in my case with TAB, produces this:

~~~ruby
something = {}
something[:key] = "some value"

something[key]
~~~

Notice the lack of a colon in `[key]` - I expect `[:key]`.

I'm using [Solargraph](https://github.com/castwide/solargraph) as a language server.

### Other information
* macOS `10.13.6`
* Installed LSP through Package Control

~~I'll be opening a pull request after I open this issue.~~
The pull request: https://github.com/tomv564/LSP/pull/624

**Comment by rwols** [comment]
Fixed by https://github.com/tomv564/LSP/pull/624.
