### ISSUE TITLE
support $cquery/progress

### ISSUE THREAD

**Issue by maddanio** [tomv564/LSP#626]
cquery works relatively well, but it would be nice to see indexing progress better by having sublime lsp support the $cquery/progress message. at least i assume thats what it would do, the log keeps saying it isnt supported when sublime starts up.

**Comment by rwols** [comment]
If I understand correctly, you should be able to write a cquery-specific "LanguageHandler". You can subscribe to the `$cquery/progress$` notification in the `on_initialized` callback:

https://github.com/tomv564/LSP/blob/master/plugin/core/windows.py#L476

Here is the interface class for a LanguageHandler: https://github.com/tomv564/LSP/blob/master/plugin/core/handlers.py

Perhaps @papadokolos already has a solution (https://github.com/cquery-project/cquery/issues/525).

**Comment by papadokolos** [comment]
Sorry, I didn't implement a solution for this.

If you plan on implementing something yourself, note that cquery's development has been stopped, but it does have an actively maitained fork, created by one of cquery's main contributers:
https://github.com/MaskRay/ccls

For more information, see this issue:
https://github.com/cquery-project/cquery/issues/867

**Comment by maddanio** [comment]
ok. so would ccls work with LSP?

**Comment by tomv564** [comment]
Hope you've tried ccls since, but I suspect clangd would also be a good option - both are compatible with this package.

**Comment by maddanio** [comment]
yep, unfortunately it sometimes keeps crashing. already made an issue, but that didnt fix it. somehow the pipe between the process and sublime seems to break, but i couldnt find out why yet. will investigate further
