### ISSUE TITLE
How to implement a LanguageHandler ?

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#628]
I want to implement a language handler for jdtls, to handle one of it's extension [methods](https://github.com/eclipse/eclipse.jdt.ls/wiki/Language-Server-Protocol-Extensions), but I can't find instructions

**Comment by AmjadHD** [comment]
I think there should be more informations on "How to implement your own LanguageHandler", in fact I believe that this plugin should focus on being a framework (like SublimeLinter) rather than trying to implement every language server out there in a suboptimal manner, having plugins gives the opportunity to provide better experience for end users.

**Comment by AmjadHD** [comment]
```python

    def on_start(self, window: sublime.Window) -> bool:
        self._view = window.active_view()
        if not self._view:
            return False
        return True

    def on_initialized(self, client: Client) -> None:

        client.on_notification("language/status", self._show_status)

    def _show_status(self, report: dict):
        ...
```
is this the best way to get the view the language server is running in ?

**Comment by rwols** [comment]
> in fact I believe that this plugin should focus on being a framework (like SublimeLinter) rather than trying to implement every language server out there in a suboptimal manner

There are some ongoing attempts with this at https://github.com/sublimelsp/. These plugins focus mostly on the initial set-up. The LanguageHandler class was also initially written for set-up routines.

I don't think anybody has truly written a LanguageHandler yet that handles non-standard notifications, so you may want to change the LanguageHandler class and make a pull request with your experiences if you feel like things could be done better/simpler.

**Comment by AmjadHD** [comment]
closing this in favor of #641
