### ISSUE TITLE
Option to disable autocomplete feature

### ISSUE THREAD

**Issue by arsham** [tomv564/LSP#629]
* OS and language server
Linux/gopls
* How you installed LSP
git

I appreciate it if you would provide an option to disable the autocomplete functionality.

Thank you.

**Comment by tomv564** [comment]
Almost a duplicate of #574. 

We could let the user blacklist some capabilities in an LSP setting and filter those out of our `initialize` request, saving us the effort of creating a new setting for every feature users want to disable.

**Comment by tomv564** [comment]
There is a new `disabled_capabilities` setting, adding "completion" to the array in your LSP settings should stop LSP from contributing to Sublime's autocompletion UI.

**Comment by arsham** [comment]
Amazing work, thank you.
