### ISSUE TITLE
Missing codeActionKind entry prevents RLS init

### ISSUE THREAD

**Issue by urschrei** [tomv564/LSP#630]
* OS and language server
macOS 10.14.6, rls 1.35.0 (49efc06 2019-04-06)
* How you installed LSP (Package Control or from git?)
LSP installed from package control today
* Minimal reproduction steps
Install current stable Rust RLS, latest LSP release, enable LSP in Rust project
* Log

    [2019-06-28T16:08:36Z ERROR rls::server] dispatch error: Error { code: InvalidParams, message: "missing field `codeActionKind`", data: None }, message:

      {
      "jsonrpc": "2.0",
      "id": 1,
      "params": {
        "rootPath": "/Users/sth/dev/proj",
        "capabilities": {
          "workspace": {
            "applyEdit": true,
            "executeCommand": {},
            "didChangeConfiguration": {}
          },
          "textDocument": {
            "codeAction": {
              "dynamicRegistration": true,
              "codeActionLiteralSupport": {}
            },
            "documentSymbol": {
              "symbolKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23,
                  24,
                  25,
                  26
                ]
              }
            },
            "rangeFormatting": {},
            "rename": {},
            "completion": {
              "completionItem": {
                "snippetSupport": true
              },
              "completionItemKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18
                ]
              }
            },
            "signatureHelp": {
              "signatureInformation": {
                "parameterInformation": {
                  "labelOffsetSupport": true
                },
                "documentationFormat": [
                  "markdown",
                  "plaintext"
                ]
              }
            },
            "formatting": {},
            "references": {},
            "synchronization": {
              "didSave": true
            },
            "documentHighlight": {},
            "definition": {},
            "hover": {
              "contentFormat": [
                "markdown",
                "plaintext"
              ]
            }
          }
        },
        "processId": 39815,
        "rootUri": "file:///Users/sth/dev/proj"
      },
      "method": "initialize"}
    

This appears to be related to a missing `codeActionKind` field sent as part of the init, within `codeActionLiteralSupport`.

Per the spec and some other extant implementations, an init message containing a complete `codeKindAction` entry might look like:

    {
      "jsonrpc": "2.0",
      "id": 1,
      "params": {
        "rootPath": "/Users/sth/dev/proj",
        "capabilities": {
          "workspace": {
            "applyEdit": true,
            "executeCommand": {},
            "didChangeConfiguration": {}
          },
          "textDocument": {
            "codeAction": {
              "dynamicRegistration": true,
              "codeActionLiteralSupport": {
                "codeActionKind": {
                  "valueSet": [
                    "",
                    "quickfix",
                    "refactor",
                    "refactor.extract",
                    "refactor.inline",
                    "refactor.rewrite",
                    "source",
                    "source.organizeImports"
                  ]
                }
              }
            },
            "documentSymbol": {
              "symbolKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18,
                  19,
                  20,
                  21,
                  22,
                  23,
                  24,
                  25,
                  26
                ]
              }
            },
            "rangeFormatting": {},
            "rename": {},
            "completion": {
              "completionItem": {
                "snippetSupport": true
              },
              "completionItemKind": {
                "valueSet": [
                  1,
                  2,
                  3,
                  4,
                  5,
                  6,
                  7,
                  8,
                  9,
                  10,
                  11,
                  12,
                  13,
                  14,
                  15,
                  16,
                  17,
                  18
                ]
              }
            },
            "signatureHelp": {
              "signatureInformation": {
                "parameterInformation": {
                  "labelOffsetSupport": true
                },
                "documentationFormat": [
                  "markdown",
                  "plaintext"
                ]
              }
            },
            "formatting": {},
            "references": {},
            "synchronization": {
              "didSave": true
            },
            "documentHighlight": {},
            "definition": {},
            "hover": {
              "contentFormat": [
                "markdown",
                "plaintext"
              ]
            }
          }
        },
        "processId": 39815,
        "rootUri": "file:///Users/sth/dev/proj"
      },
      "method": "initialize"
     }

**Comment by rwols** [comment]
I think this was fixed in ada565c70425, I'm not sure if that's already released.

**Comment by urschrei** [comment]
@rwols Having a look at the diff, it looks like ada565c adds `codeAction` but not `codeActionKind` – it seems to add an empty `codeActionLiteralSupport` entry (https://github.com/tomv564/LSP/commit/ada565c70425c78dc25a24506a0bd0ccbfd0bbfc#diff-717d01587e1b2a2e5e0ed467080c2c32R139), although I may be misunderstanding, and the entry is subsequently populated?

**Comment by tomv564** [comment]
You are correct - for the initial implementation I only wanted to provide code action literal support without trying to understand what codeActionKind means for Sublime Text. 

Can you confirm if an empty array would work there ?

**Comment by urschrei** [comment]
@tomv564 Yep, let me see if adding an empty entry satisfies RLS

**Comment by urschrei** [comment]
An empty entry fixes latest stable RLS 1.35.0 (49efc06 2019-04-06)

**Comment by AmjadHD** [comment]
I think this is causing a problem for the [julia-ls](https://github.com/julia-vscode/LanguageServer.jl)
```
LSP: window 3 requests julials for D:\Downloads\Archives\language-julia-0.11.6\extension\scripts\languageserver\main.jl
LSP: starting in D:\Downloads\Archives\language-julia-0.11.6
LSP: starting ['julia', '--startup-file=no', '--history-file=no', '-e', 'using LanguageServer, Sockets, SymbolServer;server = LanguageServerInstance(stdin, stdout, false);server.runlinter = true;run(server)']
LSP:  --> initialize
LSP: window 3 added session julials
[ Info: Started symbol server:
[ Info: store set:
ERROR: KeyError: key "codeActionKind" not found:
Stacktrace::
[1] getindex at .\dict.jl:478 [inlined]:
[2] LanguageServer.CodeActionLiteralCapabilities(::Dict{String,Any}) at C:\Users\Lehdhili\.julia\dev\LanguageServer\src\protocol\protocol.jl:25 (repeats 5 times):
[3] parse_params(::Type{Val{:initialize}}, ::Dict{String,Any}) at C:\Users\Lehdhili\.julia\dev\LanguageServer\src\requests\init.jl:72:
[4] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at C:\Users\Lehdhili\.julia\dev\LanguageServer\src\jsonrpc.jl:38:
[5] run(::LanguageServerInstance) at C:\Users\Lehdhili\.julia\dev\LanguageServer\src\languageserverinstance.jl:45:
[6] top-level scope at none:0:
LSP: LSP stdout process ended.
LSP: LSP stream logger stopped.
```

**Comment by AmjadHD** [comment]
I can confirm that adding changes in #631 fixes julials.

**Comment by tomv564** [comment]
Thanks for reporting and the fix!
