### ISSUE TITLE
A certain signatureHelp freezes sublime

### ISSUE THREAD

**Issue by karolyi** [tomv564/LSP#632]
Hey,

* I'm on WSL (Windows 10)/Ubuntu 18.04.2, and it seems a certain `signatureHelp` response makes sublime freeze completely.
* I'm on the latest sublime 3 dev.
* LSP installed from package
* Do a `signatureHelp` on a `Textfield` of `Django==1.11.21`

```
LSP:  --> textDocument/signatureHelp
LSP:      {'signatures': [{'documentation': '', 'parameters': [{'documentation': None, 'label': 'verbose_name'}, {'documentation': None, 'label': 'name'}, {'documentation': None, 'label': 'primary_key'}, {'documentation': None, 'label': 'max_length'}, {'documentation': None, 'label': 'unique'}, {'documentation': None, 'label': 'blank'}, {'documentation': None, 'label': 'null'}, {'documentation': None, 'label': 'db_index'}, {'documentation': None, 'label': 'rel'}, {'documentation': None, 'label': 'default'}, {'documentation': None, 'label': 'editable'}, {'documentation': None, 'label': 'serialize'}, {'documentation': None, 'label': 'unique_for_date'}, {'documentation': None, 'label': 'unique_for_month'}, {'documentation': None, 'label': 'unique_for_year'}, {'documentation': None, 'label': 'choices'}, {'documentation': None, 'label': 'help_text'}, {'documentation': None, 'label': 'db_column'}, {'documentation': None, 'label': 'db_tablespace'}, {'documentation': None, 'label': 'auto_created'}, {'documentation': None, 'label': 'validators'}, {'documentation': None, 'label': 'error_messages'}], 'label': ''}], 'activeParameter': 9, 'activeSignature': 0}
```

This response makes sublime go totally bonkers, eating up 100% CPU. I got lucky to be able to copy this debug message out of the console. Nothing else helps but killing sublime.

Here's a `signatureHelp` for another field that's displayed correctly:

```
LSP:  --> textDocument/signatureHelp
LSP:      {'signatures': [{'documentation': "Create a model's table.", 'parameters': [{'documentation': None, 'label': 'name'}, {'documentation': None, 'label': 'fields'}, {'documentation': None, 'label': 'options'}, {'documentation': None, 'label': 'bases'}, {'documentation': None, 'label': 'managers'}], 'label': 'CreateModel(self, name, fields, options=None, bases=None, managers=None)'}], 'activeParameter': 1, 'activeSignature': 0}
```

**Comment by tomv564** [comment]
Great you could share the example, it should be all we need to fix the hang.

If I'm reading the response correctly, it's a signature with an empty string as label, but 22 possible parameters. I wouldn't expect an empty label (at least `Textfield()`), perhaps you want to investigate why the server (python language server?) would send no label?

Amusingly, parsing and formatting this signature results in a string with more than 155603016 chars - this is probably what chokes Sublime.

**Comment by karolyi** [comment]
> Amusingly, parsing and formatting this signature results in a string with more than 155603016 chars

I have no idea how such a thing can happen but thank you for fixing it :)
When can I expect a release to test locally? Just fired up sublime, no update yet.
