### ISSUE TITLE
add an option to prevent starting language servers in transient views

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#633]
when opening a preview of a file, some (including me) may not be interested in language services, in fact launching language servers could be annoying especially for slow-starting ones, and when previewing many files in a short period, like when opening files with <kbd>ctrl</kbd>+<kbd>p</kbd> or when opening definitions with sublime's goto definitions command.

**Comment by tomv564** [comment]
I expect LSP already to be doing this - the only events that should start a language server (via `on_view_activated`) are `on_activated_async` and `on_load_async`. Those are both checked for `not is_transient_view` in DocumentSyncListener.

Can you verify why your views are bypassing this check by adding some logging to DocumentSyncListener?

It looks like a freshly opened window *will* try to start a server for transient views, see `start_active_views` in WindowManager. But I doubt this is the problem?

**Comment by AmjadHD** [comment]
> Can you verify why your views are bypassing this check by adding some logging to DocumentSyncListener?

I did:
```python
def is_transient_view(view: sublime.View) -> bool:
    window = view.window()
    if window:
        if window.get_view_index(view)[1] == -1:
            return True  # Quick panel transient views
        tv = window.transient_view_in_group(window.active_group())
        is_transient = view == tv
        print("LSP: is_transient:", is_transient, view.id(), tv.id() if tv is not None else tv)
        return is_transient
    else:
        return True
```
Apparently the problem is with `window.transient_view_in_group()` it always returns `None` for me, maybe an ST bug ?
By the way quick panel transient views are detected correctly.

**Comment by tomv564** [comment]
So to update this issue:
* Views from quick panel (ctrl+p): Correctly detected as transient.
* Views from goto definition: Open as normal files for me?
* Views opened from single-clicking files in sidebar: These are undetectable? (https://forum.sublimetext.com/t/on-load-induced-by-preview-in-goto-anything/6931/7)

If you can confirm this is what you're seeing as well, then I'm afraid there's little we can do without sublime api improvements.

**Comment by SpaceManiac** [comment]
I'm having what may be a related issue where the language server is not sent a `textDocument/didOpen` when a view changes from transient to not transient. Does this fall under the same umbrella or would you rather I file separately?

**Comment by tomv564** [comment]
Can you describe how you got your transient view? Quick panel? Side bar? The file does trigger a didOpen when opened another way?

**Comment by tomv564** [comment]
Please share if more knowledge / api improvements make it possible to detect more types of transient views.
