### ISSUE TITLE
Gets slower the more files are opened

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#637]
* OS: MacOS
* Language server: lsp-tsserver
* Package Control install

It might be specific to `lsp-tsserver` but it seems that `LSP: <--  textDocument/publishDiagnostics` messages are triggered for every file that I've opened in the editor in the same session. So if I open 30 files and then edit 31st file, I see that message being triggered 30 (or 31) times. And I might get diagnostics for that 31st file as 20th message (for example) which means diagnostics for currently being edited file can be very delayed.

I can investigate some more to see if that's expected but wanted to pass it through you to see if you know of that behaviour.

**Comment by rchl** [comment]
Also we get the same messages on each key press in the document so responsiveness of diagnostics suffer and also my computer's CPU gets quite busy.

**Comment by tomv564** [comment]
This is probably an `lsp-tsserver` issue but it's possible other servers can inflict this on LSP.
It's possible that all 31 files are affected by the edit in the 31st file - lsp-tsserver probably doesn't know that 30 files were unaffected - and doesn't check if diagnostics changed before sending them.

Alternatively, LSP could be doing too much work per notification, and should instead wait a bit longer to update UI so it can get all 31 messages before doing the update.

Have you had a chance to try another javascript / typescript server ? Would be really helpful for choosing which project to improve on :)

**Comment by rchl** [comment]
I've tried `typescript-language-server` now instead and saw the same issue.

So I've looked at the code of that server and figured out that it's typescript (tsserver) itself triggering those events (`suggestionDiag`, `semanticDiag`, `syntaxDiag`) for previously seen files.

I think typescript triggers those from this place:
https://github.com/microsoft/TypeScript/blob/f1c781fa138f67b641b26391b2574974e396fe67/src/server/session.ts#L673
and `typescript-language-server` handles those here:
https://github.com/theia-ide/typescript-language-server/blob/6faea64ba5b0c748601197fa4db309e83b838fb0/server/src/lsp-server.ts#L867

So it seems to be per design. I haven't investigated further to check the reasoning and if there is a way to do something differently to avoid that behaviour. Typescript codebase is too massive to figure it out quickly.

**Comment by tomv564** [comment]
Thanks for investigating, we can do little about the calculation of diagnostics here. In your example, can you determine if LSP itself is taking a long time to process 30 diagnostics messages, or if it's purely time from the language server? Otherwise I'd like to close this issue (or move it to a well-maintained typescript server repo)

**Comment by rchl** [comment]
Feel free to close. If I it would be a bigger annoyence for me, I would ask about that on typescript server repo, but honestly it is not that much of an issue.
