### ISSUE TITLE
Signature Help height too short (need to scroll)

### ISSUE THREAD

**Issue by FHTheron** [tomv564/LSP#646]
I am not sure if this is SublimeText or LSP. The popup cuts off after about two lines.

* Ubuntu, ccls
* Package Control or git (both do the same)
* Create a function with many long parameters.

![Screenshot from 2019-07-08 15-11-41](https://user-images.githubusercontent.com/16208294/60887754-6d3aca00-a255-11e9-83e6-3aff595c57eb.png)

**Comment by AmjadHD** [comment]
possible duplicate of #486

**Comment by tomv564** [comment]
Closing duplicate, please follow the linked issue  for updates :)
