### ISSUE TITLE
Geting Started instruction does not work (macOS)

### ISSUE THREAD

**Issue by PerMildner** [tomv564/LSP#647]
Your issue may have been solved already - please search before creating new!

Troubleshooting guide: https://lsp.readthedocs.io/en/latest/#troubleshooting

**The above troubleshooting link is broken**

Chat: https://gitter.im/SublimeLSP

Is it a language server problem? The LSP package can do little to prevent slowness or missing content - please check their support materials!

Please include in your report:

* OS and language server

macOS 10.14.5 (18F203)

That this all fails long before the actual language server becomes relevant.

* How you installed LSP (Package Control or from git?)

"run Package Control: Install Package, then select LSP" as described under Installation [Stable Version](https://github.com/tomv564/LSP#stable-version).

It seems to be doing something, and then finishes with no obvious feedback.
* Minimal reproduction steps

Install LSP as above, quit and start Sublime Text.
Now [Getting Started](https://github.com/tomv564/LSP#getting-started) says "Enable the server by running LSP: Enable Language Server from the command palette", but there is nothing like that in the command palette.

The Sublime Text version is not copyable from its about box. I downloaded and installed it today.

* Log

I do not know how to obtain a log. That would be nice to describe in the issue template.

Requesting a feature?

Please read https://github.com/tomv564/LSP/blob/master/CONTRIBUTING.md. Specifically, LSP avoids building functionality that does not exist in Sublime Text, or that serves only one language.

**Comment by rwols** [comment]
> I do not know how to obtain a log. That would be nice to describe in the issue template.

Open the Sublime Text console (View --> Show Console)

Copy the entire content on your clipboard.
Paste the entire content here in spoiler tags.

```
<details>
  <summary>Click to expand my Sublime Text log</summary>
  the content of the log
</details>
```

**Comment by PerMildner** [comment]
I removed the Sublime Text.app and removed all related files I could find:
```
cd ~
rm -rf './Library/Application Support/CrashReporter/Sublime Text_2E418004-9C49-5D1F-A8E5-04FFDC09B1E1.plist' 
rm -rf './Library/Saved Application State/com.sublimetext.3.savedState'
rm -rf './Library/Caches/com.sublimetext.3'
rm -rf './Library/Application Support/Sublime Text 3'

```
(I had several cases both before and after reinstalling where Sublime Text did not respond and used a lot of CPU. Force quitting and relaunching seemed to help.)

Then I followed the instruction. After installing LSP there is some output to the log but no visible feedback. When I try to do "Packacke Control: LSP" there is nothing matching LSP in the command palette.

(The instructions at  [Stable Version](https://github.com/tomv564/LSP#stable-version) is missing the step: "Install Package Control".)

<details>
   <summary>Click to expand my Sublime Text log</summary>
startup, version: 3207 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/perm/Library/Application Support/Sublime Text 3/Packages
state path: /Users/perm/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/perm/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 4.60891
using gpu buffer for window
startup time: 4.67876
environment variables loaded using: /bin/bash -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
plugins loaded
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading settings Packages/Package Control/Package Control.sublime-settings
reloading plugin 0_package_control_loader.00-package_control
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Exported certificate: Common Name: AffirmTrust Networking, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: StartCom Certification Authority, Organizational Unit: Secure Digital Certificate Signing, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Organizational Unit: Go Daddy Class 2 Certification Authority; Organization: The Go Daddy Group, Inc.; Country: US
Package Control: Exported certificate: Common Name: TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1, Organizational Unit: Kamu Sertifikasyon Merkezi - Kamu SM, Organization: Turkiye Bilimsel ve Teknolojik Arastirma Kurumu - TUBITAK, Locality: Gebze - Kocaeli, Country: TR
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Certplus Root CA G1, Organization: Certplus, Country: FR
Package Control: Exported certificate: Common Name: UTN-USERFirst-Client Authentication and Email, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: CFCA EV ROOT, Organization: China Financial Certification Authority, Country: CN
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Common Name: SSL.com EV Root Certification Authority RSA R2, Organization: SSL Corporation, Locality: Houston, State/Province: Texas, Country: US
Package Control: Exported certificate: Common Name: T-TeleSec GlobalRoot Class 3, Organizational Unit: T-Systems Trust Center, Organization: T-Systems Enterprise Services GmbH, Country: DE
Package Control: Exported certificate: Common Name: T-TeleSec GlobalRoot Class 2, Organizational Unit: T-Systems Trust Center, Organization: T-Systems Enterprise Services GmbH, Country: DE
Package Control: Exported certificate: Common Name: UCA Root, Organization: UniTrust, Country: CN
Package Control: Exported certificate: Common Name: Staat der Nederlanden EV Root CA, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Organization: Government Root Certification Authority, Country: TW
Package Control: Exported certificate: Common Name: Certum Trusted Network CA 2, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Common Name: Deutsche Telekom Root CA 2, Organizational Unit: T-TeleSec Trust Center, Organization: Deutsche Telekom AG, Country: DE
Package Control: Exported certificate: Common Name: Secure Global CA, Organization: SecureTrust Corporation, Country: US
Package Control: Exported certificate: Common Name: VeriSign Class 1 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: AddTrust External CA Root, Organizational Unit: AddTrust External TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Email Address: info@e-szigno.hu, Common Name: Microsec e-Szigno Root CA 2009, Organization: Microsec Ltd., Locality: Budapest, Country: HU
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Autoridad de Certificacion Firmaprofesional CIF A62634068, Country: ES
Package Control: Exported certificate: Common Name: Network Solutions Certificate Authority, Organization: Network Solutions L.L.C., Country: US
Package Control: Exported certificate: Common Name: OpenTrust Root CA G1, Organization: OpenTrust, Country: FR
Package Control: Exported certificate: Organizational Unit: Security Communication EV RootCA1; Organization: SECOM Trust Systems CO.,LTD.; Country: JP
Package Control: Exported certificate: Common Name: Global Chambersign Root, Organizational Unit: http://www.chambersign.org, Organization: AC Camerfirma SA CIF A82743287, Country: EU
Package Control: Exported certificate: Common Name: DigiCert High Assurance EV Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: SSL.com Root Certification Authority ECC, Organization: SSL Corporation, Locality: Houston, State/Province: Texas, Country: US
Package Control: Exported certificate: Common Name: ComSign CA, Organization: ComSign, Country: IL
Package Control: Exported certificate: Common Name: Entrust.net Certification Authority (2048); Organizational Unit: (c) 1999 Entrust.net Limited, www.entrust.net/CPS_2048 incorp. by ref. (limits liab.); Organization: Entrust.net
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G3, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - EC1; Organizational Unit: (c) 2012 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: COMODO Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: SwissSign Gold Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Organizational Unit: Security Communication RootCA1, Organization: SECOM Trust.net, Country: JP
Package Control: Exported certificate: Email Address: acraiz@suscerte.gob.ve, Organizational Unit: Superintendencia de Servicios de Certificacion Electronica, Organization: Sistema Nacional de Certificacion Electronica, State/Province: Distrito Capital, Locality: Caracas, Country: VE, Common Name: Autoridad de Certificacion Raiz del Estado Venezolano
Package Control: Exported certificate: Common Name: VeriSign Class 2 Public Primary Certification Authority - G3; Organizational Unit: (c) 1999 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: TrustCor RootCert CA-1, Organizational Unit: TrustCor Certificate Authority, Organization: TrustCor Systems S. de R.L., Locality: Panama City, State/Province: Panama, Country: PA
Package Control: Exported certificate: Common Name: Cisco Root CA 2048, Organization: Cisco Systems
Package Control: Exported certificate: Common Name: SecureTrust CA, Organization: SecureTrust Corporation, Country: US
Package Control: Exported certificate: Common Name: Visa eCommerce Root, Organizational Unit: Visa International Service Association, Organization: VISA, Country: US
Package Control: Exported certificate: Common Name: ApplicationCA2 Root, Organizational Unit: GPKI, Organization: Japanese Government, Country: JP
Package Control: Exported certificate: Common Name: ComSign Global Root CA, Organization: ComSign Ltd., Country: IL
Package Control: Exported certificate: Common Name: StartCom Certification Authority G2, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Common Name: GDCA TrustAUTH R5 ROOT; Organization: GUANG DONG CERTIFICATE AUTHORITY CO.,LTD.; Country: CN
Package Control: Exported certificate: Common Name: XRamp Global Certification Authority, Organization: XRamp Security Services Inc, Organizational Unit: www.xrampsecurity.com, Country: US
Package Control: Exported certificate: Common Name: USERTrust ECC Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 2 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: Chambers of Commerce Root, Organizational Unit: http://www.chambersign.org, Organization: AC Camerfirma SA CIF A82743287, Country: EU
Package Control: Exported certificate: Organizational Unit: I.CA - Accredited Provider of Certification Services; Organization: První certifikační autorita, a.s.; Common Name: I.CA - Qualified Certification Authority, 09/2009; Country: CZ
Package Control: Exported certificate: Common Name: GTS Root R3, Organization: Google Trust Services LLC, Country: US
Package Control: Exported certificate: Common Name: Staat der Nederlanden Root CA - G2, Organization: Staat der Nederlanden, Country: NL
Package Control: Exported certificate: Common Name: OISTE WISeKey Global Root GB CA, Organizational Unit: OISTE Foundation Endorsed, Organization: WISeKey, Country: CH
Package Control: Exported certificate: Common Name: TWCA Root Certification Authority, Organizational Unit: Root CA, Organization: TAIWAN-CA, Country: TW
Package Control: Exported certificate: Common Name: ISRG Root X1, Organization: Internet Security Research Group, Country: US
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign ECC Root CA - R4
Package Control: Exported certificate: Common Name: Certinomis - Root CA, Organizational Unit: 0002 433998903, Organization: Certinomis, Country: FR
Package Control: Exported certificate: Common Name: Certigna, Organization: Dhimyotis, Country: FR
Package Control: Exported certificate: Common Name: DigiCert Global Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Actalis Authentication Root CA, Organization: Actalis S.p.A./03358520967, Locality: Milan, Country: IT
Package Control: Exported certificate: Common Name: UTN-USERFirst-Hardware, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: GeoTrust Global CA, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: TeliaSonera Root CA v1, Organization: TeliaSonera
Package Control: Exported certificate: Common Name: Amazon Root CA 2, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: UCA Global Root, Organization: UniTrust, Country: CN
Package Control: Exported certificate: Common Name: GTS Root R1, Organization: Google Trust Services LLC, Country: US
Package Control: Exported certificate: Common Name: Baltimore CyberTrust Root, Organizational Unit: CyberTrust, Organization: Baltimore, Country: IE
Package Control: Exported certificate: Common Name: Swisscom Root CA 1, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority; Organizational Unit: (c) 2006 Entrust, Inc., www.entrust.net/CPS is incorporated by reference; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: D-TRUST Root CA 3 2013, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: VeriSign Universal Root Certification Authority; Organizational Unit: (c) 2008 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Class 2 Primary CA, Organization: Certplus, Country: FR
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G5; Organizational Unit: (c) 2006 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: Visa Information Delivery Root CA, Organizational Unit: Visa International Service Association, Organization: VISA, Country: US
Package Control: Exported certificate: Common Name: OISTE WISeKey Global Root GA CA; Organizational Unit: OISTE Foundation Endorsed, Copyright (c) 2005; Organization: WISeKey; Country: CH
Package Control: Exported certificate: Common Name: CA Disig Root R2, Organization: Disig a.s., Locality: Bratislava, Country: SK
Package Control: Exported certificate: Email Address: pki@sk.ee, Common Name: EE Certification Centre Root CA, Organization: AS Sertifitseerimiskeskus, Country: EE
Package Control: Exported certificate: Common Name: Buypass Class 3 Root CA, Organization: Buypass AS-983163327, Country: NO
Package Control: Exported certificate: Common Name: COMODO ECC Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: IdenTrust Commercial Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Organizational Unit: Trustis FPS Root CA, Organization: Trustis Limited, Country: GB
Package Control: Exported certificate: Common Name: DigiCert Global Root G3, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority - G3, Organizational Unit: (c) 2008 GeoTrust Inc. - For authorized use only, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root G3, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Swisscom Root EV CA 2, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: Certum Trusted Network CA, Organizational Unit: Certum Certification Authority, Organization: Unizeto Technologies S.A., Country: PL
Package Control: Exported certificate: Common Name: USERTrust RSA Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Commercial, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Premium ECC, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: Hellenic Academic and Research Institutions RootCA 2011, Organization: Hellenic Academic and Research Institutions Cert. Authority, Country: GR
Package Control: Exported certificate: Common Name: Sonera Class2 CA, Organization: Sonera, Country: FI
Package Control: Exported certificate: Common Name: Amazon Root CA 4, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: AffirmTrust Premium, Organization: AffirmTrust, Country: US
Package Control: Exported certificate: Common Name: Izenpe.com, Organization: IZENPE S.A., Country: ES
Package Control: Exported certificate: Common Name: Admin-Root-CA; Organizational Unit: Certification Authorities, Services; Organization: admin; Country: ch
Package Control: Exported certificate: Common Name: GlobalSign Root CA, Organizational Unit: Root CA, Organization: GlobalSign nv-sa, Country: BE
Package Control: Exported certificate: Common Name: E-Tugra Certification Authority, Organizational Unit: E-Tugra Sertifikasyon Merkezi, Organization: E-Tuğra EBG Bilişim Teknolojileri ve Hizmetleri A.Ş., Locality: Ankara, Country: TR
Package Control: Exported certificate: Common Name: StartCom Certification Authority, Organizational Unit: Secure Digital Certificate Signing, Organization: StartCom Ltd., Country: IL
Package Control: Exported certificate: Common Name: OpenTrust Root CA G2, Organization: OpenTrust, Country: FR
Package Control: Exported certificate: Organizational Unit: AC RAIZ FNMT-RCM, Organization: FNMT-RCM, Country: ES
Package Control: Exported certificate: Common Name: Hellenic Academic and Research Institutions ECC RootCA 2015, Organization: Hellenic Academic and Research Institutions Cert. Authority, Locality: Athens, Country: GR
Package Control: Exported certificate: Common Name: GTS Root R4, Organization: Google Trust Services LLC, Country: US
Package Control: Exported certificate: Common Name: SwissSign Platinum CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: ANF Global Root CA, Serial Number: G63287510, Email Address: info@anf.es, Organizational Unit: ANF Clase 1 CA, Organization: ANF Autoridad de Certificacion, Locality: Barcelona (see current address at http://www.anf.es/es/address-direccion.html ), State/Province: Barcelona, Country: ES
Package Control: Exported certificate: Common Name: Starfield Services Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Organizational Unit: certSIGN ROOT CA, Organization: certSIGN, Country: RO
Package Control: Exported certificate: Common Name: QuoVadis Root CA 3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: SZAFIR ROOT CA, Organization: Krajowa Izba Rozliczeniowa S.A., Country: PL
Package Control: Exported certificate: Common Name: OpenTrust Root CA G3, Organization: OpenTrust, Country: FR
Package Control: Exported certificate: Common Name: Buypass Class 2 Root CA, Organization: Buypass AS-983163327, Country: NO
Package Control: Exported certificate: Common Name: GTS Root R2, Organization: Google Trust Services LLC, Country: US
Package Control: Exported certificate: Common Name: Apple Root CA - G2, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Organizational Unit: ePKI Root Certification Authority; Organization: Chunghwa Telecom Co., Ltd.; Country: TW
Package Control: Exported certificate: Common Name: Global Chambersign Root - 2008, Organization: AC Camerfirma S.A., Serial Number: A82743287, Locality: Madrid (see current address at www.camerfirma.com/address), Country: EU
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority - G2, Organizational Unit: (c) 2007 GeoTrust Inc. - For authorized use only, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: Certum CA, Organization: Unizeto Sp. z o.o., Country: PL
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R3
Package Control: Exported certificate: Common Name: DigiCert Assured ID Root CA, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: Echoworx Root CA2, Organizational Unit: Certification Services, Organization: Echoworx Corporation, Locality: Toronto, State/Province: Ontario, Country: CA
Package Control: Exported certificate: Common Name: DST Root CA X3, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Common Name: CA Disig Root R1, Organization: Disig a.s., Locality: Bratislava, Country: SK
Package Control: Exported certificate: Common Name: AAA Certificate Services, Organization: Comodo CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: QuoVadis Root CA 3 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: Chambers of Commerce Root - 2008, Organization: AC Camerfirma S.A., Serial Number: A82743287, Locality: Madrid (see current address at www.camerfirma.com/address), Country: EU
Package Control: Exported certificate: Common Name: Hellenic Academic and Research Institutions RootCA 2015, Organization: Hellenic Academic and Research Institutions Cert. Authority, Locality: Athens, Country: GR
Package Control: Exported certificate: Common Name: Certplus Root CA G2, Organization: Certplus, Country: FR
Package Control: Exported certificate: Common Name: COMODO RSA Certification Authority, Organization: COMODO CA Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB
Package Control: Exported certificate: Common Name: AddTrust Class 1 CA Root, Organizational Unit: AddTrust TTP Network, Organization: AddTrust AB, Country: SE
Package Control: Exported certificate: Common Name: Swisscom Root CA 2, Organizational Unit: Digital Certificate Services, Organization: Swisscom, Country: ch
Package Control: Exported certificate: Common Name: Certinomis - Autorité Racine, Organizational Unit: 0002 433998903, Organization: Certinomis, Country: FR
Package Control: Exported certificate: Common Name: DST Root CA X4, Organization: Digital Signature Trust Co.
Package Control: Exported certificate: Common Name: DigiCert Global Root G2, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Common Name: SwissSign Silver Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: Apple Root CA, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root Certification Authority, Organizational Unit: Root Certification Authority, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: SwissSign Platinum Root CA - G3, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: GeoTrust Primary Certification Authority, Organization: GeoTrust Inc., Country: US
Package Control: Exported certificate: Common Name: SSL.com EV Root Certification Authority ECC, Organization: SSL Corporation, Locality: Houston, State/Province: Texas, Country: US
Package Control: Exported certificate: Common Name: TWCA Global Root CA, Organizational Unit: Root CA, Organization: TAIWAN-CA, Country: TW
Package Control: Exported certificate: Common Name: Entrust Root Certification Authority - G2; Organizational Unit: (c) 2009 Entrust, Inc. - for authorized use only, See www.entrust.net/legal-terms; Organization: Entrust, Inc.; Country: US
Package Control: Exported certificate: Common Name: Starfield Root Certificate Authority - G2; Organization: Starfield Technologies, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Organizational Unit: Starfield Class 2 Certification Authority; Organization: Starfield Technologies, Inc.; Country: US
Package Control: Exported certificate: Common Name: Amazon Root CA 3, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: UTN - DATACorp SGC, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: KISA RootCA 1, Organizational Unit: Korea Certification Authority Central, Organization: KISA, Country: KR
Package Control: Exported certificate: Common Name: Symantec Class 1 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign ECC Root CA - R5
Package Control: Exported certificate: Common Name: QuoVadis Root CA 2, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: Izenpe.com, Organization: IZENPE S.A., Country: ES
Package Control: Exported certificate: Common Name: TRUST2408 OCES Primary CA, Organization: TRUST2408, Country: DK
Package Control: Exported certificate: Common Name: SwissSign Silver CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: NetLock Arany (Class Gold) Főtanúsítvány, Organizational Unit: Tanúsítványkiadók (Certification Services), Organization: NetLock Kft., Locality: Budapest, Country: HU
Package Control: Exported certificate: Common Name: TrustCor RootCert CA-2, Organizational Unit: TrustCor Certificate Authority, Organization: TrustCor Systems S. de R.L., Locality: Panama City, State/Province: Panama, Country: PA
Package Control: Exported certificate: Common Name: D-TRUST Root Class 3 CA 2 2009, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: VRK Gov. Root CA; Organizational Unit: Varmennepalvelut, Certification Authority Services; Organization: Vaestorekisterikeskus CA; State/Province: Finland; Country: FI
Package Control: Exported certificate: Common Name: Hongkong Post Root CA 1, Organization: Hongkong Post, Country: HK
Package Control: Exported certificate: Common Name: GlobalSign, Organization: GlobalSign, Organizational Unit: GlobalSign Root CA - R2
Package Control: Exported certificate: Common Name: Belgium Root CA2, Country: BE
Package Control: Exported certificate: Common Name: Amazon Root CA 1, Organization: Amazon, Country: US
Package Control: Exported certificate: Common Name: TrustCor ECA-1, Organizational Unit: TrustCor Certificate Authority, Organization: TrustCor Systems S. de R.L., Locality: Panama City, State/Province: Panama, Country: PA
Package Control: Exported certificate: Common Name: D-TRUST Root Class 3 CA 2 EV 2009, Organization: D-Trust GmbH, Country: DE
Package Control: Exported certificate: Common Name: Symantec Class 2 Public Primary Certification Authority - G6, Organizational Unit: Symantec Trust Network, Organization: Symantec Corporation, Country: US
Package Control: Exported certificate: Common Name: SwissSign Gold CA - G2, Organization: SwissSign AG, Country: CH
Package Control: Exported certificate: Common Name: Apple Root CA - G3, Organizational Unit: Apple Certification Authority, Organization: Apple Inc., Country: US
Package Control: Exported certificate: Common Name: thawte Primary Root CA; Organizational Unit: (c) 2006 thawte, Inc. - For authorized use only, Certification Services Division; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: Go Daddy Root Certificate Authority - G2; Organization: GoDaddy.com, Inc.; Locality: Scottsdale; State/Province: Arizona; Country: US
Package Control: Exported certificate: Common Name: Apple Root Certificate Authority; Organizational Unit: Apple Computer Certificate Authority; Organization: Apple Computer, Inc.; Country: US
Package Control: Exported certificate: Common Name: SSL.com Root Certification Authority RSA, Organization: SSL Corporation, Locality: Houston, State/Province: Texas, Country: US
Package Control: Exported certificate: Common Name: QuoVadis Root CA 1 G3, Organization: QuoVadis Limited, Country: BM
Package Control: Exported certificate: Common Name: UTN-USERFirst-Object, Organizational Unit: http://www.usertrust.com, Organization: The USERTRUST Network, Locality: Salt Lake City, State/Province: UT, Country: US
Package Control: Exported certificate: Common Name: DigiCert Trusted Root G4, Organizational Unit: www.digicert.com, Organization: DigiCert Inc, Country: US
Package Control: Exported certificate: Organizational Unit: Security Communication RootCA2; Organization: SECOM Trust Systems CO.,LTD.; Country: JP
Package Control: Exported certificate: Common Name: IdenTrust Public Sector Root CA 1, Organization: IdenTrust, Country: US
Package Control: Exported certificate: Common Name: Atos TrustedRoot 2011, Organization: Atos, Country: DE
Package Control: Exported certificate: Common Name: VeriSign Class 3 Public Primary Certification Authority - G4; Organizational Unit: (c) 2007 VeriSign, Inc. - For authorized use only, VeriSign Trust Network; Organization: VeriSign, Inc.; Country: US
Package Control: Exported certificate: Common Name: thawte Primary Root CA - G3; Organizational Unit: (c) 2008 thawte, Inc. - For authorized use only, Certification Services Division; Organization: thawte, Inc.; Country: US
Package Control: Exported certificate: Common Name: ComSign Secured CA, Organization: ComSign, Country: IL
ignored packages updated to: ["LSP", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' has successfully been installed or updated
Package Control: The dependency 'python-markdown' is not currently installed; installing...
Package Control: The dependency 'python-markdown' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' is not available
Package Control: The dependency 'python-jinja2' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
</details>

I do not know why the expanded details show the entire log on one line, that is not how I entered it.

**Comment by rwols** [comment]
It looks like python-jinja2 is not getting installed. Perhaps this is the same problem as https://github.com/tomv564/LSP/issues/643?

**Comment by rwols** [comment]
I'm assuming this was the same issue as the one linked in my comment above.
