### ISSUE TITLE
yaml-language-server initialize failed

### ISSUE THREAD

**Issue by jfcherng** [tomv564/LSP#649]
I am trying to use [yaml-language-server](https://github.com/redhat-developer/yaml-language-server) but LSP simply shows `LSP: Request initialize failed with message: Cannot read property 'dynamicRegistration' of undefined` in ST's console.

# Configuration

```js
"yaml-lsp": {
    // https://github.com/redhat-developer/yaml-language-server
    // yarn global add yaml-language-server
    "enabled": true,
    "command": [
        "yaml-language-server",
        "--stdio",
    ],
    "scopes": ["source.yaml"],
    "syntaxes": ["Packages/YAML/YAML.sublime-syntax"],
    "languageId": "yaml",
},
```

# Log

```
LSP: starting ['yaml-language-server.cmd', '--stdio']
LSP:  --> initialize
LSP: window 2 added session yaml-lsp
LSP:      None
LSP: Request initialize failed with message: Cannot read property 'dynamicRegistration' of undefined
```

**Comment by tomv564** [comment]
Ah, we didn't announce our support for `workspace/symbol`, which is an optional field they hardcoded a check for 'dynamicRegistration' through:  https://github.com/redhat-developer/yaml-language-server/blob/06929e3849bbfe3a6b2cf512ccd1061a1cc26a89/src/server.ts#L348

Will add the client capability now.
