### ISSUE TITLE
orphan processes after sublime text is closed

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#65]
If a server is in busy (e.g., Julia language server may takes up to minutes to start up), I notice that LSP doesn't close all the subprocesses when sublime text is closed. It may be related to https://github.com/SublimeTextIssues/Core/issues/10

**Comment by tomv564** [comment]
Could it be that the client for Julia is not stored in the clients-per-window lookup until it has started?
Is there a project that takes a long time to start up I can try this on?

**Comment by randy3k** [comment]
I would point you to a julia project if you are interested into it.

In general, we may have a mechanism to check if a subprocess becomes orphan. Like what I did for the julia server https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/177

**Comment by randy3k** [comment]
After much experiments, I conclude that it is rather an issue of Julia. I will close it for now.
