### ISSUE TITLE
General mechanism for making LSP-applicable Key Bindings conditional

### ISSUE THREAD

**Issue by frou** [tomv564/LSP#651]
Say that in a keymap file such as `Packages/User/Default.sublime-keymap`, I want to express that a key combination should do one thing normally, but something different if the file I'm editing has LSP active...

Is there a better way to do that than the following which I came up with?

```json
{"keys": ["alt+r"], "command": "foo"},
{"keys": ["alt+r"], "command": "bar", "context": [{"key": "using_lsp"}]},
```

```python
class UsingLspCorroborator(sublime_plugin.ViewEventListener):
    def on_query_context(self, key, _, __, ___):
        if key == "using_lsp":
            return self.view.settings().get("lsp_language") is not None
```

**Comment by tomv564** [comment]
Yes, your solution avoids importing any LSP code, so that's probably preferable. I'll try not to rename  `lsp_language` 😀

**Comment by frou** [comment]
It seems this would be possible without the EventListener by using a context name with the undocumented `setting.` prefix:

```json
{"keys": ["alt+r"], "command": "foo"},
{"keys": ["alt+r"], "command": "bar", "context": [{"key": "setting.lsp_language"}]},
```

But because the value of `lsp_language` is a `dict` rather than a `bool`, that doesn't work. What do you think about setting an additional view setting (say, `lsp_active` to `True`) at the same time as setting `lsp_language`? Then users (and perhaps also some default LSP key bindings) could do it that way.

The current advice (I think I proposed it in #78) is to use a `selector` context along with a whitelist of language scopes, but it's a hassle for the user to have to maintain those whitelists.

**Comment by roblav96** [comment]
👍 Bump upvote this one huge time =]

**Comment by tomv564** [comment]
I verified @frou's approach works, so `lsp_active` (true) is now added as a view setting once opened as an LSP document.

We could apply this to the default keybindings, but we can use another issue for that :)
