### ISSUE TITLE
LSP languageId member is not documented

### ISSUE THREAD

**Issue by PerMildner** [tomv564/LSP#663]
https://lsp.readthedocs.io/en/latest/#other says:
```
languageId - used both by the language servers and to select a syntax highlighter for sublime popups.
```
but I cannot find any mention of `languageId` anywhere else. In particular no member with that name seems to be present in the various language packages.

So, it is unclear how to determine or define a `languageId` for an existing or new language.

**Comment by rwols** [comment]
It's rather arbitrary what that string should be. There is a list maintained at https://microsoft.github.io/language-server-protocol/specification#textdocumentitem

If your language server understands only one language, then I bet it doesn't even care about the languageId. Or it might look at the file extension to determine the language.

**Comment by PerMildner** [comment]
The string is not arbitrary if it need to be the same in more than one place. The places where the particular string is used and defined is what is not documented.

I do not think the language server will see the "languageId" value at all. If it does then this too should be mentioned.

**Comment by jfcherng** [comment]
> I do not think the language server will see the "languageId" value at all. If it does then this too should be mentioned.

It can. But depending on the server-side implementation.
https://www.npmjs.com/package/vscode-json-languageserver#client-requirements

**Comment by PerMildner** [comment]
@jfcherng: No, the `languageId` is not sent to the server.

The `languageId` is presumably used for associating a language defined by a language package (containing syntax definition etc) with a specification of a language server. These details are not documented and that is what this bug report is about.

**Comment by rwols** [comment]
> the languageId is not sent to the server.

It should be sent with a textDocument/didOpen notification from the client to the server:

https://github.com/tomv564/LSP/blob/a18065f562829aefef29f2c2ae7b654ca5714513/plugin/core/windows.py#L216-L228

**Comment by PerMildner** [comment]
@rwols: You are correct, I was wrong. A `languageId` is indeed part of the [TextDocumentItem](https://microsoft.github.io/language-server-protocol/specification#textdocumentitem) that is sent with various messages from the client to the server.

However, this still does not explain how to tell Sublime Text how to use a particular language server  when it opens a file `bar.mol` in a new imaginary "MyOwnLanguage" programming language.

I.e. it is not documented how to define a new language identifier "languageId - used **both** by the language servers **and** to select a syntax highlighter for sublime popups". (Reading this again I realize that I do not even understand what is meant by "sublime popups" here)

Concretely: I have a language server for a programing language that is not currently supported by Sublime Text, and whose language identifier is not in the list of known language identifiers. I.e, I am in the 'If your language server is **missing** ..., you can add/override the below settings ...'-situation but the documentation does not provide the information I need to actually add to "the below settings" so that my language server is used for my files.

**Comment by jfcherng** [comment]
> However, this still does not explain how to tell Sublime Text how to use a particular language server when it opens a file bar.mol in a new imaginary "MyOwnLanguage" programming language.

I believe it's set by `scopes` and `syntaxes`. Nothing to do with `languageId`.

> I.e. it is not documented how to define a new language identifier "languageId - used both by the language servers and to select a syntax highlighter for sublime popups". (Reading this again I realize that I do not even understand what is meant by "sublime popups" here)

The popup is the thing, for example, appears when you hover on a class.
![image](https://user-images.githubusercontent.com/6594915/61643353-4492e580-acd5-11e9-8f3b-08be4ba31330.png)

**Comment by rwols** [comment]
> Concretely: I have a language server for a programming language that is not currently supported by Sublime Text, and whose language identifier is not in the list of known language identifiers. I.e, I am in the "If your language server is missing ..., you can add/override the below settings ..."-situation but the documentation does not provide the information I need to actually add to "the below settings" so that my language server is used for my files.

Step 1: Have a MyLanguage.sublime-syntax file. It defines a base scope, say `source.mylang`. Let's say it lives in $packages/MyLanguage/MyLanguage.sublime-syntax.
Step 2: Add a new client config to your $packages/User/LSP.sublime-settings (Click on Preferences -> Packages -> LSP -> Settings)
```
{
    "clients":
    {
        "mylanguage-server":
        {
            "enabled": true,
            "command": ["path/to/mylanguage-server", "--some-option",  "--maybe-another-option=foobar"],
            "scopes": ["source.mylang"],
            "syntaxes": ["Packages/MyLanguage/MyLanguage.sublime-syntax"],
            "languageId": "mylang"
        }
    }
}
```
Step 3: Restart Sublime Text.
Step 4: You should see in the status bar that your language server becomes activated when you open a file with the `source.mylang` base scope.

The languageId is completely irrelevant in this setup and can be anything you want. I remember it being used to syntax-highlight some popups somewhere (signature help? hover?) but even that is not done anymore because the *server* should tell us which "Markdown highlighting" to use. See the `MarkedString` type documentation: https://microsoft.github.io/language-server-protocol/specification#textDocument_hover

I agree the documentation is somewhat vague in this area. Feel free to make a pull request :)

**Comment by PerMildner** [comment]
Thanks all of you for the feedback.

Further experimentation indicates that the `languageId` member is _mandatory_ and is what is sent as the `languageId` in  [TextDocumentItem](https://microsoft.github.io/language-server-protocol/specification#textdocumentitem). However, its value is not used when ST determines which language server to use and it need not be from the list of well known language identifiers. The only remaining member that could tell ST to use this particular language server is `"scopes"` (which is defined by a syntax package for my language).

None of this is clear from the documentation.

The title of this issue is no longer suitable. A better title would be something like "Adding new language and language server needs better documentation".

**Comment by jfcherng** [comment]
I think something like https://github.com/tomv564/LSP/issues/663#issuecomment-513868466 should be in the docs for sure. I actually didn't read the docs carefully but just tried unlisted LSP servers by filling what I think it should be filled (and luckily it works).

**Comment by tomv564** [comment]
Updated the outdated documentation, hope you get your server working!
