### ISSUE TITLE
Completion capability is ignored

### ISSUE THREAD

**Issue by PerMildner** [tomv564/LSP#664]
With the following response to the [initialize request](https://microsoft.github.io/language-server-protocol/specification#initialize), Sublime Text does not use my language server (`textDocument/completion` is not sent to my language server from ST when I press CTRL+SPACE).
```
LSP:  --> initialize
...
LSP:      {'capabilities': {'renameProvider': True, 'textDocumentSync': 2, 'implementationProvider': False, 'callHierarchyProvider': False, 'typeHierarchyProvider': False, 'documentHighlightProvider': True, 'documentFormattingProvider': True, 'documentRangeFormattingProvider': True, 'hoverProvider': True, 'workspaceSymbolProvider': True, 'typeDefinitionProvider': False, 'codeActionProvider': False, 'workspace': {'workspaceFolders': {'changeNotifications': True, 'supported': True}}, 'definitionProvider': True, 'referencesProvider': True, 'completionProvider': {}, 'documentSymbolProvider': True}}
```
Note that `completionProvider` is present but the sub-capabilities are all absent. As far as I can tell from the [LSP specification](https://microsoft.github.io/language-server-protocol/specification#initialize) the presence (non-nullness) of the `completionProvider` member should tell the client (ST) that the server supports `textDocument/completion`.

If a `triggerCharacters` member is added to the value of `completionProvider`, the completion requests are sent to my language server and everything works as expected. I.e. if my language server instead replies as follows:
```
LSP:  --> initialize
...
LSP:      {'capabilities': {'documentRangeFormattingProvider': True, 'workspace': {'workspaceFolders': {'changeNotifications': True, 'supported': True}}, 'callHierarchyProvider': False, 'workspaceSymbolProvider': True, 'definitionProvider': True, 'implementationProvider': False, 'documentSymbolProvider': True, 'completionProvider': {'triggerCharacters': ['(']}, 'renameProvider': True, 'typeDefinitionProvider': False, 'documentHighlightProvider': True, 'codeActionProvider': False, 'referencesProvider': True, 'hoverProvider': True, 'typeHierarchyProvider': False, 'textDocumentSync': 2, 'documentFormattingProvider': True}}

```
(Not everything works as expected even in this case, I had expected left parenthesis to trigger completion but it does not. CTRL+SPACE does work though.)

**Comment by rwols** [comment]
This was fixed a few days ago: https://github.com/tomv564/LSP/pull/652
You can try fetching the git master branch instead of a version from Package Control.

**Comment by tomv564** [comment]
Fix is now released, closing this duplicate!
