### ISSUE TITLE
Only show diagnostic panel when uri matches current view

### ISSUE THREAD

**Issue by randy3k** [tomv564/LSP#67]
In Julia server, it starts by linting all files at the current directory. It may make sense to only show the panel when the uri of notification matches the current view. Otherwise, it will popup and refresh the panel multiple times.

**Comment by tomv564** [comment]
The panel refresh in the current implementation is quite slow and distracting. Improving this would give all users are better experience.
Are you closing the panel every time and getting new lint results immediately after?
About matching URI - I think LSP should offer a way to see that a change in file A broke file B, even if file B is not the current view.

**Comment by randy3k** [comment]
> Are you closing the panel every time and getting new lint results immediately after?

Yes, as I may be mentioned earlier, julia server may be slow sometimes (if there are packages need to be recompiled). I close the panel when I see it, then the panel pops up again a few second later when new notification arrives.

**Comment by tomv564** [comment]
That sounds annoying, although not a fix I would suggest setting `auto_show_diagnostics_panel` to false and using the keyboard shortcut (super+shift+M / ctr+alt+M) to open the panel manually once the language server has started.

Besides improvement to the panel refresh logic, I am open to other suggestions on a clever panel-opening mechanism - although preferably without hiding errors from users who want to see them.

**Comment by tomv564** [comment]
To bring this issue to some conclusion:
* The diagnostics refresh logic has come up in issue #84, so let's talk about panel improvements there.
* LSP displays diagnostics for all files in the workspace - we could configure this to only show diagnostics for *opened* files in the workspace. 

@randy3k, does that sound reasonable? I would love a PR implementing a `only_show_diagnostics_for_open_files` (or better named) setting!

**Comment by deathaxe** [comment]
> LSP displays diagnostics for all files in the workspace - we could configure this to only show diagnostics for opened files in the workspace.

Sounds good. I just struggled with the same issue. I have a project which points to Sublime Text Packages path. The diagnostics panel offers diagnostics for all files I recently opened even though I am no longer interested in them. This is really annoying having a list of 30 files with tons of "errors" but not seeing the current ones.

It is especially an issue as nearly none of the packages provides configurations the python-language-server or LSP is able to handle. Therefore tons of linting issues are raised as false positives. The packages just use different rules with longer lines (120 chars) as an example.

**Comment by tomv564** [comment]
I too have noticed that diagnostics remain after I closed some files - the `remove_diagnostics` function should be clearing these but perhaps it's worth adding a "LSP - Clear Diagnostics" command.

**Comment by deathaxe** [comment]
Can't see this function being called at all, when closing a python file. Seems the event chain is broken somewhere.

**Comment by tomv564** [comment]
Fixes to panel update rendering and diagnostic removal should have helped this issue.
PR #96 offered a setting for this which did not receive feedback, so it was closed.

Closing this issue until new interest appears.

**Comment by deathaxe** [comment]
The diagnostics are correctly removed now, if a file is closed. This is ok so far.
