### ISSUE TITLE
customise popup?

### ISSUE THREAD

**Issue by kud** [tomv564/LSP#675]
Hey,

Is there a way to customise the popup?

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/655838/62459488-c5df8300-b77f-11e9-825d-c845b99e051d.png">

I'd like to change the font-family, the font-size, for instance.

**Comment by kud** [comment]
I don't know which plugin installed it, maybe yours, but it's all in https://facelessuser.github.io/sublime-markdown-popups/styling/ :)

`Packages/User/mdpopups.css`

**Comment by rwols** [comment]
Indeed, this plugin has mdpopups as a dependency.

**Comment by kud** [comment]
Okay! I'll add it to the readme. :)

**Comment by tomv564** [comment]
Thanks for the contribution by the way!

**Comment by kud** [comment]
Thanks to you! This plugin helps me a lot everyday. Makes my ST a bit more IDE but not too much (performance).
