### ISSUE TITLE
No syntax highlighting for Reason in popup

### ISSUE THREAD

**Issue by KevinSjoberg** [tomv564/LSP#677]
I've setup LSP for native Reason development. My configuration look like this.

```json
 "reason": {
  "enabled": true,
    "command": ["ocaml-language-server", "--stdio"],
    "scopes": [
      "source.reason",
      "source.ocaml"
    ],
    "syntaxes": [
      "Packages/Reason/Reason.tmLanguage",
      "Packages/sublime-reason/Reason.tmLanguage",
      "Packages/OCaml/OCaml.sublime-syntax"
    ],
    "languageId": "reason"
  }
}
```

It works just fine. However, hovering over types/functions does not give me proper syntax highlighting. See attached screenshot.

![hover](https://user-images.githubusercontent.com/503025/62704287-4ce46380-b9eb-11e9-9b4d-b90ea01a3be0.png)

Initially, I thought it be related to [sublime-markdown-popups](https://github.com/facelessuser/sublime-markdown-popups) since Reason is not part of the [default language mappings](https://github.com/facelessuser/sublime-markdown-popups/blob/master/st3/mdpopups/st_mapping.py).

So, I added the following to my preferences.

```json
"mdpopups.sublime_user_lang_map": {
  "reason": [["reason"], ["Reason/Reason", "sublime-reason/Reason"]],
}
```

However, the issue persists. Still now highlighting.

Any ideas?

**Comment by rwols** [comment]
To better figure out what to do, it's good to see the complete JSON payload of the server. Please do the following:

- set `"log_debug": true` and `"log_payloads": true` in your LSP preferences.
- Restart ST.
- Run your example again, open the ST console, and copy-and-paste the resulting JSON payload from the ocaml-language-server here from our textDocument/hover request.

**Comment by KevinSjoberg** [comment]
@rwols here is the output from LSP as I hover that same code again.

```
LSP:  --> textDocument/hover
LSP:      {'contents': [{'value': '(module Oni_Extensions__TextmateClient.TokenizationResult)', 'language': 'reason.hover.type'}]}
```

**Comment by rwols** [comment]
What happens then is that your markdown will look like this:

````
```reason.hover.type
(module Oni_Extensions__TextmateClient.TokenizationResult)
```
````
That is handled here:
https://github.com/tomv564/LSP/blob/186b8d1dc0b6d47d779103a57d00766efa765bfb/plugin/hover.py#L154-L167

Perhaps you can inform the maintainers of ocaml-language-server about this, because the `language` key *should* be a string that can be understood by vanilla markdown parsers.

From the LSP docs:
```
/**
 * MarkedString can be used to render human readable text. It is either a markdown string
 * or a code-block that provides a language and a code snippet. The language identifier
 * is semantically equal to the optional language identifier in fenced code blocks in GitHub
 * issues. See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
 *
 * The pair of a language and a value is an equivalent to markdown:
 * ```${language}
 * ${value}
 * ```
 *
 * Note that markdown strings will be sanitized - that means html will be escaped.
* @deprecated use MarkupContent instead.
*/
type MarkedString = string | { language: string; value: string };
```

You could try the following to get syntax highlighting, but I haven't tested this:

```
"mdpopups.sublime_user_lang_map": {
  "reason": [["reason.hover.type"], ["Reason/Reason", "sublime-reason/Reason"]],
}
```

**Comment by KevinSjoberg** [comment]
@rwols thanks for the very fast and detailed follow up. I really appreciate it. ❤️ You're absolutely right, I even found references in the [language server specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover).

I'll try what you suggested as a temporary fix and I'll raise the issue with the maintainers of the ocaml-language-server.

Thanks!
