### ISSUE TITLE
LSP not loading Typescript servers in Sublime Text 3

### ISSUE THREAD

**Issue by adriandeveloper** [tomv564/LSP#679]
I'm having a weird issue with LSP in Sublime Text 3.  

I've installed LSP Service package and then went to install Sourcegraph's javascript-typescript-langserver. 

This were working great, but after my work, I saved and closed my editor.  I reopen my editor and I'm constantly greeted with this:

![](https://cl.ly/9be80eb2dc5e/Image%2525202019-08-08%252520at%2525206.41.38%252520PM.png)

I don't know what happened.  I uninstalled and reinstalled Sourgraph's javascript-typescript-langserver multiple times.  I've even tried another service, Theia's [typescript-language-server](https://github.com/theia-ide/typescript-language-server) and I still get the same message for that one. 

Any ideas?  Literally spent the bulk of my day trying to resolve this.  I've posted an issue on Souregraph's repo as well.

OS: MacOS Mojave Typescript language server.
I've installed LSP from Package Control, then ran and build by cloning the repo to see if results still persist. In my tests, they did.

Reproduction steps:  
1. install LSP via Package Control
2. Run npm install -g javascript-typescript-langserver in terminal
3. Open code that contains Typescript and start LSP server, select javascript-typescript-langserver

**Comment by rwols** [comment]
Perhaps the node bin directory is not in your $PATH? Open the SublimeText console, and run the following:

```
import os; os.environ["PATH"]
```
is the path to javascript-typescript-stdio among those paths?

Try putting the absolute path to javascript-type-script-stdio in your client config JSON and see if that works.

**Comment by tomv564** [comment]
Closing for lack of response, hope you got it working!

**Comment by bartoszkrawczyk2** [comment]
I have the same problem. @adriandeveloper have you found a solution?

**Comment by tomv564** [comment]
@bartoszkrawczyk2, can you try @rwols's suggestion? Much better if we find your solution here and share it.
