### ISSUE TITLE
Correctly handle notifications before initialized

### ISSUE THREAD

**Issue by Narretz** [tomv564/LSP#680]
I stumbled over this comment after getting a bunch of "unhandled notfication" messages:

https://github.com/tomv564/LSP/issues/613#issuecomment-512554847

I think it's useful to track this separately. I would even work on it, but need some pointers first where to make the necessary changes.

**Comment by predragnikolic** [comment]
This was already fixed with #665 and merged in master.

**Comment by Narretz** [comment]
Oh, thanks, sorry for the noise. Hope to see another update soon!
