### ISSUE TITLE
LSP disables Sublime's builtin autocomletions in strings

### ISSUE THREAD

**Issue by jwortmann** [tomv564/LSP#686]
LSP seems to prevent Sublime from showing its builtin autocompletion feature within strings. This happens even in files for which no language server is enabled and with the default setting `only_show_lsp_completions` set to `false`.

I guess [this](https://github.com/tomv564/LSP/blob/master/plugin/completion.py#L206) might be the erroneous line, because those flags prevents Sublime from showing its standard completions and completions from `.sublime-completions` files.

**Comment by tomv564** [comment]
Good catch, that should probably have the same logic in it:
```
0 if not settings.only_show_lsp_completions
                else sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS
```
Feel free to open a pull request, or I will try to fix it in the next days.

**Comment by jwortmann** [comment]
Now, I believe it still won't show completions in strings if `only_show_lsp_completions` is set to `true` and no language server is enabled for the opened file. I for example have it set to `true`, but I like that Sublime still shows its own completions for filetypes that have no language server enabled. Perhaps it would be better to add a check for that too. I guess this is what `self.enabled` is for? So I would suggest to either place those lines into the `if self.enabled` block below, or use something like
```python
0 if not self.enabled or not settings.only_show_lsp_completions
else sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS
```

**Comment by tomv564** [comment]
Thanks for suggesting under `if self.enabled`!
