### ISSUE TITLE
Typo in the popup: "implemenation"

### ISSUE THREAD

**Issue by tommit** [tomv564/LSP#687]
* Running on macOS 10.14.6 with [Rust Language Server](https://github.com/rust-lang/rls)
* Installed LSP via Package Control

In the popup that appears when hovering with mouse pointer, the word _implementation_ is misspelled as _implemenation_.

![LSP-Typo](https://user-images.githubusercontent.com/7393895/63228991-d83bd100-c203-11e9-82a4-bc1b17ae4814.png)

**Comment by tomv564** [comment]
Fixed by #688
