### ISSUE TITLE
Does this plugin have configuration capability?

### ISSUE THREAD

**Issue by jfcherng** [tomv564/LSP#692]
Related to https://github.com/bmewburn/vscode-intelephense/issues/614#issuecomment-522914068.

> Does sublime text lsp client have configuration capability? https://microsoft.github.io/language-server-protocol/specification#workspace_configuration

If yes, how can I config them?

**Comment by rwols** [comment]
No, it doesn't (yet) have this capability.

**Comment by jfcherng** [comment]
> No, it doesn't (yet) have this capability.

Get it.
