### ISSUE TITLE
Dart config uses obsolete LSP server

### ISSUE THREAD

**Issue by mit-mit** [tomv564/LSP#694]
From [the docs](https://lsp.readthedocs.io/en/latest/#dart), support for the Dart programming language is based on on the Dart LSP implementation in https://github.com/natebosch/dart_language_server. That is obsolete, and the Dart SDK now has it's own LSP implementation in the [Dart Analysis Server](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md)

What's the process for getting this reconfigured?

**Comment by tomv564** [comment]
Thanks for the heads-up, do you have this server up and running? If so, a pull request to the LSP.sublime-settings file and docs would be much appreciated!

**Comment by mit-mit** [comment]
Thanks much @tomv564; I don't know the inner-workings of this package, but that looks like the correct way to launch the Dart language server!
