### ISSUE TITLE
Support workspace/configuration?

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#699]
Related to #526 where the ESLint server makes the request and subsequently fails to start.

Spec here:
https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#workspace_configuration

Do other language servers need it?
What is authoritative on these scope names used in the URI? VS Code? EditorConfig?
How does it apply to our package: try to read Sublime settings, or store them in EditorConfig or each language client's settings?

**Comment by rwols** [comment]
As with all `any[]` types in the LSP spec that go directly against the spirit of LSP we can't really do anything generic.

My idea about this was to let a LanguageHandler handle this.

Here's a basic outline of how that would look:

```
windows.py

        client.on_request(
            "workspace/configuration",
            lambda params, request_id: self._handle_configuration(params, client, request_id))


    def _handle_configuration(self, params, client, id) -> None:
        # LanguageHandler.get_configuration would be a new interface method
        maybe = self._handlers.get_configuration(params)
        if maybe:
            client.send_response(maybe ...)
            return
        # fall back to just getting the view settings
        view = self.window.active_view()
        setting = view.settings().get(params[ ... ])
        client.send_response(setting ...)
```

**Comment by tomv564** [comment]
Some interesting background in this discussion: https://github.com/microsoft/language-server-protocol/issues/567#issuecomment-420589320

**Comment by tomv564** [comment]
@rwols, to respond to your suggestion:

Looking at the code, a LanguageHandler can replace the default implementation by calling `client.on_request("workspace/configuration", my_handler)` in the `on_initialized` hook. 

As for storing server configuration in the Sublime settings structure instead of the LSP client configs, I think it's interesting (as we discussed in the format on save PR). But I think that servers likely expect the same content as they got from `didChangeConfiguration`?

**Comment by tomv564** [comment]
As an implementation is merged now, I will close the issue until we have more servers that challenge the current functionality.
