### ISSUE TITLE
Reduce impact of LSP color listener by default.

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#703]
@predragnikolic: Noticed while closing views after find-replace in pyls:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 506, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "/Users/tomv/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/color.py", line 47, in on_activated_async
    self.schedule_request()
  File "/Users/tomv/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/color.py", line 53, in schedule_request
    current_point = self.view.sel()[0].begin()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 649, in __getitem__
    raise IndexError()
IndexError
```

* We should probably fix the above issue (maybe it's rare but I ran into this edge case pretty quickly)
* We could avoid creating ViewEventListeners for a few kinds of irrelevant views: Read-only, transient, unsupported syntaxes ( Maybe `DocumentSyncListener` `is_applicable` is suitable?)
* We could avoid running `LspColorListener`'s `schedule_request` until a session with colorProvider for a given view has been found.

**Comment by predragnikolic** [comment]
Hello @tomv564 .
Can you tell me what steps do I need to take to get that error?
I have been trying to reproduce it, but I didn't succeed.

**Comment by tomv564** [comment]
Sorry, it should be a "replace in files".
Replace all 'debug' with 'dbg' in all of LSP. You should get a bunch of changed files opened.
Close these these files (ctrl-w or cmd-w) selecting "Don't Save" and you should see the error.

**Comment by predragnikolic** [comment]
Thanks, I reproduced it. Now I can work on a fix.

**Comment by predragnikolic** [comment]
- I fixed the IndexError.

- The schedule_request is not called until a session is found.
-  Added a `is_supported_syntax` check to `is_applicable` method in LspColorListener. 

What I didn't do from the above is: 
`"avoid creating ViewEventListeners for a few kinds of irrelevant views: Read-only, transient"`.

Why the need to avoid Read-only and transient views?
