### ISSUE TITLE
Latest documentation home page at ReadTheDocs is broken

### ISSUE THREAD

**Issue by davidfstr** [tomv564/LSP#719]
The main documentation homepage for this project at the following URL is broken:
* https://lsp.readthedocs.io/en/latest/

The stable version of the same page is okay:
* https://lsp.readthedocs.io/en/stable/

Screenshot:
![Screen Shot 2019-09-14 at 2 18 45 PM](https://user-images.githubusercontent.com/764688/64913749-bf3b1880-d6fa-11e9-877e-9044c0303f34.png)

**Comment by tomv564** [comment]
Thanks for pointing this out, seems the index file was inadvertently moved in https://github.com/tomv564/LSP/pull/715 (@rchl, sounds like a git oopsie?)

**Comment by rchl** [comment]
Opsie, indeed. Sorry, will fix.
