### ISSUE TITLE
Smart field completion for arrays

### ISSUE THREAD

**Issue by tsujp** [tomv564/LSP#720]
**macOS Mojave 10.14.6 (18G95)**
**Install LSP via Package Control**
**Sublime Text 3.2.1 3207**

## Reproduction

1. Install LSP
2. Install `typescript-language-server` via `npm install -g typescript-language-server` (must be this one as `javascript-typescript-langserver` does _not_ support field completion).
3. Copy boilerplate code below, and observe the same.

## Description

In VSCode the default Typescript completion converts access to array indices into their proper syntax `[n]` from `variable.n`.

### Expected behaviour (VSCode)

![bad](https://i.imgur.com/iVuEmGf.gif)

### Actual behaviour (Sublime Text)

![good](https://i.imgur.com/889kZY8.gif)

**Comment by rwols** [comment]
Could you enable `"log_payloads": true` and `"log_debug": true` in your LSP settings and post the payload of the completions here? The extra debugging output is sent to the SublimeText console.

**Comment by tomv564** [comment]
One completion:
```
{
'sortText': '0', 'label': '0', 'kind': 10, 'insertText': '[0]', 
'textEdit': {
  'newText': '[0]', 
  'range': {'start': {'line': 76, 'character': 3}, 'end': {'line': 77, 'character': 0}}}
}
```
LSP would like to fix the edit, but doesn't recognise the leading `.`. 

`LSP: could not find completion item for inserted ".[0]"`

This feels similar to #714 where skipping the trigger character when looking for inserted text has the right effect.
