### ISSUE TITLE
Hover diagnostics

### ISSUE THREAD

**Issue by Resike** [tomv564/LSP#724]
An option to completely disable hover diagnostics would be neat.

**Comment by tomv564** [comment]
Can you clarify a bit when the hover diagnostics are getting in the way, and why? Have a screenshot to illustrate it?

**Comment by Resike** [comment]
I would like to be able to just completely disable the diagnostics:
![image](https://user-images.githubusercontent.com/3955703/65348292-0cc6f200-dbe1-11e9-898a-2d314a53da5e.png)

Maybe allow it to be disabled in `disabled_capabilities`?

**Comment by tomv564** [comment]
Thanks, that definitely looks distracting (but it is meant to be!). 

Diagnostics should be useful for anyone - what server are you using, and is that diagnostic otherwise correct or helpful? How do you error-check if you don't want the editor to do it?

**Comment by Resike** [comment]
The diagnostics correct and helpful however i'm using luacheck on the side which already gives me the exactly same error notifications.

I'm using these:
https://github.com/sublimelinter
https://github.com/SublimeLinter/SublimeLinter-luacheck
https://github.com/mpeterv/luacheck

https://github.com/sumneko/lua-language-server

**Comment by tomv564** [comment]
I think adding yet another UI setting to hide diagnostics is not really what you're after - I think you'd be better served configuring lua-language-server to not run luacheck.

**Comment by Resike** [comment]
You don't have to add another setting, if you could allow this: ˙"show_diagnostics_severity_level": 0,˙
