### ISSUE TITLE
[Lua] Hover tooltip issues

### ISSUE THREAD

**Issue by Resike** [tomv564/LSP#725]
Lua tooltips are filled with some empty lua blocks:

![image](https://user-images.githubusercontent.com/3955703/65253262-a36cb380-dafa-11e9-926a-16aeecc5e6e1.png)

It can be fixed by chaninging `hover.py: 164` to:

`value = item.get("value").replace("```lua\n\n```", "")`

![image](https://user-images.githubusercontent.com/3955703/65253538-1413d000-dafb-11e9-84a6-09c04751a7da.png)

But i couldn't figured out the root issue.

**Comment by AmjadHD** [comment]
This is probably a server issue, you should open an issue [there](https://github.com/sumneko/lua-language-server).
