### ISSUE TITLE
Is there a way I can use Microsoft's python-language-server for my Python code ? 

### ISSUE THREAD

**Issue by gj1118** [tomv564/LSP#726]
This is not a bug, but rather a request please . 
Can you please let me know how can I setup https://github.com/Microsoft/python-language-server for my Python code please ?

They have already created a `MD` file which basically gives the hint on how you can use it , but it uses a ".dll" and I am on a mac, so I am pretty sure that it is not going to work. 

Thanks
Gagan

**Comment by rwols** [comment]
That language server is written in C#, so you'll have to build it using tooling around C#.

**Comment by tomv564** [comment]
I assume you tried downloading a version of the server as described in this issue? https://github.com/microsoft/python-language-server/issues/770

Might be counter-intuitive but I believe the dotnet DLLs _do_ work on any platform. So `["dotnet", "exec", "/Users/gj1118/python-language-server/Microsoft.Python.LanguageServer.dll"] should work, I think?

**Comment by gj1118** [comment]
I did see that but when I click on that link for Mac, I get the following error 

![image](https://user-images.githubusercontent.com/473101/65322163-0b131500-db74-11e9-88a8-95785b945f41.png)

I have checked out the sources, nevertheless, but I am not sure about the `dll`.

**Comment by tomv564** [comment]
Yes, the issue points to a version that no longer exists, can you change
the URL to get a newly released version?

**Comment by deathaxe** [comment]
```
		"mspyls":
		{
			"command":
			[
				"dotnet.exe",
				"exec",
				"C:\\Apps\\Sublime Text 3\\mspyls\\Microsoft.Python.LanguageServer.dll"
			],
			"enabled": true,
			"env":
			{
				"PYTHONPATH": "C:\\Apps\\Sublime Text 3;C:\\Apps\\Sublime Text 3\\Data\\lib\\python3.3;C:\\Apps\\Sublime Text 3\\Data\\Packages"
			},
			"initializationOptions":
			{
				"interpreter":
				{
					"properties":
					{
						"InterpreterPath": "C:\\Apps\\python33\\python.exe",
						"UseDefaultDatabase": true,
						"Version": "3.3"
					}
				}
			},
			"languageId": "python",
			"scopes":
			[
				"source.python"
			],
			"syntaxes":
			[
				"Packages/Python/Python.sublime-syntax"
			]
		},
```

**Comment by evandrocoan** [comment]
@deathaxe, which python language server you are referring to be better:
1. https://github.com/palantir/python-language-server
1. https://github.com/Microsoft/python-language-server

**Comment by deathaxe** [comment]
The orignal one of course. (1.)

**Comment by tomv564** [comment]
Closing this, hoping @gj1118 has gotten a python-language-server working :)
