### ISSUE TITLE
support for common lisp ?

### ISSUE THREAD

**Issue by syeerzy** [tomv564/LSP#728]
there's a common lisp language server :    

https://github.com/cxxxr/cl-lsp
 
which serve for vscode.

**Comment by tomv564** [comment]
You will need to set up a client configuration in your LSP package settings (documented here: https://lsp.readthedocs.io/en/latest/#server-configuration)

Looking at https://github.com/cxxxr/cl-lsp/blob/master/vscode/src/extension.ts, I think your `command` would be `["cl-lsp", "stdio"]`. LanguageId looks to be `lisp`.
If you're using the built-in syntax, the scopes would only be `["source.lisp"]` and syntaxes `["Packages/Lisp/Lisp.sublime-syntax"]`. And set the `enabled` key to `True`.

If you can confirm the server behaves, we'll gladly take your config to add to the defaults!
One thing to watch for is that `cl-lsp` needs to be on the path for your editor to be able to launch it.
