### ISSUE TITLE
PHP server not updating properly

### ISSUE THREAD

**Issue by genericptr** [tomv564/LSP#730]
I enabled a PHP server for a project and successfully get completions for the project (see the console output below). However, after making changes or saving files the index does not seem to get updated (i.e. new functions don't appear in the auto-complete panel) unless I close and reopen the project.

It's maybe unrelated but if I use the "LSP: Setup Language Server" command I get a "No Language Server support" message even though the phpls program is clearly running.  The "Show Diagnostics" command opens a panel with no content.

Are these bugs with the phpls server or something with the Sublime Text plugin? Sorry if this isn't the right place to post this.

From the console:

```
phpls: 4 files total
phpls: Indexing project for definitions and static references
phpls: Parsing file:///Users/me/Desktop/PHP-test/arrays.php
phpls: Parsing file:///Users/me/Desktop/PHP-test/http.php
phpls: Parsing file:///Users/me/Desktop/PHP-test/struct.php
phpls: Indexing project for dynamic references
phpls: Parsing file:///Users/me/Desktop/PHP-test/arrays.php
phpls: Parsing file:///Users/me/Desktop/PHP-test/http.php
phpls: Parsing file:///Users/me/Desktop/PHP-test/struct.php
phpls: 0 Packages
phpls: All 4 PHP files parsed in 0 seconds. 170 MiB allocated.
```

**Comment by tomv564** [comment]
Some good feedback here about unhelpful LSP features ("Setup Language Server sounds broken, and the diagnostics panel is for issues with your code, not with the server for example).

The real source of trouble seems to be the PHP language server you are using - perhaps the issue is documented in their GitHub repo. Alternatively, have you tried the intelephense server? I've noticed more PHP developers using that one lately.

**Comment by genericptr** [comment]
Eager to try LSP but still getting errors. I installed intelephense  with "npm i intelephense -g" and enabled the server. I get some messages in the console which suggest it started but then I see little message in the status bar that says "Request initialize failed with message: cannot read property 'dataPaths' of undefined.". After that I don't get any completions or indication anything is working.

From the console:

intelephense-ls: Initialising intelephense 1.2.3
intelephense-ls: Reading state from /var/folders/yq/b24z_wm56xn4_58ww3685jsc0000gn/T/intelephense/5b7d754c.

**Comment by tomv564** [comment]
Sorry, that server has a bug that this package hasn't worked around yet - you can install the `LSP- intelephense` package from package control instead!

**Comment by jfcherng** [comment]
it may be a bug of intelephense it self? https://github.com/bmewburn/vscode-intelephense/issues/532

**Comment by genericptr** [comment]
Thanks Tom, this one finally seems to be working. Btw the flickering code completion is much better with this package so it may have been something with the performance of the other "phpls" server.

You want to suggest in your documentation that using "LSP- intelephense" is the best option for PHP. LSP is still pretty new a really bug prone from what I'm seeing so far. Thanks for your work.

**Comment by rwols** [comment]
For some language servers it takes some effort to set it up properly. But once it works it works extremely well. You can regard this plugin as the "base" LSP implementation for ST. Most language servers can work with just some simple JSON setup and the base plugin. For language servers that don't make an effort to be editor-agnostic there are great "glue" packages maintained at https://github.com/sublimelsp/

Happy coding!

**Comment by genericptr** [comment]
Btw, another user referenced this issue at " bmewburn/vscode-intelephense#532". Should I keep the issue open? I didn't want to clutter up your forum with my questions so I closed it.

**Comment by jfcherng** [comment]
Honestly I cannot understand why [lsp-intelephense](https://github.com/sublimelsp/LSP-intelephense/blob/master/plugin.py#L67) works after reading its source code while `lsp` + `intelephense` can't. To me, `lsp-intelephense` looks just like a hard-coded pre-configured one and has no (obvious?) way to overwrite its configuration.

But it resolves your issue, I am confused. :confused:

**Comment by predragnikolic** [comment]
Lsp-intelephense used an older version(1.1.5) of the intelephense server.

The newest version of intelephense 1.2.3 shows an error "Request initialize failed with message: cannot read property 'dataPaths' of undefined." when the server is starting to initialize. 
Version 1.1.5 didn't have this problem.

One way to fix it it simply add "storagePath" to the initialization params, like so, and it will work. 
"initializationOptions": {
     "storagePath": null
 }
This is probably a little bug with intelephense.

>  just like a hard-coded pre-configured one and has no (obvious?) way to overwrite its configuration

True :) but not for long...
The next thing on my todo list is to make all LSP plugins configurable (and if I make it to add #709 to lsp-intelephense, so people can store the licence key in another file)

**Comment by predragnikolic** [comment]
I made a release to lsp-intelephense (0.0.5). In the following hours it will be on package control.
- It uses the latest intelephese server 1.2.3 
- User configuration is added
- And #709 is added as well  :)
