### ISSUE TITLE
LSP underline setting not taking effect

### ISSUE THREAD

**Issue by genericptr** [tomv564/LSP#732]
Is it possible to remove the underlines like in the screenshot? Below are my LSP.sublime-settings for the user but they don't seem to have any effect.

Also as a side note shouldn't "only_show_lsp_completions" only take affect if the language server is running? I set this to true but it blocked completions for other projects that didn't have a language server running in the project.

{
  "only_show_lsp_completions": false,
  "auto_show_diagnostics_panel_level": 0,
  "document_highlight_style": "",
  "diagnostics_gutter_marker": ""
}

![Screen Shot 2019-09-25 at 3 01 35 PM](https://user-images.githubusercontent.com/10937186/65631412-778f7900-dfa5-11e9-818e-92960f75d63f.png)

**Comment by rwols** [comment]
When changing settings of this plugin, you need to completely restart SublimeText. Unfortunately, this is somewhat unintuitive because the settings of the Default package (the one shipped with SublimeText) are applied immediately.

> Also as a side note shouldn't "only_show_lsp_completions" only take affect if the language server is running? I set this to true but it blocked completions for other projects that didn't have a language server running in the project.

Nice observation. This is indeed annoying if there's no language server active.

**Comment by genericptr** [comment]
I think the right preference was "diagnostics_highlight_style" but I'm still getting outlines (the style changed now though).

{
  "only_show_lsp_completions": false,
  "auto_show_diagnostics_panel_level": 0,
  "document_highlight_style": "",
  "diagnostics_gutter_marker": "",
  "diagnostics_highlight_style": "",
}

![Screen Shot 2019-09-25 at 3 19 35 PM](https://user-images.githubusercontent.com/10937186/65632534-e79efe80-dfa7-11e9-93a3-7f95d91d10bd.png)

**Comment by tomv564** [comment]
Try setting `show_diagnostics_severity_level` to 1 or 2 depending on if you wish to see errors.

**Comment by genericptr** [comment]
Setting `show_diagnostics_severity_level` to 0 turned off the underlines. Maybe a little note in the preferences would have been helpful. Thanks.

**Comment by genericptr** [comment]
Just had another thought. Maybe there should be an option to turn off linting entirely? I don't need the feature at all so if it's still communicating with the server that's just a waste of CPU. Thanks again.

**Comment by tomv564** [comment]
This package has no control over it, the language server can perhaps be
configured to turn it off?

**Comment by genericptr** [comment]
I thought your package could control that by not sending certain messages or ignoring certain messages. I guess that's not how it works though. Thanks.
