### ISSUE TITLE
How to automatically enable LSP globally ?

### ISSUE THREAD

**Issue by CorneliusCao** [tomv564/LSP#734]
Your issue may have been solved already - please search before creating new!

Troubleshooting guide: https://lsp.readthedocs.io/en/latest/#troubleshooting
Chat: https://gitter.im/SublimeLSP

Is it a language server problem? The LSP package can do little to prevent slowness or missing content - please check their support materials!

Please include in your report:

* OS and language server
* How you installed LSP (Package Control or from git?)
* Minimal reproduction steps
* Log

Requesting a feature?

Please read https://github.com/tomv564/LSP/blob/master/CONTRIBUTING.md. Specifically, LSP avoids building functionality that does not exist in Sublime Text, or that serves only one language.

**Comment by tomv564** [comment]
You mean that we'd enable all language servers if we detect they are installed? That sounds like a helpful feature but perhaps a bit expensive / unexpected for a few users. 

Can you clarify if that's what you mean? The body of your issue only contains the default template.
