### ISSUE TITLE
Available communication methods

### ISSUE THREAD

**Issue by genericptr** [tomv564/LSP#736]
I would like to make language server for Pascal but I'm not sure which methods LSP uses for communication with the server. I think the options are named pipes and sockets, is that correct? If sockets are used is there a default port to listen on and if named pipes a specific name to be used?

I looked over the spec at https://microsoft.github.io/language-server-protocol/ but they just say the data format is JSON-RPC but nothing as to how the tools communicate (I guess that application specific details).

**Comment by tomv564** [comment]
Named pipes (stdout and stderr) are the most common. 
Some servers (also) support TCP, this package currently only allows users to hardcode the port as an argument to the server (there is no default)
In the future this package will select the port automatically and pass it to the server as an argument - this is what the LSP spec suggests

**Comment by genericptr** [comment]
Thanks, I see in the preference there is a "tcp_port" setting.  If I use sockets can I run the server from the terminal so I debug input from LSP? I think LSP is meant to spawn the process itself but using sockets means this isn't strictly necessary.

I've never used named pipes before but I think you mean that if I simply write to stdout then LSP will parse the output? That sounds easiest for sure.

**Comment by tomv564** [comment]
Correct, tcp mode makes it easy to run from a debugger. 
Some challenge with named pipes exists - for example in PHP on Windows stdio communication blocks the process/threads - only TCP mode works there. But most other languages have no such issues.

**Comment by genericptr** [comment]
Then do we even need the "command" setting? I'm trying my first tests by running the server on 127.0.0.1 and listening on port 6050 but I don't get any data back from LSP when I enable it in the project.

Does that setting look correct? I'm thinking I can omit "command" because the server is already running and so LSP shouldn't need to spawn the process itself. Looking at the ST console I don't get any feedback either (I was expected LSP errors to appear at least)

"clients": {
    "fpc-language-server":
    {
      "command": ["/Users/ryanjoseph/Desktop/symbols/fpcls"],
      "scopes": ["source.pascal"],
      "syntaxes": ["Packages/FPC/FPC.sublime-syntax"],
      "languageId": "pascal",
      "tcp_port": 6050,
    }
  },

**Comment by tomv564** [comment]
Correct, command can be omitted in this  case (did you try it?)

I'd like to invite you to the gitter chat (gitter.im/SublimeLSP/Lobby) as this is turning more into a support discussion.

**Comment by genericptr** [comment]
I asked my question again on gitter. Thanks.
