### ISSUE TITLE
Navigate through references

### ISSUE THREAD

**Issue by xDarksome** [tomv564/LSP#738]
Is there a way to navigate through references after "lsp_symbol_references" has listed them?

**Comment by rwols** [comment]
1) You can double-click on the references with your mouse, if you're using the "panel" style.
2) You can use the quick-panel style references instead: run `pref:lsp` from the command panel, and add the following line in the right-most view that appears:
```
  // Show symbol references in Sublime's quick panel instead of the bottom panel.
  "show_references_in_quick_panel": true,
```

**Comment by xDarksome** [comment]
Thanks!

**Comment by tomv564** [comment]
F4 / shift-F4 also should work for the bottom output panel
