### ISSUE TITLE
Diagnostics not always up to date on saving with linters that run on save

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#740]
* OSX, python-language-server==0.26.1 (https://github.com/palantir/python-language-server)

Configuration:
```json
		"pyls":
		{
			"command":
			[
				"pyls"
			],
			"enabled": true,
			"languageId": "python",
			"scopes":
			[
				"source.python"
			],
			"settings":
			{
				"pyls":
				{
					"configurationSources":
					[
						"flake8",
						"pycodestyle"
					],
					"plugins":
					{
						"pyflakes":
						{
							"enabled": false
						},
					}
				}
			},
			"syntaxes":
			[
				"Packages/Python/Python.sublime-syntax"
			]
```

Reproduce:
1. Create an issue in python file that trigger `pylint` warning/error (for example missing documentation for class).
2. Fix the error and save the file

Expected: That the highlight around error/warning disappears after issue is fixed
Actual: The highlight typically doesn't disappear after saving. It does on second save.

More info:
I've also mentioned it in https://github.com/tomv564/LSP/pull/731#discussion_r329347519 and as far as I can see, it is fixed by triggering `global_events.publish("view.on_purge_changes", self.view)` from `didSave` but you might want to verify that.

**Comment by tomv564** [comment]
Thanks, I didn't set up pylint but could see the issue in the sublime console as well. Thanks for reporting an issue and testing the fix!
