### ISSUE TITLE
problem parsing signature parameters

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#742]
the first occurence of the parameter name is highlighted in lieu of the actual parameter (here `t`):
![image](https://user-images.githubusercontent.com/33235928/65993839-4970d400-e492-11e9-8671-42cfae30f017.png)
* OS: Windows 10
* pyls
* How you installed LSP (Package Control or from git?): git latest master cae1e4b051b489e9f7749978ec7c81d9c492401c
* Minimal reproduction steps
in a python file type `isinstance(`
* log
```
LSP:  --> textDocument/signatureHelp
LSP:      {'activeSignature': 0, 'activeParameter': 0, 'signatures': [{'documentation': 'Return whether an object is an instance of a class or of a subclass thereof.\n\nA tuple, as in ``isinstance(x, (A, B, ...))``, may be given as the target to\ncheck against. This is equivalent to ``isinstance(x, A) or isinstance(x, B)\nor ...`` etc.', 'parameters': [{'documentation': None, 'label': 'o'}, {'documentation': None, 'label': 't'}], 'label': 'isinstance(o: object, t: Union[type, Tuple[Union[type, Tuple], ...]], /) -> bool'}]}
```

**Comment by tomv564** [comment]
I can't reproduce this example using pyls, seeing this instead:

<img width="523" alt="Screenshot 2019-10-03 at 13 22 17" src="https://user-images.githubusercontent.com/4395832/66122773-d7f36b80-e5e0-11e9-95c7-c3e9a0df6554.png">

What version of pyls are you running?

**Comment by AmjadHD** [comment]
0.28.3
I suspect this has anything to do with pyls version
you can try this instead
```python
def f(x: str, t):
    pass

f()
```
the 't' in str is highlighted instead of the actual t parameter.

**Comment by tomv564** [comment]
Ah great, that example is an easy repro. My pyls is out of date so I suspect I'll see the extra typings when I upgrade!
