### ISSUE TITLE
Signature help triggered in inline comments after a function call

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#743]
Signature help is triggered in inline comments that comes after a function call

![image](https://user-images.githubusercontent.com/33235928/66006386-ca3dc900-e4ae-11e9-8260-af23936c7169.png)

* OS: Windows 10
* Language Server: pyls
* How you installed LSP (Package Control or from git?): git latest master cae1e4b051b489e9f7749978ec7c81d9c492401c
* Minimal reproduction steps
in a python file type
```
def f(x):
    pass

f(1)  # ,
```
* Log
```
LSP:  --> textDocument/signatureHelp
LSP:      {'signatures': [{'documentation': '', 'parameters': [{'documentation': None, 'label': 'value'}], 'label': 'f(value: Dict[str, str]) -> Dict[str, str]'}], 'activeSignature': 0, 'activeParameter': 0}
```

**Comment by tomv564** [comment]
Thanks for reporting, LSP will now only request signature help in the same scopes as auto completion.
