### ISSUE TITLE
Enable "only_show_lsp_completions" only for running servers

### ISSUE THREAD

**Issue by genericptr** [tomv564/LSP#744]
I would like to make a formal request that the "only_show_lsp_completions" setting only take effect if there is an actively running server in the project. The problem is that it disables completions for projects that don't have a running server or even intend to use LSP at all.

**Comment by tomv564** [comment]
Agreed. 

The current check of `is_supported_syntax` creates ViewEventListeners for all known server configs, even if disabled.

Changing this to an `is_enabled_syntax` check would be an improvement, with some exceptions:
* Need to verify that all configs (even from language handlers) are correctly seen as enabled when the first vieweventlistener is created.
* Need to communicate that user should re-open views after enabling a language server.

**Comment by tomv564** [comment]
This issue might be incorrect: Although a CompletionHandler is created even though there are no enabled servers for a document, this handler will only reply with `None`. It will never send `INHIBIT_WORD_COMPLETIONS` if `only_show_lsp_completions` is true.

Here I get word completions within a Lisp document (for which I have no server):

<img width="324" alt="Screenshot 2019-11-29 at 13 17 52" src="https://user-images.githubusercontent.com/4395832/69868675-ae865180-12aa-11ea-8c81-04e1f81282db.png">

Can you share some more details about your specific case?
