### ISSUE TITLE
How to jump to next/previous diagnostic?

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#746]
I saw #350 but that didn't really answer my question.

I see the `F4` and `shift+F4` bindings are disabled by default:
https://github.com/tomv564/LSP/blob/81631161d920206f64291d62ff70fdfd2ffe27ba/Keymaps/Default%20(OSX).sublime-keymap#L19-L20

But if I enable them, they work, but only until I trigger search-in-files (which I do often). Then the results from search-in-files take over the shortcuts and I can no longer use them just within given file with diagnostic shown

If diagnostics panel is open and focused, I can use F4 and Shift+F4 to jump through diagnostics but I'd rather not have to open the panel as it's less convenient.

So I think proper solution would be to add extra View commands that I could trigger manually from my key bindings.

**Comment by tomv564** [comment]
Sure, we could follow the keys used by sublimelinter or see what VS Code uses?
Perhaps you want a window command instead, so you can cycle through diagnostics from different files?

**Comment by rchl** [comment]
Yes, I'd like to use the same keybindings as SublimeLinter - https://github.com/SublimeLinter/SublimeLinter/blob/8a96c0bf0a73c36b1fd2edc5253508c89788ca78/keymaps/Default%20(OSX).sublime-keymap#L14

> Perhaps you want a window command instead, so you can cycle through diagnostics from different files?

I wouldn't want that to be the only option as I'm only interested in diagnostics in the current file. It would be confusing to jump to some other random file on pressing the shortcut.
