### ISSUE TITLE
Signature help request is not sent

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#749]
* OS: Windows 10
* Language server: pyls
* How you installed LSP: git latest master
* Minimal reproduction steps
In a python file write `str.replace()`

**Comment by tomv564** [comment]
Since you have the source handy, can you see if you one of these recent commits caused it, and why?

https://github.com/tomv564/LSP/commit/e3090d1775587eedcf1ca65df62ba4bb67cc79c8
or
https://github.com/tomv564/LSP/commit/b814a7fe13fc0f0b1d6fe02b3db1b1dd06d9822d

**Comment by AmjadHD** [comment]
I don't have a pc at the moment, i'll check later, can't you reproduce it ?

**Comment by AmjadHD** [comment]
That's strange it's working fine now ! I don't know why it happened before. sorry for this 😅
