### ISSUE TITLE
debugging ccls crashes

### ISSUE THREAD

**Issue by maddanio** [tomv564/LSP#750]
Hi,

I keep on having ccls crash, which looks like this on the console:
```
LSP:  --> textDocument/hover
Failure writing to stdout
Traceback (most recent call last):
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/transports.py", line 232, in write_stdin
    self.process.stdin.flush()
OSError: [Errno 9] Bad file descriptor

LSP: transport failed
```

is there any way to get the ccls log to debug this a bit further?

**Comment by tomv564** [comment]
Did you see anything after enabling the settings under "Self-help" here? https://lsp.readthedocs.io/en/latest/troubleshooting/
There is also a `log_server` setting to enable, that should be documented there.

You can try enabling ccls's logging to file here: https://github.com/MaskRay/ccls/wiki/Customization

If it's the hover call that triggers the crash, would be interesting to see if it's all hover requests or only specific locations?

**Comment by maddanio** [comment]
Hmm, no, I am sorry, it was late...starting to enable those now and see what I find...

**Comment by tomv564** [comment]
Closing this as it's unclear what LSP can do here.

**Comment by maddanio** [comment]
You are right

**Comment by rwols** [comment]
You seem to be using OS X. Are you on 10.15 Catalina?

**Comment by maddanio** [comment]
yeah, but I think I had those crashes before

**Comment by maddanio** [comment]
also caching seems to not work as well as i hope, but that are all ccls issues i think
