### ISSUE TITLE
Rename not working

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#755]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/33235928/67046824-4f70e100-f131-11e9-99b2-c6da3541ff42.gif)

I guess this was introduced in 5c3d502a1b51cdd38a7cfe12fd7ebaf420d645ae

* How you installed LSP: git latest master (1a2af66)
* Minimal reproduction steps
1. open a supported document
2. invoke rename on a symbol
* Log
```
LSP:  --> textDocument/rename
LSP:      {'changes': {'file:///D:/Amjad/rls-vscode/src/spinner.ts': [{'range': {'start': {'character': 11, 'line': 0}, 'end': {'character': 16, 'line': 0}}, 'newText': ''}, {'range': {'start': {'character': 14, 'line': 1}, 'end': {'character': 19, 'line': 1}}, 'newText': ''}, {'range': {'start': {'character': 9, 'line': 2}, 'end': {'character': 14, 'line': 2}}, 'newText': ''}]}}
```

**Comment by maddanio** [comment]
same here :(. great feature, saves an hour of time at least...

**Comment by tomv564** [comment]
Thanks for reporting!
