### ISSUE TITLE
Don't show lsp commands in the context menu when there's no server running

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#758]
When there's no server running in the view, disabled lsp commands take up a considerable amount of space in the context menu:
![image](https://user-images.githubusercontent.com/33235928/67531566-75632c00-f6c3-11e9-8daa-546544f08727.png)
`LspTextCommand.is_visible()` => `is_supported_view()` => `configs_for_scope()` => `windows.lookup(window)._configs.scope_configs(view, point)` =>
https://github.com/tomv564/LSP/blob/8463278eb784b530ccba408c2e5f478a11d6e79c/plugin/core/types.py#L176-L177
which has no implementation.

**Comment by tomv564** [comment]
This choice was a bit like the links in the hover : we wanted to show LSP features even if the server didn’t support them (yet) to promote them. That said, with the explosion of go to items I agree, we can hide them if not supported by any server

**Comment by rwols** [comment]
Somewhat alleviated by #767.

**Comment by tomv564** [comment]
I think the submenu is the better solution. 

If the items under the LSP menu were to hide themselves, the LSP entry (with arrow) continues to show up even with no child menu.

<img width="236" alt="Screenshot 2019-11-29 at 01 06 25" src="https://user-images.githubusercontent.com/4395832/69835797-7d733600-1244-11ea-938e-c485b54f9461.png">

Ok to close?

**Comment by AmjadHD** [comment]
Ok that's excellent.
