### ISSUE TITLE
Generality of sublime.pyi and sublime_plugin.pyi type stubs

### ISSUE THREAD

**Issue by frou** [tomv564/LSP#761]
This is obviously low priority, but what do you think about splitting the type stubs for ST out into their own repo? That repo could be added as a git submodule on this one, and, usefully, on others too!

**Comment by tomv564** [comment]
I’m all for sharing, but can it be added as a dev-only dependency? I don’t want endusers having to install or run mypy-related stuff

**Comment by frou** [comment]
I must admit that I'm somewhat clueless about Python beyond using it for ST plugins. The use-case I had in mind here was simply for all interested ST plugin authors to be able to benefit from more descriptive autocompletion of the ST API.

Now that I think about it more, one can already get that by doing the following :)

* Have a local clone of this LSP repo.
* Make a dedicated directory off to the side somewhere.
* In that dedicated directory:
  * Create symlinks to LSP's `sublime{_plugin,}.pyi` files.
  * Create symlinks to ST's `sublime{_plugin,}.py` files.
* Run `pyls` with the `PYTHONPATH` environment variable set to the path of that directory.
