### ISSUE TITLE
'lsp_symbol_definition' via keybinding  using `ccls' as client.

### ISSUE THREAD

**Issue by ergotamin** [tomv564/LSP#764]
While I was trying to bind the 'lsp_symbol_definition'-command to my custom keys, I had so suffer from a `... type str does not support Buffer API´.
On revisiting the relevant file ("plugin/goto.py") I found the TODO comment which mentions the future implementation of DocumentLink-support.

By dumping the response-payload of the 'lsp_symbol_definition'-command I found out that the received payload has different keys as beeing parsed by the 'handle_response()' function.
See here:
```
[{targetUri: file:///usr/include/bash/builtins/bashgetopt.h, targetRange: {end: {line: 38, character: 30}, start: {line:
38, character: 0}}, targetSelectionRange: {end: {line: 38, character: 26}, start: {line: 38, character: 11}}}]
```

### Solution

So I added the following snippet to provide the right parsing method in case of this setup/scenario:

```python
            if 'targetUri' in location:
                file_path = uri_to_filename(location['targetUri'])
                start = Point.from_lsp(location['targetRange']['start'])
            else:
                file_path = uri_to_filename(location["uri"])
                start = Point.from_lsp(location['range']['start'])
```

By adding this the desired function of my keybinding worked.

I just wanted to share this in the hope it might be useful.
Best regards !

**Comment by rwols** [comment]
Instead of targetRange, should we not use targetSelectionRange? Where does the cursor end up on with targetRange versus targetSelectionRange in the case of CCLS? Can you provide some examples?

Here's the definition of LocationLink for reference:

```
interface LocationLink {

	/**
	 * Span of the origin of this link.
	 *
	 * Used as the underlined span for mouse interaction. Defaults to the word range at
	 * the mouse position.
	 */
	originSelectionRange?: Range;

	/**
	 * The target resource identifier of this link.
	 */
	targetUri: DocumentUri;

	/**
	 * The full target range of this link. If the target for example is a symbol then target range is the
	 * range enclosing this symbol not including leading/trailing whitespace but everything else
	 * like comments. This information is typically used to highlight the range in the editor.
	 */
	targetRange: Range;

	/**
	 * The range that should be selected and revealed when this link is being followed, e.g the name of a function.
	 * Must be contained by the the `targetRange`. See also `DocumentSymbol#range`
	 */
	targetSelectionRange: Range;
}
```

**Comment by tomv564** [comment]
Also, is this LocationLink support not something the server should detect support for?

**Comment by tomv564** [comment]
> The result type LocationLink[] got introduce with version 3.14.0 and depends in the corresponding client capability `clientCapabilities.textDocument.declaration.linkSupport`.

Feels like a quick win but not a high priority as I assume most servers will check capabilities.
