### ISSUE TITLE
Completion inputs label instead of textEdit newText

### ISSUE THREAD

**Issue by ckipp01** [tomv564/LSP#771]
scalameta/metals#1031 was recently merged which adds an "implement all members" completion option. However, in Sublime it seems to not show up in the same order in the completions as the other editors. It seems to be triggered by e for some reason. Apart from that, if you do decide to use that completion, the completion seems to instead of implementing the `newText` it implements the `label`.

I'm on MacOS using the [Metals Language Server](https://github.com/scalameta/metals) with this SNAPSHOT `0.7.6+224-b3ea857f-SNAPSHOT`

Here is a gif illustrating what I'm talking about

![mygif](https://user-images.githubusercontent.com/13974112/68654280-db5a0b00-052d-11ea-8b86-5669621326cb.gif)

And here is the snippet of lsp json that shows the completion item

```
[Trace - 08:54:53 AM] Received request 'completionItem/resolve - (30)'
Params: {
  "label": "Implement all members",
  "kind": 12,
  "sortText": "00002",
  "filterText": "e",
  "insertTextFormat": 2,
  "textEdit": {
    "range": {
      "start": {
        "line": 9,
        "character": 3
      },
      "end": {
        "line": 9,
        "character": 4
      }
    },
    "newText": "def foo: Int \u003d ${0:???}\n   def boo: Int \u003d ${0:???}"
  },
  "data": {
    "target": "file:/Users/ckipp/Documents/scala-workspace/test-project/?id\u003droot",
    "symbol": "local6"
  }
}


[Trace - 08:54:53 AM] Sending response 'completionItem/resolve - (30)'. Processing request took 1ms
Result: {
  "label": "Implement all members",
  "kind": 12,
  "sortText": "00002",
  "filterText": "e",
  "insertTextFormat": 2,
  "textEdit": {
    "range": {
      "start": {
        "line": 9,
        "character": 3
      },
      "end": {
        "line": 9,
        "character": 4
      }
    },
    "newText": "def foo: Int \u003d ${0:???}\n   def boo: Int \u003d ${0:???}"
  },
  "data": {
    "target": "file:/Users/ckipp/Documents/scala-workspace/test-project/?id\u003droot",
    "symbol": "local6"
  }
}
```

If I can provide any more details, just let me know!

**Comment by rwols** [comment]
Related: https://github.com/SublimeTextIssues/Core/issues/2754

**Comment by tomv564** [comment]
Should this not be a code action instead of a completion?

**Comment by ckipp01** [comment]
The plan I believe is to eventually have this case as a code action, yes. However, for the time being we implemented it this way, which works as expected in vim/emacs/atom/VSCode. I'll page @gabro, @tgodzik , or @olafurpg  since they'll probably be able to provide more/better context than I about why it's not a code action at this point.

**Comment by tgodzik** [comment]
@tomv564 we plan to have it available both as code action and completion. Completion seems a bit more convenient, it's suggested when you are trying to override a symbol and proved to be very useful.

**Comment by rwols** [comment]
I agree this seems more suitable as a code action. The completion replaces all characters that the user just typed. Philosophically the textEdit of a completion should contain at least *something* of the completion label.

**Comment by gabro** [comment]
We provide this completion for symmetry with the `override def` completion that suggests a single member. We may decide to provide this as a code action as well, but we'll probably keep both options anyway.

Regardless, I think inserting the text from `label` instead of `newText` is a bug  (not sure what's the root cause)

**Comment by gabro** [comment]
> Regardless, I think inserting the text from `label` instead of `newText` is a bug (not sure what's the root cause)

Rephrasing this, since it's a bit more involved: the spec says that `label` is the default text to insert, but if `insertText` is present, the client should use that instead of `label`.

Then it goes on saying that when `textEdit` is present, then `insertText` is ignored.

At this point, it's kind of ambiguous whether `label` should be ignored when `textEdit` is present. All other LSP clients seem to think so (correct me if I'm wrong @ckipp01), but I understand it's not so clear.

Is there any reason to use `textEdit` instead of `insertText`, @ckipp01?

**Comment by ckipp01** [comment]
This might just be me not being extremely familiar with the spec, but we have another case in metals (an exhaustive match), that works correctly and seems to be a really similar case. Here is an example:
```
    {
      "label": "match (exhaustive)",
      "kind": 7,
      "detail": " Option[Int] (2 cases)",
      "sortText": "00005",
      "filterText": "match (exhaustive)",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 10,
            "character": 4
          },
          "end": {
            "line": 10,
            "character": 5
          }
        },
        "newText": "match {\n\tcase None \u003d\u003e $0\n\tcase Some(value) \u003d\u003e\n}"
      },
      "data": {
        "symbol": "scala/Option#",
        "target": "file:/Users/ckipp/Documents/scala-workspace/test-project/?id\u003droot"
      }
    },
```
Why is it that this one is seems to work fine when the "imlement all members" doesn't?

**Comment by gabro** [comment]
> Is there any reason to use `textEdit` instead of `insertText`, @ckipp01?

Answering myself here. This is from the spec, and they encourage using `textEdit` over `insertText`

```ts
   /**
	 * A string that should be inserted into a document when selecting
	 * this completion. When `falsy` the label is used.
	 *
	 * The `insertText` is subject to interpretation by the client side.
	 * Some tools might not take the string literally. For example
	 * VS Code when code complete is requested in this example `con<cursor position>`
	 * and a completion item with an `insertText` of `console` is provided it
	 * will only insert `sole`. Therefore it is recommended to use `textEdit` instead
	 * since it avoids additional client side interpretation.
	 */
	insertText?: string;

```

**Comment by ckipp01** [comment]
> Is there any reason to use textEdit instead of insertText, @ckipp01?

Was just about to answer that I wasn't sure, but that snippet from the spec is helpful.

> All other LSP clients seem to think so (correct me if I'm wrong @ckipp01), but I understand it's not so clear.

My naive answer is yes, that seems to be the case since it's working in the other editors. I'll look into to see if that is indeed the case.

**Comment by rwols** [comment]
> Why is it that this one is seems to work fine when the "imlement all members" doesn't?

That is because the ST3 API doesn't actually understand the notion of a TextEdit. So we apply a bunch of heuristics until SublimeTextIssues/Core#2754 is implemented (if ever). Naturally these heuristics may fail.

In my PR you can see that I'm adding another edge-case.

**Comment by tomv564** [comment]
The issue with the completion item showing up as `e` is because the `prefer_label_over_filter_text` setting is default `false`. This is actually recommended to be changed to `true` in your documentation, but I think we will remove that setting soon.

With that setting as `true`,  I can get the item by ctrl+space or by triggering with `I`. If I type `Im` then the item disappears. 

As for using `textEdit`, the current behaviour is conservative. I'm all for removing our label/insertText fallback, if there is an edge case then I think Metals will find it soon enough :)
