### ISSUE TITLE
Error on completing methods (pyls)

### ISSUE THREAD

**Issue by mchoji** [tomv564/LSP#784]
Hi guys,

I'm trying to setup my sublime with LSP and pyls without success. I have already tried installing the packages on different virtual environments with different python versions and lastly using system pip (but with --user flag).

Apparently everything is fine. I have even managed to enable auto-completion on imports and the I can see the available modules. Running the code throws no error, so the interpreter can see the libs. The problem is that I can't have completions for packages installed on virtual environments (test with pipenv and raw pyenv). For modules like os and system everything looks fine.

Anyone have experienced something similar? Any tips on how to setup LSP using pyenv? 

Thanks in advance. Here is the log:

https://pastebin.com/raw/04AFFR6w

**Comment by mchoji** [comment]
> Hi guys,
> 
> I'm trying to setup my sublime with LSP and pyls without success. I have already tried installing the packages on different virtual environments with different python versions and lastly using system pip (but with --user flag).
> 
> Apparently everything is fine. I have even managed to enable auto-completion on imports and the I can see the available modules. Running the code throws no error, so the interpreter can see the libs. The problem is that I can't have completions for packages installed on virtual environments (test with pipenv and raw pyenv). For modules like os and system everything looks fine.
> 
> Anyone have experienced something similar? Any tips on how to setup LSP using pyenv?
> 
> Thanks in advance. Here is the log:
> 
> https://pastebin.com/raw/04AFFR6w

Some updates:

- Completions work fine after dot plus something as in `import pandas as pd; pd.S`. This would suggest `pd.Series`.
- Completions throw the errors described in the original post if only used dot as in `import pandas as pd; pd.`.
- For numpy, no completion were given at all.
- I tested dot completion with Flask and Scapy and both were ok.

Apparently it is somewhat related to numpy (and possibly others). Analogous issue were found on *emacs-jedi*:
https://github.com/tkf/emacs-jedi/issues/339

I found this issue from jedi itself:
https://github.com/davidhalter/jedi/issues/1414

And this might have solved the issue on emacs-jedi:
https://github.com/tkf/emacs-jedi/pull/340

Do you think the issue on sublime could be related to those? Something could be done on LSP side as with emacs? Or does it sound more like a pyls issue?

**Comment by rwols** [comment]
Your log shows this:

```
2019-11-20 04:27:20,520 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 13:
Traceback (most recent call last)::
File "/home/choji/.local/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume:
self._handle_request(message['id'], message['method'], message.get('params')):
File "/home/choji/.local/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request:
handler_result = handler(params):
File "/home/choji/.local/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler:
return method(**(params or {})):
File "/home/choji/.local/lib/python3.8/site-packages/pyls/python_ls.py", line 319, in m_text_document__completion:
return self.completions(textDocument['uri'], position):
File "/home/choji/.local/lib/python3.8/site-packages/pyls/python_ls.py", line 237, in completions:
completions = self._hook('pyls_completions', doc_uri, position=position):
File "/home/choji/.local/lib/python3.8/site-packages/pyls/python_ls.py", line 153, in _hook:
return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs):
File "/home/choji/.local/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__:
return self._hookexec(self, self.get_hookimpls(), kwargs):
File "/home/choji/.local/lib/python3.8/site-packages/pluggy/manager.py", line 92, in _hookexec:
return self._inner_hookexec(hook, methods, kwargs):
File "/home/choji/.local/lib/python3.8/site-packages/pluggy/manager.py", line 335, in traced_hookexec:
return outcome.get_result():
LSP:File "/home/choji/.local/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result:
 raise ex[1].with_traceback(ex[2]):
File "/home/choji/.local/lib/python3.8/site-packages/pluggy/callers.py", line 52, in from_call:     None
```
That's probably coming from [python-language-server](https://github.com/palantir/python-language-server), so you should open an issue there.

**Comment by mchoji** [comment]
Confirmed as a bug in `jedi` as described in https://github.com/davidhalter/jedi/issues/1414. Virtual env is working perfectly.
