### ISSUE TITLE
Feature request: info in completion

### ISSUE THREAD

**Issue by maclam** [tomv564/LSP#786]
Hi,
Have you planned to develop the feature that displays docstings during the completion like in vscode named "quick info"?

![vscode](https://user-images.githubusercontent.com/22882318/69352237-db1fe500-0c7c-11ea-88cc-c5d3d7ac2221.png)

![intellisense_docs](https://user-images.githubusercontent.com/22882318/69352251-e2df8980-0c7c-11ea-9f1b-fd67ce6715a5.gif)

**Comment by tomv564** [comment]
Would have loved to, but in Sublime Text 3 the completion list exposes no event saying "item `atan2`" was selected. We can only find out _after_ you commit a completion from the list.

There are some new APIs recently revealed for a future Sublime Text version, I haven't seen if it can be built now yet. Maybe @rwols has looked closer?

**Comment by ayoub-benali** [comment]
I want to add that such a feature provides a better experience for lsp servers, like Metals, to return completion faster (doc strings would be fetched later)

**Comment by tomv564** [comment]
I didn't find any evidence of a "completion selected from list" event even in the new APIs.

The only new thing is support for icons (like VS Code in your screenshot). 

@ayoub-benali, don't you already exclude `documentation` for un-resolved completion items? Sublime doesn't use it, and `detail` has to be really short for it to fit..

**Comment by ayoub-benali** [comment]
> I didn't find any evidence of a "completion selected from list" event even in the new APIs.

We should probably request this as part of the feedback for build 4XXX 

as far as I know document isn't even returned by metals for sublime as the API doesn't provide a call back when the user cycle through auto complete.
cc @olafurpg for confirmation.

**Comment by olafurpg** [comment]
Metals fetches docstrings on-demand as the user cycles through the completion items. We do it this way to remove potentially expensive operations from the critical path. Rendering the docstring requires fetching the external dependency sources, parsing, extracting docstrings and a few other steps. One completion list can easily have symbols from dozens of files so it would be performance regression to eagerly fetch docstrings during `textDocument/completions`
