### ISSUE TITLE
get_project_path() incorrectly determines path

### ISSUE THREAD

**Issue by rmccue** [tomv564/LSP#79]
If you have multiple sibling directories in a workspace with common prefix characters, it will incorrectly use a partial path for this.

I have two directories open, which are `~/Projects/example1` and `~/Projects/example2`. `os.path.commonprefix()` will hence return `~/Projects/example`, which is not a directory that exists. (The Python docs note that `os.path.commonpath()` should be used instead.)

This approach is generally problematic anyway. I have two subdirectories deep inside a common directory, and even without the partial filename problem, this is still problematic for me as it causes **a lot** more files than I care about to be indexed. This causes the initial parsing to take roughly *forever*.

VS Code is currently working on adding multi-root support (https://github.com/Microsoft/vscode/issues/28344), so I suspect they'll add support to the Language Server protocol at some point. The current behaviour in the beta is just to index the first directory in the project. IMO, this is the best behaviour until the protocol actually supports multi-root.

**Comment by tomv564** [comment]
Thanks for the detailed bug report, sounds like `commonpath` is the intended behaviour.

I am myself not convinced of the shared-root-of-multiple-folders approach, but would only supporting the first folder be an improvement?

**Comment by rmccue** [comment]
> would only supporting the first folder be an improvement?

I definitely think so; the way I use Sublime projects typically is by having a main directory with multiple auxiliary directories for easy access (for example, a component of a large system along with the core library for said system). Having all of it integrated would be nice, but in lieu of that, just using the first folder I think is the best behaviour (and matches VS Code's current behaviour).

**Comment by rmccue** [comment]
Filed #81 which switches to the first folder approach; if you'd prefer to keep the common parent approach, I can switch it over to `commonpath` instead.

**Comment by rmccue** [comment]
(Here's the actual draft spec for multi-root support, btw: https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.workspaceFolders.proposed.md )
