### ISSUE TITLE
Server isn't automatically started when Sublime is already open

### ISSUE THREAD

**Issue by brainplot** [tomv564/LSP#792]
Hi, I'm using Sublime Text 3.2.2 (build 3211) on Arch Linux. Here's the output of `uname -a`:
```
Linux mars 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux
```
I'm using LSP v.0.9.0 and I installed it through Package Control.

Ever since I started using this plugin I've experienced a little issue while using my language servers.
Basically, if I have Sublime Text open with no projects in it and then I decide to load in a project, the language server associated with that project won't start automatically. In order to get the server running I have to open a project, then close down Sublime, and then reopen it again. Thanks to Sublime's hot exit feature the project will already be there and the server will be started as intended.
Same thing happens if I have a project already open and then decide to switch to another one: if a project has a language server running and then I switch to another one via the `Quick Switch Project` feature, the server for the newly-open project won't start as well. However, if I then go back to the first project - always via `Quick Switch Project` - the server will still be there running.

So basically, also as a recap, intuitively it seems like LSP doesn't shut down the current language server and starts the other one when switching to a new project, neither does it start the language server when opening a project in an already-running Sublime Text instance.
I recorded [a video](https://www.youtube.com/watch?v=TIE1dvsm9nk) that hopefully should clarify what the issue is.

For reference, this is my `LSP` configuration:
```json
{
  "auto_show_diagnostics_panel_level": 2,
  "log_debug": true,
  "log_stderr": true,
  "show_diagnostics_count_in_view_status": true,
  "clients": {
    "rls":
    {
      "command": ["rls"],
      "scopes": ["source.rust"],
      "syntaxes": [
        "Packages/Rust/Rust.sublime-syntax",
        "Packages/Rust Enhanced/RustEnhanced.sublime-syntax"
      ],
      "languageId": "rust"
    },
    "clangd":
    {
      "command": [
        "clangd",
        "--background-index",
        "--compile-commands-dir=build",
        "--header-insertion=iwyu",
        "--pch-storage=memory",
        "-j=6"
      ],
      "languages": [{
        "scopes": ["source.c"],
        "syntaxes": ["Packages/C++/C.sublime-syntax"],
        "languageId": "c"
      },{
        "scopes": ["source.c++"],
        "syntaxes": ["Packages/C++/C++.sublime-syntax"],
        "languageId": "cpp"
      },{
        "scopes": ["source.objc"],
        "syntaxes": ["Packages/Objective-C/Objective-C.sublime-syntax"],
        "languageId": "objective-c"
      },{
        "scopes": ["source.objc++"],
        "syntaxes": ["Packages/Objective-C/Objective-C++.sublime-syntax"],
        "languageId": "objective-cpp"
      },
    ]
    }
  }
}
```
and here are the `.sublime-project` files for the projects I used in the video:
```json
// Rust project
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
        "LSP":
        {
            "rls":
            {
                "enabled": true
            }
        }
    }
}
```
```json
// C project
{
    "folders":
    [
        {
            "file_include_patterns":
            [
                "compile_commands.json"
            ],
            "folder_exclude_patterns":
            [
                "*"
            ],
            "path": "build"
        },
        {
            "folder_exclude_patterns":
            [
                "build*"
            ],
            "path": "."
        }
    ],
    "settings":
    {
        "LSP":
        {
            "clangd":
            {
                "enabled": true
            }
        }
    }
}
```
With `"log_debug"` enabled in my `LSP` preferences, I opened the console on a new instance of Sublime Text (with no projects open) and these are the only entries related to `LSP`:
```
LSP: global configs ['ra-lsp=False', 'phpls=False', 'typescript-language-server=False', 'haskell-ide-engine=False', 'eslint=False', 'reason=False', 'flow=False', 'metals=False', 'bashls=False', 'rls=False', 'gopls=False', 'vscode-css=False', 'ocaml=False', 'javascript-typescript-langserver=False', 'clangd=False', 'lsp-tsserver=False', 'pyls=False', 'jdtls=False', 'golsp=False', 'dart=False', 'intelephense-ls=False', 'polymer-ide=False', 'cquery=False', 'ruby=False']
LSP: window 2 starting 1 initial views
```
When I open the Rust project (with the same steps as shown in the video) these are the only lines of output added to the console:
```
git: tracking working dir /home/gianluca/Projects/rust-sandbox
```
and this is what appears on the console when I switch to the C project via Quick Switch:
```
git: untracking working dir /home/gianluca/Projects/rust-sandbox
```
The C project isn't a Git repo so that's why the same messages don't appear for it as well.
So basically nothing seems to be happening, as far as LSP can tell.
If I try to **restart** Sublime Text with the project already loaded in, as mentioned earlier, this is what I get on the console:
```
LSP: global configs ['polymer-ide=False', 'eslint=False', 'cquery=False', 'jdtls=False', 'vscode-css=False', 'ra-lsp=False', 'haskell-ide-engine=False', 'reason=False', 'lsp-tsserver=False', 'javascript-typescript-langserver=False', 'flow=False', 'ocaml=False', 'phpls=False', 'ruby=False', 'clangd=False', 'gopls=False', 'rls=False', 'golsp=False', 'intelephense-ls=False', 'typescript-language-server=False', 'bashls=False', 'metals=False', 'pyls=False', 'dart=False']
LSP: window 2 has override for clangd {'enabled': True}
LSP: window 2 starting 1 initial views
LSP: window 2 requests clangd for /home/gianluca/Projects/hash-test/src/main.c
LSP: starting in /home/gianluca/Projects/hash-test/build
LSP: starting ['clangd', '--background-index', '--compile-commands-dir=build', '--header-insertion=iwyu', '--pch-storage=memory', '-j=6']
LSP:  --> initialize
LSP: window 2 added session clangd
I[02:48:13.842] clangd version 9.0.0 (tags/RELEASE_900/final):
I[02:48:13.842] Working directory: /home/gianluca/Projects/hash-test/build:
I[02:48:13.842] argv[0]: clangd:
I[02:48:13.842] argv[1]: --background-index:
I[02:48:13.842] argv[2]: --compile-commands-dir=build:
I[02:48:13.842] argv[3]: --header-insertion=iwyu:
I[02:48:13.842] argv[4]: --pch-storage=memory:
I[02:48:13.842] argv[5]: -j=6:
Path specified by --compile-commands-dir does not exist. The argument will be ignored.:
I[02:48:13.842] Starting LSP over stdin/stdout:
I[02:48:13.843] <-- initialize(1):
I[02:48:13.843] --> reply:initialize(1) 0 ms:
LSP:  --> initialized
I[02:48:13.843] <-- initialized:
I[02:48:13.843] unhandled notification initialized:
LSP:  --> textDocument/didOpen
I[02:48:13.845] <-- textDocument/didOpen:
I[02:48:13.846] Failed to find compilation database for /home/gianluca/Projects/hash-test/src/main.c:
I[02:48:13.846] Updating file /home/gianluca/Projects/hash-test/src/main.c with command clangd fallback:
[/home/gianluca/Projects/hash-test/src]:
/usr/bin/clang /home/gianluca/Projects/hash-test/src/main.c -fsyntax-only -resource-dir=/usr/lib/clang/9.0.0:
I[02:48:13.912] --> textDocument/publishDiagnostics:
LSP: <--  textDocument/publishDiagnostics
```
and now it works as intended with no issues.

I tried to make this as comprehensive as I could. Let me know if there's any other thing I can do to try and figure out what's going on :slightly_smiling_face:

**Comment by tomv564** [comment]
Thanks for the detailed report! The issue is unique to Quick Switch Project and having servers enabled per project - we are missing the logic to update the project overrides on an existing window after switching.

It's probably a good time to finish pull request #708 as it will help fix this bug.

In the meantime, having servers globally enabled will make Quick Switch work.

**Comment by brainplot** [comment]
I understand. Thanks for the quick reply and for the alternative solution until this is fixed! :)
