### ISSUE TITLE
Diagnostic navigation ignores severity levels 

### ISSUE THREAD

**Issue by ayoub-benali** [tomv564/LSP#795]
I have `show_diagnostics_severity_level` and `auto_show_diagnostics_panel_level` set to 1
and when navigating though diagnostics (https://github.com/tomv564/LSP/pull/783) I reach `warn` diagnostic while I should have only `error`.

Maybe these two settings should also be merged ?

I tested with metals.

**Comment by tomv564** [comment]
I'll take a look at this as it also helps #762.

**Comment by tomv564** [comment]
@ayoub-benali, how do you solve this with Metals in VS Code?

**Comment by ayoub-benali** [comment]
@tomv564 I don't use vscode at all. 
Can't LSP filter out warnings from the list of diagnostic received from servers ?

**Comment by tomv564** [comment]
LSP absolutely can, but I like to prioritise building features that VS Code already has ;)

Anyways, I like this comment in VS Code issue 45436:

> By default, TS suggestion diagnostics such as convert a es5 class to an es6 class show as faint gray underlines in the editor. This would let users know where they can perform code actions. These diagnostics would not show in the problems view or participate in F8

In other words, `show_diagnostics_severity_level` should apply to the diagnostic panel and the diagnostic navigation. But *info* and *hint* will always have regions and show up in hovers.

**Comment by tomv564** [comment]
If we drop `auto_show_diagnostics_panel_level`, the ability to show info and hint diagnostics in the diagnostics panel without it popping open disappears. I'm okay with this - underlined regions should be enough for those diagnostics.
