### ISSUE TITLE
LSP works in transient views

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#801]
Related to #633

When cycling through files in the "goto anything" menu, language services are provided for the previews even though `is_transient_view()` returns True
modify these methods in plugin.core.documents.DocumentSyncListener:
```python

    def on_load_async(self) -> None:
        # skip transient views:
        it = is_transient_view(self.view)
        print("loaded", it)
        if not it:
            self.manager.activate_view(self.view)
            self.manager.documents.handle_view_opened(self.view)

    def on_activated_async(self) -> None:
        it = is_transient_view(self.view)
        print("activated", it)
        if self.view.file_name() and not it:
            self.manager.activate_view(self.view)
            self.manager.documents.handle_view_opened(self.view)
```

Please include in your report:

* OS: Windows 10
* How you installed LSP: git latest
* Minimal reproduction steps
1. bring up the "Goto Anything" menu (<kbd>ctrl</kbd>+<kbd>p</kbd>)
2. Highlight a LSP-supported file, which isn't currently open
3. Hover over a name in the previewed file

**Comment by tomv564** [comment]
This is as-designed - the spec doesn't say anything about documents needing to be open for editing to get language features. 
As for unwanted slow server startups, it sounds like disabling the server globally and enabling per-project should help?

**Comment by AmjadHD** [comment]
can't this be bound to a setting ?

**Comment by tomv564** [comment]
It could, but I don't believe your experience is painful enough to add it.
