### ISSUE TITLE
Powershell configuration for Sublime text 3

### ISSUE THREAD

**Issue by georgeabr** [tomv564/LSP#804]
Hello

I cannot integrate Sublime text 3 with PowerShellEditorServices/LSP plugin, as per the instructions on the LSP documentation.
I have also opened an issue with PowerShellEditorServices below:
https://github.com/PowerShell/PowerShellEditorServices/issues/1113

I'd appreciate if anyone could post a step by step guide on how to achieve Powershell intellisense with Sublime, by using pwsh (plugins and configs used, and in what order).

**Comment by tomv564** [comment]
Hi, from the linked issue: Can you make sure the PowerShell configuration you added to the LSP user setting lives under a “clients” key?

**Comment by georgeabr** [comment]
Thanks, @tomv564, your suggestion helped, and I am now able to use Sublime + LSP + Powershell.
Maybe the documentation in the link below could be supplemented with a skeleton `LSP.sublime-settings` file, to show a full example of adding a language.
Docs are below, they reference the "clients" section, but do not actually provide an example with this section included:
https://lsp.readthedocs.io/en/latest

Something like this to illustrate a short complete example:
```
{
	"auto_show_diagnostics_panel_level": 2,
	"clients":
	{
		"omnisharp": 
		{
		"command":
		  [
		    "/home/tb/prebuilt/omnisharp/OmniSharp.exe", // or eg. /usr/local/opt/omnisharp/run
		    "-lsp"
		  ],
		  "enabled": true,
		  "languageId": "csharp",
		  "syntaxes": ["Packages/C#/C#.sublime-syntax"],
		  "scopes":
		  [
		    "source.cs"
		  ]
		}
	}
}
```

**Comment by rwols** [comment]
Having a step by step tutorial in the docs sounds like a good idea. Also the maintainers of PowershellEditorServices seem like nice people.
