### ISSUE TITLE
There is no mention of R in the docs, nor how to set it up in context of this package

### ISSUE THREAD

**Issue by HarrisonWilde** [tomv564/LSP#812]
Been setting up LSP today and noticed there was no documentation for R strangely, might be worth letting people know that they have to first do:

```
R$> install.packages("languageserver")
```

and then add something to the tune of:

```
		"rlang":
		{
			"command":
			[
				"R", "--slave", "-e", "languageserver::run()"
			],
			"languageId": "r",
			"scopes":
			[
				"source.r"
			],
			"syntaxes":
			[
				"Packages/R/R.sublime-syntax"
			],
			"enabled": true
		}
```

to their `LSP.sublime-settings` to get stuff working, or maybe even add this to the default clients as I think it should be the same in almost all cases?

**Comment by tomv564** [comment]
That looks really straightforward! Feel free to add it to the docs and the default config (minus the `enabled`). Otherwise, thanks for letting us know!

**Comment by predragnikolic** [comment]
Isn't there a R-IDE plugin that works with LSP? https://packagecontrol.io/packages/R-IDE

> although I would really like that the plugin was named LSP-r

**Comment by HarrisonWilde** [comment]
@predragnikolic yes but it just says to install R-IDE, which doesn't alter the LSP settings in a way that makes it work off the shelf; may as well have R amongst the default clients but will potentially follow up with the maintainers of R-IDE to see if they can fix it on their end

**Comment by rwols** [comment]
Thanks for your contribution @HarrisonWilde :)

**Comment by randy3k** [comment]
Here the author of R-IDE. Actually, R-IDE does more than just providing the handler for LSP, it also defines build systems and includes other helper features for helping R coding.

If a user installs R-IDE, the default settings will be overridden by our tailer made handlers: https://github.com/REditorSupport/sublime-ide-r/blob/2e0295a78ecddf2e0eb338934cee179994a651d0/ride/lsp.py#L29-L29

**Comment by randy3k** [comment]
@HarrisonWilde Did R-IDE not setup the config automatically for you? It has been working for me for months.
