### ISSUE TITLE
Bind Go To Symbol Definition to Ctrl + Click

### ISSUE THREAD

**Issue by ryanpcmcquen** [tomv564/LSP#816]
Couldn't find this issue anywhere. I just want to bind Go To Symbol Definition to Ctrl + Click, is this possible? It seems the key bindings are only for keyboard shortcuts, not mouse shortcuts.

**Comment by jfcherng** [comment]
I didn't actually test it but you can bind a command to a mouse map.
https://forum.sublimetext.com/t/how-to-achieve-sublime-ctrl-left-mouse-button-function-jump-function-like-intellij-idea-that-function/34918/3

**Comment by ryanpcmcquen** [comment]
@jfcherng, thank you, I got it (`Default.sublime-mousemap`):
```
[
...
    {
        "button": "button1",
        "count": 1,
        "modifiers": ["ctrl"],
        "press_command": "drag_select",
        "command": "lsp_symbol_definition"
    }
]
```

**Comment by tomv564** [comment]
Good example of how things are documented (see "Mouse map configuration" on https://lsp.readthedocs.io/en/latest/features/) but not findable :)

**Comment by predragnikolic** [comment]
Maybe we should add ctrl + mouse click as a default shortcut to LSP, so people don't have to hunt down that documentation for that?

**Comment by mtvbrianking** [comment]
You can achieve this by doing the following:

    Preferences menu -> Browse Packages
    Go into the User folder
    Create a new file called `Default.sublime-mousemap`
    Open it in ST
    Paste in the following:

> @jfcherng, thank you, I got it (`Default.sublime-mousemap`):
> 
> ```
> [
> ...
>     {
>         "button": "button1",
>         "count": 1,
>         "modifiers": ["ctrl"],
>         "press_command": "drag_select",
>         "command": "lsp_symbol_definition"
>     }
> ]
> ```

Source: https://forum.sublimetext.com/t/how-to-achieve-sublime-ctrl-left-mouse-button-function-jump-function-like-intellij-idea-that-function/34918/3

**Comment by rchl** [comment]
ctrl+click opens context menu on Mac and cmd+click creates new selection/cursor

**Comment by Gin-Quin** [comment]
ctrl+click on Mac is not very useful, whether you use a mouse or the touchpad you can open the context menu very easily.

What would be ideal for mac users:

- cmd + click -> go to definition (like other editors),
- ctrl + click -> add a cursor at mouse location.

**Comment by jgb-solutions** [comment]
This option should be included by default in the plugin. VS Code has it by default and it's free. I like Sublime but hey it's been lacking for the last few years, and it now it sells for 99 dollars.

**Comment by zzag** [comment]
How do you make back and forward mouse buttons works with

```json
    {
        "button": "button1",
        "count": 1,
        "modifiers": ["ctrl"],
        "press_command": "drag_select",
        "command": "lsp_symbol_definition"
    }
```

?
