### ISSUE TITLE
Increase delay before lint/diagnostics runs

### ISSUE THREAD

**Issue by dvcrn** [tomv564/LSP#818]
A very specific problem to my case but wanted to ask anyway. 

I am using a vim heavy setup with `fd` bound to ESC / exit insert mode. 

What happens a lot is that when I type something and quickly hammer `fd` to exit insert mode back into normal mode, diagnostics runs before the `fd` can be turned into a ESC and I end up with errors like this one: 

![Screen Shot 2019-12-06 at 15 43 57](https://user-images.githubusercontent.com/688326/70302148-a5175f00-183f-11ea-9bb9-4fa78d01ffd7.png)

aka the diagnostic is run on a version that still has the `f` in it which results in a syntax error.

Re-saving the file in normal mode is usually getting rid of it, but do you have any smart ideas on how to fix this behavior once and for all? An idea would be to increase the delay after a keypress before the diagnostics run

**Comment by tomv564** [comment]
Normally we want 500ms before sending buffer changes - enough time for your vim plugin to revert the content. 
Something like saving the file, triggering signature help or completion request will immediately purge the pending changes, perhaps before the vim plugin reverts the `fd`.
LSP already logs the `textDocument/didChange` if you have `log_payloads` turned on. Perhaps you can investigate the timing by adding a `print` to the vim plugin whenever it exits insert mode?
