### ISSUE TITLE
Should WorkspaceFolder be renamed to ProjectFolder ?

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#828]
should this become `ProjectFolder` in conformance with https://github.com/tomv564/LSP/pull/809/commits/5cbd0360297466726a6c5250bbadbd5cad7b3b1e ?
https://github.com/tomv564/LSP/blob/c5e5473e5cd6051b1e0e7baf6c1de93c8fdbef3f/plugin/core/protocol.py#L416

**Comment by tomv564** [comment]
Don't know, perhaps `ProjectFolders` should become something larger that also encompasses project data?

**Comment by rwols** [comment]
I consider ProjectFolders a sublime concept, so it can have any name. While WorkspaceFolder is an LSP concept. The name of the class should mirror the definition in the LSP spec. Also, ProjectFolders is essentially a container of WorkspaceFolder.

**Comment by tomv564** [comment]
We can rename it later, closing the issue as there's nothing urgent to be done here.
