### ISSUE TITLE
Diagnostics panel flickers constantly

### ISSUE THREAD

**Issue by rmccue** [tomv564/LSP#84]
When the diagnostics panel is open while you're typing, it appears to redraw multiple times per change, which a) is very distracting, and b) presumably isn't intentional.

Here's what happens when I type a single character:

![lsp-diag-flicker](https://user-images.githubusercontent.com/21655/30236771-3e099b52-9565-11e7-8ca8-ff2ac9bfbf32.gif)

This is redrawing a **lot** considering there was a single character changed. Viewing the GIF frame-by-frame shows the redraws (this was recorded at 60fps).

Not sure if this is a problem with the language server I'm using ([PHP](https://github.com/felixfbecker/php-language-server)) or with the plugin, but I suspect it's the plugin. Potentially a race condition? (Haven't debugged it yet.)

**Comment by rmccue** [comment]
Debouncing the update would help somewhat here (VS Code seems to use `"editor.quickSuggestionsDelay": 10`) but I think there's also an issue with the redrawing generally.

**Comment by chenglou** [comment]
This is especially disturbing when the error surpasses a screenful. The whole view starts scrolling a lot

**Comment by tomv564** [comment]
Could you enable `log_debug` in your settings and share the results of a single keypress? A single diagnostics update should result in 1 update of the panel, but the way we write lines to the panel may not be batched in an efficient manner.

**Comment by chenglou** [comment]
Here's the log on a Reason file:

```
LSP: notify: textDocument/didSave
LSP: got json: ...
```

For OCaml:

```
LSP: document not tracked path/to/test.ml
```

Here's some quirky behavior:

- Restart ST
- See the diagnose on for the OCaml file for the first time
- Fix the error, see that diagnosis is stale and doesn't refresh
- Close & reopen file
- Get the same message as above

**Comment by deathaxe** [comment]
Each time a new diagnostics response is received, the panel's content is cleared and rebuilt from scratch using "view.insert()" for each message. This causes flickering, if many items are added. 

To solve this issue, all responses must be converted to the text content in the background and then be used to replace the whole panal's content with one "view.replace()" call.

**Comment by tomv564** [comment]
@deathaxe that sounds like a great fix!
@chenglou Two didSave events! That's not good - are you running some format-on-save logic (eg. another plugin?)?

**Comment by chenglou** [comment]
No format on save

**Comment by rmccue** [comment]
I'm only seeing the one `textDocument/didChange` event here, but that's still causing the flickering. I'll look at the `view.replace()` fix and see if that helps.

**Comment by tomv564** [comment]
Merging the PR closed the issue, we can re-open if this hasn't improved.

**Comment by tsujp** [comment]
This is still an issue.

**Comment by tomv564** [comment]
Hi @tsujp, thanks for commenting in the original issue!
Can you share some details (what server are you running, when does it flicker?) A log covering a fresh start to a repro (with the LSP `log_debug` setting would be much appreciated!

**Comment by tsujp** [comment]
@tomv564 very sorry, I did not have `"only_show_lsp_completions": true` set which was the cause of the issue, I should've more thoroughly checked the setup. When I removed some things to get the diagnostics I noticed the setting.

So, setting `"only_show_lsp_completions": true` removed the 'problem' (which was really me hehe).
