### ISSUE TITLE
ocaml-language-server doesn't work for ocaml files

### ISSUE THREAD

**Issue by chenglou** [tomv564/LSP#85]
[ocaml-language-server](https://github.com/freebroccolo/ocaml-language-server) is used by VSCode and a few others to power LSP for OCaml and Reason files. Ironically, somehow for Sublime LSP I couldn't activate it for OCaml files. The scope is correctly detected; no errors or autocompletion, etc.

**Comment by tomv564** [comment]
OCaml may be missing from the syntaxes entry (which also filters LSP functionality)?

**Comment by chenglou** [comment]
Here's the log on a Reason file:

```
LSP: notify: textDocument/didSave
LSP: got json: ...
```

For OCaml:

```
LSP: document not tracked path/to/test.ml
```

Here's some quirky behavior:

- Restart ST
- See the diagnose on for the OCaml file for the first time
- Fix the error, see that diagnosis is stale and doesn't refresh
- Close & reopen file
- Get the same message as above

**Comment by tomv564** [comment]
First, let's check what syntax OCaml uses with `sublime.active_window().active_view().settings().get("syntax")`

<img width="667" alt="screen shot 2017-09-10 at 10 37 15" src="https://user-images.githubusercontent.com/4395832/30247421-9ce367e8-9614-11e7-9193-88b540c87af1.png">

We may want to provide configuration for ocaml separate from reason. With this configuration, the language server starts up when opening ocaml files:

```
"ocaml":
      {
        "command": ["ocaml-language-server", "--stdio"],
        "scopes": ["source.ocaml"],
        "syntaxes": ["Packages/OCaml/OCaml.sublime-syntax"],
        "languageId": "ocaml"
      }
```

Can you confirm if that configuration works? Then we should update the settings and documentation for ocaml users who don't use reason.

**Comment by chenglou** [comment]
Aaah yes, that indeed worked!
