### ISSUE TITLE
Disable Sublime Text's own hovers if LSP provides feature

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#9]
As suggested by @deathaxe, Sublime's built-in hovers will likely flash on-screen before LSP's hovers pop up. 

I've seen some packages provide instructions to the user on adding `show_definitions: false` to syntax-specific settings.

We could also set `show_definitions` to false programmatically per view once LSP has loaded, or perhaps there is another clever way to suppress sublime's hover _until_ we've tried the language service?

**Comment by deathaxe** [comment]
For convenience I'd suggest to automatically disable it for a view, if LSP connects to a server.

  `view.settings().set("show_definitions", False)`

Jedi - Python AutoCompletion package does so as well.
