### ISSUE TITLE
Go Support 

### ISSUE THREAD

**Issue by gmichokostas** [tomv564/LSP#99]
Hi guys, 

I've tried to add support for Golang but maybe I am doing something wrong.
I've installed the [go-langserver](https://github.com/sourcegraph/go-langserver) but it looks like is not working.
Here is my config:

```
{
  "clients":
  {
    "golsp":
    {
      "command": ["go-langserver"],
      "scopes": ["source.go"],
      "syntaxes": ["Packages/Go/Go.sublime-syntax"],
      "languageId": "go"
    }
  },
}
```

Thanks,
George

**Comment by rwols** [comment]
Does running the command `LSP: Restart Servers` work?

**Comment by tomv564** [comment]
Hi George,

I pasted your settings in to my config, and the language server started up right away, so those appear to be correct!

Could you update your LSP Settings to set `"log_debug": true` and share the contents of your console on a fresh start after opening the go file?

Does running `go-langserver` on the command line work?

**Comment by gmichokostas** [comment]
Hi @tomv564 and @rwols,

Thanks for your comments! 
I've managed to solved the problem. Actually there was a conflict between the LSP package and the [GoSublime](https://github.com/DisposaBoy/GoSublime) package.

I've attached a screenshot too with the problem resolved!

Thank you very much for the amazing plugin!
George

ps: Shall I open a pull request including the Go config or you guys plan to do it?

<img width="881" alt="screen shot 2017-09-14 at 21 50 36" src="https://user-images.githubusercontent.com/7119729/30452690-d7b4e4ca-9996-11e7-842e-d10be036ed3b.png">

**Comment by tomv564** [comment]
Great work!

A PR adding this client to `docs/index.md` and the default sublime-settings would be a good service to future go users. 

Feel free to close the issue, and please create a new issue if you discover further problems.

**Comment by justinfx** [comment]
I've just tried to start using LSP with Go support, but I am not getting anything except the default Sublime symbol completion. I've enabled debug mode and it seems go-langserver is reporting errors?

```
LSP: notify: textDocument/didChange
LSP: checking for clients on on  /Users/justin/src/go/src/github.com/justinfx/gofileseq
LSP: request 2: textDocument/hover 
LSP: got json:  {"id":2,"error":{"code":0,"message":"failed to find doc object for /usr/local/Cellar/go/1.9/libexec/src/regexp/regexp.go:237:6","data":null},"jsonrpc":"2.0"}
LSP: got error:  {'data': None, 'code': 0, 'message': 'failed to find doc object for /usr/local/Cellar/go/1.9/libexec/src/regexp/regexp.go:237:6'}
```

Using this on a go 1.9 install, via homebrew on OSX Sierra. Any idea why this doesn't work? There doesn't seem to be much else in the way of available settings that I could change.

**Comment by tomv564** [comment]
Thanks for reporting!

We have the same configuration (go 1.9 via homebrew on Sierra, with go-langserver installed via `go get`), so we must be able to get hover and go-to-definition working at least.
 
I opened `regexp.go` and found the same results, `MustCompile` doesn't have hover results, but `quote` and `strconv.CanBackquote` do. 
It could be this issue: https://github.com/sourcegraph/go-langserver/issues/174

Completion and diagnostics are **not supported** yet by this server (see http://langserver.org/#implementations-server). 
- [ ] Document this as users likely consider these critical features.

The language server reported some "position out of bounds" errors after some edits. Would be ideal if someone working with this language server volunteered to narrow down a repro.

**Comment by justinfx** [comment]
Oh I see now. It is a limitation of the Go language server. I'm new to LSP so I didn't realize the separation until reading those links.

**Comment by tomv564** [comment]
I added a note about this, referring users to the GoSublime package instead. I've found Sourcegraph pretty receptive about contributions to their servers, so it would be awesome if someone helped them out with these features!
